### ISSUE TITLE
Descrizione ripetuta

### ISSUE THREAD

**Issue by magiaslab** [italia/design-scuole-wordpress-theme#1]
Negli articoli delle strutture la descrizione del campo PEC dove si deve inserire l'indirizzo PEC riporta la descrizione "numero di telefono" come il campo precedente

**Comment by webgrafia** [comment]
Grazie Alessandro, lo sistemerò alla prossima release (il tema è ancora in lavorazione)

**Comment by magiaslab** [comment]
Si ho visto ed è un ottimo lavoro al momento complimenti, anche io stavo sviluppando alcune parti mediante ACF e CPT dedicati ai documenti ed alla creazione delle circolari se vuoi mettiamo insieme il tutto

**Comment by webgrafia** [comment]
Purtroppo non ho potuto usare acf (lo adoro e ci ho provato in tutti i modi) perchè essendo un progetto da rilasciare per le scuole non potevo vincolarlo ad un plugin che richiede una licenza.
Sto quindi utilizzando cmb2, che è un pò meno raffinato e ha alcune lacune, ma ha una bella community intorno al repo github, e tutto sommato mi permette di fare quasi tutto
https://github.com/CMB2/CMB2
Sulla gestione delle circolari stavo valutando l'integrazione con questo plugin:
https://it.wordpress.org/plugins/gestione-circolari-groups/
Sono in contatto con Ignazio, il developer, per trovare la migliore integrazione possibile, se hai suggerimenti o altro materiale è bel accetto :)

**Comment by magiaslab** [comment]
Si ho visto CMB2 in realtà è giusto non associare ad un plugin però ACF e CTP li uso per creare i field che mi servono e poi esporto tutto in php quindi non c'è bisogno di installarlo vedo se riesco a riportare quello che avevo fatto io sulle circolari e sui documenti perchè avevo integrato anche datatables con css bootstrap ed era molto comodo puoi vedere un esempio qui https://sviluppo.magiaslab.com/marconi

**Comment by webgrafia** [comment]
No aspetta, è vero che con ACF puoi esportare la configurazione su php, ma devi comunque avere il plugin attivo!
Interessante il lavoro che stai facendo, vedo che stai utilizzando il format delle linee guida della PA, mentre per le scuole c'è tutto un filone nuovo di architettura e design che trovi qui
https://docs.italia.it/italia/designers-italia/design-scuole-docs/it/bozza/
e che sto usando come riferimento per la produzione del tema wordpress

**Comment by magiaslab** [comment]
Sai che ero convinto del contrario! perchè mi sbagliavo con CPT, ho provato su una sandbox per verificare. Si quello che sto elaborando è sul design kit di PA perchè mi sono concentrato su aspetti più operativi che servivano per la pubblicazione delle circolari e dei documenti e quindi non ho perso tempo con la realizzazione del template. Ho utilizzato quello di Boris che era già pronto, privo di visual editor e semplice da comprendere per la modifica dei template. Le bozze che mi hai suggerito le conosco bene seguo il tread dalla sua creazione

**Comment by webgrafia** [comment]
Intanto ho risolto il problema della label sbagliata :)
grazie!
