### ISSUE TITLE
Nuova versione del tema 2.0.0 - malfunzionamenti

### ISSUE THREAD

**Issue by anitamaccio** [italia/design-scuole-wordpress-theme#100]
Salve, ho provato a installare la nuova versione del tema, ma sono tornata alla versione precedente...
il menu principale appare due volte, una sopra l'altra, la zona banner c'è ma lo spazio è vuoto, anche se i banner ci sono... sono andata in configurazione a salvare di nuovo tutto, ma la situazione non è cambiata, per cui, non trovando nemmeno indicazioni se ci fosse qualche procedura da fare, ho ripristinato la versione precedente del tema. 

Saluti
Anita

**Comment by d3em64** [comment]
Confermo! Inoltre: a) sembrano esserci problemi nella visualizzazione delle mappe; b) in home non si visualizza il calendario: c) caricato il tema dal child theme ( [che sul sito online sembra non dare alcun problema](www.scuolacalamandrei.edu.it) ) la situazione disastrosa è quella allegata al file.
[IISS P. Calamandrei – Torino.pdf](https://github.com/italia/design-scuole-wordpress-theme/files/9119510/IISS.P.Calamandrei.Torino.pdf)

p.s.
sperimento con Wamp

**Comment by zetareticoli** [comment]
ciao @anitamaccio,
potresti gentilmente allegare alla issue degli screen relativi al menu?
Grazie

**Comment by zetareticoli** [comment]
> Confermo! Inoltre: a) sembrano esserci problemi nella visualizzazione delle mappe;

Che tipo di problemi stai sperimentando?

 > b) in home non si visualizza il calendario
 
 Il calendario è stato rimosso dal nuovo aggiornamento perché così come era stato realizzato non era accessibile. Puoi vedere l'[anteprima della hp del nuovo modello](https://design-scuole-pagine-sta-git-67c2c8-dip-trasformazione-digitale.vercel.app/scuole-home.html)
 
> c) caricato il tema dal child theme ( che sul sito online sembra non dare alcun problema: [www.scuolacalamandrei.edu.it](http://www.scuolacalamandrei.edu.it)) la situazione disastrosa è quella allegata al file. [IISS P. Calamandrei – Torino.pdf](https://github.com/italia/design-scuole-wordpress-theme/files/9119510/IISS.P.Calamandrei.Torino.pdf)

A prima vista, sembra un problema di caricamento delle risorse CSS. I path sono corretti?

**Comment by d3em64** [comment]
**Allego screen per le mappe**

![2ds](https://user-images.githubusercontent.com/68131121/179568872-bc1bca21-c03d-4ff9-816e-e4c8f43fc730.JPG)
![3sd](https://user-images.githubusercontent.com/68131121/179568932-ab5ef96a-5e10-4f99-87cc-568a16191c03.JPG)

------------------------------------------------------------------------------------------------
**Ad oggi la situazione dei menu in home è la seguente**

![1ds](https://user-images.githubusercontent.com/68131121/179569201-fc5fc58d-d9ec-483f-9c12-decce4010498.JPG)

--------------------------------------------------------------------------------------------------------------
Per il problema legato al child theme ho analizzato gli errori della console del browser è sembra proprio che cerchi di caricare i *.css dalla directory del child invece da quella principale del tema.
Tieni presente che il child theme è lo stesso del sito pubblicato: dove non compare alcun errore!

**Comment by anitamaccio** [comment]
> ciao @anitamaccio, potresti gentilmente allegare alla issue degli screen relativi al menu? Grazie

![Selezione_002](https://user-images.githubusercontent.com/58820327/184324742-95818957-2542-475f-a504-e155cf0e43e8.jpg)

Scusatemi, sono riuscita a farlo solo oggi, allego lo screen con le due righe del menu, il menu sopra non funge, quello sotto sì.
Per aggiornare il tema l'ho scaricato con il comando git clone, poi ho caricato la cartella via ftp, sovrascrivendo quella vecchia, per non perdere le personalizzazioni, può essere quello il problema?
Buona giornata
Anita

**Comment by astagi** [comment]
Buongiorno! Potete verificare che sia installato plugin 'Version Control for JQuery' richiesto dal tema? Grazie

**Comment by anitamaccio** [comment]
Era installato, ma non attivo, non ricordando se quando avevo aggiornato il tema lo avessi attivato, ho riprovato a riaggiornare il tema, controllando che il plugin fosse attivo, ma il menù doppio appare lo stesso, così come non si vedono i banner,
C'è qualche settaggio particolare del plugin Version Control for JQuery da impostare?

**Comment by astagi** [comment]
Perfetto grazie del riscontro @anitamaccio buon lavoro!
