### ISSUE TITLE
NON FUNZIONANTE - fresh install wordpress +  design-scuole-wordpress-theme

### ISSUE THREAD

**Issue by spicer1** [italia/design-scuole-wordpress-theme#101]
Ho reinstallato ex novo wordpress e installato il tema design-scuole-wordpress-theme v2.0.0 al seguente link
istitutocomprensivoempoliovest.edu.it/httpdocs/v2

Dopo aver attivato il tema ricevo il seguente messaggio 
```
Warning: Cannot modify header information - headers already sent by (output started at /var/www/vhosts/istitutocomprensivoempoliovest.edu.it/httpdocs/v2/wp-content/themes/design-scuole-wordpress-theme-main/walkers/header-walker.php:1) in /var/www/vhosts/istitutocomprensivoempoliovest.edu.it/httpdocs/v2/wp-includes/pluggable.php on line 1421

Warning: Cannot modify header information - headers already sent by (output started at /var/www/vhosts/istitutocomprensivoempoliovest.edu.it/httpdocs/v2/wp-content/themes/design-scuole-wordpress-theme-main/walkers/header-walker.php:1) in /var/www/vhosts/istitutocomprensivoempoliovest.edu.it/httpdocs/v2/wp-includes/pluggable.php on line 1424
```
Il problema risiede in tre file:

design-scuole-wordpress-theme-main/walkers/class-header-walker-nav-menu.php
design-scuole-wordpress-theme-main/walkers/footer-walker.php
design-scuole-wordpress-theme-main/walkers/header-walker.php

i quali prima della riga 
`<?php`

contengono una riga vuota.

Eliminando la riga vuota il problema si risolve

**Comment by zetareticoli** [comment]
Ciao,
grazie per la segnalazione, il bug è stato risolto in 94ba010472567e8dbf603da67fdb3ec2dc432431

Chiudo la issue 👍
