### ISSUE TITLE
nuova versione 2.0 - problema AVVISI DI ALLERTA IN HOME PAGE

### ISSUE THREAD

**Issue by AlexDarkGraphic** [italia/design-scuole-wordpress-theme#102]
il problema riscontrato (tra l'altro non presente nella v.1.0) è nello specifico:

1. selezionando "visualizza icona" viene mostrata un'icona gigante che prende tutto lo schermo.

2. in "Selezione colore del messaggio", non viene mostrata nessuna fascia colorata e in aggiunta fa sparire il pulsante di eventuale link inserito riguardante il messaggio da visualizzare.

**Comment by mariantanase** [comment]
Confermo

**Comment by Simsimus** [comment]
Confermo anche io il problema ed auspico che tale bug venga corretto quanto prima essendo una funzione molto utile...

**Comment by Cate55** [comment]
Confermo stessa disfunzione, provato anche con tema-child a sostituire il file messagges.php sovrascrivendolo con quello della versione v.1.0, ma non cambia la situazione. Grazie a tutti

**Comment by zetareticoli** [comment]
Dovrebbe essere stato risolto in 5c01f5384e0c9f362eb0f1a333feee92802d42ad

Fatemi sapere se vi torna, così chiudo la issue 🙏

**Comment by Simsimus** [comment]
> Dovrebbe essere stato risolto in [5c01f53](https://github.com/italia/design-scuole-wordpress-theme/commit/5c01f5384e0c9f362eb0f1a333feee92802d42ad)
> 
> Fatemi sapere se vi torna, così chiudo la issue 🙏

Ho effettuato alcuni test ed ora funziona tranquillamente.
Grazie per la risoluzione

**Comment by Cate55** [comment]
Perfetto confermo la risoluzione del problema! Un consiglio per coloro che non visualizzassero il corretto funzionamento, dopo aver sostituito il file aggiornato "scuole.css", di svuotare la cache del browser.
Grazie mille per il tempestivo intervento!
