### ISSUE TITLE
Opzione presentazione home

### ISSUE THREAD

**Issue by Simsimus** [italia/design-scuole-wordpress-theme#103]
Salve,
vorrei suggerire l'aggiunta di una opzione nella configurazione della home.
Andando su Configurazione > Home > Selezione automatica e quindi selezionando "No", credo sia utile dare la possibilità di scegliere una sola pagina per farne vedere direttamente il contenuto per l'intera larghezza, non in termini di solo titolo/anteprima (com'è attualmente), ma tutto il contenuto della pagina costruita in base alle proprie esigenze.
Grazie e buon lavoro

**Comment by astagi** [comment]
Buongiorno @Simsimus grazie del suggerimento! Lo marco come richiesta e ne parlo poi con il team operativo. Saluti!
