### ISSUE TITLE
Bug generazione PDF su Circolari - PHP 8.x

### ISSUE THREAD

**Issue by Simsimus** [italia/design-scuole-wordpress-theme#106]
Buongiorno,

se sulle Circolari si prova a generare il PDF attraverso la funzione presente sia sul frontend che sul backend, il sito va in errore (pagina bianca).

Preciso che ciò accade solo con la versione di PHP 8 o successive, invece con la 7.4 va tutto bene.
Auspico venga risolto con il prossimo aggiornamento.

Saluti

**Comment by astagi** [comment]
Buongiorno @Simsimus ,

hai dei log php dove sono scritti gli errori che avvengono? se si puoi allegarli a questa conversazione? Grazie!

**Comment by astagi** [comment]
Forse [questo articolo](https://make.wordpress.org/core/2022/01/10/wordpress-5-9-and-php-8-0-8-1/) può aiutare.

**Comment by Simsimus** [comment]
Buongiorno,
dopo l'aggiornamento del tema alla versione 2.0.1 gli errori di cui al punto 1 sono rientrati, mentre continua a persistere quello del punto 2, ovvero il pdf delle circolari non viene generato (allego lo screenshot dell'errore segnalato da wordpress dopo aver cliccato sul bottone Stampa/Condividi > Genera PDF). 
Grazie
![screen shot errore pdf](https://user-images.githubusercontent.com/108821309/187408103-2e0ac9ce-bc76-49b8-b888-033e67c0bd78.jpg)

**Comment by astagi** [comment]
Grazie @Simsimus per dare maggior chiarezza ho editato la issue in modo da concentrarci solo sul secondo punto.

**Comment by zetareticoli** [comment]
Ciao @Simsimus 
ho provato a riprodurre il bug e non ho riscontrato alcun errore. Nello specifico ho creato una nuova circolare, compilato i campi Titolo, Abstract, Descrizione allegando un PDF. 

Qual'è il flusso da te svolto? Grazie

**Comment by Simsimus** [comment]
Ciao, allego registrazione schermo che riproduce il problema.
Grazie
![errore generazion PDF](https://user-images.githubusercontent.com/108821309/188893654-ab97649a-52e0-4a31-bc44-68a7e2b28a42.gif)

**Comment by astagi** [comment]
Grazie @Simsimus ho appena mergiato questo bug relativo alle circolari https://github.com/italia/design-scuole-wordpress-theme/pull/95/files potresti provare se con tale modifica funziona tutto?

**Comment by Simsimus** [comment]
Purtroppo il problema che ho segnalato ancora persiste, ma faccio presente che non si riferisce alla notifica della circolare, bensì alla generazione del PDF illustrata nella gif animata presente nel precedente post.

**Comment by astagi** [comment]
Grazie della verifica! Si si mi è chiaro stavo solo pensando che potesse essere legato alla circolare.

**Comment by lorenzo-vernocchi** [comment]
Buongiorno @Simsimus,
è possibile avere informazioni sull'ambiente di installazione di Wordpress?

**Comment by Simsimus** [comment]
Certo, si tratta di hosting wordpress di Aruba con php 8, ma avevo provato anche su pc windows con xampp (sempre php 8) ed il risultato è sempre lo stesso.

**Comment by lorenzo-vernocchi** [comment]
Grazie per le info!
Andrebbe verificata la presenza del modulo gd_extension di php, richiesto dal plugin dompdf (incluso nel tema wordpress). 
Un'altra informazione utile sarebbe il log dell'errore php generato.

**Comment by Simsimus** [comment]
Allego report di quanto rihiesto:
[Errore PDF tema scuole.pdf](https://github.com/italia/design-scuole-wordpress-theme/files/9565429/Errore.PDF.tema.scuole.pdf)

**Comment by lorenzo-vernocchi** [comment]
Ciao @Simsimus 
abbiamo analizzato l'error log che ci hai inviato. 

PHP Warning: file_get_contents(): https:// wrapper is disabled in the 
server configuration by allow_url_fopen=0 

E' possibile che la problematica si verifichi a causa di un parametro da dover settare correttamente, nello specifico allow_url_fopen che dovrebbe essere abilitato.

**Comment by Simsimus** [comment]
Ho fatto una verifica e questo stesso warning compare anche se imposto la versione php 7.4, ma in quest'ultimo caso la procedura va avanti tranquillamente senza errori ed il pdf viene generato in modo corretto, quindi deduco che non sia questa la causa, ma qualcosa che nella versione php 8 impedisce tale elaborazione.
Se avete fatto dei test anche voi impostando php 8 e l'errore segnalato a voi non risulta, allora la cosa potrebbe essere imputabile ai server aruba (anche se dubito sia così) e quindi tutte le scuole che useranno il tema su hosting linux aruba (che credo sia l'hosting più utilizzato dalle stesse) con php 8 avranno lo stesso problema che ho segnalato.
Non ne ho la certezza, ma avendo provato sia su server aurba che in locale con xampp, credo che con qualsiasi hosting, se la versione php è la 8, si verificherà il problema.

**Comment by lorenzo-vernocchi** [comment]
Ciao @Simsimus 
Abbiamo fatto ulteriori verifiche e il problema sembrerebbe essere proprio legato al parametro allow_url_fopen. Riusciresti a verificare settando il parametro su On dal file php.ini di xampp e/o Aruba?
Grazie

**Comment by Simsimus** [comment]
Ciao @lorenzo-vernocchi,
ho provato su xampp, dove tale parametro è su ON, ma il problema persiste.
Ho verificato anche su Aruba dove tale parametro è su OFF in ambedue le versioni di php (7.4 e 8), ma purtroppo non posso passarlo ad ON autonomamente perchè bisogna fare richiesta ad aruba stessa. Ad ogni modo pur restando sempre su OFF, con php 7.4 va tutto bene, mentre con php 8 va in errore.

**Comment by Simsimus** [comment]
Buongiorno,
volevo segnalare che tale problema persiste. Anche impostando allow_url_fopen su on il pdf non viene generato.
Ribadisco che l'errore viene generato solo con php 8.x, mentre con php 7.4 va tutto bene.
Spero possiate analizzare e risolvere la problematica, grazie.

**Comment by astagi** [comment]
@Simsimus se hai modo contattami sullo Slack di Developers Italia magari possiamo organizzare una call per vedere il problema dal vivo e risolverlo! Grazie mille!

**Comment by Simsimus** [comment]
Sono riuscito a capire il problema, ovvero non era abilitata la libreria GD.
Attivando GD e portando allow_url_fopen su ON il problema si è risolto, ma se display_errors è su On vengono fuori questi warning:
- Warning: Undefined array key "csv" in /wp-content/themes/design-scuole-wordpress-theme-main/inc/admin/circolare.php on line 524
- Warning: Undefined array key "pdf" in /wp-content/themes/design-scuole-wordpress-theme-main/inc/dompdf.php on line 16
- Warning: Array to string conversion in /wp-includes/general-template.php on line 184

Aggiungo una domanda: portando allow_url_fopen su ON non si rende il sito potenzialmente più vulnerabile?

**Comment by astagi** [comment]
@Simsimus ottima notizia! Tecnicamente dipende molto dall'[applicazione](https://security.stackexchange.com/questions/103427/what-are-php-allow-url-fopen-security-risk) anche [qua](https://vulncat.fortify.com/en/detail?id=desc.config.php.php_misconfiguration_allow_url_fopen#:~:text=When%20enabled%2C%20the%20allow_url_fopen%20option,malicious%20content%20into%20an%20application.) c'è un po' di spiegazione .. sinceramente anche me sembra un po' rischioso chiedo chiarimenti a @lorenzo-vernocchi
