### ISSUE TITLE
Calendario eventi

### ISSUE THREAD

**Issue by anitamaccio** [italia/design-scuole-wordpress-theme#11]
Salve, ho installato il tema in una sottocartella nel sito della mia scuola, e sto cercando di implementarlo. Lo sto utilizzando così come scaricato, non ho aggiunto moduli diversi. 
Ho un malfunzionamento del calendario eventi: ho inserito un evento in questo anno scolastico, ma andando sulla voce della barra del menu Novità -> Calendario eventi  https://www.icvs.edu.it/wp/evento/ il calendario parte da gennaio 1970, non ho trovato modo di modificarlo.
Se nella stessa pagina clicco sulla tipologia https://www.icvs.edu.it/wp/tipologia-evento/eventi-della-scuola/ il calendario sparisce, mi appare un evento che ha la data della creazione e non quella impostata per l'evento, cliccando sul quale non succede nulla.
Inoltre tutte le volte che vado in modifica evento, devo riscrivere le date inizio/fine dell'evento perchè spariscono.
Per il resto finora mi sembra funzioni tutto molto bene, non capisco se per il calendario mi sfugge qualcosa.
Grazie!
Anita Macciò

**Comment by webgrafia** [comment]
ciao Anita, 
molto strano, non riesco a replicarlo in locale.
Quando hai scaricato il tema l'ultima volta?
Se è passata più di una settimana prova a riscaricarlo aggiornando i file, e dimmi se risolve.

**Comment by anitamaccio** [comment]
l'ho scaricato il 6 dicembre, domani mattina provo a riscaricarlo e vedere come va.
Grazie
Anita Macciò

**Comment by anitamaccio** [comment]
Niente, ho fatto velocemente stasera: ho scaricato di nuovo il tema, ho scaricato wordpress "vergine", ho caricato tutto via ftp, senza fare nient'altro oltre ad attivare il tema ho provato ad inserire un evento, e fa la stessa cosa: il calendario parte da gennaio 1970 https://www.icvs.edu.it/wp2/evento/
e cliccando su tipologia evento appare l'evento con data di oggi, cliccando sul quale non si apre niente https://www.icvs.edu.it/wp2/tipologia-evento/eventi-della-scuola
Ho provato anche a modificare l'evento, e di nuovo devo riscrivere le date di inizio e fine perché spariscono...
Ho guardato nei due siti messi come esempio, e in uno dei due il calendario sembra faccia come il mio: https://comprensivobosisio.la-scuola.it/evento/
Anita

**Comment by anitamaccio** [comment]
Può dipendere dalla versione php? su Strumenti -> Salute del sito (Site Health) mi appare l'avviso:
"La tua versione di PHP (7.2.22) non è aggiornata. PHP è il linguaggio di programmazione utilizzato per realizzare e manutenere WordPress. Le nuove versioni di PHP sono più veloci e più sicure, restare aggiornato favorisce le prestazioni generali e la sicurezza del tuo sito. La versione minima raccomandata di PHP è 7.3.
Ma io sono su Aruba, non mi consente di andare oltre la 7.2.22
Grazie
Anita

**Comment by webgrafia** [comment]
Non è la versione php, è un bug nel formato della data evento
Dovrei aver risolto, puoi provare a riscaricare l'ultima versione del tema?
Basta il tema base, non serve aggiornare i sottomoduli
Poi dovrai rieditare l'evento verificando che non si sia persa la data (probabile) e risalvandolo

Dovrebbe aggiustarsi tutto, in caso sia ok puoi chiudere questa issue :)
grazie del feedbak

**Comment by anitamaccio** [comment]
Perfetto, ho riscaricato il tema, rieditato l'evento e ora tutto funziona come da aspettative!
Grazie mille
Anita
