### ISSUE TITLE
Richiesta file sorgente SCSS e JS

### ISSUE THREAD

**Issue by ToldoDesign128** [italia/design-scuole-wordpress-theme#110]
Buongiorno,  scrivo in merito alla necessità di avere i file sorgente SCSS e JS, c'è la possibilità di ottenere il caricamento dei file sorgente?
Grazie per la disponibilità.

**Comment by astagi** [comment]
Buongiorno @ToldoDesign128 si stiamo lavorando sulla parte statica per risolvere il problema. Spero di avere aggiornamenti a breve. Chiudo in quanto duplicato sulla parte statica.
