### ISSUE TITLE
Supportare Gutenberg

### ISSUE THREAD

**Issue by simonezanella** [italia/design-scuole-wordpress-theme#113]
Buongiorno, quando si aggiorna un articolo e si salva, vengono perse tutte le tipologie articolo assegnate.

**Comment by simonezanella** [comment]
Ciao, nel frattempo ho risolto per caso, il bug si verifica se si lascia Gutenberg abilitato, praticamente non viene mostrato il box con la scelta della tipologia articolo e quindi salvando se lo perde, usando il plugin per disabilitare Gutenberg torna a funzionare, ma magari sarebbe opportuno lasciare la possibilità di usarlo

**Comment by astagi** [comment]
@simonezanella quindi dici non utilizzando Gutenberg ma l'editor di base fila tutto liscio? In pratica è il tema che non mostrando la scelta della tipologia articolo impedisce il salvataggio (o peggio in modifica fa scomparire la precedente scelta) è giusto?

**Comment by simonezanella** [comment]
@astagi esatto, con Gutenberg attivo non mostra la scelta, pertanto quando salvi l'articolo deduco imposti come NULL (o analogo)  il campo della tipologia. Con l'editor di base il box c'è ed in modifica articolo è valorizzato con la tipologia corretta.

**Comment by astagi** [comment]
Lo metto come richiesta di miglioramento, il tema di default disabilita Gutenberg di base, non è l'unica miglioria che andrebbe fatta per poter usare quell'editor. Ad oggi per usare il tema scuole deve rimanere disabilitato.
