### ISSUE TITLE
Warning su file wp-admin-menu-classes.php

### ISSUE THREAD

**Issue by aresuma** [italia/design-scuole-wordpress-theme#115]
Ciao,
sto installando per la prima volta la **versione 2.0.1 del tema** su un **Wordpress 6.0.2** vergine.
Possiedo i messaggi di warning ed errore di PHP attivi.

Nella navigazione sul backend, visualizzo i seguenti messaggi di warning:
```
key 0 in /var/www/html/wp-content/themes/design-scuole-wordpress-theme/inc/vendor/wp-admin-menu-classes.php on line 321
Warning: Trying to access array offset on value of type null in /var/www/html/wp-content/themes/design-scuole-wordpress-theme/inc/vendor/wp-admin-menu-classes.php on line 321
Warning: Undefined array key 2 in /var/www/html/wp-content/themes/design-scuole-wordpress-theme/inc/vendor/wp-admin-menu-classes.php on line 145
Warning: Undefined array key 2 in /var/www/html/wp-content/themes/design-scuole-wordpress-theme/inc/vendor/wp-admin-menu-classes.php on line 145
Warning: Undefined array key 2 in /var/www/html/wp-content/themes/design-scuole-wordpress-theme/inc/vendor/wp-admin-menu-classes.php on line 145
Warning: Undefined array key 2 in /var/www/html/wp-admin/includes/plugin.php on line 1896
Warning: Undefined array key 2 in /var/www/html/wp-admin/includes/plugin.php on line 1424
Warning: Undefined array key 2 in /var/www/html/wp-admin/includes/plugin.php on line 1896
Warning: Undefined array key 2 in /var/www/html/wp-admin/includes/plugin.php on line 1424
Warning: Undefined array key 1 in /var/www/html/wp-admin/includes/menu.php on line 163
Warning: Undefined array key 2 in /var/www/html/wp-admin/includes/menu.php on line 164
Warning: Undefined array key 2 in /var/www/html/wp-admin/includes/menu.php on line 171
Warning: Undefined array key 2 in /var/www/html/wp-admin/includes/menu.php on line 180
Warning: Undefined array key 2 in /var/www/html/wp-admin/includes/menu.php on line 182
```

Spegnendo i messaggi di warning, il messaggio scompare. Secondo me sarebbe opportuno risolverli.

Riporto alcune considerazioni:
- Debuggando il codice, i messaggi vengono generati dalla funzione `dsi_custom_admin_menu` del file `inc/menu-order.php`
La funzione, da quello che si capisce dovrebbe modificare diverse voci di menu.
- Nello stack delle chiamate, viene chiamata la funzione `WP_AdminMenuSection` del file `inc/vendor/wp-admin-menu-classes.php`
Dovrebbe settare la varaibile `$this->index`, però non sempre viene fatto.
- Successivamente, viene richiamata la variabile `$this->index` che essendo false, non può essere considerata come un array. Ciò genera una serie di warning.

Allego una patch che risolve i messaggi di warning. La patch è stata prodotta non conoscendo il progetto e non avendo una visione completa di tutte le funzionalità del tema. In caso decidiate di applicarla, controllatela attentamente.
[Link alla patch](https://gist.github.com/aresuma/0ba4683816e541c13869e8252073cf50)

Saluti
Marco

**Comment by zetareticoli** [comment]
Ciao @aresuma , che versione di PHP stai utilizzando?

**Comment by aresuma** [comment]
> Ciao @aresuma , che versione di PHP stai utilizzando?

Ciao, la versione di PHP è la 8.1.

> Ciao @aresuma grazie del report. Potresti aprire una PR partendo dal link della patch? almeno riusciamo ad avere una visione migliore del codice. Grazie :)

La pull request è stata aperta ed è la numero [118](https://github.com/italia/design-scuole-wordpress-theme/pull/118)

**Comment by astagi** [comment]
@zetareticoli @GiandonatoGreco PR aperta da @aresuma che ringrazio

**Comment by GiandonatoGreco** [comment]
@astagi si può procedere al merge della PR 118.

Grazie
