### ISSUE TITLE
Eventi - visualizzazione

### ISSUE THREAD

**Issue by zerooverflow** [italia/design-scuole-wordpress-theme#12]
Salve, 
segnalo che un post di tipo evento non viene visualizzato nel percorso home/novità/eventi. Riesco invece a vederlo in Home/novita. 
( allineato con master )
![image](https://user-images.githubusercontent.com/2944889/70796322-3e93c300-1da2-11ea-80e0-c12052ea8dbb.png)
![image](https://user-images.githubusercontent.com/2944889/70796351-53705680-1da2-11ea-910e-6dd227189dc9.png)

**Comment by webgrafia** [comment]
Puoi provare a scaricare l'ultima versione? ho appena pushato un fix che dovrebbe aver risolto il problema.
Dovrete probabilmente rieditare la data degli eventi, entrando nel singolo evento e risalvandolo, verificando non sia sparita

In caso sia ok puoi chiudere la issue :)

**Comment by zerooverflow** [comment]
grazie adesso è fixato, scusa ma non ho potuto pullare prima e chiudere la issue
