### ISSUE TITLE
Voce di menu Notizie

### ISSUE THREAD

**Issue by aresuma** [italia/design-scuole-wordpress-theme#122]
Non trovo la voce di menu per le notizie. Mi riferisco alla dashboard raggiungibile dall'url /wp-admin/edit.php?post_type=post
Ho installato il sito da zero e non la trovo. Posso aggiungere notizie, ma poi non trovo una voce di menu per amministrarne i contenuti.
Perché non c'è?

**Comment by astagi** [comment]
@aresuma per raggiungere le notizie come tipologia di articolo sono andato su

<img width="155" alt="image" src="https://user-images.githubusercontent.com/537363/189622577-8baf7105-a13d-4189-9a14-bbf0191bde8d.png">

Poi cliccando sul numero degli articoli come tipologia `notizia` (in questo caso `1`)

<img width="796" alt="image" src="https://user-images.githubusercontent.com/537363/189622500-16c4d912-3425-4816-8a66-4030688b173e.png">

vengono mostrate le notizie ed è possibile amministrare gli eventuali contenuti

<img width="1272" alt="image" src="https://user-images.githubusercontent.com/537363/189622825-e24203d3-5c28-4418-9957-7e7324309012.png">

Spero possa aiutare!

**Comment by aresuma** [comment]
Ciao, grazie per la spiegazione. Continuo però a non trovare la voce di menu.

La voce di menu viene nascosta via PHP dalla funzione `dsi_custom_admin_menu` del file `menu-order.php`. 
La voce di menu compare se viene commentata la riga
`swap_admin_menu_sections('Strutture','Articoli');`

Perchè è presente tale istruzione?

Se dovesse servire, lascio un commit su un fork. Il commit è il seguente:
https://github.com/italia/design-scuole-wordpress-theme/compare/main...aresuma:design-scuole-wordpress-theme:HOTFIX/menu-article

**Comment by astagi** [comment]
@aresuma grazie mille mi è anche più chiara la problematica! Perché non apri quel commit su una pull request almeno possiamo analizzarla e inserirla nel codice! Grazie

**Comment by aresuma** [comment]
Ecco la pull request #123

**Comment by boazaob** [comment]
Ho lo stesso problema dopo aver aggiornato dalla versione "design-scuole-wordpress-theme-2.0.2" alla "design-scuole-wordpress-theme-2.0.2" anzi peggio. Non solo non ho più il menu Articoli, ma si sono duplicati i menu Pagine e Strutture. 
![Screenshot 2022-09-23 at 18-43-31](https://user-images.githubusercontent.com/114248388/192011446-2e129ae8-d51a-4d13-b7eb-c7df64805f28.png)

**Comment by aresuma** [comment]
Ciao, ho rilasciato sulla Ecco la pull request [#123](https://github.com/italia/design-scuole-wordpress-theme/pull/123) alcune modifiche riguardanti il menu di amministrazione. Le modifiche riguardano:

1. ripristino voce Articoli
2. eliminazione duplicazione voce Pagine
3. eliminazione duplicazione voce Strutture
