### ISSUE TITLE
Tema child 

### ISSUE THREAD

**Issue by ogatto23** [italia/design-scuole-wordpress-theme#125]
Salve, 
avrei bisogno di creare il tema child per poter fare delle personalizzazioni.
Ho provato a creare il tema child, sia con vari plugin sia manualmente, ma il sito non viene caricato correttamente.

Che indicazioni ci sono al riguardo?
Oppure posso utilizzare un altro sistema per non perdere le mie modifiche in caso di aggiornamento del tema?

Grazie mille

**Comment by zetareticoli** [comment]
Ciao @ogatto23 , potresti aggiungere qualche dettaglio ulteriore sul problema in questione? Grazie 🙏

**Comment by ogatto23** [comment]
Ciao, 
Quando creo il tema child si perde completamente lo stile e il template, sembra che non vengano caricati ne i file js ne i file css del tema originale. 
Ecco come appare il sito con il tema child: https://scuola.ogatto.it/
Allego il file style.css e functions.php del tema child creato con un plugin.

![SharedScreenshot-functions php](https://user-images.githubusercontent.com/103357861/191100841-311eac7d-a7b7-43a6-acc1-f43614c4cead.jpg)
![SharedScreenshot-style css](https://user-images.githubusercontent.com/103357861/191100847-bf644754-df4a-4c71-91a0-cbc69f77676b.jpg)

Grazie mille

**Comment by boazaob** [comment]
mi associo, sembra impossibile creare un tema child

**Comment by tonypoly** [comment]
Confermo questa problematica.

**Comment by zetareticoli** [comment]
Ciao @ogatto23 , ho visto il link che hai postato e il sito mi sembra si veda bene.

Questa problematica è ancora reale e necessita di supporto? /cc @tonypoly @boazaob

**Comment by tonypoly** [comment]
> Ciao @ogatto23 , ho visto il link che hai postato e il sito mi sembra si veda bene.
> 
> Questa problematica è ancora reale e necessita di supporto? /cc @tonypoly @boazaob

Ciao @zetareticoli,  ti confermo che la problematica persiste e necessita di supporto, non si riesce a creare un child theme funzionante (come da errore segnalato da @ogatto23 ) e viste alcune limitazioni attuali, ho necessità di eseguire modifiche al tema per variare alcuni template.

Grazie per il vostro lavoro.

**Comment by ogatto23** [comment]
> Ciao @ogatto23 , ho visto il link che hai postato e il sito mi sembra si veda bene.
> 
> Questa problematica è ancora reale e necessita di supporto? /cc @tonypoly @boazaob

Ciao @zetareticoli , 
La problematica del tema child persiste, quindi abbiamo optato per rimuoverlo .
Grazie mille per la vostra disponibilità e il vostro lavoro

**Comment by boazaob** [comment]
Confermo l'impossibilità di creare tema child.

**Comment by astagi** [comment]
@ogatto23 @tonypoly @boazaob la lavorazione per il tema child è in corso cc @zetareticoli

**Comment by boazaob** [comment]
Questa mattina ho già provato a inserire le modifiche di @milesimarco e sono riuscito a creare il tema child. Mi sono perso le modifiche che avevo fatto sui menù, ma sembra che il resto funzioni.
Grazie

**Comment by astagi** [comment]
Ottima notizia @boazaob 👍 grazie del riscontro!

**Comment by camillo860** [comment]
La soluzione di @milesimarco  permette di avere un child themes. Grazie !!

**Comment by zompa-zampa** [comment]
Ho creato il tema child ma perde la voce scuola!!! e quando passo da child a principale perdo le voci aggiunte nel menu!

**Comment by milesimarco** [comment]
@zompa-zampa questo comportamento è spesso presente nel cambio di temi WordPress. Anche con i temi child è richiesto il setup da zero di alcune configurazioni del tema e di menù/widget.

**Comment by salvastore** [comment]
Buongiorno, leggo che molti hanno riscontrato problemi nell'installazione dei temi child, in quanto non vengono mantenute le impostazioni di menu e widget iniziali.
C'è stata una evoluzione su questo aspetto?
