### ISSUE TITLE
Scorrimento automatico nella sezione banner

### ISSUE THREAD

**Issue by ricdip** [italia/design-scuole-wordpress-theme#127]
Salve,
nella sezione banner mostrata nella home page è possibile abilitare in qualche modo lo scorrimento automatico dei banner presenti nello slider?
Nel caso la funzionalità fosse mancante, vorrei suggerirne l'aggiunta tra le opzioni nella configurazione della sezione banner.

Grazie mille e buon lavoro.

**Comment by astagi** [comment]
Ciao @ricdip intendi una sorta di timer che fa scorrere lo slider alla visualizzazione?

**Comment by ricdip** [comment]
Esattamente. Uno scorrimento automatico delle immagini presenti nello slider dopo un certo periodo di tempo

**Comment by vcoopcsc** [comment]
Buongiorno, mi permetto di accodarmi alla conversazione. Sono d'accordo con l'idea dello scorrimento automatico che potrebbe essere comodo e dare dinamicità alla pagina. Mi permetto solo di sottolineare alcuni aspetti di accessibilità da tenere a mente: lo slideshow deve poter essere comunque controllato dall'utente che, se non erro, deve poter mettere in pausa lo scorrimento automatico, scorrere le immagini tramite comandi e/o riavviare lo scorrimento automatico. 

Buona giornata a tutti!
