### ISSUE TITLE
Tema nel marketplace ufficiale di Wordpress

### ISSUE THREAD

**Issue by Simsimus** [italia/design-scuole-wordpress-theme#128]
Buongiorno,
essendo questo un tema importante, sponsorizzato dal Dipartimento per la trasformazione digitale + AGID, entro quanto tempo verrà in inserito nel marketplace ufficiale di Wordpress?
Avendo un certo peso credo sia necessario inserirlo quanto prima.
Grazie

**Comment by Orsomaggiore** [comment]
Sono d'accordo, sostengo anch'io questa richiesta.

**Comment by leosamuele221** [comment]
Ci sono novità su questo thread? Sarebbe molto utile aggiungerlo al marketplace di Wordpress
Mi sto informando su come farlo in questo momento
