### ISSUE TITLE
Notifica Circolare 

### ISSUE THREAD

**Issue by Cate55** [italia/design-scuole-wordpress-theme#129]
Buongiorno le circolari riservate vengono notificate solo se i destinatari sono associati al gruppo di appartenenza e non  al ruolo. Sbaglio la configurazione oppure è corretto che sia così?
Grazie mille per il supporto
caterina toccafondi
![impostazioni-circolari](https://user-images.githubusercontent.com/9642253/191705269-2a2b16cb-74d9-4bde-824c-8162df92a9a3.png)

**Comment by zetareticoli** [comment]
@Cate55 Il problema, segnalato anche sul [canale Slack](https://developersitalia.slack.com/archives/CQ7J0KANT/p1663854925751229)

Attendiamo apertura della PR per la review del fix.

**Comment by Cate55** [comment]
Grazie mille per la fiducia @zetareticoli, non sono esperta di Github ho cliccato per aprire PR, ma adesso non so come inserire la modifica al file /inc/admin/circolare.php
