### ISSUE TITLE
Loghi personalizzati in home page

### ISSUE THREAD

**Issue by anitamaccio** [italia/design-scuole-wordpress-theme#13]
Salve, non è proprio un problema ma una cosa che ci manca. Sto popolando i vari content-type e nel nostro Istituto Comprensivo ci sembrano abbastanza rispondenti alle nostre necessità, però dobbiamo piazzare in homepage il logo PON, l'unico posto possibile per i widget è il footer ma mettere il logo PON nel footer non ci piace, lo vorremmo nell'header o poco più sotto, e vorremmo linkarci la relativa pagina con la pubblicazione di tutti i documenti obbligatori... C'è il modo?
Grazie e cordiali saluti
Anita Macciò

**Comment by anitamaccio** [comment]
Anche piazzare il qr code arrivato da Scuola in Chiaro...

**Comment by webgrafia** [comment]
Buongiorno Anita,
al momento  non è prevista la possibilità di modificare la homepage con banner o immagini, ma guardando nel dettaglio la questione PON effettivamente siete obbligati a posizionare quel banner in home page in alto.
Stiamo valutando come integrare una soluzione che risponda a queste esigenze, appena troveremo una soluzione la rilasceremo qui

**Comment by webgrafia** [comment]
Buonasera Anna,
nell'ultimo deploy è stata inserita nell'area di configurazione della homepage la possibilità di attivare l'area banner, in cui caricare immagini e eventuale link. Vengono rappresentati in formato slider se sono più di 2

**Comment by anitamaccio** [comment]
Ciao, ho scaricato e nella parte amministrativa ho trovato dove aggiungere il banner, l'ho impostato con il logo PON ufficiale, ma andando in homepage non appare poi nulla da nessuna parte...
Saluti
Anita

**Comment by webgrafia** [comment]
Hai flaggato "Visualizza la fascia banner" su si?
In link in cui l'hai installato è pubblico? puoi girarmelo?

**Comment by anitamaccio** [comment]
Ops! non avevo flaggato si, non l'avevo visto! ora è tutto a posto, scusami :)
Anita
