### ISSUE TITLE
Richiesta sezione Bacheca sindacale

### ISSUE THREAD

**Issue by aresuma** [italia/design-scuole-wordpress-theme#130]
Ciao, sarebbe possibile integrare una nuova sezione dedicata alla **Bacheca sindacale**? 
La sezione dovrebbe mostrare la lista delle circolari e delle notizie che vengono classificate come Bacheca sindacale.

**Comment by astagi** [comment]
Ciao @aresuma grazie! Segno questa issue come enhancement e la giro al team!
