### ISSUE TITLE
Menu principale: richiesta di altre voci di menu di primo livello

### ISSUE THREAD

**Issue by aresuma** [italia/design-scuole-wordpress-theme#131]
Ciao, nel menu principale, potreste prevedere l'aggiunta di ulteriori voci di menu di primo livello?
Le 4 voci di menu Scuola, Servizi, Novità, Didattica sono limitanti. Potreste prevedere l'aggiunta di altre voci di menu di primo livello (almeno 2)?

**Comment by astagi** [comment]
Ciao @aresuma non capisco qual'è il risultato che vuoi ottenere, potresti fare un esempio delle voci che vorresti che comparissero?

Grazie mille!

**Comment by tonypoly** [comment]
Ciao, mi trovo nella stessa situazione e sto pensando di sostituire il menù principale del tema per questo motivo. 
Nel mio caso, invece che "servizi" nel menù di primo livello, vorrei due occorrenze diverse per  servizi per famiglie e quelli per docenti.

**Comment by aresuma** [comment]
> Ciao @aresuma non capisco qual'è il risultato che vuoi ottenere, potresti fare un esempio delle voci che vorresti che comparissero?
> 
> Grazie mille!

Secondo me sarebbe meglio dare la possibilità di avere più voci di primo livello possibili. Naturalmente compatibilmente con

1. il layout grafico su Desktop. Sulla destra del menu c'è dello spazio bianco non sfruttato. Secondo me, altre due voci di menu potrebbero starci. Forse tre voci aggiuntive sarebbero troppo troppe perché su tablet potrebbero mandare a "capo il menu", ma alte due dovrebbero starci
2. le direttive del piano redazionale fornito dall'AGID per la composizione del menu principale. C'è la possibilità di variare rispetto all'[architettura dell'informazione](https://docs.google.com/spreadsheets/d/1MoayTY05SE4ixtgBsfsdngdrFJf_Z2KNvDkMF3tKfc8/edit#gid=99325200) della mappa di navigazione?

Il menu principale potrebbe essere così composto:
Scuola Servizi Novità Didattica Famiglie Docenti

Grazie

**Comment by CampusDaVinci** [comment]
Sarebbe ottimo dare la possibilità di aggiungere delle voci "custom" di 1°, 2° e 3° livello al menù principale
altrimenti così è troppo limitante

**Comment by attiliopecora** [comment]
SONO D'ACCORDO con @CampusDaVinci

**Comment by Jamielrey** [comment]
Io ho aggiunto altre 3 voci al menù principale, ma le ho disabilitate da poco perché l'app di controllo mi segnalava in giallo per l'aggiunta di queste voci. 
Se volete vi passo comunque il codice. 
![menu](https://user-images.githubusercontent.com/124105310/215920323-73f20c70-86e3-4af9-9024-a423fd5869ec.jpg)

**Comment by Jamielrey** [comment]
![Screenshot from 2023-02-01 02-10-56](https://user-images.githubusercontent.com/124105310/215920735-61dafe4f-4f0e-44e7-9a8d-f6dae756ae15.png)

Questo però è l'errore che compare se li attivo.

**Comment by CampusDaVinci** [comment]
Ma perché non consentite di aggiungere voci di secondo livello come questa issue aperta qua ?
https://github.com/italia/design-scuole-wordpress-theme/issues/142
Renderebbe il tema conforme e darebbe comunque la possibilità di gestire le personalizzazioni

**Comment by CampusDaVinci** [comment]
Ma perché non consentite di aggiungere voci di secondo livello come questa issue aperta qua ?
https://github.com/italia/design-scuole-wordpress-theme/issues/142

> Io ho aggiunto altre 3 voci al menù principale, ma le ho disabilitate da poco perché l'app di controllo mi segnalava in giallo per l'aggiunta di queste voci. Se volete vi passo comunque il codice. ![menu](https://user-images.githubusercontent.com/124105310/215920323-73f20c70-86e3-4af9-9024-a423fd5869ec.jpg)

Una cortesia... come si chiama e dove si trova l'app di controllo ?

**Comment by Jamielrey** [comment]
https://docs.italia.it/italia/designers-italia/app-valutazione-modelli-docs/it/versione-attuale/index.html

Qui trovi tutte le informazioni, link compresi

**Comment by zetareticoli** [comment]
Ciao, al momento non è prevista alcuna modifica delle impostazione per il menu di primo livello.

Tutti i progetti che accedono ai fondi PNRR infatti sono chiamati a rispettare i criteri di conformità, tra cui quello citato da @Jamielrey.

**Comment by zetareticoli** [comment]
Ciao, al momento non è prevista alcuna modifica delle impostazione per il menu di primo livello.

Tutti i progetti che accedono ai fondi PNRR infatti sono chiamati a rispettare i criteri di conformità, tra cui quello citato da @Jamielrey.

**Comment by CampusDaVinci** [comment]
> Io ho aggiunto altre 3 voci al menù principale, ma le ho disabilitate da poco perché l'app di controllo mi segnalava in giallo per l'aggiunta di queste voci. Se volete vi passo comunque il codice. ![menu](https://user-images.githubusercontent.com/124105310/215920323-73f20c70-86e3-4af9-9024-a423fd5869ec.jpg)

Salve, capisco che segni in giallo, ma si potrebbe avere comunque il codice ?
Grazie mille

**Comment by Jamielrey** [comment]
> > Io ho aggiunto altre 3 voci al menù principale, ma le ho disabilitate da poco perché l'app di controllo mi segnalava in giallo per l'aggiunta di queste voci. Se volete vi passo comunque il codice. ![menu](https://user-images.githubusercontent.com/124105310/215920323-73f20c70-86e3-4af9-9024-a423fd5869ec.jpg)
> 
> Salve, capisco che segni in giallo, ma si potrebbe avere comunque il codice ? Grazie mille

Ciao, il codice è un po' lungo, spero si capisca. Ti passo gli appunti che ho salvato. Considera che si rifanno alla versione del template di febbraio, ma se non sono stati toccati i file cambia poco e niente. Assicurati solo che la riga sia ancora quella corrispondente.
Fai ovviamente prima qualche prova in locale ed un bel backup prima di provare sul sito della scuola. Il codice funziona, ma l'ho provato poco in quanto mi dava quella segnalazione gialla e quindi l'ho levato di mezzo:

`AGGIUNGERE NUOVI MENU:
1)	Aspetto->Editor del tema->functions.php
Aggiungere dopo la riga 160:
'menu-personale-5' => esc_html__( 'Menù accanto a didattica 1', 'design_scuole_italia' ),
'menu-personale-6' => esc_html__( 'Menù accanto a didattica 2', 'design_scuole_italia' ),
'menu-personale-7' => esc_html__( 'Menù accanto a didattica 3', 'design_scuole_italia' ),
----------------------------------------------------------------------------------------------------------------------------------------------
PER AGGIUNGERE MENU UGUALI A QUELLI DI PRIMO LIVELLO
Aspetto->Editor del tema->header.php
RIGA 397

}
                                ?>
								
								<?php
                                // check if Menù accanto a didattica 1 has menu
                                $numero=5;
								$theme_location = "menu-personale-".$numero;
                                unset($menu_obj);
                                if(isset($theme_locations[$theme_location]))
									{$menu_obj = get_term( $theme_locations[$theme_location], 'nav_menu' );}
                                    
                                if(isset($menu_obj) && !is_wp_error($menu_obj)) {
                                        $items_wrap = '<ul class="%2$s">%3$s</ul>';

                                    ?>
                                    <li class="menu-dropdown-simple-wrapper">
										<a class="nav-link dropdown-toggle" style="color: #a52a2a !important;" data-toggle="dropdown" role="button" href="#" aria-expanded="false" id="mainNavDropdown<?php echo $numero ?>" data-focus-mouse="false"><?php echo $menu_obj->name; ?></a>
                                        <div class="dropdown-menu menu-dropdown dl-submenu menu-dropdown-simple"  aria-labelledby="mainNavDropdown<?php echo $numero ?>">
                                            <div class="link-list-wrapper">
                                                <?php wp_nav_menu(array(
                                                    "menu" => $menu_obj, 
                                                    "items_wrap" => $items_wrap,
                                                    "depth" => 1, 
                                                    "menu_class" => "link-list", 
                                                    "container" => "", 
                                                    "walker" => new Header_Menu_Walker()
                                                )) ?>
                                            </div>
                                        </div>
                                    </li>
                                    <?php
                                }
                                ?>
								
								<?php
                                // check if Menù accanto a didattica 2 has menu
                                $numero++;
                                $theme_location = "menu-personale-".$numero;
                                unset($menu_obj);
                                if(isset($theme_locations[$theme_location]))
									{$menu_obj = get_term( $theme_locations[$theme_location], 'nav_menu' );}
                                    
                                if(isset($menu_obj) && !is_wp_error($menu_obj)) {
                                        $items_wrap = '<ul class="%2$s">%3$s</ul>';

                                    ?>
                                    <li class="menu-dropdown-simple-wrapper">
										<a class="nav-link dropdown-toggle" style="color: #ff69b4 !important;" data-toggle="dropdown" role="button" href="#" aria-expanded="false" id="mainNavDropdown<?php echo $numero ?>" data-focus-mouse="false"><?php echo $menu_obj->name; ?></a>
                                        <div class="dropdown-menu menu-dropdown dl-submenu menu-dropdown-simple"  aria-labelledby="mainNavDropdown<?php echo $numero ?>">
                                            <div class="link-list-wrapper">
                                                <?php wp_nav_menu(array(
                                                    "menu" => $menu_obj, 
                                                    "items_wrap" => $items_wrap,
                                                    "depth" => 1, 
                                                    "menu_class" => "link-list", 
                                                    "container" => "", 
                                                    "walker" => new Header_Menu_Walker()
                                                )) ?>
                                            </div>
                                        </div>
                                    </li>
                                    <?php
                                }
                                ?>
								
								<?php
                                // check if Menù accanto a didattica 3 has menu
                                $numero++;
                                $theme_location = "menu-personale-".$numero;
                                unset($menu_obj);
                                if(isset($theme_locations[$theme_location]))
									{$menu_obj = get_term( $theme_locations[$theme_location], 'nav_menu' );}
                                    
                                if(isset($menu_obj) && !is_wp_error($menu_obj)) {
                                        $items_wrap = '<ul class="%2$s">%3$s</ul>';

                                    ?>
                                    <li class="menu-dropdown-simple-wrapper">
										<a class="nav-link dropdown-toggle" style="color: #808080 !important;" data-toggle="dropdown" role="button" href="#" aria-expanded="false" id="mainNavDropdown<?php echo $numero ?>" data-focus-mouse="false"><?php echo $menu_obj->name; ?></a>
                                        <div class="dropdown-menu menu-dropdown dl-submenu menu-dropdown-simple"  aria-labelledby="mainNavDropdown<?php echo $numero ?>">
                                            <div class="link-list-wrapper">
                                                <?php wp_nav_menu(array(
                                                    "menu" => $menu_obj, 
                                                    "items_wrap" => $items_wrap,
                                                    "depth" => 1, 
                                                    "menu_class" => "link-list", 
                                                    "container" => "", 
                                                    "walker" => new Header_Menu_Walker()
                                                )) ?>
                                            </div>
                                        </div>
                                    </li>
                                    <?php
                                }
                                ?>

a.	RIGA 264
<ul class="dl-menu nav-list nav-list-primary" data-element="menu">
								

b.	RIGA 189
 }
                                    ?>
<?php
                                    // check if Menù accanto a didattica 1 has menu
                                    $numero=5;
                                    $theme_location = "menu-personale-".$numero;
                                    unset($menu_obj);
                                    if(isset($theme_locations[$theme_location]))
                                        $menu_obj = get_term( $theme_locations[$theme_location], 'nav_menu' );
                                    if(isset($menu_obj) && !is_wp_error($menu_obj)) {
										$items_wrap = '<ul  aria-labelledby="mainNavDropdown'.$numero.'" id="%1$s" class="%2$s">%3$s</ul>';
                                        ?>
                                        <li class="menu-dropdown-simple-wrapper">
											<a class="toggle-dropdown toggle-dropdown-simple keychainify-checked" style="color: #a52a2a !important;" role="button" href="#" aria-expanded="false" id="mainNavDropdown<?php echo $numero; ?>" data-focus-mouse="false"><?php echo $menu_obj->name; ?></a>
                                            <?php wp_nav_menu(array(
                                                "menu" => $menu_obj, 
                                                "items_wrap" => $items_wrap,
                                                "depth" => 1, 
                                                "menu_class" => "menu-dropdown dl-submenu menu-dropdown-simple",
                                                "container" => "", 
                                                "walker" => new Mobile_Header_Menu_Walker()
                                            )) ?>
                                        </li>
                                        <?php
                                    }
                                    ?>
									
									<?php
                                    // check if Menù accanto a didattica 2 has menu
                                    $numero++;
                                    $theme_location = "menu-personale-".$numero;
                                    unset($menu_obj);
                                    if(isset($theme_locations[$theme_location]))
                                        $menu_obj = get_term( $theme_locations[$theme_location], 'nav_menu' );
                                    if(isset($menu_obj) && !is_wp_error($menu_obj)) {
										$items_wrap = '<ul  aria-labelledby="mainNavDropdown'.$numero.'" id="%1$s" class="%2$s">%3$s</ul>';
                                        ?>
                                        <li class="menu-dropdown-simple-wrapper">
											<a class="toggle-dropdown toggle-dropdown-simple keychainify-checked" style="color: #ff69b4 !important;" role="button" href="#" aria-expanded="false" id="mainNavDropdown<?php echo $numero; ?>" data-focus-mouse="false"><?php echo $menu_obj->name; ?></a>
                                            <?php wp_nav_menu(array(
                                                "menu" => $menu_obj, 
                                                "items_wrap" => $items_wrap,
                                                "depth" => 1, 
                                                "menu_class" => "menu-dropdown dl-submenu menu-dropdown-simple",
                                                "container" => "", 
                                                "walker" => new Mobile_Header_Menu_Walker()
                                            )) ?>
                                        </li>
                                        <?php
                                    }
                                    ?>
									
									<?php
                                    // check if Menù accanto a didattica 3 has menu
                                    $numero++;
                                    $theme_location = "menu-personale-".$numero;
                                    unset($menu_obj);
                                    if(isset($theme_locations[$theme_location]))
                                        $menu_obj = get_term( $theme_locations[$theme_location], 'nav_menu' );
                                    if(isset($menu_obj) && !is_wp_error($menu_obj)) {
										$items_wrap = '<ul  aria-labelledby="mainNavDropdown'.$numero.'" id="%1$s" class="%2$s">%3$s</ul>';
                                        ?>
                                        <li class="menu-dropdown-simple-wrapper">
											<a class="toggle-dropdown toggle-dropdown-simple keychainify-checked" style="color: #808080 !important;" role="button" href="#" aria-expanded="false" id="mainNavDropdown<?php echo $numero; ?>" data-focus-mouse="false"><?php echo $menu_obj->name; ?></a>
                                            <?php wp_nav_menu(array(
                                                "menu" => $menu_obj, 
                                                "items_wrap" => $items_wrap,
                                                "depth" => 1, 
                                                "menu_class" => "menu-dropdown dl-submenu menu-dropdown-simple",
                                                "container" => "", 
                                                "walker" => new Mobile_Header_Menu_Walker()
                                            )) ?>
                                        </li>
                                        <?php
                                    }
                                    ?>

c.	RIGA 73
<ul class="dl-menu nav-list nav-list-primary" data-element="menu">

`

**Comment by Jamielrey** [comment]
> > Io ho aggiunto altre 3 voci al menù principale, ma le ho disabilitate da poco perché l'app di controllo mi segnalava in giallo per l'aggiunta di queste voci. Se volete vi passo comunque il codice. ![menu](https://user-images.githubusercontent.com/124105310/215920323-73f20c70-86e3-4af9-9024-a423fd5869ec.jpg)
> 
> Salve, capisco che segni in giallo, ma si potrebbe avere comunque il codice ? Grazie mille

Ciao, ti passo gli appunti che mi ero salvato. Sono un po' lunghi ma spero si capiscano. Considera però che salgono alla versione del template di febbraio, non credo sia cambiato qualcosa, ma assicurati che le righe siano corrispondenti. Ovviamente ti consiglio di fare prima una prova in locale, poi un bel backup del sito e poi la prova sul sito della scuola. 
Io questo codice l'ho usato poco e niente perché non volevo quella segnalazione gialla.

```
AGGIUNGERE NUOVI MENU:
1)	Aspetto->Editor del tema->functions.php
Aggiungere dopo la riga 160:
'menu-personale-5' => esc_html__( 'Menù accanto a didattica 1', 'design_scuole_italia' ),
'menu-personale-6' => esc_html__( 'Menù accanto a didattica 2', 'design_scuole_italia' ),
'menu-personale-7' => esc_html__( 'Menù accanto a didattica 3', 'design_scuole_italia' ),
----------------------------------------------------------------------------------------------------------------------------------------------
PER AGGIUNGERE MENU UGUALI A QUELLI DI PRIMO LIVELLO
Aspetto->Editor del tema->header.php
RIGA 397

}
                                ?>
								
								<?php
                                // check if Menù accanto a didattica 1 has menu
                                $numero=5;
								$theme_location = "menu-personale-".$numero;
                                unset($menu_obj);
                                if(isset($theme_locations[$theme_location]))
									{$menu_obj = get_term( $theme_locations[$theme_location], 'nav_menu' );}
                                    
                                if(isset($menu_obj) && !is_wp_error($menu_obj)) {
                                        $items_wrap = '<ul class="%2$s">%3$s</ul>';

                                    ?>
                                    <li class="menu-dropdown-simple-wrapper">
										<a class="nav-link dropdown-toggle" style="color: #a52a2a !important;" data-toggle="dropdown" role="button" href="#" aria-expanded="false" id="mainNavDropdown<?php echo $numero ?>" data-focus-mouse="false"><?php echo $menu_obj->name; ?></a>
                                        <div class="dropdown-menu menu-dropdown dl-submenu menu-dropdown-simple"  aria-labelledby="mainNavDropdown<?php echo $numero ?>">
                                            <div class="link-list-wrapper">
                                                <?php wp_nav_menu(array(
                                                    "menu" => $menu_obj, 
                                                    "items_wrap" => $items_wrap,
                                                    "depth" => 1, 
                                                    "menu_class" => "link-list", 
                                                    "container" => "", 
                                                    "walker" => new Header_Menu_Walker()
                                                )) ?>
                                            </div>
                                        </div>
                                    </li>
                                    <?php
                                }
                                ?>
								
								<?php
                                // check if Menù accanto a didattica 2 has menu
                                $numero++;
                                $theme_location = "menu-personale-".$numero;
                                unset($menu_obj);
                                if(isset($theme_locations[$theme_location]))
									{$menu_obj = get_term( $theme_locations[$theme_location], 'nav_menu' );}
                                    
                                if(isset($menu_obj) && !is_wp_error($menu_obj)) {
                                        $items_wrap = '<ul class="%2$s">%3$s</ul>';

                                    ?>
                                    <li class="menu-dropdown-simple-wrapper">
										<a class="nav-link dropdown-toggle" style="color: #ff69b4 !important;" data-toggle="dropdown" role="button" href="#" aria-expanded="false" id="mainNavDropdown<?php echo $numero ?>" data-focus-mouse="false"><?php echo $menu_obj->name; ?></a>
                                        <div class="dropdown-menu menu-dropdown dl-submenu menu-dropdown-simple"  aria-labelledby="mainNavDropdown<?php echo $numero ?>">
                                            <div class="link-list-wrapper">
                                                <?php wp_nav_menu(array(
                                                    "menu" => $menu_obj, 
                                                    "items_wrap" => $items_wrap,
                                                    "depth" => 1, 
                                                    "menu_class" => "link-list", 
                                                    "container" => "", 
                                                    "walker" => new Header_Menu_Walker()
                                                )) ?>
                                            </div>
                                        </div>
                                    </li>
                                    <?php
                                }
                                ?>
								
								<?php
                                // check if Menù accanto a didattica 3 has menu
                                $numero++;
                                $theme_location = "menu-personale-".$numero;
                                unset($menu_obj);
                                if(isset($theme_locations[$theme_location]))
									{$menu_obj = get_term( $theme_locations[$theme_location], 'nav_menu' );}
                                    
                                if(isset($menu_obj) && !is_wp_error($menu_obj)) {
                                        $items_wrap = '<ul class="%2$s">%3$s</ul>';

                                    ?>
                                    <li class="menu-dropdown-simple-wrapper">
										<a class="nav-link dropdown-toggle" style="color: #808080 !important;" data-toggle="dropdown" role="button" href="#" aria-expanded="false" id="mainNavDropdown<?php echo $numero ?>" data-focus-mouse="false"><?php echo $menu_obj->name; ?></a>
                                        <div class="dropdown-menu menu-dropdown dl-submenu menu-dropdown-simple"  aria-labelledby="mainNavDropdown<?php echo $numero ?>">
                                            <div class="link-list-wrapper">
                                                <?php wp_nav_menu(array(
                                                    "menu" => $menu_obj, 
                                                    "items_wrap" => $items_wrap,
                                                    "depth" => 1, 
                                                    "menu_class" => "link-list", 
                                                    "container" => "", 
                                                    "walker" => new Header_Menu_Walker()
                                                )) ?>
                                            </div>
                                        </div>
                                    </li>
                                    <?php
                                }
                                ?>

a.	RIGA 264
<ul class="dl-menu nav-list nav-list-primary" data-element="menu">
								<!--<li class="menu-dropdown-simple-wrapper"><a style="color: #000000 !important;" class="nav-link dropdown-toggle keychainify-checked" href="<?php echo home_url(); ?>">Home</a></li>-->

b.	RIGA 189
 }
                                    ?>
<?php
                                    // check if Menù accanto a didattica 1 has menu
                                    $numero=5;
                                    $theme_location = "menu-personale-".$numero;
                                    unset($menu_obj);
                                    if(isset($theme_locations[$theme_location]))
                                        $menu_obj = get_term( $theme_locations[$theme_location], 'nav_menu' );
                                    if(isset($menu_obj) && !is_wp_error($menu_obj)) {
										$items_wrap = '<ul  aria-labelledby="mainNavDropdown'.$numero.'" id="%1$s" class="%2$s">%3$s</ul>';
                                        ?>
                                        <li class="menu-dropdown-simple-wrapper">
											<a class="toggle-dropdown toggle-dropdown-simple keychainify-checked" style="color: #a52a2a !important;" role="button" href="#" aria-expanded="false" id="mainNavDropdown<?php echo $numero; ?>" data-focus-mouse="false"><?php echo $menu_obj->name; ?></a>
                                            <?php wp_nav_menu(array(
                                                "menu" => $menu_obj, 
                                                "items_wrap" => $items_wrap,
                                                "depth" => 1, 
                                                "menu_class" => "menu-dropdown dl-submenu menu-dropdown-simple",
                                                "container" => "", 
                                                "walker" => new Mobile_Header_Menu_Walker()
                                            )) ?>
                                        </li>
                                        <?php
                                    }
                                    ?>
									
									<?php
                                    // check if Menù accanto a didattica 2 has menu
                                    $numero++;
                                    $theme_location = "menu-personale-".$numero;
                                    unset($menu_obj);
                                    if(isset($theme_locations[$theme_location]))
                                        $menu_obj = get_term( $theme_locations[$theme_location], 'nav_menu' );
                                    if(isset($menu_obj) && !is_wp_error($menu_obj)) {
										$items_wrap = '<ul  aria-labelledby="mainNavDropdown'.$numero.'" id="%1$s" class="%2$s">%3$s</ul>';
                                        ?>
                                        <li class="menu-dropdown-simple-wrapper">
											<a class="toggle-dropdown toggle-dropdown-simple keychainify-checked" style="color: #ff69b4 !important;" role="button" href="#" aria-expanded="false" id="mainNavDropdown<?php echo $numero; ?>" data-focus-mouse="false"><?php echo $menu_obj->name; ?></a>
                                            <?php wp_nav_menu(array(
                                                "menu" => $menu_obj, 
                                                "items_wrap" => $items_wrap,
                                                "depth" => 1, 
                                                "menu_class" => "menu-dropdown dl-submenu menu-dropdown-simple",
                                                "container" => "", 
                                                "walker" => new Mobile_Header_Menu_Walker()
                                            )) ?>
                                        </li>
                                        <?php
                                    }
                                    ?>
									
									<?php
                                    // check if Menù accanto a didattica 3 has menu
                                    $numero++;
                                    $theme_location = "menu-personale-".$numero;
                                    unset($menu_obj);
                                    if(isset($theme_locations[$theme_location]))
                                        $menu_obj = get_term( $theme_locations[$theme_location], 'nav_menu' );
                                    if(isset($menu_obj) && !is_wp_error($menu_obj)) {
										$items_wrap = '<ul  aria-labelledby="mainNavDropdown'.$numero.'" id="%1$s" class="%2$s">%3$s</ul>';
                                        ?>
                                        <li class="menu-dropdown-simple-wrapper">
											<a class="toggle-dropdown toggle-dropdown-simple keychainify-checked" style="color: #808080 !important;" role="button" href="#" aria-expanded="false" id="mainNavDropdown<?php echo $numero; ?>" data-focus-mouse="false"><?php echo $menu_obj->name; ?></a>
                                            <?php wp_nav_menu(array(
                                                "menu" => $menu_obj, 
                                                "items_wrap" => $items_wrap,
                                                "depth" => 1, 
                                                "menu_class" => "menu-dropdown dl-submenu menu-dropdown-simple",
                                                "container" => "", 
                                                "walker" => new Mobile_Header_Menu_Walker()
                                            )) ?>
                                        </li>
                                        <?php
                                    }
                                    ?>

c.	RIGA 73
<ul class="dl-menu nav-list nav-list-primary" data-element="menu">
<!--<li class="menu-dropdown-simple-wrapper"><a style="color: #000000 !important;" class="nav-link dropdown-toggle keychainify-checked" href="<?php echo home_url(); ?>">Home</a></li>-->

```
