### ISSUE TITLE
Bug dopo aggiornamento alla versione 2.0.2 del tema

### ISSUE THREAD

**Issue by Simsimus** [italia/design-scuole-wordpress-theme#132]
Come da oggetto, dopo l'aggiornamento alla versione 2.0.2 del tema, nel backend sono scomparse le voci di menù "Articoli" e "Documenti" e risultano duplicate le voci "Pagine" e "Strutture".
Spero venga pubblicato al più presto un fix risolutivo.

**Comment by zetareticoli** [comment]
Ciao, il problema è stato risolto nella PR #123
