### ISSUE TITLE
Immagini predefinite per servizi, luoghi, eventi, notizie, progetti

### ISSUE THREAD

**Issue by vcoopcsc** [italia/design-scuole-wordpress-theme#134]
Buongiorno, 

ho notato che, per **i servizi, i luoghi, gli eventi, le notizie** rispetto alla versione precedente, sono scomparse le immagini predefinite che comparivano nel caso in cui l'istituto non avesse alcuna immagine principale da inserire (come accade ancora per le strutture per capirci).
Questo attualmente comporta il fatto di avere un enorme spazio vuoto che graficamente non è il massimo da vedere. Per i servizi la conseguenza è anche uno spostamento a destra ingiustificato. 
<img width="1101" alt="image" src="https://user-images.githubusercontent.com/92174841/192525114-ea2ad082-3494-45a3-8ebc-ddaf42dbd98a.png">
<img width="1126" alt="image" src="https://user-images.githubusercontent.com/92174841/192525406-288e3a9a-48f7-41ca-af47-8d8e81441733.png">

Segnalo poi che per i **progetti** invece, qualora non venga inserita l'immagine principale compare un rettangolo grigio-blu.
<img width="800" alt="image" src="https://user-images.githubusercontent.com/92174841/192531818-609a9e28-5c84-446d-9b6b-5f2e4ff75ebb.png">

Grazie in anticipo,

Valentina

**Comment by astagi** [comment]
Grazie del report @vcoopcsc il comportamento desiderato sarebbe quello di rimuovere gli spazi se non presente un contenuto, ho capito bene?

**Comment by vcoopcsc** [comment]
Il comportamento desiderato è o quello di togliere gli spazi riadattando il testo o quello di riempirli con delle immagini predefinite come avviene nell'attuale versione pubblicando un contenuto di tipo struttura senza immagine. 
Grazie a voi!

**Comment by astagi** [comment]
Cc @zetareticoli

**Comment by zetareticoli** [comment]
Ciao @vcoopcsc , intendi immagini come questa sotto in allegato?
![Schermata 2022-10-07 alle 15 17 29](https://user-images.githubusercontent.com/69706/194562972-b8375c38-91b7-42e2-99b6-e3416e89c8af.png)

**Comment by vcoopcsc** [comment]
Esatto, o come questa 
<img width="1128" alt="image" src="https://user-images.githubusercontent.com/92174841/194581838-a27d7b0b-b66c-4785-b773-f450e4389276.png">

**Comment by vcoopcsc** [comment]
Confermo che il problema persiste anche nell'ultima versione.

**Comment by astagi** [comment]
Creare immagini placeholder decorative da mettere nello spazio bianco/grigio.
