### ISSUE TITLE
Errori riguardanti gli eventi

### ISSUE THREAD

**Issue by vcoopcsc** [italia/design-scuole-wordpress-theme#135]
Buongiorno, 

con la nuova versione c'è un problema di gestione della galleria foto video: 

- se pubblico un evento senza inserire né foto né video nella galleria, in basso mi compare comunque la sezione "Foto e video" vuota
- se pubblico delle foto nella galleria dell'evento mi compaiono sia sotto nella sezione "foto e video" sia sotto la parte di descrizione dell'evento 

<img width="1128" alt="image" src="https://user-images.githubusercontent.com/92174841/192748229-c395e261-1bd3-4f1d-8166-2138212a7a7f.png">
<img width="1111" alt="image" src="https://user-images.githubusercontent.com/92174841/192748420-f0244792-d6bb-43dc-947c-7653953c4016.png">

Inoltre, la sezione "Eventi" cambia a seconda che io sia loggata o meno:  

- quando sono loggata, si visualizzano correttamente solo gli eventi non ancora verificatisi, con in fondo il button: "Consulta l'archivio".
- quando si è disconnessi invece, quindi in modalità pubblica, gli eventi sono tutti mischiati e nonostante ci siano i button "Consulta l'archivio" e "consulta gli eventi futuri" la visualizzazione non cambia.

Grazie in anticipo per l'aiuto

**Comment by Odraode04** [comment]
Si conferma la presenza della sezione foto e video vuota quando l'evento non contiene né foto né video.

Wordpress 6.1.1
Php 8.1.6
Tema 2.1.0

**Comment by astagi** [comment]
Grazie @Odraode04 per la PR! @vcoopcsc facciamo dei test e appena integriamo possiamo ritenere risolta la problematica
