### ISSUE TITLE
Problema d'installazione

### ISSUE THREAD

**Issue by AriotaG** [italia/design-scuole-wordpress-theme#14]
Sto provando ad installare il tema su un WP 5.3.1 pulito, PHP 7.3 ma gli errori iniziali sono  relativi ai richiami require "vendor/CMB2/init.php"; 
Commentata questa riga (riga 3 del file /wp-content/themes/design-scuole-wordpress-theme-master/inc/cmb2.php)

riesco a vedere il sito ma nell'backend gli errori sono tanti

> Notice: Undefined offset: 2 in wp-content/themes/design-scuole-wordpress-theme-master/inc/vendor/wp-admin-menu-classes.php on line 321
> Notice: Undefined offset: 2 in wp-content/themes/design-scuole-wordpress-theme-master/inc/vendor/wp-admin-menu-classes.php on line 145
> Notice: Undefined offset: 2 in wp-content/themes/design-scuole-wordpress-theme-master/inc/vendor/wp-admin-menu-classes.php on line 145
> Notice: Undefined offset: 2 in wp-content/themes/design-scuole-wordpress-theme-master/inc/vendor/wp-admin-menu-classes.php on line 145
> Notice: Undefined offset: 1 in wp-admin/includes/menu.php on line 163
> Notice: Undefined offset: 2 in wp-admin/includes/menu.php on line 164
> Notice: Undefined offset: 2 in wp-admin/includes/menu.php on line 171
> Notice: Undefined offset: 2 in wp-admin/includes/menu.php on line 180
> Notice: Undefined offset: 2 in wp-admin/includes/menu.php on line 182
> 

Come posso risolvere? problema già riscontrato?

**Comment by AriotaG** [comment]
> Notice: Undefined offset: 2 in /var/www/vhosts/scolasticaweb.it/httpdocs/wp-content/themes/design-scuole-wordpress-theme-master/inc/vendor/wp-admin-menu-classes.php on line 145
> 
> Notice: Undefined offset: 2 in /var/www/vhosts/scolasticaweb.it/httpdocs/wp-content/themes/design-scuole-wordpress-theme-master/inc/vendor/wp-admin-menu-classes.php on line 145
> 
> Notice: Undefined offset: 2 in /var/www/vhosts/scolasticaweb.it/httpdocs/wp-content/themes/design-scuole-wordpress-theme-master/inc/vendor/wp-admin-menu-classes.php on line 145
> 
> Notice: Undefined offset: 2 in /var/www/vhosts/scolasticaweb.it/httpdocs/wp-admin/includes/plugin.php on line 1369
> 
> Notice: Undefined offset: 1 in /var/www/vhosts/scolasticaweb.it/httpdocs/wp-admin/includes/menu.php on line 163
> 
> Notice: Undefined offset: 2 in /var/www/vhosts/scolasticaweb.it/httpdocs/wp-admin/includes/menu.php on line 164
> 
> Notice: Undefined offset: 2 in /var/www/vhosts/scolasticaweb.it/httpdocs/wp-admin/includes/menu.php on line 171
> 
> Notice: Undefined offset: 2 in /var/www/vhosts/scolasticaweb.it/httpdocs/wp-admin/includes/menu.php on line 180
> 
> Notice: Undefined offset: 2 in /var/www/vhosts/scolasticaweb.it/httpdocs/wp-admin/includes/menu.php on line 182
> 
> Non hai il permesso di accedere a questa pagina.

**Comment by webgrafia** [comment]
credo sia normale l'errore se hai commentato l'include di cmb2.
Perchè lo hai commentato?
Hai scaricato il tema seguendo le indicazioni del readme?:
li riporto qui:

git clone https://github.com/italia/design-scuole-wordpress-theme.git
cd design-scuole-wordpress-theme/
git submodule init
git submodule update

**Comment by AriotaG** [comment]
Ovviamente, ma stavo semplicemente cercando di venire a capo dell'errore iniziale.
No, l'installazione è stata fatta semplicemente includendo il tema in WordPress, l'errore sarà appunto questo.

**Comment by AriotaG** [comment]
qui stavo testando il tutto https://scolasticaweb.it/

**Comment by AriotaG** [comment]
Buongiorno, proprio non riesco a risolvere il problema, potete aiutarmi?

**Comment by AriotaG** [comment]
all'interno del tema manca a questo percorso design-scuole-wordpress-theme-master/inc/vendor/CMB2/il file init.php

**Comment by webgrafia** [comment]
ciao, hai scaricato il tema tramite un client git seguendo le istruzioni che ti avevo mandato, e ti da ancora lo stesso problema?
Esegui:
git clone https://github.com/italia/design-scuole-wordpress-theme.git
cd design-scuole-wordpress-theme/
git submodule init
git submodule update

Alla fine dovresti avere un pacchetto completo senza errori

**Comment by AriotaG** [comment]
Ciao e grazie 1000 per la risposta.
Purtroppo come vedi, si il problema nonostante la procedura si è ripresentato.
L'errore che mi segnalava era l'assenza di un file init.php del CMB2 

Ho anche riprovato, ma nulla !!!

**Comment by webgrafia** [comment]
dentro inc/vendor hai la cartella CMB2?

**Comment by AriotaG** [comment]
si, certo

**Comment by AriotaG** [comment]
/var/www/vhosts/scolasticaweb.it/httpdocs/wp-content/themes/design-scuole-wordpress-theme/inc/vendor/CMB2

**Comment by webgrafia** [comment]
ho appena rifatto la procedura e nella cartella CMB2 divresti avere questi file, Dentro c'è il init.php, tu lo hai?

apigen         CHANGELOG.md   composer.lock    coverage.clover  Dockunit.json          Gruntfile.js  includes   init.php  languages     package-lock.json  README.md   tests
bootstrap.php  composer.json  CONTRIBUTING.md  css              example-functions.php  images        index.php  js        package.json  phpunit.xml.dist   readme.txt

BTW: rileggendo il post iniziale, vedo che i messaggi che noti sono  notice. Limita la visualizzazione sul frontend agli errori, le notice sono indicazioni che non generano problemi

**Comment by AriotaG** [comment]
:( no! purtroppo no

**Comment by webgrafia** [comment]
Allora hai avuto qualche intoppo nell'aggiornamento dei moduli probabilmente ha fallito la submodule update, controlla permessi delle directory e messaggi durante la procedura.

**Comment by AriotaG** [comment]
Perfetto tutto ok, grazie 1000
adesso va che è una meraviglia, ottimo lavoro!

**Comment by webgrafia** [comment]
Bene, poi scrivi qui cosa avevi sbagliato e come hai risolto, e chiudi il commento. 
Potrebbe essere di aiuto ad altri

**Comment by oscarbadoino** [comment]
@AriotaG puoi dirmi quale sia stato il problema? anch'io ho lo stesso identico problema quindi mi sarebbe utilissimo capire cosa sia successo 
cc 
@webgrafia

**Comment by AriotaG** [comment]
@oscarbadoino certo, innanzitutto mi scuso, avrei voluto scrivere prima ma purtroppo il lavoro degli ultimi giorni prima delle ferie natalizie...
Sul mio server utilizzo PLESK, sebbene con l'installazione sia dell'estensione git sia con la semplice procedura che veniva indicato, il richiamo all'installazione non andava a buon fine.
Inizialmente credevo ci fosse un problema al codice del tema, poi confrontandomi gentilmente con @webgrafia che probabilmente non aveva intuito immediatamente il problema, ci siamo accorti che uno dei files (vedere post precedenti), non veniva generato e caricato.
Tutto però dipendeva da un problema mio di richiamo e quindi non dal tema che è ben fatto nello sviluppo (permettetemi solo di aggiungere che qualche possibilità di personalizzazione per il personale scolastico che non conosce alcun tipo di codice, potevate lasciarlo :) )

PER CONCLUDERE
Io ho risolto accedendo da SSH, portandomi semplicemente nella cartella ... /wp-content/themes/ installare la dipendenza .git seguire la procedura indicata 

> git clone https://github.com/italia/design-scuole-wordpress-theme.git
> cd design-scuole-wordpress-theme/
> git submodule init
> git submodule update

e per quel che mi riguarda, successivamente rivedere i permessi di gruppo
VALE SOLO PER PLESK

> cd /var/www/vhosts/nomedominio.it  
> chown -R nomeutente:psacln httpdocs  (cambia tutta la directory)
> chown nomeutente:psaserv httpdocs   (cambia la sola cartella)

Nulla di che insomma.
