### ISSUE TITLE
Richiesta Top Menu Secondario (in alto a destra)

### ISSUE THREAD

**Issue by Simsimus** [italia/design-scuole-wordpress-theme#142]
Salve,
attualmente il Top Menu Secondario (in alto a destra) mostra solo voci di primo livello:
posso suggerire di consentire l'aggiunta di voci di secondo livello?
Sarebbe ottimo arrivare fino al terzo livello, ma anche il secondo rappresenterebbe una più concreta suddivisione delle varie aree spesso necessarie nelle scuole.
Grazie

**Comment by CampusDaVinci** [comment]
Si, sarebbe un'ottima idea, soprattutto in fase di Orientamento ed altre situazioni di questo tipo.

**Comment by CampusDaVinci** [comment]
Ci sono novità riguardo questa possibilità ?

**Comment by Simsimus** [comment]
Spero che gli sviluppatori del tema stiamo prendendo in considerazione tale possibilità perchè diventa sempre più necessaria per le scuole...

**Comment by CampusDaVinci** [comment]
Salve, ci sono novità per questa funzione ?

**Comment by zetareticoli** [comment]
Ciao, il menu in oggetto viene utilizzato per promuovere degli argomenti in evidenza in header.

Come tali, non esistono livelli primari o secondari di navigazione.

**Comment by CampusDaVinci** [comment]
Ok, ma se servono altre voci di menù come si fa ?
Nei menù "ufficiali" non si possono aggiungere, in quello secondario non è consentito il 2° livello... allora come si fa ?
Grazie mille

**Comment by marcogasparini72** [comment]
Interesserebbe anche a me poterlo fare. In scuole "speciali" come i CPIA (che il modello offerto non contempla e per adattarlo ho fatto i salti mortali) o in scuole capofila di reti e progetti i menu standard sono decisamente limitanti.
