### ISSUE TITLE
Formattazione

### ISSUE THREAD

**Issue by dg7dd** [italia/design-scuole-wordpress-theme#143]
Nella versione 2.0.2 e 2.0.3, il testo dei link non è colorato ma uguale al corpo del testo: i link così non risultano identificabili al lettore.

Inoltre, le immagini pubblicate nel corpo del testo delle pagine (Articoli, Servizi, Strutture ecc..), se di grandi dimensioni non sono responsive e fuoriescono dalla impaginazione.

**Comment by astagi** [comment]
@dg7dd grazie della segnalazione potresti inserire qualche screenshot giusto per riprodurre il problema?

Grazie!

**Comment by Simsimus** [comment]
Buongiorno,
mi associo a tale richiesta perchè link colorato e immagini responsive sono importanti per una buona navigazione e accessibilità dei dati.
Grazie

**Comment by dg7dd** [comment]
A che punto siamo con questo problema? 
Sarebbe urgente risolverlo, anche perché siamo in periodo di Orientamento e molti utenti stanno visitando il sito...
Un saluto e grazie come sempre!

**Comment by astagi** [comment]
Ciao @dg7dd lo abbiamo schedulato per lunedì come lavorazione, se hai modo di entrare su canale Slack vista l'urgenza possiamo anche sentirci direttamente per validare la correzione! Grazie a te!

**Comment by dg7dd** [comment]
Ah ok, perfetto per lunedì👍🏻

**Comment by astagi** [comment]
Con alcune regole custom css riusciamo a inserire i link all'interno degli articoli e arginare l'overflow delle immagini

<img width="205" alt="image" src="https://user-images.githubusercontent.com/537363/207050258-e0166b2c-1590-453b-b98b-07d5e58c60de.png">

**Comment by astagi** [comment]
Risolto qua, presente nel commit https://github.com/italia/design-scuole-wordpress-theme/commit/efdb0583e3e0e8620252371c2bba7d4aa85864e6 e nella versione `2.1.4` del tema.
