### ISSUE TITLE
Problema con Elementor Page Builder

### ISSUE THREAD

**Issue by CampusDaVinci** [italia/design-scuole-wordpress-theme#144]
Quando si prova ad usare Elementor come Page Builder, i contenuti creati con esso vanno a finire in più parti della pagina.
Per esempio, nella sezione "Indirizzi di Studio" compaiono dopo la "descrizione estesa" e dopo "Programma di studio"
Ed il campo "descrizione estesa" non è più editabile.

**Comment by astagi** [comment]
Ciao @CampusDaVinci questo va un attimo verificato, non sono esperto di Elementor. Puoi fornire qualche screenshot?

**Comment by astagi** [comment]
@zetareticoli potrebbe aver senso metterlo in consolidamento?
