### ISSUE TITLE
Possibilità di reindirizzare le voci di menù Albo, Circolari e altro a link esterni

### ISSUE THREAD

**Issue by CampusDaVinci** [italia/design-scuole-wordpress-theme#145]
Spesso le scuole utilizzano servizi esterni per pubblicare l'albo e le circolari e cambiare il flusso di lavoro e le "abitudini" potrebbe essere molto complicato.
Sarebbe molto utile dare la possibilità di inserire una URL per queste posizioni esterne al di fuori dell'ambito della sezione "Servizi Esterni" perché sono semplicemente link esterni che devono essere raggiunti al posto di quelli esistenti e previsti nel sito.

**Comment by attiliopecora** [comment]
io ho semplicemente modificato la voce di menu
