### ISSUE TITLE
Assenza voce "Personalizza" nel menu "Aspetto"

### ISSUE THREAD

**Issue by CampusDaVinci** [italia/design-scuole-wordpress-theme#146]
La voce di sotto menù "Personalizza" non è presente nel menu "Aspetto" e quindi non è possibile cambiare la FAVICON del sito

**Comment by astagi** [comment]
Grazie @CampusDaVinci , ricordo che @aresuma aveva fatto qualcosa in merito al ripristino delle voci di menù, forse anche in questo caso andrebbe rifatto lo stesso (#123)

**Comment by aresuma** [comment]
Ciao, 
confermo che la voce di menu personalizza è assente da menu. La voce viene nascosta via codice sul file inc/actions.php.
Sul codice sono presenti diverse istruzioni che si occupano di nascondere tale voce di menu. Le istruzioni sono le seguenti:

```
// rimuovo customizer
add_action( 'admin_menu', function () {
    global $submenu;
    if ( isset( $submenu[ 'themes.php' ] ) ) {
        foreach ( $submenu[ 'themes.php' ] as $index => $menu_item ) {
            foreach ($menu_item as $value) {
                if (strpos($value,'customize') !== false) {
                    unset( $submenu[ 'themes.php' ][ $index ] );
                }
            }
        }
    }
});
```

Perché è stato voluto tale comportamento?

Comunque, la personalizzazione della favicon è ancora accessibile dalle impostazioni del tema:


![image](https://user-images.githubusercontent.com/26236487/200189853-a6a10127-78ab-4f65-9695-986b728040a6.png)
![image](https://user-images.githubusercontent.com/26236487/200189892-57d06162-4db7-4676-86f7-27bad3f1067e.png)
![image](https://user-images.githubusercontent.com/26236487/200189936-06daa30f-7845-48e9-a964-470abd98f005.png)

**Comment by astagi** [comment]
Grazie @aresuma possiamo chiudere la segnalazione
