### ISSUE TITLE
Mancata visualizzazione della mappa sul fondo della pagina del luoghi

### ISSUE THREAD

**Issue by vcoopcsc** [italia/design-scuole-wordpress-theme#147]
Buongiorno, 

rispetto alla versione 1 ho notato che **nella pagina dei luoghi la mappa non compare più in fondo alla pagina, nonostante io abbia flaggato l'opzione "Mappa in primo piano" "no" in Configurazione->Luoghi.** 
Se metto la mappa in primo piano compare correttamente a sinistra, ma se scelgo di non metterla in primo piano non appare in fondo alla pagina come accadeva prima correttamente nella v. 1 del tema. Allego screen

- Versione 2.0.3 visualizzazione in primo piano "Sì" 

<img width="799" alt="image" src="https://user-images.githubusercontent.com/92174841/196449155-78de1863-f576-4e11-89a4-e05420e51bc9.png">

- Versione 2.0.3 visualizzazione in primo piano "No"

<img width="800" alt="image" src="https://user-images.githubusercontent.com/92174841/196448096-97a6248a-5524-449e-89aa-78e5b8d6c492.png">

- Versione 1 visualizzazione in primo piano "No"

<img width="798" alt="image" src="https://user-images.githubusercontent.com/92174841/196448886-b6cacfb2-dec5-414c-be45-3e2ce7c9d889.png">

**Comment by astagi** [comment]
@vcoopcsc ho ripristinato l'ultima immagine, comunque si da segnalare, grazie!
