### ISSUE TITLE
Errore di impaginazione scheda progetti

### ISSUE THREAD

**Issue by vcoopcsc** [italia/design-scuole-wordpress-theme#149]
Buongiorno, 

Segnalo che nell'ultima versione del tema **la pagina dei progetti ha dei problemi di impaginazione**. Il contenuto sotto gli obiettivi è spostato tutto a sinistra in maniera disallineata con il resto. 
<img width="799" alt="image" src="https://user-images.githubusercontent.com/92174841/196479751-f9f04676-698e-4788-b537-19a64eba3d42.png">

Grazie in anticipo, buona serata!

**Comment by zetareticoli** [comment]
Ciao @vcoopcsc ,

grazie della segnalazione, ho verificato il [template statico](https://italia.github.io/design-scuole-pagine-statiche/scuole-scheda-progetto.html) e si comporta correttamente.
Verifichiamo il tema e in caso allineiamo i due template.
