### ISSUE TITLE
Icone social

### ISSUE THREAD

**Issue by Richard1984** [italia/design-scuole-wordpress-theme#15]
Buonasera, complimenti per l'ottimo lavoro. Sarebbe possibile aggiungere delle icone relative alle varie pagine social (es. pagina Facebook, Canale YouTube, Canale Telegram, ecc.)? Magari nella prima sezione in alto.

**Comment by webgrafia** [comment]
ciao Riccardo,
non è prevista la presenza dei link social in testata nei modelli grafici approvati.
Tengo comunque questa issue aperta come todo, appena chiudiamo i punti più critici per la gestione dei contenuti scolastici la elaboriamo. Nel frattempo puoi usare i link del footer, con un widget menu o un widget grafico ad hoc che puoi inserire in una delle colonne del footer

**Comment by webgrafia** [comment]
Aggiungo che se nel frattempo vuoi fare una pull request con una proposta di integrazione la accettiamo con piacere :)

**Comment by webgrafia** [comment]
ciao Riccardo, nell'ultima release abbiamo introdotto i link social, c'è una nuona pagina di configurazione per gestirli.
Compaiono in header e in footer, stiamo rilasciando dei piccoli fix css e di accessibilità, ma intanto se scarichi il repo aggiornato le trovi
