### ISSUE TITLE
Importando degli Articoli, non è possibile impostare il valore dell'abstract

### ISSUE THREAD

**Issue by CampusDaVinci** [italia/design-scuole-wordpress-theme#151]
Provando ad importare degli articoli con un file CSV, non è possibile impostare il valore del campo abstract
Il campo Excerpt viene importato ma poi non c'è modo di modificarlo

**Comment by zetareticoli** [comment]
Ciao @CampusDaVinci ,
potresti allegare uno screen del problema? Grazie
