### ISSUE TITLE
Consentire che un Servizio sia per Studenti/Famiglie E anche per Personale Scolastico

### ISSUE THREAD

**Issue by CampusDaVinci** [italia/design-scuole-wordpress-theme#153]
Attualmente durante la creazione di un servizio si può scegliere, alternativamente, se questo sia per Famiglie/Studenti o per Personale Scolastico
Sarebbe utile avere la possibilità di indicare un servizio che valga per entrambe le categorie in quanto ci sono dei casi (tipo la Segreteria Didattica) che servono a tutte e 2 le tipologie di utenza.

**Comment by sdi-sw** [comment]
Se entri dall'elenco dei Servizi, selezioni il servizio che vuoi e scegli "Azioni di gruppo" mettendo "Modifica" entri in una scheda in cui si possono selezionare entrambi.

E' una soluzione "fai da te" comunque in attesa può essere utile...

**Comment by astagi** [comment]
Direi che la soluzione di utilizzare le "azioni di gruppo" suggerita da @sdi-sw che ringrazio è quella corretta, per ora lasciamo questa soluzione e chiudiamo la issue.
