### ISSUE TITLE
Gestione documenti

### ISSUE THREAD

**Issue by Jhndo** [italia/design-scuole-wordpress-theme#155]
Buongiorno, non mi è chiaro come gestire la questione dei documenti messi a disposizione degli utenti.. Per esempio modulistica in pdf destinata ai genitori o al personale ATA o docenti (il materiale a disposizione dei genitori dovrebbe essere visibile a tutti, mentre l'area riservata dei docenti dovrebbe essere visibile dopo il login). Nella spiegazione dei content type su GitHub dice che La sezione documenti raccoglie tutti i documenti scolastici, dai file PDF ai documenti dell’albo online e della sezione amministrazione trasparente, ma nel menu della console di WP non trovo la sezione documenti, vedo solo la sezione Media. Qualcuno mi potrebbe aiutare a capire? Grazie mille

**Comment by zetareticoli** [comment]
Ciao @Jhndo , posso chiederti quale versione del tema stai usando?
Nella versione più recente esiste la voce "Documenti" dal menu di Wordpress (vedi allegato)
<img width="321" alt="menu-wp" src="https://user-images.githubusercontent.com/69706/199951822-38dce49c-e64d-44d1-9956-0e2260e567ca.png">

**Comment by Jhndo** [comment]
Grazie mille. Sì, stavo usando la versione 2.0.2. Ora ho aggiornato e ho visto.
