### ISSUE TITLE
Moment.js vulnerabile

### ISSUE THREAD

**Issue by lightuono** [italia/design-scuole-wordpress-theme#156]
Utilizzando il vostro validatore esce fuori che il vostro tema utilizza una libreria Javascript vulnerabile. 

![immagine](https://user-images.githubusercontent.com/116577839/198263529-997ebd38-dd34-4cb1-83ed-374833a527fe.png)

Qui anche il link con le vulnerabilità 

https://security.snyk.io/package/npm/moment

**Comment by astagi** [comment]
Grazie della segnalazione @lightuono  ho creato una PR https://github.com/italia/design-scuole-wordpress-theme/pull/157 avresti modo di verificare mergiandola se funziona e spariscono i warning? Grazie ancora

**Comment by mariantanase** [comment]
Ciao @astagi ,
Puoi inserire una PR anche per il modello comuni ?
Grazie

**Comment by astagi** [comment]
Grazie del check e della review @lightuono 

Sempre riguardo a moment.js @mariantanase ?

**Comment by astagi** [comment]
Trovato @mariantanase risolto anche su Comuni, a breve (domani penso) rilasciamo nuova versione per entrambi i temi
