### ISSUE TITLE
Ordine Eventi

### ISSUE THREAD

**Issue by dg7dd** [italia/design-scuole-wordpress-theme#158]
Gli Eventi vengono visualizzati in ordine cronologico in base alla data/ora di pubblicazione (dal più recente al meno recente), e non in base al calendario degli stessi. 
Ad esempio, l'ultimo evento che ho pubblicato è calendarizzato per il 13 gennaio 2023, ma risulta visualizzato come prossimo evento (prima di quelli calendarizzati per novembre e dicembre).

**Comment by astagi** [comment]
@dg7dd ti stai riferendo alla pagina eventi o nel pannello di amministrazione?

**Comment by dg7dd** [comment]
Alla pagina Eventi. 
Inoltre anche nella Home rimane sempre l'ultimo evento pubblicato, senza scorrere temporalmente a quello successivo (una volta terminato quello scaduto).

**Comment by astagi** [comment]
@dg7dd sarebbe corretto quindi questo ordine eventi giusto?

<img width="1306" alt="image" src="https://user-images.githubusercontent.com/537363/205696452-40e53da4-3ada-4fa7-a9e1-6d5de69ef667.png">

Controllo anche la home

**Comment by dg7dd** [comment]
Secondo me sì. Gli Eventi dovrebbero essere visualizzati in ordine cronologico in base al calendario...

**Comment by astagi** [comment]
@dg7dd perfetto grazie del feedback, in home la situazione è diversa, si tratta di elementi eterogenei tra loro messi `In evidenza`, è compito dell'utente decidere l'ordine, potrebbe anche essere quello di far visualizzare un evento in prima posizione, poi diverse news e di nuovo l'evento..

<img width="814" alt="image" src="https://user-images.githubusercontent.com/537363/205737305-a3186397-4418-4047-81a6-48fc65d72ccb.png">


Intanto apro il fix per l'ordinamento.

**Comment by dg7dd** [comment]
Bene, grazie, ok il fix (poi, appena possibile, in settimana lo proverò). 
Per quanto riguarda la Home, specifico che io non l'ho impostata nella modalità "In evidenza" (in cui l'amministratore seleziona manualmente gli elementi da visualizzare e in che ordine), ma lasciando le tre sezioni Notizie/Eventi/Circolari. In questo modo, l'ordinamento degli elementi di ciascuna sezione è automatico: nella Home viene visualizzato, automaticamente e per ciascuna sezione, solo l'ultimo elemento pubblicato. 
Ora, sono curioso di vedere se il fix appena rilasciato risolve automaticamente anche questo problema. Nel senso: se adesso gli eventi vengono ordinati correttamente nella pagina "Eventi", e il primo evento visualizzato risulta [prossimo-da-calendario], forse anche nella Home l'evento visualizzato sarà [prossimo-da-calendario]? O continuerà a rimanere [ultimo-pubblicato]? 
Non so se mi spiego: comunque quando riprenderò il PC in settimana proverò, e nel caso farò degli screenshot per chiarire..

PS. Per intenderci, questo è il link alla home del sito: www.istitutosignorelli.edu.it

**Comment by astagi** [comment]
Credo di aver capito @dg7dd il tuo problema sulla home, ho appena messo un fix su `main` (https://github.com/italia/design-scuole-wordpress-theme/commit/f7949cfde169739416215e378f78fbc39ed9d407) appena puoi provalo e fammi sapere (apri comunque una nuova issue) :)

Grazie!

**Comment by dg7dd** [comment]
Ok poi provvederò👍🏻
