### ISSUE TITLE
tag nei content type

### ISSUE THREAD

**Issue by anitamaccio** [italia/design-scuole-wordpress-theme#16]
Salve, siamo scuola etwinning per cui ho messo il banner in home page, e volevo linkarci la pagina dell'argomento "eTwinning" che dovrebbe nella mia idea elencare tutto ciò che nel sito è stato taggato con l'argomento eTwinning. però la pagina del tag https://www.icvs.edu.it/icvs/argomento/etwinning/ è vuota, anche se ho taggato con il termine due progetti.
Non è previsto l'elenco di tutti i content type? c'è qualche opzione da qualche parte per far sì che vengano elencati anche loro? Anche se metto la spunta su "schede progetti" la pagina rimane vuota.
Grazie
Anita Macciò

**Comment by webgrafia** [comment]
Era un bug, risolto con l'ultimo commit.
Se aggiorni il tema ora dovresti vederli

grazie della segnalazione

**Comment by anitamaccio** [comment]
Ho aggiornato il tema, ma continuo a non vedere i content type 'Schede Progetti' nell'elenco dei documenti con tag eTwinning: https://www.icvs.edu.it/icvs/argomento/etwinning/ (c'è solo un contenuto di tipo Articolo)
C'è qualche spunta da mettere da qualche parte?
