### ISSUE TITLE
Violazione GDPR tramite G.Maps

### ISSUE THREAD

**Issue by fa-ro** [italia/design-scuole-wordpress-theme#160]
è stata contestata alla mia scuola la violazione del GDPR a causa dell'utilizzo nel sito di script legati a Google Maps.
Non riesco a capire se la cosa sia fondata....
Il template usa Google Maps nella pagine che fanno riferimento ai luoghi.... non capisco come questo impatti sui dati dei visitatori che verrebbero (secondo la contestazione) inviati fuori Europa.
Riuscite a chiarirmi la questione? uso l'ultima versione del template senza altri plugin.

**Comment by attiliopecora** [comment]
lo hanno fatto a tutte le scuole è il solito gruppo MONITORAPA che sta rompendo i c..... da un po di tempo. per le cose tecniche rimando ai webmaster

**Comment by Simsimus** [comment]
Non sono certo che il tema usi Google Maps in termini di navigazione interna (iframe), mi sembra un altro servizio. Quello che invece è presente relativamente a Google Maps è un collegamento alla mappa che però si apre all'esterno del sito e che quindi la relativa gestone dati (cookie, ecc) è demandata direttamente al portale esterno collegato.
Ovviamente gli sviluppatori del tema sapranno dirci se effettivamente nella codifica siano presenti gli elementi potenzialmente lesivi della privacy citati da MonitoraPa (Google Analytics, Google Fonts, reCAPTCHA (Google LLC), Google Hosted Libraries (Google LLC), Google Maps).

**Comment by fa-ro** [comment]
Usando Ublock Origin ho visto che Jquery viene caricato da internet e dalle impostazioni non è possibile scegliere di caricarlo da locale ma solo scegliere tra tre fonti esterne (Google, Cdn, altro). Disattivando Jquery, le mappe non vengono mostrate, ma stare senza Jquery penso abbia conseguenze su altre funzioni del sito.... Quindi non so se si risolve il problema evidenziato da Monitor-PA disattivando Jquery Version Control. Ublock Origin evidenzia anche accesso a youtube ed altri siti esterni sulle pagine che includono video yt.....

**Comment by emafer** [comment]
> è stata contestata alla mia scuola la violazione del GDPR a causa dell'utilizzo nel sito di script legati a Google Maps. Non riesco a capire se la cosa sia fondata.... Il template usa Google Maps nella pagine che fanno riferimento ai luoghi.... non capisco come questo impatti sui dati dei visitatori che verrebbero (secondo la contestazione) inviati fuori Europa. Riuscite a chiarirmi la questione? uso l'ultima versione del template senza altri plugin.

Salve, 
il tema usa leafmap, quindi non dovrebbe porsi il problema googlemap
qual è, se posso chiedere, il sito segnalato?

**Comment by zetareticoli** [comment]
Non c'è una vera e propria integrazione di Google Maps per i luoghi, viene pubblicato un link esterno. Quindi non dovrebbero esserci problemi GDPR.

**Comment by fa-ro** [comment]
> 
> Salve, il tema usa leafmap, quindi non dovrebbe porsi il problema googlemap qual è, se posso chiedere, il sito segnalato?

www.isisromero.it
Adesso ho "spento" Jquery (dal pannello impostazioni) in modo che non sbuchino le mappe (cosa che onestamente mi spiace moltissimo!)

**Comment by zetareticoli** [comment]
Ciao, faremo un ulteriore verifica interno sul rispetto delle norme GDPR da parte della libreria leaflet (che[ usa OpenStreetMap](https://leafletjs.com/examples/quick-start/)) e vi facciamo sapere. Grazie

**Comment by sdi-sw** [comment]
> > Salve, il tema usa leafmap, quindi non dovrebbe porsi il problema googlemap qual è, se posso chiedere, il sito segnalato?
> 
> [www.isisromero.it](http://www.isisromero.it) Adesso ho "spento" Jquery (dal pannello impostazioni) in modo che non sbuchino le mappe (cosa che onestamente mi spiace moltissimo!)

Come hai fatto a "spengere" jquery? 
Io riesco solo a disattivare ed eventualmente cancellare il plugin "Version Control for jQuery", che però non credo disabiliti Jquery... ? Mi sbaglio?

**Comment by astagi** [comment]
Per il momento chiudo la issue, jQuery come libreria deve rimanere, ho visto l'altra segnalazione in merito a jQuery migrate sulla quale stiamo indagando. Cercheremo di rendere tutto conforme sistemando il problema partendo dall'altra issue #190
