### ISSUE TITLE
Correlazione tra utenti/persone e strutture

### ISSUE THREAD

**Issue by monicacarlino** [italia/design-scuole-wordpress-theme#161]
1. Al momento della creazione di un utente, riesco a collegarlo ad una struttura/ufficio. Ma, da frontend, nella scheda della persona non viene visualizzato l'ufficio di riferimento. Es. di impiegato amministrativo correlato ad ufficio Amministrazione e Segreteria: https://pa7-wip.produzione.clio.it/wp/?author=4

2. All'interno della struttura, non riesco a visualizzare la correlazione che seleziono nel momento della creazione di un nuovo utente ad essa associato, ma solo quelle selezionate dall'interno della struttura stessa.

**Comment by astagi** [comment]
@monicacarlino buongiorno e grazie della segnalazione. Potrebbe fornirci qualche screenshot per capire meglio la problematica e gli step per riprodurre il problema?

**Comment by marcoverze93** [comment]
Buongiorno,
mi rifaccio alla domanda precedente: all'interno delle strutture è possibile vedere le persone responsabili ma cliccando su esse, quando si apre la pagina personale, non compare la struttura, o le strutture, a cui essa è collegata.
Inoltre non esiste una pagina dove poter vedere tutte le persone della scuola? Potrebbe essere comodo...

**Comment by astagi** [comment]
Buongiorno @marcoverze93 chiuderei questa issue e terrei l'altra #224  come riferimento per le altre problematiche che dici?
