### ISSUE TITLE
Segnalazione bug su articoli con password

### ISSUE THREAD

**Issue by Simsimus** [italia/design-scuole-wordpress-theme#163]
Salve,
volevo segnalare che se si pubblica un articolo, pagina, documento, circolare, ecc, applicando una password per la relativa visualizzazione (funzione nativa di wordpress), l'unica cosa che viene protetta è il contenuto di tale pubblicazione, ma non gli allegati inseriti attraverso il bottone "Carica documenti"
![bottone-carica-documenti](https://user-images.githubusercontent.com/108821309/200640047-11071a13-c101-48e6-a385-e7e2831376a8.jpg)

Di seguito il risultato dell'articolo con password ma con allegato visibile:
![articolo-password](https://user-images.githubusercontent.com/108821309/200640875-76c7c5ba-ed7f-404a-b881-77a173161e16.jpg)

**Comment by astagi** [comment]
Il fix alla seguente issue è presente nella versione del tema 2.1.3 https://github.com/italia/design-scuole-wordpress-theme/releases/tag/v2.1.3. Grazie della segnalazione.

**Comment by astagi** [comment]
Manca la protezione di password su tutto il documento

**Comment by astagi** [comment]
Implementato tutto in https://github.com/italia/design-scuole-wordpress-theme/commit/1f4526189e58a7d6d05a0b30fce15a8a2a0800cc

**Comment by Simsimus** [comment]
Buongiorno,
volevo segnalare che la problematica in oggetto è stata risolta negli articoli e nei documenti, ma ancora persiste nelle circolari.
Grazie
