### ISSUE TITLE
C.SC.1.1 - COERENZA DELL'UTILIZZO DEI FONT 

### ISSUE THREAD

**Issue by attiliopecora** [italia/design-scuole-wordpress-theme#166]
come mai usando l'app di valutazione su un sito di test dove è caricato solo il template "design-scuole-wordpress-theme" 2.0.3, ed inserito qualche articolo, un servizio, una scheda didattica uno dei fallimenti è 

![Senza titolo](https://user-images.githubusercontent.com/113541384/201410130-3365a2a6-e9a8-4f37-abb1-a655f066447e.png)

e cosa intende per non è stata trovata nessuna  "scheda servizio" ?

**Comment by attiliopecora** [comment]
toc toc c'è nessuno che possa darmi una mano ?

**Comment by mariantanase** [comment]
Hai provato a utilizzare la versione più recente (1.0.13) dell'app di valutazione ? 
Sembra che contiene vari fix, magari risolve anche il tuo di problema.

**Comment by attiliopecora** [comment]
appena provato ... nulla :-(

**Comment by zetareticoli** [comment]
Ciao @attiliopecora, 
l'errore riscontrato fa riferimento ad una scheda servizio mancante. Hai qualche informazione in più da condividere in merito al test effettuato?

**Comment by attiliopecora** [comment]
ciao zeta. Allora ho rilanciato di nuovo l'applicazione di controllo, l'ultima disponibile, dopo aver cancellato la cache e la prima volta non mi ha comunicato l'incoerenza, rieseguendo l'applicativo anche più volte ritorna l'errore. il sito sul quale sto testando il tutto è https://www.prosoftbn.it, il sito contiene solo un documento generico, una scheda servizio, 2 o tre strutture scolastiche. E' pubblicato sui server di aruba, il php in uso è 8.1.12, se ti servono altre info .... chiedimi pure, se vuoi le credenziali per l'accesso te le posso dare in privato.

**Comment by emafer** [comment]
@attiliopecora a me da il problema quando non c'è almeno un servizio in una tipologia o quando il menù non ha applicato il data-element "service-type"
Ad esempio Personale scolastico è privo di servizi, quindi se apre quella pagina per fare il controllo rimane triste e sconsolato, mentre se entra in "famiglie" trova il servizio di prova

**Comment by attiliopecora** [comment]
grazie @emafer ce provo

**Comment by attiliopecora** [comment]
ciao vito :-) .... prova a seguire il consiglio di @emafer qui sopra e fammi sapere come è andata io non ho il tempo di farlo in questo momento :-(

**Comment by vitolamacchia** [comment]
Ho provato di tutto e inserito tutto il possibile ma nulla
Accetto suggerimenti

**Comment by attiliopecora** [comment]
su che sito stai testando ? è in locale o produzione ?

**Comment by vitolamacchia** [comment]
in produzione

**Comment by zetareticoli** [comment]
Ciao @attiliopecora, hai provato creando servizi per tutte le tipologie?

**Comment by vitolamacchia** [comment]
Già fatto

**Comment by emafer** [comment]
@vitolamacchia prova a aggiornare i nomi nel menù: servizi per il personale scolastico
servizi per famiglie e studenti

non riconosce il menù come servizi, quindi non mette il data-element necessario al riconoscimento

**Comment by vitolamacchia** [comment]
Fatto cancellato tipologia e servizi ma nulla

**Comment by attiliopecora** [comment]
> Ciao @attiliopecora, hai provato creando servizi per tutte le tipologie?

si e cosi sembra funzionare grazie
