### ISSUE TITLE
Errore con php 8

### ISSUE THREAD

**Issue by dadah3** [italia/design-scuole-wordpress-theme#167]
Hello, i'm using Design Scuole Italia I tried to update the php from 7 to 8 as recommended by wordpress, but I get this error even disabling members
Warning: Trying to access array offset on value of type bool in /membri/maffi/wp-content/plugins/version-control-for-jquery/settings.php on line 275.
can you help me?
dadah

**Comment by astagi** [comment]
@dadah3 we're experiencing some problems with php 8.. https://github.com/italia/design-scuole-wordpress-theme/issues/106

We'll investigate soon

**Comment by astagi** [comment]
@dadah3 is this issue blocking? is theme working if you turn off error reporting?

**Comment by dadah3** [comment]
Actually I can't know yet the site is under construction I'm practicing with the theme, but with the old version of php (7.3.33). Let's say it crashes and doesn't work well if I use the php version recommended by this warning: "Your site uses an outdated version of PHP (7.3.33), which is not receiving security updates. You should update it."
The minimum recommended PHP version is 7.4. and I have to use the previous one instead.

**Comment by mariantanase** [comment]
The error has been fixed in [3.0.2 version](https://wordpress.org/support/topic/php-8-trying-to-access-array-offset/).
Try to update the plugin.

**Comment by zompa-zampa** [comment]
ho sempre problemi anche con il plugin aggiornato, con la php 8.2
