### ISSUE TITLE
Nuove tipologie di Documenti aggiunte non vengono mostrate né i documenti visualizzati

### ISSUE THREAD

**Issue by CampusDaVinci** [italia/design-scuole-wordpress-theme#168]
Se si crea una nuova tipologia di documento questa non viene mostrata nella pagina principale delle carte della scuola ed eventuali documenti assegnati non vengono visualizzati

**Comment by astagi** [comment]
Grazie della segnalazione @CampusDaVinci è possibile avere qualche screenshot per rendersi conto del problema?

**Comment by astagi** [comment]
@CampusDaVinci avrei bisogno di qualche screenshot e una procedura per riprodurre il problema, grazie

**Comment by CampusDaVinci** [comment]
Certo, chiedete pure, volndo possiamo darvi anche l'accesso al portale se serve

**Comment by zetareticoli** [comment]
Ciao @CampusDaVinci, non abbiamo riscontrato il bug da te segnalato. 

Di seguito la procedura seguita:
1. Creare una nuova tipologia di documento
2. Creare un documento e assegnare la tipologia
3. Pubblica il documento

Ti allego screen del test
<img width="1224" alt="Schermata 2022-12-05 alle 09 51 02" src="https://user-images.githubusercontent.com/69706/205594358-2a34688f-35dc-4684-bebd-49b703dcc71d.png">

**Comment by CampusDaVinci** [comment]
Grazie per il supporto e l'indicazione , ora sembra funzionare.

**Comment by CampusDaVinci** [comment]
Grazie per il supporto e l'indicazione , ora sembra funzionare.
