### ISSUE TITLE
"Modifica rapida" di un Documento cancella tutte le informazioni relative al documento

### ISSUE THREAD

**Issue by CampusDaVinci** [italia/design-scuole-wordpress-theme#169]
Se si procede alla "modifica rapida" di un documento, vengono perse tutte le informazioni come Titolo, Tipologia e altro ancora

**Comment by boazaob** [comment]
confermo lo stesso problema

**Comment by astagi** [comment]
@CampusDaVinci @boazaob ho messo qui il fix https://github.com/italia/design-scuole-wordpress-theme/pull/188

potete dirmi se funziona?

**Comment by boazaob** [comment]
si confermo funziona

**Comment by zompa-zampa** [comment]
Scusa @boazaob ho la versione del tema 2.1.6 è già compresa il tuo #188 ?

**Comment by boazaob** [comment]
Come dicevo il 5 dicembre, funziona. Non ricordo da quale versione, ma mella 2.1.6 è sicuramente compresa
