### ISSUE TITLE
Nella home page compare sempre la sezione "Circolari"

### ISSUE THREAD

**Issue by CampusDaVinci** [italia/design-scuole-wordpress-theme#170]
Nella homepage non è possibile nascondere la sezione "Circolari".
Se si visualizzano le Notizie, viene visualizzata anche la sezione Circolari

**Comment by astagi** [comment]
@CampusDaVinci che versione del tema state utilizzando?

**Comment by CampusDaVinci** [comment]
Salve, la 2.0.3

**Comment by CampusDaVinci** [comment]
Salve, attualmente stiamo usando la versione 2.0.3

**Comment by CampusDaVinci** [comment]
Salve, la 2.0.3

**Comment by zetareticoli** [comment]
Ciao @CampusDaVinci, non riusciamo a replicare il bug, potresti gentilmente condividerci le impostazioni di configurazione della Home, da menu di Wordpress? Grazie

**Comment by CampusDaVinci** [comment]
Ecco gli screenshot della sezione Home e Novità
![ConfigHome](https://user-images.githubusercontent.com/115779224/205593124-919078c3-837b-4a8e-8597-c8a1ec37ad00.png)
![ConfigNovita](https://user-images.githubusercontent.com/115779224/205593147-2f34a8a3-40fd-40f8-bbd9-704d536ba982.png)
Grazie per il supporto

**Comment by CampusDaVinci** [comment]
Aggiornando il tema alla 2.1.0 il problema persiste

**Comment by astagi** [comment]
@CampusDaVinci da valutazioni il campo circolari dovrebbe rimanere fisso sulla homepage di una scuola. Per il momento non prevediamo la modifica ma manteniamo la segnalazione. Per il momento l'unica possibilità di nascondere la sezione Circolari è che voi effettuiate una modifica al template.

**Comment by CampusDaVinci** [comment]
Ok, ma la cosa non ha molto senso, soprattutto se, come avviene nella stragrande maggioranza delle scuole, non viene usato il sistema di circolari del sito in quanto si utilizzano i servizi in cloud dei vari fornitori di Registro Elettronico.
Credo che aggiungere una opzione che escluda la visualizzazione sarebbe l'ideale e renda il template molto più flessibile.
Grazie per il vostro supporto
