### ISSUE TITLE
Problema di stili nei menu a fondo pagina

### ISSUE THREAD

**Issue by vcoopcsc** [italia/design-scuole-wordpress-theme#172]
Buongiorno, 
nel passaggio dalla versione 1 all'ultima versione abbiamo notato un problema di stili nei menu a fondo pagina: cambiando i link alle voci di menu o aggiungendo nuove voci, il testo del link non appare sottolineato e questo crea un effetto disomogeneo e fa sembrare che le sotto-voci di menu non siano link.
Allego immagine di esempio 
<img width="469" alt="image" src="https://user-images.githubusercontent.com/92174841/202403632-87050278-6c5b-4284-9774-e5018f0f9301.png">
Grazie in anticipo!

**Comment by dg7dd** [comment]
Confermo. Stesso problema anche nel nostro sito.

**Comment by astagi** [comment]
@vcoopcsc @dg7dd la PR #175 risolve questo problema?

**Comment by vcoopcsc** [comment]
Confermo! Grazie

**Comment by dg7dd** [comment]
> @vcoopcsc @dg7dd la PR #175 risolve questo problema?

Perfetto. Tutto risolto! Grazie

**Comment by astagi** [comment]
@dg7dd @vcoopcsc nuova versione rilasciata 🎉 buon weekend!
