### ISSUE TITLE
Warning se nel php.ini display_errors è su On

### ISSUE THREAD

**Issue by Simsimus** [italia/design-scuole-wordpress-theme#173]
Salve,
volevo segnalare che se nel php.ini si lascia display_errors=On il tema presenta i seguenti warning:
1) visualizzando alcune pagine/post da frontend:
Warning: Array to string conversion in "/wp-includes/general-template.php on line 184"

2) visualizzando le varie sezioni da backend (luoghi, strutture, documenti, ecc) nel campo/colonna "Argomento":
Warning: Undefined property: stdClass::$no_terms in "/wp-admin/includes/class-wp-posts-list-table.php on line 1313"

Spero possa essere risolto per una ottimizzazione del codice.
Saluti

**Comment by zetareticoli** [comment]
Ciao @Simsimus, 
facciamo una verifica e ti aggiorniamo, grazie

**Comment by astagi** [comment]
@Simsimus questo avviene in PHP 8 giusto? la stessa cosa avviene sulla versione 7 di PHP?
