### ISSUE TITLE
Dimensioni foto in home page

### ISSUE THREAD

**Issue by scal1974** [italia/design-scuole-wordpress-theme#174]
Buongiorno volevo sapere le dimensioni e i pixel delle foto in home page.

**Comment by vcoopcsc** [comment]
Ciao! Io ho visto che tenendola in questi parametri funziona: dimensioni minimo di 600 di larghezza * 400 di altezza

**Comment by scal1974** [comment]
ho provato ad inserirla con queste caratteristiche nel logo identificativo dell'evento ma la taglia. Di che dimensioni va inserita?

**Comment by Simsimus** [comment]
Purtroppo il tema non gestisce le immagini in modo responsive (in pratica non le adatta allo spazio disponibile), quindi in base alle dimensioni dello schermo potrebbe essere vista per intero o tagliata a destra.
Il problema è stato già segnalato nella issue #143

**Comment by astagi** [comment]
Grazie della segnalazione @scal1974 , la chiudo come duplicato della #143
