### ISSUE TITLE
Validazione voci del menù "Servizi" *IMPORTANTE*

### ISSUE THREAD

**Issue by sdi-sw** [italia/design-scuole-wordpress-theme#177]
Segnalo un malfunzionamento piuttosto preoccupante in relazione al nuovo strumento di verifica messo a disposizione per la verifica dei siti internet.

Utilizzando la "app-valutazione-scuole" recentemente resa disponibile, la verifica:

> R.SC.1.2 - SCHEDE INFORMATIVE DI SERVIZIO 
> Fallisce perché: 
> " Più di 2 voci obbligatorie non sono presenti o più di 1 voce non è nell'ordine corretto.  https://liceodavincifi.edu.it/servizio/nuovi-docenti/  "
> Segnala come mancanti: "Cosa serve, Tempi e scadenze, Contatti, Ulteriori informazioni, Struttura responsabile del servizio, indirizzo, orari, gps, email, pec, telefono, Metadati".

Il problema è che anche quando vengono inserite tutte le voci  nelle schede, viene comunque segnalato lo stesso messaggio di errore.

Mi chiedo se tale errore è dovuto allo strumento di verifica oppure ad un problema con il template.

**Comment by attiliopecora** [comment]
hai inserito un luogo collegato al servizio ? nel luogo hai inserito tutti i campi ?

**Comment by sdi-sw** [comment]
Inserendo tutte le informazioni va tutto bene. 
Le schede su cui mi dà errore sono quelle a cui avevo limitato la visualizzazione solo ad alcune categorie, essendo relative a servizi riservati agli insegnanti. 

Possiamo chiudere questo issue...
