### ISSUE TITLE
Luogo che appare nel posto dei documenti

### ISSUE THREAD

**Issue by anitamaccio** [italia/design-scuole-wordpress-theme#18]
Ciao, mi succede questo: il luogo "Scuola dell'Infanzia di Rossiglione" non appare nell'elenco dei luoghi disponibili, per cui clicco sul pulsante "Cerca", lo trovo, metto la spunta e clicco su Seleziona, e il luogo invece di apparire a fianco nei luoghi selezionati, appare nella sezione sottostante, quella dei Documenti selezionati (non c'è ovviamente un documento che si chiama così, è proprio il luogo.
![Schermata del 2019-12-22 18-49-10](https://user-images.githubusercontent.com/58820327/71325376-22073180-24ec-11ea-95d9-60430d4cdeb9.png)

Anche visualizzando l'articolo, il luogo "Scuola dell'Infanzia di Rossiglione" appare con il titolo "Documenti"
![Schermata del 2019-12-22 18-49-38](https://user-images.githubusercontent.com/58820327/71325417-b1144980-24ec-11ea-98ce-f2fdf4f749e6.png)
Cliccandoci, si apre il luogo.

Per i luoghi che appaiono direttamente in quelli disponibili, invece funziona tutto regolarmente, come da aspettative.

**Comment by webgrafia** [comment]
Abbiamo risolto il problema nell'ultimo commit
grazie della segnalazione

**Comment by anitamaccio** [comment]
Ciao, negli articoli il problema è risolto, ma anche con l'aggiornamento mi fa lo stesso errore nel tipo di contenuto "Eventi"

**Comment by webgrafia** [comment]
@anitamaccio risolto anche sul post type evento, puoi aggiornare il repo (anche senza update dei sottomoduli)

Grazie del feedback
