### ISSUE TITLE
Home: non corretta disposizione di Notizie e Circolari

### ISSUE THREAD

**Issue by santomarco** [italia/design-scuole-wordpress-theme#182]
Come da titolo,
segnalo che la disposizione su colonne, nella home, delle Notizie e delle Circolari non avviene in modo corretto.

Allego foto:

![image](https://user-images.githubusercontent.com/6921709/204777381-54bd51c7-9696-4b64-b39b-124187ce8a0d.png)

**Comment by santomarco** [comment]
Buonasera, no, nessuna modifica di layout.

Ho provato ad inserire un testo "più lungo" e la colonna assume la giusta
larghezza, quindi non so se può esser messo un qualche min-width con la
giusta media query.

PS. Anche se all'atto pratico è molto difficile che una notizia abbia così
pochi caratteri.

Grazie

Il mer 30 nov 2022, 15:33 Francesco Improta ***@***.***> ha
scritto:

**Comment by zetareticoli** [comment]
Ciao @santomarco, per riprodurre il bug mi servirebbe di capire quali impostazioni di "Configurazione" della Home stai usando. Il tema prevede di default una sezione "In evidenza" in cui aggiungere contenuti di vario tipo.

**Comment by astagi** [comment]
@zetareticoli @santomarco penso la configurazione sia questa

<img width="854" alt="image" src="https://user-images.githubusercontent.com/537363/206194851-c6d636aa-0751-4d60-8e76-423de7e60602.png">

che porta a questo 

<img width="1255" alt="image" src="https://user-images.githubusercontent.com/537363/206194770-1cfb83d9-2d7a-4b79-84db-05aca3a91e23.png">

**Comment by astagi** [comment]
@santomarco hai una url sulla quale possiamo vedere il frontend e fare le opportune verifiche?

**Comment by santomarco** [comment]
Sì, posso indicarlo in qualche modo diretto?

(Attualmente il sito è ospitato su un dominio non ufficiale della scuola - per tanto eviterei di pubblicarlo direttamente qui)

**Comment by astagi** [comment]
Certo @santomarco puoi trovarmi su [![canale Slack di Developers Italia ](https://slack.developers.italia.it/badge.svg)](https://slack.developers.italia.it/) puoi scrivermi privatamente l'indirizzo.

**Comment by santomarco** [comment]
Buongiorno, sia seguendo il "get invite" che lei ha inserito che andando sulla pagina di DevelopersItalia, l'accesso a slack non avviene dicendo che l'invito non è più valido

**Comment by santomarco** [comment]
Inviato msg con LinkedIn - con tutte le foto delle config, riferimenti e versione tema usato.

Grazie mille!

**Comment by santomarco** [comment]
Trovato l'elemento che fa calcolare male le colonne (sembrerebbe almeno)

![image](https://user-images.githubusercontent.com/6921709/207904964-0f0bf488-2cd8-43bc-b8df-287880693203.png)

Se viene selezionato "Mostra gli eventi in home" -> "No" - l'incolonnamento diventa non consistente

**Comment by zetareticoli** [comment]
Ciao @santomarco, 
in seguito ad un'analisi della tua installazione emerge chiaramente un'alterazione del templates

Questo è il tuo:
![template-errato](https://user-images.githubusercontent.com/69706/208632913-8314416f-5389-4e51-9ccc-c3803bddeb44.png)

Questo è come dovrebbe essere:
![template-corretto](https://user-images.githubusercontent.com/69706/208632950-b8841787-3ffa-4f20-8718-1b4c24723378.png)
