### ISSUE TITLE
Errore trying to access array offset

### ISSUE THREAD

**Issue by Jhndo** [italia/design-scuole-wordpress-theme#185]
Buongiorno, 

sul nostro sito (https://www.icbrentonico.it/) compare il seguente warning:

Warning: Trying to access array offset on value of type bool in /web/htdocs/www.icbrentonico.it/home\wp-content\plugins\wp-guest-bar\guestbar.php on line 102

![Screenshot 2022-12-01 at 09-37-27 ICBR – Istituto Comprensivo di Brentonico](https://user-images.githubusercontent.com/113902185/205006874-c5b28b39-267e-4269-a029-2c9bd2cbd4c7.png)

Come potremmo risolvere?

Grazie mille.

**Comment by astagi** [comment]
@Jhndo potete disabilitare i warning sul tema in produzione, qua una guida su come configurare il PHP https://www.wpbeginner.com/wp-tutorials/how-to-turn-off-php-errors-in-wordpress/
