### ISSUE TITLE
Indirizzi cancellati compaiono nell'Offerta Formativa

### ISSUE THREAD

**Issue by CampusDaVinci** [italia/design-scuole-wordpress-theme#187]
Anche se si cancella un indirizzo, spostandolo nel cestino, esso rimane comunque accessibile e visibile nella pagina della offerta formativa.
Per non averlo più visibile si deve eliminare definitivamente dal cestino
![IndirizzoCestinato](https://user-images.githubusercontent.com/115779224/205598079-a16b28a3-983c-4a5e-9b26-7d54cc37064d.png)
![IndirizzoCancellato](https://user-images.githubusercontent.com/115779224/205598112-c8c948fc-c891-4d95-beb9-4c387d097094.png)

**Comment by astagi** [comment]
@CampusDaVinci lo mettiamo come miglioria visto esiste un workaround

**Comment by CampusDaVinci** [comment]
Beh, è un bug, non una miglioria, svuotare il cestino per non far apparire un elemento cancellato non è il comportamento "normale" in wordpress.
Anche perchè l'opzione di svuotamento serve proprio per dare la possibilità di recuperare i lavori se si cambia idea

**Comment by CampusDaVinci** [comment]
Beh, è un bug, non una miglioria, svuotare il cestino per non far apparire un elemento cancellato non è il comportamento "normale" in wordpress.
Anche perché l'opzione di svuotamento serve proprio per dare la possibilità di recuperare i lavori se si cambia idea

**Comment by astagi** [comment]
@CampusDaVinci devo aver frainteso la richiesta, si è un bug e a occhio mi sembra un errore proprio nella query. Ci guardiamo quanto prima, grazie ancora.

**Comment by astagi** [comment]
Il fix alla seguente issue è presente nella versione del tema 2.1.3 https://github.com/italia/design-scuole-wordpress-theme/releases/tag/v2.1.3. Grazie della segnalazione.
