### ISSUE TITLE
malfunzionamento Autorizzazioni sui contenuti

### ISSUE THREAD

**Issue by anitamaccio** [italia/design-scuole-wordpress-theme#19]
Salve, ho inserito una UdA in una scheda didattica e ho impostato nelle "Autorizzazioni sui contenuti" la limitazione a "Sottoscrittore". Il risultato per i normali visitatori  è questo: 
https://www.icvs.edu.it/scheda-didattica/uda-il-testo-narrativo/  
è tutto visibile e scaricabile, tranne l'Argomento, dove appare "Non hai il permesso di visualizzare questo contenuto."
Dovrebbe essere l'intera scheda non visualizzabile senza autorizzazione, anche se comunque ho poi inserito le Uda in pagine normali, per organizzarle meglio.

Grazie e cordiali saluti
Anita Macciò

**Comment by webgrafia** [comment]
Abbiamo replicato l'errore, a breve rilasceremo il fix correttivo

grazie della segnalazione

**Comment by webgrafia** [comment]
Buongiorno Anita,
abbiamo rilasciato le modifiche che correggono la visibilità dei post type in caso di non autorizzazione alla fruizione.
Puoi scaricare l'ultima versione, anche senza aggiornare i sottomoduli
