### ISSUE TITLE
Eventi in home

### ISSUE THREAD

**Issue by dg7dd** [italia/design-scuole-wordpress-theme#192]
Buongiorno.
Nella pagina Home impostata con le tre sezioni (Notizie/Eventi/Circolari), per ogni sezione appare sempre l'ultimo elemento pubblicato. 
Ora, per quanto riguarda la sezione Eventi, non essendoci più la possibilità di visualizzare il calendario, l'evento che resta visibile è sempre quello pubblicato per ultimo, e questo risulta fuorviante per l'utente (che vede visualizzato un evento già passato, e non quello nuovo in programma).
Sarebbe invece opportuno che l'evento visualizzato fosse, di volta in volta e automaticamente, il prossimo in ordine temporale (altrimenti l'amministratore deve ogni volta entrare in backend e modificare la data di pubblicazione dell'evento per farlo apparire in home). La visualizzazione dell'evento in home dovrebbe cioè scorrere automaticamente e temporalmente tra quelli che vengono creati e pubblicati (magari inserendo anche un messaggio del tipo "Nessun evento in programma" se non ci sono nuovi eventi in lista dopo l'ultimo trascorso).
Questo sarebbe importante per la fruibilità del flusso informativo del sito.
Non so se è chiaro... Nel caso resto a disposizione per ulteriori approfondimenti.
Grazie, un saluto

**Comment by dg7dd** [comment]
Sì, v2.1.2
In home continuo a vedere l'evento con data di pubblicazione più recente, e non quello che sarà il prossimo in ordine temporale. L'evento visualizzato è trascorso il 4 dicembre, invece quello che dovrebbe essere visualizzato è il prossimo in ordine temporale (17 dicembre).
Corretto invece, con la nuova release, l'ordine visualizzato nella pagina Eventi.

**Comment by astagi** [comment]
Grazie del feedback @dg7dd metto nelle segnalazioni e verifico lunedì

**Comment by astagi** [comment]
@dg7dd l'ultimo commit https://github.com/italia/design-scuole-wordpress-theme/commit/c6f6f3eb2af2065ffb261babbc07c4971146cf5f dovrebbe risolvere il tuo problema. Fammi sapere!

**Comment by astagi** [comment]
@dg7dd sono stato forzato a rilasciare una nuova versione. Il fix alla seguente issue è presente nella versione del tema 2.1.3 https://github.com/italia/design-scuole-wordpress-theme/releases/tag/v2.1.3. Fammi sapere se il bug persiste.
