### ISSUE TITLE
R.SC.1.2 problema irrisolto non trova servizi

### ISSUE THREAD

**Issue by attiliopecora** [italia/design-scuole-wordpress-theme#193]
come da oggetto si rinnova il problema. Ho buttato giù il sito di prova, ho installato tutto da zero ho inserito puntualmente tutte le voci di servizio secondo le indicazioni della documentazione del modello scuole ma il validatore continua a non trovare schede di servizio. e chiaramente anche l'utilizzo dei font risulta incoerente. la versione del tema è la 2.1.2

![Senzanome](https://user-images.githubusercontent.com/113541384/206663903-a7fc6e2d-fd2b-41b9-970e-94a8bd67e7a8.png)

**Comment by attiliopecora** [comment]
la 2.1.2 non valorizza il **data element** "service-type"

questo è un esempio 
![no element](https://user-images.githubusercontent.com/113541384/206732865-3318e6b3-2941-4be6-a866-29acd1d5f658.png)

questa invece è di un sito che utilizza "**design-scuole-wordpress-theme-main**"

![service type](https://user-images.githubusercontent.com/113541384/206733148-80e1815c-2979-41d6-aae4-297e59a018c2.png)

le tipologie servizio dei due siti sono identiche, i servizi sono identici, tutti i dati sono stati caricati 

attilio pecora

**Comment by attiliopecora** [comment]
analizzando l' **header-walker**, l'istruzione 
	**if ( stripos( $item->post_name, 'personale-scolastico' ) !== false || stripos( $item->post_name, 'famiglie-e-studenti' ) !== false ) {
			$custom_data = 'data-element="service-type"';** .......

non valorizzava il $custom_data 

 e pertanto il controllo 
		**if($custom_data) { .....**

ritornava un false. 

a questo punto ho controllato il database e nella tabella   **..._posts**, la field post_name non contiene una descrizione (famiglie e studenti) bensi riporta il valore della Field "ID", quindi un numero.

come è possibile ?

attilio

**Comment by attiliopecora** [comment]
con le dovute modifiche al database

![image](https://user-images.githubusercontent.com/113541384/206766497-c5d2248e-4194-43f4-b6be-81fde56a20c8.png)

**Comment by astagi** [comment]
@attiliopecora per dovute modifiche al database intende che ha inserito i valori manualmente? Ovvero ha sostituito l'id con il valore corretto? Possiamo controllare cosa viene inserito in fase di creazione, se ha modificato del codice e vuole contribuire può aprire una pull request sul progetto stesso. Grazie mille!

**Comment by attiliopecora** [comment]
se può servire, quando l'installazione genera i record che popolano i menù, ci sono due errori:
**1) la sequenza del menù la scuola che dovrebbe essere:** 
presentazione
i luoghi
le persone
i numeri
le carte
organizzazione
la storia

**2) non inserisce i valori esatti dei servizi in post-name**

questo accade anche quando si ricaricano i dati con la funzione predisposta

**Da dove la procedura attinge i dati per popolare il database con i records relativi ai menù preimpostati ?**

**Comment by astagi** [comment]
Grazie @attiliopecora !

**Comment by zetareticoli** [comment]
@attiliopecora in merito all'ordine delle voci, l'app di valutazione nella sua ultima versione controlla esclusivamente la corrispondenza del nome e non la posizione nel menu di secondo livello.

In merito all'ordine, hai ragione, nel tema WP e nei templates statici è sbagliato e lo sistemeremo il prima possibile.

Il riferimento principale per queste cose è il [documento di Architettura dell'Informazione](https://docs.google.com/spreadsheets/d/1MoayTY05SE4ixtgBsfsdngdrFJf_Z2KNvDkMF3tKfc8/edit#gid=174172059), su cui ti puoi basare quando hai un dubbio.

**Comment by attiliopecora** [comment]
Ok @zetareticoli quindi è rimasta da risolvere la questione dei servizi perchè se nel database il campo name del post servizio non è valorizzato con il nome del servizio, il validatore riporta errore ed attualmente il campo è valorizato con l'id numerico.

**Comment by zetareticoli** [comment]
@attiliopecora in fase di creazione del servizio hai selezionato una delle 2 tipologie presenti?
![Schermata 2022-12-19 alle 18 25 14](https://user-images.githubusercontent.com/69706/208484262-6906a8e6-3db9-4285-ad8e-2190dbc92983.png)

**Comment by attiliopecora** [comment]
certo @zetareticoli sono le uniche che ho

**Comment by zetareticoli** [comment]
Stiamo facenedo ulteriori verifiche, ti aggiorno non appena possibile

**Comment by attiliopecora** [comment]
tranquillo continuo il debugging su altre cose

**Comment by astagi** [comment]
@attiliopecora grazie del contributo! Versione 2.1.5 rilasciata. Una volta installata questa versione, si prega di:

- Disabilitare e rimuovere il plugin jQuery Version Control (non più necessario e non più conforme)
- Aggiornare Wordpress (tema testato con successo sulla versione 6.1.1)
- Aggiornare le voci di menù con le nuove (conformi) utilizzando la seguente procedura
  - Nel backoffice, nel menù laterale entrare nella voce `Aspetto`
  - Compare una dropdown con la voce `Ricarica i dati`, una volta cliccato ed eseguita la procedura dovreste vedere la voce di menù aggiornata.

**Comment by Jamielrey** [comment]
Se qualcun altro dovesse avere lo stesso problema gli basta cambiare in header-walker la variabile "$item->post_name" con la variabile "$item->title". 
Qui un esempio per aggiungere il $custom_data anche a "percorsi di studio" e "tutti i servizi"

if ($item->post_name == "servizi-per-il-personale-scolastico" || $item->post_name == "servizi-per-famiglie-e-studenti" || $item->title == "Percorsi di studio" || $item->title == "Tutti i servizi") {
			$custom_data = 'data-element="service-type"';
		}
		
Io ho avuto lo stesso problema con il footer, ed ho risolto così:

if ($item->title == 'Privacy' || $item->title == 'Dichiarazione di accessibilità') { 
			$custom_data = $item->title == 'Privacy' 
			? 'data-element="privacy-policy-link"' 
			: 'data-element="accessibility-link"';
		}
