### ISSUE TITLE
test aggiuntivi 100 - condisione modifiche ?

### ISSUE THREAD

**Issue by attiliopecora** [italia/design-scuole-wordpress-theme#196]
![image](https://user-images.githubusercontent.com/113541384/208313817-e334f7a2-b103-4dec-93d9-2affc16cc1e3.png)

@astagi @zetareticoli 
**vorrei condividere le modifiche ma non so come si fa #**

![image](https://user-images.githubusercontent.com/113541384/208313841-1bc3c658-c9bf-4fe1-8880-8ac3cc57bf3f.png)

**Comment by astagi** [comment]
Buongiorno @attiliopecora perdonami non ho capito, intendi le modifiche al codice di wordpress tramite pull request?

**Comment by attiliopecora** [comment]
ciao si @astagi non riesco a fare una richiesta per una pull ... clicco su nuova pull request ma mi chiede se voglio fare una comparazione.... boh

**Comment by Simsimus** [comment]
Mi pare di capire che l'intento di @attiliopecora sia quello di arrivare al 100% di corrispondenza su tutti i controlli fatti dall'app, comprese le raccomandazioni ed i test aggiuntivi, quindi se posso vorrei fare una domanda:
mi confermate che il raggiungimento degli obiettivi avviene anche solo rispettando il 100% dei "criteri di conformità"?
Se non sbaglio le altre raccomandazioni sono un qualcosa a cui ambire, ma non pregiudicano l'asseverazione del progetto stesso.

**Comment by attiliopecora** [comment]
ciao @Simsimus, beh la mia è una specie di sfida con me stesso e per tutti; da quanto ho compreso per ogni parametro c'è una condizione di successo che ti fa diventare l'indicatore verde anche senza il raggiungimento del 100%. ci sono alcune che sono solo raccomandazioni e non pesano sulla valutazione ma i criteri fondamentali sono quelli che ti fanno salire l'indicatore. Eliminando quindi i problemi su quelli, il tutto diventa conforme :)

**Comment by zetareticoli** [comment]
@attiliopecora il problema degli ID da te segnalato si risolve usando `id` differenti per il dropdown della navigazione, uno per la versione mobile e uno per quella desktop. 

Fai questa prova e fammi sapere se risolvi.

**Comment by attiliopecora** [comment]
infatti l'avevo già fatto e funzionava
