### ISSUE TITLE
SEMPRE SULL'ORDINE DEGLI EVENTI

### ISSUE THREAD

**Issue by fa-ro** [italia/design-scuole-wordpress-theme#198]
La pagina "tutti gli eventi" è ora correttamente ordinata.
Se però gli eventi vengono suddivisi in "tipologie", la versione 2.1.4 mostra gli eventi già avvenuti e mantiene l'ordinamento sulla base della data di inserimento.
Vedere per esempio 
https://www.isisromero.it/tipologia-evento/colloqui-genitori/

**Comment by zetareticoli** [comment]
Ciao @fa-ro,
avremo quanto prima un template per aprire una _issue_, nel frattempo però evitiamo di usare il maiuscoletto e titoli che poco descrittivi. 

La tua segnalazione sembra correlata a qualcosa già aperto. In tal caso, ti suggerisco di proseguire nello stesso _thread_.

Grazie

**Comment by fa-ro** [comment]
Credo venia.... mi accorgo di dovere imparare parecchio....
