### ISSUE TITLE
Errore CMB

### ISSUE THREAD

**Issue by Barritta** [italia/design-scuole-wordpress-theme#20]
Ho provato a installare il tema ma mi richiamava un errore per il plugin CMB. 
Ho quindi installato il plugin e ricevo questo messaggio:

Warning: require(vendor/CMB2/init.php): failed to open stream: No such file or directory in /home/mhd-01/www.nomesito.it/htdocs/wp-content/themes/design-scuole-wordpress-theme-master/inc/cmb2.php on line 3

Fatal error: require(): Failed opening required 'vendor/CMB2/init.php' (include_path='.:/usr/share/php') in /home/mhd-01/www.nomesito.it/htdocs/wp-content/themes/design-scuole-wordpress-theme-master/inc/cmb2.php on line 3

l'installazione è su un wp multisite.

**Comment by webgrafia** [comment]
E' perchè non hai scaricato correttamente i sottomoduli git.
Per scaricare il progetto completo esegui i seguenti comandi

git clone https://github.com/italia/design-scuole-wordpress-theme.git
cd design-scuole-wordpress-theme/
git submodule init
git submodule update
