### ISSUE TITLE
Pulsanti radio tipologia articolo su creazione Nuovo Articolo

### ISSUE THREAD

**Issue by grethel** [italia/design-scuole-wordpress-theme#202]
Buonasera,
è possibile cambiare i pulsanti radio per la scelta della tipologia dell'articolo, all'interno della pagina di creazione di un nuovo articolo, in pulsanti checkbox, così da poter selezionare più tipologie per lo stesso articolo?

**Comment by astagi** [comment]
Buonasera @grethel questo lo posso segnalare come miglioramento, al momento dovrei indagare se possibile.

**Comment by grethel** [comment]
Grazie @astagi. In verità, è già presente tale opportunità, cliccando dall'elenco degli articoli su modifica rapida.

**Comment by astagi** [comment]
Ah perfetto @grethel allora possiamo chiudere la segnalazione?
