### ISSUE TITLE
mancanza gestione cookies su 2.1.5

### ISSUE THREAD

**Issue by fa-ro** [italia/design-scuole-wordpress-theme#203]
Dopo l'aggiornamento a 2.1.5 non ho più il plugin per la gestione dei cookies.
Non so se ho pasticciato io o se è un problema effettivo.
Come posso fare per ripristinare la funzionalità?

**Comment by attiliopecora** [comment]
mmmm credo tu abbia pasticciato perchè il tema non esclude i plug-in

**Comment by fa-ro** [comment]
> mmmm credo tu abbia pasticciato perchè il tema non esclude i plug-in

Mi diresti il nome del plugin che ne fa la gestione? Non ricordo proprio quale sia. Ho come l'impressione che il fatto che mi manchino le mappe e pure la gestione dei cookies siano due cose collegate dal jQuery. Più che caricare la cartella del tema tramite FileZilla e attivare il tema, comunque non ho fatto. Boh!

**Comment by attiliopecora** [comment]
io uso cookie yes che penso sia un ottimo plugin

**Comment by fa-ro** [comment]
Grazie Attilio. In effetti ho tra le dipendenze del tema (che ho trovato nella cartella inc) la parte che riguarda i Cookies è commentata e dunque non attiva. Sto ricostruendo la storia del gestore cookies che avevo.... era Ginger Cookies e l'autore era Butterino, lo stesso che ha iniziato il progetto di questo tema. Questo plugin, però, adesso non è più disponibile, per cui proverò il tuo o quello che anche altri vorranno consigliarmi.
Ero convinto che la gestione cookies fosse implementata di default nel tema.
Grazie ancora

**Comment by fa-ro** [comment]
Cookiesyes è bella ma è free solo per siti personali a basso traffico. Niente. Cerco una alternativa.
