### ISSUE TITLE
Documenti allegati compaiono con utente e non autore

### ISSUE THREAD

**Issue by marcoverze93** [italia/design-scuole-wordpress-theme#204]
Buongiorno
ho il seguente problema:
ho caricato un documento, inserito tutti i dati e anche l'autore (che non sono io). Se però vado sul sito sulla pagina dove ci sono le mie informazioni compare il documento mentre dovrebbe comparire all'autore.
Inoltre, in questa pagina (https://www.isisromero.it/author/marco-verzeroli/), non mi compaiono le strutture di cui faccio parte.
Grazie

**Comment by astagi** [comment]
@marcoverze93 pull request aperta, dovrebbe funzionare tutto adesso.

**Comment by marcoverze93** [comment]
Ciao @astagi e grazie
Il problema dei documenti è ora risolto.
Sulla pagina personale dell'utente ora di vedono le strutture di cui si fa parte.
Restano purtroppo i seguenti problemi:
- se di una struttura sono persona responsabile non compare tra le mie strutture, ma solo se sono una persona
- se nella pagina dell'utente aggiungo una struttura questa non compare (già segnalato in #161) né nella struttura né nella mia pagina personale; una volta aggiunta alla struttura allora compare.
- nella pagina della persona non compaiono le informazioni inserite in "Atri ruolo - funzioni strumentali"
Grazie del tuo lavoro

Marco

**Comment by astagi** [comment]
Ho impostato la #161 come bug, passo poi al fornitore. Per quanto riguarda  "Altri ruoli - funzioni strumentali" ci guardo subito. Domani sera rilasciamo una nuova versione con questi fix e altre cose

**Comment by astagi** [comment]
Perdonami @marcoverze93 ma nei template statici non vedo la sezione "Altri ruoli - funzioni strumentali" https://italia.github.io/design-scuole-pagine-statiche/scuole-scheda-persona.html

Dove dovrebbe stare?

**Comment by marcoverze93** [comment]
> Perdonami @marcoverze93 ma nei template statici non vedo la sezione "Altri ruoli - funzioni strumentali" https://italia.github.io/design-scuole-pagine-statiche/scuole-scheda-persona.html
> 
> Dove dovrebbe stare?

A dire il vero non lo so...io vedo così la gestione...penso dovrebbe andare dopo le strutture di riferimento (che però non vedo nel link che hai messo).
![image](https://user-images.githubusercontent.com/120751528/209988979-308495e7-928b-4693-b4e4-c6852386cfa1.png)
![image](https://user-images.githubusercontent.com/120751528/209988878-48797260-866a-4c48-bf81-f18e233063cf.png)
Inoltre io non riesco a inserire le materie come invece tu ha mostrato nell'immagine...non c'è il posto dove compilare.
Grazie

**Comment by astagi** [comment]
@marcoverze93 dovrei guardarci con più calma scusami, magari anche con gli altri colleghi. Posso chiederti la cortesia di aprire una nuova issue per questi ultimi problemi? questa verrà chiusa con il merge! Grazie!
