### ISSUE TITLE
Notifica circolare #129

### ISSUE THREAD

**Issue by Cate55** [italia/design-scuole-wordpress-theme#205]
Mi dispiace che non sia stata presa in considerazione la PR  #141 perchè considerata inutile. Ribadisco che il file circolare.php anche nella versione 2.1.5 non notifica le circolari agli utenti se selezionati in base al ruolo. 
Vi invito a verificare.  Grazie

**Comment by astagi** [comment]
@Cate55 nessun ha considerato inutile la PR #141 dobbiamo capire un attimo cosa non funziona perchè non riusciamo a riprodurre. Inoltre il codice sembra non cambi niente rispetto all'originale. Chiudo questa issue perchè possiamo tranquillamente discutere il tutto sotto i commenti della PR e non aprendo segnalazioni fuori luogo. Grazie.
