### ISSUE TITLE
Sezione foto e video duplicata in eventi

### ISSUE THREAD

**Issue by astagi** [italia/design-scuole-wordpress-theme#207]
se pubblico delle foto nella galleria dell'evento mi compaiono sia sotto nella sezione "foto e video" sia sotto la parte di descrizione dell'evento

![image](https://user-images.githubusercontent.com/537363/209955133-4293db87-aa73-4b7c-8770-8baea2599959.png)
![image](https://user-images.githubusercontent.com/537363/209955143-04fd6e7e-c600-4d30-8352-8889361ded58.png)

Riportare le modifiche apportate nel [template statico](https://italia.github.io/design-scuole-pagine-statiche/scuole-scheda-evento.html).

**Comment by astagi** [comment]
cc @vcoopcsc

**Comment by boazaob** [comment]
Ci sono novità per risolvere?
Inoltre, è previsto un prossimo ampliamento con Lightbox?
Grazie

**Comment by danieledexter** [comment]
Anche io sono interessato per l'utilizzo futuro di un lightbox
