### ISSUE TITLE
Mancata tipologia in breadcrumb su Eventi

### ISSUE THREAD

**Issue by astagi** [italia/design-scuole-wordpress-theme#209]
Se entro in un singolo evento mi aspetto di trovare nella breadcrumb prima del titolo dell'evento la sua tipologia.

**Comment by vcoopcsc** [comment]
Ciao, segnalo che anche nell'ultima versione il problema persiste

**Comment by vcoopcsc** [comment]
Buongiorno, segnalo che dopo test sulla versione 2.3.0 il breadcrumb non è cambiato.
