### ISSUE TITLE
Impossibilità a caricare il tema su un sito wordpress

### ISSUE THREAD

**Issue by giannizav** [italia/design-scuole-wordpress-theme#21]
Salve, l'errore è il seguente:
Installazione tema dal file caricato: design-scuole-wordpress-theme-master.zip
Scompattamento del pacchetto…Installazione del tema…Il pacchetto non può essere installato. **Nel tema manca il foglio di stile style.css.** Installazione del tema fallita.

**Comment by webgrafia** [comment]
Probabilmente c'è qualche problema nello zip che hai creato, nel repo lo style.css è presente.
Ricordati poi di scaricare l'archivio completo seguendo le istruzioni indicate nel readme: 

git clone https://github.com/italia/design-scuole-wordpress-theme.git
cd design-scuole-wordpress-theme/
git submodule init
git submodule update
