### ISSUE TITLE
Flaggando la categoria delle schede progetti il colore non rimane blu ma diventa rosso

### ISSUE THREAD

**Issue by astagi** [italia/design-scuole-wordpress-theme#211]
<img width="1094" alt="image" src="https://user-images.githubusercontent.com/537363/209956848-edd991a4-0684-40dd-8f36-78d5a8f8821d.png">

**Comment by vcoopcsc** [comment]
Ciao, segnalo che il problema persiste

**Comment by vcoopcsc** [comment]
Buongiorno, segnalo che anche nella versione 2.3.0 il problema persiste
