### ISSUE TITLE
Content-type che non appaiono nelle pagine archivio

### ISSUE THREAD

**Issue by anitamaccio** [italia/design-scuole-wordpress-theme#22]
Salve, avevo già posta la questione e mi era stato detto che che era risolta, ma a me anche con l'ultima versione scaricata adesso continua a fare lo stesso "errore": nelle pagine archivio per tag, i content-type diversi da articoli e pagine non appaiono: ad esempio qui https://www.icvs.edu.it/argomento/progetti-etwinning/ non appaiono le schede progetto con tag progetti-etwinning.
C'è qualche errore che faccio io?
Grazie
Anita Macciò

**Comment by webgrafia** [comment]
ciao Anita,
ho provato a replicare il tuo problema, creando un argomento al quale ho associato diverse tipologie di contenuti (compresa una scheda progetto) e qui la vedo:
https://demo.la-scuola.it/argomento/argomento-1/
anche creandola con lo stesso nome:
https://demo.la-scuola.it/argomento/progetti-etwinning/
In realtà anche sul tuo ambiente funziona per un'altra tassonomia:
https://www.icvs.edu.it/argomento/etwinning/

Puoi provare a cambiare la data e / o l'anno della scheda, e verificare se il problema non sia legato all'annualità delle schede progetto?
Il tema filtra automaticamente la pagina di lista dei progetti, mostrando solo quelli dell'anno in corso, forse il filtro si è esteso anche alla lista per argomento

**Comment by anitamaccio** [comment]
Ciao, 
in realtà nel mio ambiente non funziona per nessuna tassonomia, alla pagina 
https://www.icvs.edu.it/argomento/etwinning/
quello che vedi è un articolo normale, e gli articoli normali sono gli unici che si vedono nelle pagine di archivio tassonomia, tutti gli altri tipi di contenuto no, fatti quest'anno o relativi all'anno scorso che sia.
Ho comunque inserito un progetto di prova relativo a quest'anno:
https://www.icvs.edu.it/scheda-progetto/progetto-etwinning-2019-20/
e continua a non vedersi:
https://www.icvs.edu.it/argomento/etwinning/

e ad esempio con il tag modulistica ho inserito sia servizi che documenti con data di quest'anno, ma anche questo argomento mi appare desolatamente vuoto:
https://www.icvs.edu.it/argomento/modulistica/

non so se sono io che devo impostare qualcosa da qualche parte, per vederli come nel vostro ambiente di prova, ma non ho trovato nulla.

**Comment by webgrafia** [comment]
Hai ragione, avevo visto male.
Quali plugin hai attivi sull'installazione?

**Comment by anitamaccio** [comment]
Ciao, i plugin sono questi:

- Add Categories to Pages
- Akismet Anti-Spam
- Amministrazione Aperta
- amr shortcode any widget
- ANAC XML Bandi di Gara RELOADED
- ANAC XML Viewer
- Contact Form 7
- Contact Form CFDB7
- Disable Gutenberg
- Ginger - EU Cookie Law
- Members
- Raw HTML
- WP QuickLaTeX
- WP Super Cache
- Yoast SEO

**Comment by webgrafia** [comment]
ad occhio potrebbe essere colpa del primo:
Add Categories to Pages
che potrebbe riscrivere le regole di estrazione delle tassonomie 
Prova a disattivarlo

L'altro che non ho testato (escludo sia lui, ma tentare non nuoce) è yoast

**Comment by anitamaccio** [comment]
Hai ragione, ho disattivato Add Categories to Pages e ora vedo tutti i content-type nelle pagine archivio, non l'avevo considerato perchè non era installato la prima volta che avevo aperto l'issue, ma probabilmente l'ho attivato prima della tua risoluzione.

Grazie
Anita

**Comment by webgrafia** [comment]
bene, chiudo la issue
