### ISSUE TITLE
All'interno di strutture cambiare H4 > H2 e H6 > H3

### ISSUE THREAD

**Issue by astagi** [italia/design-scuole-wordpress-theme#222]
<img width="452" alt="image" src="https://user-images.githubusercontent.com/537363/209963035-17a3cf4e-1cd4-45db-9e9e-3a555a6e9360.png">

**Comment by vcoopcsc** [comment]
Buongiorno, 

segnalo che il problema è stato in parte risolto ma restano da sistemare gli altri H: 

- Organizzazione e contatti da H4 ad H2
- Strutture dipendenti da H6 ad H3
- Contatti da H6 ad H3
- Sede da H4 a H2
<img width="605" alt="image" src="https://user-images.githubusercontent.com/92174841/215510367-51dd09b9-d953-49ba-b8e3-ff1f2d58ff6e.png">

Resto a disposizione, grazie in anticipo
