### ISSUE TITLE
Vari problemi su Utenti/Persone

### ISSUE THREAD

**Issue by marcoverze93** [italia/design-scuole-wordpress-theme#224]
Buongiorno,
di seguito alcuni problemi riscontrati su Utenti:
- Nella pagina mostrata al link: https://italia.github.io/design-scuole-pagine-statiche/scuole-scheda-persona.html, come dovrebbe essere, compare la sezione didattica con le materie, ma nella gestione dell'utente non è possibile inserire in quanto manca lo spazio dove metterle.
- A seguito della #204 è stato risolto con il fix #206 il problema che non comparivano le strutture alle quali si era associati. Ora compaiono ma ci sono alcuni problemi: se in una struttura sono responsabile e non persona non compare; se la struttura la allego all'utente dalla sua pagina non si viene collegati (stessa cosa detta in #161), inoltre questa sezione di strutture non compare nella pagina riportata al link sopra che è il modello.
- In utente è possibile inserire "Altri ruoli" che però poi non compaiono da nessuna parte nella pagine della persona.

Grazie

**Comment by astagi** [comment]
buongiorno @marcoverze93 per quanto riguarda gli Altri ruoli intendi questi?

<img width="461" alt="image" src="https://user-images.githubusercontent.com/537363/211274131-b62ccd6f-b3a8-4524-8b59-8bee2801588d.png">

dovrebbero restare privati all'interno del CMS.

**Comment by marcoverze93** [comment]
No, nell'immagine sotto si vede quali sono:
![image](https://user-images.githubusercontent.com/120751528/211275401-f5f50474-3458-4c2d-9b34-136340ee2f7d.png)
Grazie

**Comment by astagi** [comment]
@marcoverze93 ok visto, questo solo nel caso dei docenti. Diciamo che non lo consideriamo prioritario, che cosa vorreste inserire all'interno di questa sezione lato vostro e quanto può essere fondamentale da mostrare pubblicamente sulla pagina del profilo?

**Comment by marcoverze93** [comment]
@astagi in realtà pensavo che rimaneva anche per gli altri, in particolare per la segreteria, in modo da poter inserire i compiti che svolgono i vari segretari. Per quanto riguarda i docenti avremmo poco da mettere.

**Comment by zetareticoli** [comment]
Ciao @marcoverze93, per semplificare il lavoro di gestione delle issues ti chiederei la cortesia di aprirne una per ogni problema.
