### ISSUE TITLE
Slide documenti non funziona

### ISSUE THREAD

**Issue by boazaob** [italia/design-scuole-wordpress-theme#225]
in Versione 2.1.5

- Nella stessa sezione sembra non funzionare lo slide dei documenti (anche i pallini segnaposto sotto i documenti non funzionano)

Grazie

**Comment by marcoverze93** [comment]
Ciao @boazaob 
per la visualizzazione della mappa nella sezione luoghi mi sembra strano che non funzioni...nel sito della mia scuola va benissimo. https://www.isisromero.it/luogo/
Anche "carte della scuola" da noi è corretto.

**Comment by boazaob** [comment]
Grazie @marcoverze93.
Per le mappe non vedevo neanche le vostre, ma ho scoperto che è un problema di cookies.
Invece per le carte della scuola, mi riferisco a:
https://www.isisromero.it/la-scuola/
![immagine](https://user-images.githubusercontent.com/114248388/210140814-09a7238a-c4d3-41a4-be5e-2ee08bd3fc1f.png)
il titolo risulta: "Le carte dAlla scuola" dalla invece di della e i pallini di scorrimento non funzionano.

**Comment by fa-ro** [comment]
> Grazie @marcoverze93.
> Per le mappe non vedevo neanche le vostre, ma ho scoperto che è un problema di cookies.
> Invece per le carte della scuola, mi riferisco a:
> https://www.isisromero.it/la-scuola/
> ![immagine](https://user-images.githubusercontent.com/114248388/210140814-09a7238a-c4d3-41a4-be5e-2ee08bd3fc1f.png)
> il titolo risulta: "Le carte dAlla scuola" dalla invece di della e i pallini di scorrimento non funzionano.

Ti confermo la dipendenza dai Cookies per la visualizzazione delle mappe. I cookies non accettati non rendono visibili nemmeno il link su Youtube (il che va bene, dato che la visualizzazione di video yt manda cookies fuori sito). Ora con @marcoverze93 devo configurare bene il modulo cookies in modo che sia possibile accettare tutto/in parte e sia chiaro cosa funzionerà/non funzionerà in base alla scelta

**Comment by zetareticoli** [comment]
> * Il menu Top (secondario in alto a destra) visualizza l'ultima voce a destra in grassetto (font-weight:600)
> 
> Grazie

l'ultima voce del menu Top deve rimandare alla lista degli argomenti

**Comment by astagi** [comment]
@boazaob ho modificato la descrizione della issue.
