### ISSUE TITLE
Errore  scheda autore nella versione del tema 2.1.6

### ISSUE THREAD

**Issue by Simsimus** [italia/design-scuole-wordpress-theme#226]
Salve,
volevo segnalare che, a seguito aggiornamento alla versione 2.1.6, cliccando sulla scheda autore, viene segnalato questo errore:
Fatal error: Uncaught TypeError: in_array(): Argument 2 ($haystack) must be of type array, string given in \wp-content\themes\design-scuole-wordpress-theme-main\author.php:130 
Stack trace: 
0 \wp-content\themes\design-scuole-wordpress-theme-main\author.php(130): in_array('3', '') 
1 [internal function]: filter_my_structures(Object(WP_Post)) 
2 \wp-content\themes\design-scuole-wordpress-theme-main\author.php(136): array_filter(Array, 'filter_my_struc...') 
3 \wp-includes\template-loader.php(106): include('...') 
4 \wp-blog-header.php(19): require_once('...') 
5 \index.php(17): require('...') 
6 {main} thrown in \wp-content\themes\design-scuole-wordpress-theme-main\author.php on line 130

Preciso che il test è stato effettuato su un demo in locale con dati minimali (un articolo e poco più) e che con la versione 2.1.5 tale problema non c'era.

**Comment by astagi** [comment]
Grazie @Simsimus forse qua dovremmo mettere un if prima del filter per vedere che l'array sia effettivamente valorizzato https://github.com/italia/design-scuole-wordpress-theme/commit/f77374bcc7bf7258f21afa01d42843c32e3245fc .. riprendiamo lo sviluppo dopo il 9 gennaio, se vuoi provare a modificare e fare una PR ben venga! Grazie mille 🙏
