### ISSUE TITLE
Bandiera Italia vicino a collegamento Amministrazione Trasparente.

### ISSUE THREAD

**Issue by Jhndo** [italia/design-scuole-wordpress-theme#228]
Buongiorno, nella mia scuola chiedono di aggiungere una piccola bandiera dell'Italia a fianco della scritta Amministrazione trasparente, nel menù Top in alto a destra. E' possibile? qualcuno potrebbe darmi qualche indicazione?
Grazie mille.

**Comment by astagi** [comment]
@Jhndo buongiorno, non ho capito dove volete inserire la bandierina, puoi farmi uno screenshot?

**Comment by Jhndo** [comment]
![Screenshot 2023-01-09 at 11-14-42 ICBR – Istituto Comprensivo di Brentonico](https://user-images.githubusercontent.com/113902185/211285851-d4064654-a7bc-4cbf-9a4b-34dca2809870.jpg)

**Comment by Jhndo** [comment]
Dovrebbe essere una cosa così!

**Comment by astagi** [comment]
@Jhndo modificando la label all'interno del codice inserendo una semplice emoji 🇮🇹 può funzionare?

**Comment by astagi** [comment]
In alternativa aggiungerei del CSS custom aggiuntivo e agirei sul :before senza toccare le label

**Comment by Jhndo** [comment]
Con l'emoji ha funzionato, grazie. Più avanti proverò anche l'altra soluzione.
