### ISSUE TITLE
Multi-lingua, quale sistema usare?

### ISSUE THREAD

**Issue by SamuelManca** [italia/design-scuole-wordpress-theme#229]
Alcune scuole, principalmente quelle che si trovano al confine con Slovenia, Austria ecc., hanno necessità di inserire i contenuti in più lingue, i plugin più usati solitamente sono WPML, TranslatePress, Loco Translate o PolyLang.

Non ho trovato alcuna menzione ad un sistema multi-lingua nella documentazione.

Per via di come funzionano i contenuti, WPML non é compatibile (ho provato).
In alternativa ho provato TranslatePress (che usavamo con il vecchio tema di Design Italia), però sembrerebbe che nemmeno questo sia compatibile, perchè genera la pagina tradotta in una sottocartella (www.sito.com/sito-wp/en) e va in conflitto.

Immagino che anche altre scuole più lontane dai confini vorranno tradurre il loro sito in inglese o tedesco, qual é il plugin "ufficiale" che supporta il tema?

Aggiornamento: Cambiare dalle impostazioni la struttura dei permalink a "nome articolo" fa funzionare correttamente TranslatePress, è una soluzione corretta?

**Comment by zetareticoli** [comment]
Ciao @SamuelManca, 
non c'è un'indicazione particolare su quali plugin usare per la funzionalità multi-lingua. 

Quando dici che non sono compatibili, intendi che non riesci a farli funzionare?

**Comment by igorsko** [comment]
Ciao, io ho iniziato questa settimana a tradurre il tema in sloveno, per adesso non vedo particolari criticità (uso WPML)

**Comment by astagi** [comment]
WPML credo sia la strada migliore. @igorsko sta migliorando anche il supporto all'interno del tema. Possiamo chiudere, grazie :)
