### ISSUE TITLE
Calendario sparito

### ISSUE THREAD

**Issue by anitamaccio** [italia/design-scuole-wordpress-theme#23]
Salve, mi sono accorta oggi che alla pagina https://www.icvs.edu.it/evento/ si vedono gli eventi ma non si vede più il calendario. Non ho notato da quando non si vede più.
Grazie e cordiali saluti
Anita Macciò

**Comment by webgrafia** [comment]
Buongiorno Anita
puoi girarmi (caricandolo a questa issue) un export degli eventi del tuo sito, così che possa replicare il problema?
Sul nostro ambiente di test non succede:
https://demo.la-scuola.it/evento/

L'export puoi farlo su 
Strumenti > Esporta -> Eventi

**Comment by anitamaccio** [comment]
Posso provare a farlo, ma sul vostro ambiente di test io vedo la pagina esattamente come nel mio sito, senza il calendario ma solo gli eventi, allego lo screen.
![2020-01-16](https://user-images.githubusercontent.com/58820327/72524667-ab4b2300-3862-11ea-8221-dd3b0cd6a73b.png)
Eppure ho cancellato la cache diverse volte, sia su Firefox che su chrome, ma continuo a non vederlo...

**Comment by anitamaccio** [comment]
Qui c'è l'export degli eventi, l'ho salvato in txt perchè in xml non si può allegare:
[istitutocomprensivovallestura.WordPress.2020-01-16.xml.txt](https://github.com/italia/design-scuole-wordpress-theme/files/4071373/istitutocomprensivovallestura.WordPress.2020-01-16.xml.txt)

**Comment by webgrafia** [comment]
Ciao, 
sono riuscito a riprodurre (ma solo una volta) il problema del calendario tramite firefox.
Però solo al primo caricamento, ricaricando la pagina il calendario si vede correttamente, e non da più errore. 
Mi confermi se succede anche a te?

**Comment by anitamaccio** [comment]
No, a me no, ho provato a ricaricare un sacco di volte, sia su firefox che su chrome, andando anche a cancellare la cache, ma non mi appare in nessun modo... Pensandoci ci sembra che sia successo nel momento in cui abbiamo provato ad abilitare un altro tema, poi abbiamo riabilitato il tema design-scuole e da allora il calendario non si vede.

**Comment by webgrafia** [comment]
Lo vedi male anche ricaricando la pagina, sul nostro ambiente?
https://demo.la-scuola.it/evento/

**Comment by anitamaccio** [comment]
No, ricaricando la pagina nel vostro ambiente adesso vedo il calendario, al suo posto.

**Comment by webgrafia** [comment]
ok allora sono 2 problemi distinti. Continuiamo ad indagare :)

**Comment by webgrafia** [comment]
domanda: hai installato il plugin Ginger? Puoi provare a spegnerlo / disattivarlo e vedere se il calendario si vede correttamente?

In caso sia quello, cancella il plugin e reinstallalo (abbiamo rilasciato un fix anche su quel repo: https://github.com/webgrafia/ginger/ )

**Comment by anitamaccio** [comment]
Si, l'avevo installato e attivato, era nel pacchetto. L'ho disattivato e il calendario è apparso correttamente, ho cancellato il plugin e scaricata la nuova versione, attivata, e il calendario è sempre al suo posto, risolto :)

**Comment by webgrafia** [comment]
Ottimo! chiudo la issue
