### ISSUE TITLE
Errore in apertura pagina argomento e presenza voce in menù secondario

### ISSUE THREAD

**Issue by sviluppoRobyone** [italia/design-scuole-wordpress-theme#230]
Buon pomeriggio,
nonostante la presenza di argomenti,
la parte pubblica del sito web non apre la pagina dell'argomento
(restituisce errore 404 all'indirizzo [sitoweb.edu.it/argomento/[parola-chiave]](http://sitoweb.edu.it/argomento/[parola-chiave])).
Chiedo inoltre informazioni riguardo la predisposizione degli argomenti nel menù secondario come da modello.
Ringrazio anticipatamente

**Comment by astagi** [comment]
Buongiorno @sviluppoRobyone abbiamo fatto una prova sulla nostra installazione locale e la pagina si apre correttamente, filtrando per argomenti rispetto alla parola chiave

<img width="1263" alt="image" src="https://user-images.githubusercontent.com/537363/212640989-88d2107e-017e-4735-8865-cd8d95f67ff3.png">

**Comment by sviluppoRobyone** [comment]
Buon pomeriggio,
al momento della segnalazione il problema riguardava le sorgenti presenti nel ramo main (riprovando oggi risulta funzionante).

Riguardo invece al menù secondario, il modello prevederebbe 3 voci scelte ad-hoc e un link a una pagina con la lista di tutti gli argomenti
![image](https://user-images.githubusercontent.com/13221786/212698368-6dfd0ae8-009f-4995-87bf-30909bd7e324.png)

Quali meccanismi sono stati previsti in merito?

Se per i 3 argomenti in evidenza possiamo provvedere all'inserimento manuale delle voci nella sezione Menù di Wordpress, non sembrerebbe esserci la possibilità di avere invece una voce "Tutti gli argomenti"

**Comment by sviluppoRobyone** [comment]
Ci sono novità in merito alla richiesta?
Ringrazio anticipatamente

**Comment by astagi** [comment]
@sviluppoRobyone  cambio il tag in domanda, a quanto mi sembra di capire la voce `Tutti gli argomenti` dovrebbe presentarsi automaticamente a prescindere da quanti argomenti avete inserito o se sono più di 3? da dove state aggiungendo gli argomenti in evidenza, da quale voce del backoffice?

**Comment by sviluppoRobyone** [comment]
Attualmente il tema non prevede funzionalità particolari in merito a quel menù secondario (ipotizziamo questa scelta sia stata compiuta per fornire più libertà e poter inserire qualsiasi tipo di link).

La configurazione attualmente avviene tramite un generico inserimento di voci di menù da "Aspetto" di Wordpress > "Menu", selezionando "Top (Menu secondario in alto a destra)".

Per quanto base, la sola predisposizione di una pagina che raccolga la lista di tutte le voci degli argomenti presenti sarebbe sufficiente per prevedere il link "Tutti gli argomenti" come previsto da modello. Ad oggi però il tipo di voce non ci risulta essere predisposta.

Rimango in attesa di riscontro e ringrazio

**Comment by sviluppoRobyone** [comment]
Attualmente la pull request su questo repository è ferma, in attesa dell'aggiornamento della grafica sul repo delle pagine statiche.
Quindi il problema c'è ancora...
