### ISSUE TITLE
Bug nel sistema di notifiche delle circolari: /inc/admin/circolare.php (con soluzione!)

### ISSUE THREAD

**Issue by netpaolo** [italia/design-scuole-wordpress-theme#232]
Il sistema non notifica né a tutta la scuola, né secondo il ruolo. Il bug è nella funzione dsi_feedback_circolare del file in oggetto.

Nello specifico dovrebbe essere così modificato:

```php
if($destinatari_circolari == "all"){
		$users = get_users( array( 'fields' => 'ID'  ) );
	}else if($destinatari_circolari == "ruolo"){
		$ruoli_circolari = dsi_get_meta("ruoli_circolari", '', $post->ID);
		$users = get_users( array( 'role__in' => $ruoli_circolari, 'fields' => 'ID'  ) );
	}else if($destinatari_circolari == "gruppo"){
		$gruppi_circolari = dsi_get_meta("gruppi_circolari", '', $post->ID);
		$users = get_objects_in_term( $gruppi_circolari, "gruppo-utente" );
	}
```

Perché la funzione get_users non restituisce un array di WP_USER se fields è un array e non una stringa come nello snippet qui pubblicato. Spero di essere stato utile.

**Comment by boazaob** [comment]
Grazie @netpaolo

**Comment by astagi** [comment]
Grazie @netpaolo potresti aprire una PR con la modifica così la rendiamo ufficiale? Grazie!

**Comment by netpaolo** [comment]
No ho aperto una PR perché dovrei eseguire un fork...
