### ISSUE TITLE
Perdita voci personalizzate dopo update thema

### ISSUE THREAD

**Issue by franzuin** [italia/design-scuole-wordpress-theme#233]
Buongiorno,

ho provato ad aggiornare il tema dalla 2.0.3 all'ultima versione. Il problema è che perdo le modifiche che abbiamo fatto nei diversi menù e link personalizzati.
Come posso fare per mantenerli?

**Comment by boazaob** [comment]
Salve @franzuin,
questo problema lo avevo già notato con versioni precedenti del tema. Risolto poi installando il tema child.
Aggiungo però che per verificare, tramite app dedicata, la conformità del sito, ho provato a disabilitare il tema child per usare il tema padre e anche in questo caso ho perso tutte le modifiche fatte ai menù di secondo livello.
A nulla è servito ripristinare il tema child.
Unica soluzione ricostruire manualmente tutte le modifiche perse.

**Comment by franzuin** [comment]
Infatti sto procedendo alla ricostruzione manuale.

Grazie mille

Il giorno gio 12 gen 2023 alle ore 16:44 boazaob ***@***.***>
ha scritto:

**Comment by zompa-zampa** [comment]
Anch'io ho questo problema. Avete notizie se si sta lavorando per superare questo bug?

**Comment by zetareticoli** [comment]
Ciao @zompa-zampa, purtroppo ad oggi non so darti una stima se e quando ci sarà un aggiornamento in merito a questo problema.

**Comment by FioreG1** [comment]
Ho aggiornato alla versione 2.6.1 il tema ed adesso non riesco ad aggiornare la home. Malgrado abbia configurato la home in modo che siano visibili in automatico messaggi ed eventi non c'è niente nella home pubblicata. Cosa devo fare?

**Comment by FioreG1** [comment]
inoltre se provo a creare il pdf delle circolari pubblicate ricevo questo messaggio:

Si è verificato un errore critico sul tuo sito web.

**Comment by danieledexter** [comment]
Anche io ho riscontrato questa anomalia con l'utilizzo del tema child.
Sembra che le modifiche su voci di menù e link vengano perse.

Credo si verifichi in particolare con il cambio del tema attivo.

Ieri ho fatto i controlli con lo strumento di validazione su entrambi i temi per notare eventuali differenze, ed oggi infatti mi sono trovato con il menù senza le mie modifiche.

**Comment by boazaob** [comment]
L'anomalia non è causata dal tema child, anzi con il tema child è possibile aggiornare il tema padre senza perdere le modifiche ai menù.
Diversamente utilizzando il solo tema principale (senza child) ogni volta che lo si aggiorna si perdono le modifiche al menù.
Questo avviene anche se, utilizzando il tema child, si attiva momentaneamente il tema padre (esempio per fare un test).
Praticamente il tema padre resetta tutti i menù. Tornare al tema child non serve.

**Comment by danieledexter** [comment]
Grazie per l'informazione, mi chiedo quindi se questo può essere sistemato oppure se si tratta di un comportamento corretto.

**Comment by boazaob** [comment]
Bella domanda che giro a @zetareticoli anche se ha già risposto.

> Ciao @zompa-zampa, purtroppo ad oggi non so darti una stima se e quando ci sarà un aggiornamento in merito a questo problema.

Comunque sembrerebbe che, per questioni di conformità, ci vincolino a non modificare i menù.
Pur avendo buone ragioni, questo ci limita non poco.
Non so se sarà possibile, ma l'ideale potrebbe essere poter aggiungere menù di secondo livello senza modificare gli esistenti.
Detto per inciso, il test di conformità sembrerebbe verificare la presenza di menù di secondo livello diversi da quelli autorizzati. Facendo poi una media con questi ultimi, ne attribuisce un punteggio inferiore.

**Comment by EasyTeamSrl** [comment]
Aggiungo che non solo vengono perse le modifiche ai menu, ma si resettano anche tutti i widget delle quattro colonne del footer.
Se per i menu si può anche comprendere la motivazione, perdere i widget del footer ad ogni modifica, anche temporanea, del tema, costringe a molto lavoro supplementare per ricostruire tutto a mano

**Comment by astagi** [comment]
@boazaob @EasyTeamSrl @danieledexter @FioreG1 @zompa-zampa @franzuin quindi fatemi capire, con il tema child si andrebbe a risolvere l'aggiornamento del tema padre giusto? Penso che se si va ad aggiornare il tema ogni volta che esce una nuova versione sostituendo i file, se si lavora solo sul tema padre questo viene a tutti gli effetti sovrascritto (si tratta proprio di un replace dei file del tema). Per voi è possibile provare a lavorare su un tema child e lasciare intatte le modifiche del tema padre?

**Comment by EasyTeamSrl** [comment]
> @boazaob @EasyTeamSrl @danieledexter @FioreG1 @zompa-zampa @franzuin quindi fatemi capire, con il tema child si andrebbe a risolvere l'aggiornamento del tema padre giusto?

Con un tema child si risolve una parte del problema: quella dell'aggiornamento del tema padre che causa l'azzeramento delle modifiche a menu e widget del footer.
Non si risolve invece l'altra parte del problema: quando si cambia tema e si attiva anche temporaneamente il tema padre, vengono resettate le impostazioni di menu e widget del footer

**Comment by boazaob** [comment]
Confermo quanto riferito da @EasyTeamSrl mantenedo attivo il tema child si può aggiornare il tema padre senza perdere nulla, ma se si attiva il tema padre si perdono le modifiche a menu e widget del footer e non serve riattivare il tema child.

**Comment by EasyTeamSrl** [comment]
> Comunque sembrerebbe che, per questioni di conformità, ci vincolino a non modificare i menù. Pur avendo buone ragioni, questo ci limita non poco.

Questo può anche essere accettato. Il test di validazione fa effettivamente una verifica sulle voci del menu e abbassa il punteggio se si discostano da quelle standard.
Il problema però NON è solo il menu: cambiando tema anche solo per un secondo, si perdono tutti i footer personalizzati (che non sono interessati dalla validazione), si perde il menu secondario (che non è interessato dalla validazione)..
E' come se la riattivazione anche temporanea del tema facesse un "resettone" di tante impostazioni, non solo delle quattro voci del menu principale.

**Comment by leosamuele221** [comment]
Sto facendo delle prove in questo momento:
Aggiornando dalla 2.1.7 alla 2.3.2
Il footer nell'aggiornamento non mi scompare 
Il menù secondario in alto a destra e nel footer non vengono eliminati ma semplicemente si resettano quelli di default, per recuperarli basta andare in "Gestione posizioni" e rimettere il menu precedente.
Per i menu principali le voci nel database rimangono ma non capisco come non le mostri dopo l'aggiornamento

Le prove sono state fatte con i plugin disattivati (ho solo rinominato la cartella "plugins")

**Comment by EasyTeamSrl** [comment]
Il codice responsabile di quanto accade si trova in function.php

Riga 165:
`add_action( 'after_setup_theme', 'dsi_setup' );`

La funzione dsi_setup , che si trova alla riga 104, fa una serie di cose tra cui appunto occuparsi del reset dei menu

**Comment by zetareticoli** [comment]
Ciao, 
vorrei capire meglio qual'è l'esigenza di eseguire lo switch tra tema padre e tema child a sviluppo in corso.

Gli aggiornamenti presenti nella v2.3.2 hanno parzialmente risolto questi problemi, come indicato da @leosamuele221 ?



> Il codice responsabile di quanto accade si trova in function.php
> 
> Riga 165: `add_action( 'after_setup_theme', 'dsi_setup' );`
> 
> La funzione dsi_setup , che si trova alla riga 104, fa una serie di cose tra cui appunto occuparsi del reset dei menu

@EasyTeamSrl hai avuto un riscontro positivo, eliminandola?
