### ISSUE TITLE
Errore nell'indicazione dell'anno scolastico corrente

### ISSUE THREAD

**Issue by danibrundu** [italia/design-scuole-wordpress-theme#234]
Sembrerebbe che ci sia un problema nella funzione dsi_get_current_anno_scolastico() nella determinazione dell'anno scolastico.
![error](https://user-images.githubusercontent.com/90426973/212126447-10ab35da-b321-48b5-bc77-21b7ef25fa93.JPG)
Grazie

**Comment by sagredo-dev** [comment]
file inc/utils.php riga 734 diventa

-  if(is_string($anno) && ($anno != "")) {
+ if(is_int($anno)) {

**Comment by danibrundu** [comment]
Grazie Grazie

**Comment by zetareticoli** [comment]
Ciao @danibrundu, il problema è stato risolto?

**Comment by danibrundu** [comment]
Buongiorno @zetareticoli, si grazie a @sagredo-dev 
![Cattura](https://user-images.githubusercontent.com/90426973/212641340-25a36b05-911c-459b-948e-702c50fc573c.PNG)

**Comment by astagi** [comment]
@danibrundu @sagredo-dev grazie mille, potete aprire una PR che include quel fix?
