### ISSUE TITLE
Registrazione script errata

### ISSUE THREAD

**Issue by claudiobat** [italia/design-scuole-wordpress-theme#237]
Installando il tema versione `2.1.6` nella console del browser compare l'errore:
`_Failed to load resource: the server responded with a status of 500 (Internal Server Error)
themes.php:1          GET http://localhost/laboratorio1/wp-admin/themes.php_`

Probabilmente nella seguente funzione **dsi_ammap_getJs** del file actions.php:

```php
function dsi_ammap_getJs(){
    wp_deregister_script('ammap_functions');
    wp_dequeue_script('ammap_functions');

    wp_register_script( 'ammap_functions', plugins_url('amministrazione-aperta/js/ammap.js'));
    wp_enqueue_script( 'ammap_functions');
}
```

va corretta la registrazione dello script in questo modo:

```php
    wp_register_script( 'ammap_functions', plugins_url('italia-amministrazione-aperta/js/ammap.js'));
```

**Comment by astagi** [comment]
Buongiorno @claudiobat ! Lascio la verifica a @milesimarco su questa questione :)

**Comment by astagi** [comment]
Ci sono aggiornamenti qua? @milesimarco @claudiobat

**Comment by giovannicaini** [comment]
Anche io ho verificato e bisogna effettuare quella modifica (la directory del plugin non è più amministrazione-aperta ma italia-amministrazione-aperta).

**Comment by sviluppoRobyone** [comment]
Buongiorno,
vorrei tornare su questa versione in quanto saremmo ben disposti a fare una pull request per correggere la registrazione dello script del plugin, ma non riesco a trovare il plugin a cui ci si sta riferendo. Cercando "amministrazione aperta" tra i plugin di WordPress, sono presenti:

- [Amministrazione Trasparente](https://it.wordpress.org/plugins/amministrazione-trasparente/) la cui cartella di root è `amministrazione-trasparente`;
- [Amministrazione Aperta](https://it.wordpress.org/plugins/amministrazione-aperta/) la cui cartella di root è `amministrazione-aperta`.

Nessuno dei due ha come root `italia-amministrazione-aperta` e nessuno dei due contiene un file che si chiami `ammap.js`. Probabilmente non sto trovando il plugin corretto. Avete per caso maggiori informazioni su come sistemare la cosa?

Per fornire più contesto, saremmo interessati a risolvere questo problema in quanto l'errore 404 dovuto al file mancante causa un leggero ritardo che impedisce a un plugin di terze parti per gestire i media di funzionare correttamente (che è un bug del plugin, ma abbiamo più speranze di risolvere il problema agendo sul tema anziché attendendo una risposta dagli sviluppatori, che abbiamo comunque sollecitato).

**Comment by VinsMach** [comment]
la seguente issue è collegata con altra #683  se viene considerata risolta quella potremmo chiuderle entrambe. Grazie
