### ISSUE TITLE
Problema nel caricamento jQuery nelle mappe

### ISSUE THREAD

**Issue by ID-Lab-dev1** [italia/design-scuole-wordpress-theme#238]
Buonasera,

Vorrei segnalare un problema nel caricamento di jQuery nelle pagine del sito. Anche se jQuery non è richiesto nella maggior parte del sito, in alcune pagine come la panoramica e il dettaglio dei luoghi, nelle quali sono presenti le mappe di leaflet, queste ultime non vengono caricate e danno un messaggio di errore sul log.

![image](https://user-images.githubusercontent.com/122626866/212360549-094df322-ec65-4233-a08e-ab6e8e187192.png)

Sospetto che il problema sia legato al caricamento asincrono di jQuery, dal momento che il metodo per caricare le mappe viene richiamato sul dom. Per il momento ho risolto caricando jQuery all'interno del file header.php, all'interno dell'<head>

![image](https://user-images.githubusercontent.com/122626866/212360684-f84ef919-fc76-4455-82b0-bdfda8f2fb13.png)

è possibile che questa modifica venga sovrascritta nel momento in cui è necessario aggiornare il tema? 

Grazie in anticipo per la disponibilità.

**Comment by astagi** [comment]
Buonasera @ID-Lab-dev1 

da nostra installazione risulta funzionante la mappa 
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/537363/212638476-7e360462-bbe4-4021-be0e-e1305ec5c92c.png">


inoltre allego lo screen del codice dove viene caricato jQuery

<img width="1222" alt="image" src="https://user-images.githubusercontent.com/537363/212638588-8d8f03ca-730f-4931-b8f6-0b49dbe626f1.png">


questo avviene nell'head

**Comment by astagi** [comment]
@netpaolo molto interessante, forse può essere il caso di aggiungerlo proprio nel codice del tema di base in modo da renderlo disponibile a tutti? cc @ID-Lab-dev1

**Comment by netpaolo** [comment]
> @netpaolo molto interessante, forse può essere il caso di aggiungerlo proprio nel codice del tema di base in modo da renderlo disponibile a tutti? cc @ID-Lab-dev1

bé sì.... è un bug!

**Comment by astagi** [comment]
Puoi eventualmente aprire una PR con questa modifica @netpaolo ?

**Comment by astagi** [comment]
Già che ci sono @netpaolo non so se avevi letto i commenti anche sull'altra PR che avevi aperto https://github.com/italia/design-scuole-wordpress-theme/pull/235 ti ringrazio tantissimo del tuo contributo!

**Comment by netpaolo** [comment]
> Già che ci sono @netpaolo non so se avevi letto i commenti anche sull'altra PR che avevi aperto #235 ti ringrazio tantissimo del tuo contributo!

Non un programmatore PHP, ma non ho mai usato github... non sono molto esperto...

**Comment by astagi** [comment]
@netpaolo ho aperto la PR seguendo le tue indicazioni :) ditemi se funziona https://github.com/italia/design-scuole-wordpress-theme/pull/240 cc @ID-Lab-dev1
