### ISSUE TITLE
Amministrazione trasparente non funziona

### ISSUE THREAD

**Issue by maddom73** [italia/design-scuole-wordpress-theme#24]
Non riesco a caricare i file in amministrazione trasparente. Quando creo documento e faccio flag su presente in amministrazione trasparente non vedo tipologia. 
![Screenshot_2020-01-16-18-50-49-311_com android chrome](https://user-images.githubusercontent.com/5103247/72549564-3c38f300-3891-11ea-8684-e95044a57f78.jpg)

**Comment by webgrafia** [comment]
ciao,
quei campi dovrebbe averlo autopopolati all'attivazione del tema.
Se non hai quelli immagino non hai neanche i menu, e tutte le altre tassonomie, giusto?

Prova a cambiare tema, selezionando quello di default, e poi riassociando questo. 
Questa operazione dovrebbe eseguire il popolamento della base dati

**Comment by maddom73** [comment]
Purtroppo non è cambiato nulla. Tipologia di amministrazione trasparente sempre blank. Ho i menù e le tassonomia di tutto tranne che di amministrazione trasparente.

**Comment by webgrafia** [comment]
Ok allora tento di replicare il problema

**Comment by maddom73** [comment]
Ho provato clonare il repo e creare un altro file zip. Disinstallato tema e reinstallato col nuovo zip e problema persiste.

**Comment by webgrafia** [comment]
Ma hai installato i sottomoduli del tema? Questi i comandi da usare per generare un archivio consistente:
git clone https://github.com/italia/design-scuole-wordpress-theme.git
cd design-scuole-wordpress-theme/
git submodule init
git submodule update

**Comment by maddom73** [comment]
Assolutamente sì. Poi creato archivio zip e installato

**Comment by maddom73** [comment]
Puoi postare uno screenshot di come dovrebbe essere quella sezione? Così per rendermi conto

**Comment by webgrafia** [comment]
Ho capito il problema:
il campo "taxonomy_select_hierarchical" che è quello usato nel selettore di amministrazione trasparente, è sul ramo develop di CMB2. Nonostante il fatto che abbia dichiarato quel ramo sul file .gitmodule, perchè venga effettivamente recuperato il comando da usare non è solo
git submodule update
ma bensì
git submodule update --remote

Ho aggiornato il readme dettagliando questo comando

Sul tuo ambiente, se esegui 
git submodule update --remote
dovrebbe aggiornarti i file e sparire quell'errore, e dovresti vedere una schermata come quella che ti allego

![Schermata del 2020-01-20 10-29-09](https://user-images.githubusercontent.com/9932389/72715305-84e1fc00-3b70-11ea-8a35-a99bd196358c.png)
Grazie della segnalazione

**Comment by maddom73** [comment]
Era quello il problema. Grazie a te

**Comment by webgrafia** [comment]
ottimo, chiuso la issue
