### ISSUE TITLE
Aggiornamento tema

### ISSUE THREAD

**Issue by mariozUT** [italia/design-scuole-wordpress-theme#241]
Buongiorno, ho aggiornato il tema alla versione 2.1.6 dalla 2.1.4, scaricando il file zip in locale e aggiungendo il nuovo tema da wordpress, ma ogni volta perdo tutti i link che ho impostato nel footer.
Probabilmente sbaglio qualcosa, ma sapreste dire come fare correttamente per non perdere sempre questi dati??
Grazie

**Comment by Jhndo** [comment]
#233

**Comment by astagi** [comment]
Chiudo. Duplicato
