### ISSUE TITLE
Contatto da MONITORA PA per problemi

### ISSUE THREAD

**Issue by mariozUT** [italia/design-scuole-wordpress-theme#242]
Vi riporto quanto arrivato per pec: sapreste dirmi come risolvere? Grazie

> All'attenzione di: - ..................................... in qualità di
> soggetto titolare del trattamento ai sensi dell'art. 4 par. 1 n. 7 - GDPR. Il
> sottoscritto Giacomo Tesio, nato a Asti il 29/11/1980 (codice fiscale:
> TSEGCM80S29A479Z), scrive nell'ambito nel progetto Monitora PA
> (https://monitora-pa.it) e con il sostegno dei cittadini che vi collaborano e
> delle associazioni elencate in calce, eleggendo ai fini del presente atto a
> domicilio digitale l'indirizzo di posta elettronica certificata
> comunicazioni@pec.monitora-pa.it, e a domicilio fisico via Aretusa 34, a
> Milano. Vogliamo segnalarvi che, tramite l'esecuzione del nostro
> osservatorio, in data 2023-01-15 02:33:19.147925, abbiamo rilevato che il sito
> web del vostro Ente www.ictravagliato.edu.it incorpora: JsDelivr (Cloudflare,
> Inc.) - https://cdn.jsdelivr.net/gh/FormulaAgile/CookieShield/cookie-
> shield.js jquery.com (StackPath) - https://code.jquery.com/jquery-
> 3.6.3.min.js?ver=3.6.3 - https://code.jquery.com/jquery-migrate-
> 3.4.0.min.js?ver=3.4.0 determinando trasferimenti sistematici non
> attualmente conformi, in assenza di efficaci misure tecniche supplementari,
> alle disposizioni del GDPR in ordine al trasferimento transfrontaliero di diversi
> dati personali dei visitatori, fra cui: - indirizzo IP - User Agent - sistema
> operativo - lingue conosciute - la visita al vostro sito - la data e l'ora di tale
> visita - i dati personali descrittivi deducibili dall'incrocio dei dati precedenti con
> i contenuti visualizzati sul vostro sito Le informazioni inviate durante tali
> trasferimenti sono più che sufficienti ad identificare il soggetto interessato,
> tracciarne la navigazione e ad arricchirne il profilo cognitivo-
> comportamentale.

**Comment by manjaro16** [comment]
Confermo, ricevuto anche noi un contatto da monitora-pa per lo stesso motivo. È causato da jquery che viene servita da CDN tramite plugin "Version control for jquery", suggerito dal tema.

**Comment by astagi** [comment]
@manjaro16 @mariozUT il tema nelle ultime versioni non include più jquery version control. Se lo avete ancora attivato disabilitatelo.

**Comment by astagi** [comment]
@manjaro16 procedo al merge e al rilascio della versione!

**Comment by astagi** [comment]
Versione rilasciata https://github.com/italia/design-scuole-wordpress-theme/releases/tag/v2.1.7
