### ISSUE TITLE
Jquery

### ISSUE THREAD

**Issue by scal1974** [italia/design-scuole-wordpress-theme#244]
Buongiorno è arrivata una segnalazione, nell'ambito 
nel progetto Monitora PA (https://monitora-pa.it) che, tramite l'esecuzione del loro osservatorio,
in data 2023-01-15 17:44:04.004191, il sito web www.iisolivetipanettalocri.edu.it incorpora:

jquery.com (StackPath)
- https://code.jquery.com/jquery-3.6.3.min.js?ver=3.6.3
- https://code.jquery.com/jquery-migrate-3.4.0.min.js?ver=3.4.0

determinando trasferimenti sistematici non attualmente conformi, 
in assenza di efficaci misure tecniche supplementari, alle 
disposizioni del GDPR in ordine al trasferimento transfrontaliero 
di diversi dati personali dei visitatori, fra cui:

- indirizzo IP
- User Agent
- sistema operativo
- lingue conosciute
- la visita al vostro sito
- la data e l'ora di tale visita
- i dati personali descrittivi deducibili dall'incrocio dei dati precedenti con i contenuti visualizzati sul vostro sito.

Effettuando un controllo ho verificato che il modulo members eseguiva queste query di cui allego screen.
Volevo sapere se il template usa queste query e se esiste un tools per verificare se ce ne siano altre. 
![screenshot-www iisolivetipanettalocri edu it-2023 01 19-08_52_00](https://user-images.githubusercontent.com/114990331/213385286-feb9f5d8-47d7-4ccd-a5df-ed1e3a6fa765.png)

[Grazie]

**Comment by astagi** [comment]
Buongiorno @scal1974 consiglio di disattivare e rimuovere il plugin e di aggiornare all'ultima versione del tema. Questa soluzione e la problematica stessa sono già state riportate in issue già chiuse per nuovi problemi aprire un'altra issue più specifica. Grazie

**Comment by scal1974** [comment]
Ho eliminato il plugin ma ugualmente quando vado su impostazioni e po su Version Control for jQuery 
le query ci sono. in ogni caso ho messo il flag per disabilitarle. é sufficiente? Allego Screen 

![screenshot-www iisolivetipanettalocri edu it -1](https://user-images.githubusercontent.com/114990331/213403399-ba0cb90e-b1d0-498b-a0f8-9f31ff885e3a.png)

**Comment by astagi** [comment]
@scal1974 se il plugin Version Control of jQuery è eliminato come si fa ad accedere alle impostazioni?

**Comment by astagi** [comment]
Ah no no mi scusi intendevo il plugin jQuery version control esatto!! Se lo elimina e aggiorna il tema all'ultima versione non verrà più cercato jQuery esternamente.

**Comment by scal1974** [comment]
Ma ho letto che aggiornando il tema le modifiche apportate verranno perse😒. Mi conferma? Grazie per la collaborazione
