### ISSUE TITLE
Suggerimento per personalizzazione contenuti home

### ISSUE THREAD

**Issue by Simsimus** [italia/design-scuole-wordpress-theme#248]
Buonasera,
volevo proporre una modifica alle impostazioni del tema.
Attualmente nel backend, in Configurazione > Home > Selezione automatica, ci sono le seguenti scelte:

**_- se si selezione SI la schermata sarà:_**
![visualizzazione-automatica](https://user-images.githubusercontent.com/108821309/213879103-7040532c-d6f8-457b-abed-ef9649a1ff70.jpg)

**_- se si selezione NO e quindi si scelgono manualmente più articoli (diciamo 6) la schermata sarà:_**
![visualizzazione-manuale](https://user-images.githubusercontent.com/108821309/213879192-c9928241-2f5d-410a-86f0-ac34b327ed35.jpg)

Sarebbe utilissimo per le scuole poter presentare i contenuti in base alle proprie esigenze, quindi, lasciando le impostazioni come sono nel backend, ovvero:
![impostazioni](https://user-images.githubusercontent.com/108821309/213879283-7a89608b-6eef-4cdf-b111-80306fb33be8.jpg)
se si potesse aggiungere una condizione (credo nel file template-parts\home\articoli-manuali.php) che SE l'articolo selezionato è uno solo ALLORA "class=col-lg-12" (invece di col-lg-4) e il contenuto di questa singola pagina, ovviamente costruita come si vuole, dovrebbe essere visibile per intero.
Ad esempio, con l'utilizzo di qualche plugin, si potrebbe ottenere un risultato del genere:
![esempio-home](https://user-images.githubusercontent.com/108821309/216562714-663ca197-b58c-4f18-89e1-2a6e2d2a63eb.jpg)

Spero sia chiaro quanto proposto e che sia fattibile, in quanto di sicuro darebbe una marcia in più al tema.
Grazie

**Comment by astagi** [comment]
Grazie @Simsimus per ora lo teniamo segnato come miglioria, vediamo se riusciamo ad integrarlo nelle migliorie in questa o in una futura versione del tema.

**Comment by zetareticoli** [comment]
Ciao @Simsimus, nella tua richiesta hai specificato di voler avere un layout a tutta pagina nel caso in cui si inserisce un solo articolo manualmente.

Questo va in controtendenza rispetto allo screen che hai postato dopo, dove invece ci sono più notizie su tre colonne.

Il tema ora consente una gestione piuttosto coerente dei contenuti in homepage, pertanto non daremo seguito alla tua richiesta. Grazie
