### ISSUE TITLE
Problema nel visualizzare author

### ISSUE THREAD

**Issue by leosamuele221** [italia/design-scuole-wordpress-theme#249]
Buongiorno, con l'aggiornamento all'ultima versione le pagine authors hanno smesso completamente di funzionare, controllando il codice e gli errori che mi dava PHP ho trovato queste problematiche:

la versione che uso di PHP è 8.0.27

qui un estratto del log:
```
[23-Jan-2023 11:37:31 UTC] PHP Warning:  Undefined variable $document in /home/wp-content/themes/design-scuole-wordpress-theme-217/author.php on line 130
[23-Jan-2023 11:37:31 UTC] PHP Warning:  Attempt to read property "ID" on null in /home/wp-content/themes/design-scuole-wordpress-theme-217/author.php on line 130
[23-Jan-2023 11:37:31 UTC] PHP Fatal error:  Uncaught TypeError: in_array(): Argument #2 ($haystack) must be of type array, string given in /home/wp-content/themes/design-scuole-wordpress-theme-217/author.php:151
Stack trace:
#0 /home/wp-content/themes/design-scuole-wordpress-theme-217/author.php(151): in_array()
#1 [internal function]: filter_my_documents()
#2 /home/wp-content/themes/design-scuole-wordpress-theme-217/author.php(155): array_filter()
#3 /home/wp-includes/template-loader.php(106): include('...')
#4 /home/wp-blog-header.php(19): require_once('...')
#5 /home/index.php(17): require('...')
#6 {main}
  thrown in /home/wp-content/themes/design-scuole-wordpress-theme-217/author.php on line 151
```

Qui un estratto di authors.php versione 2.1.7 (https://github.com/italia/design-scuole-wordpress-theme/blob/v2.1.7/author.php)
```
function filter_my_structures($structure) {
    if ( !empty( get_post_meta( $document->ID, "_dsi_documento_autori", true ) ) ) {
        return in_array(
            (string)$GLOBALS['author_id'],
            get_post_meta( $structure->ID, "_dsi_struttura_persone", true )
        );
    }
    
    return false;
}

$strutture = array_filter($strutture, "filter_my_structures");

$args = array(
    'posts_per_page' => -1,
    'post_type' => 'documento'
);
$documenti = get_posts($args);

function filter_my_documents($document) {
    return in_array(
        (string)$GLOBALS['author_id'],
        get_post_meta( $document->ID, "_dsi_documento_autori", true )
    );
}
```

- a [riga 130](https://github.com/italia/design-scuole-wordpress-theme/blob/v2.1.7/author.php#L130) va a cercare una variabile $document che non esiste, probabilmente volevate scrivere $structure (il parametro della funzione), comunque questo è "solo" un Warning
- [riga 151](https://github.com/italia/design-scuole-wordpress-theme/blob/v2.1.7/author.php#L151):
 - si usa la funzione "[in_array](https://www.php.net/manual/en/function.in-array.php)" che richiede una striinga e come secondo parametro un array (giustamente, serve a cercare un elemento dentro un array). Il problema è che usanto "[get_post_meta](https://developer.wordpress.org/reference/functions/get_post_meta/)" con single impostato a true [restituirà sempre un valore](https://developer.wordpress.org/reference/functions/get_post_meta/#return) e non un array come richiesto da "in_array"
 - questo errore può presentarsi anche a [riga 133](https://github.com/italia/design-scuole-wordpress-theme/blob/v2.1.7/author.php#L133) per lo stesso identico motivo

Questo il mio codice con le correzioni:
```
function filter_my_structures($structure) {
    if (!empty( get_post_meta( $structure->ID, "_dsi_documento_autori", true ) ) ) {
        return in_array(
            (string)$GLOBALS['author_id'],
            get_post_meta( $structure->ID, "_dsi_struttura_persone", false)
        );
    }
    return false;
}

$strutture = array_filter($strutture, "filter_my_structures");

$args = array(
    'posts_per_page' => -1,
    'post_type' => 'documento'
);
$documenti = get_posts($args);

function filter_my_documents($document) {
    return in_array(
        (string)$GLOBALS['author_id'],
        get_post_meta( $document->ID, "_dsi_documento_autori", false)
    );
}
```
Ho semplicemente cambiato riga 133 e 151 in "false" e corretto riga 130 con $structure
Fatemi sapere se mi è sfuggito qualcosa

**Comment by astagi** [comment]
@leosamuele221 forse i problemi che riscontri sono già stati risolti dalla modifica di @barilefrancesco https://github.com/italia/design-scuole-wordpress-theme/pull/245

Fammi sapere se ti torna.

**Comment by barilefrancesco** [comment]
@leosamuele221 prova a sostituire il tuo `author.php` con il nuovo che trovi qui: [author.php](https://github.com/italia/design-scuole-wordpress-theme/blob/main/author.php)

**Comment by leosamuele221** [comment]
Sostituito, ora quegli errori non si presentano più, in compenso si presenta questo:
```
[26-Jan-2023 15:38:53 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function dsi_get_img_from_id_url() in /home/wp-content/themes/design-scuole-wordpress-theme-217/author.php:177
Stack trace:
#0 /home/wp-includes/template-loader.php(106): include()
#1 /home/wp-blog-header.php(19): require_once('...')
#2 /home/index.php(17): require('...')
#3 {main}
  thrown in /home/wp-content/themes/design-scuole-wordpress-theme-217/author.php on line 177
```

**Comment by barilefrancesco** [comment]
@leosamuele221 devi aggiornare il file `inc/utils.php`, lo trovi qui: [utils.php](https://github.com/italia/design-scuole-wordpress-theme/blob/main/inc/utils.php)

**Comment by leosamuele221** [comment]
Okay grazie, ora funziona tutto. Consiglierei di fare una nuova relase, perchè chiunque abbia scaricato la 2.1.7 potrebbe trovarsi questi problemi

**Comment by astagi** [comment]
Certo @leosamuele221 procediamo con una nuova release. Grazie ancora @barilefrancesco

**Comment by astagi** [comment]
Nuova versione 2.1.8 rilasciata.
