### ISSUE TITLE
Problema di istallazione

### ISSUE THREAD

**Issue by roberto-martorana** [italia/design-scuole-wordpress-theme#25]
Buon giorno, gestisco il sito della mia scuola e, in vista di un prossimo rifacimento, sto cercando si aggiungere il tema a una istallazione pulita di WordPress 5.0.8 (ho visto sul readme che il tema è testato fino alla versione 5.1, e per questo motivo non ho scelto una versione più aggiornata di Wordpress), ma l'Anteprima mi restituisce un errore 500 ("xxxxxxxxxxx.it al momento non è in grado di gestire la richiesta."), senza ulteriori indicazioni. Con tutti gli altri temi con i quali ho provato a fare la stessa cosa il problema non si pone. 
La versione di php del server è la 7.0.7 

Qualcuno potrebbe aiutarmi?

**Comment by webgrafia** [comment]
ciao Roberto,
per la versione di wordpress, devo aggiornare il readme, funziona anche con l'ultima rilasciata.
Per l'errore, quale anteprima ti da errore? quella di un articolo in bozza? uno pubblicato ma modificato?

**Comment by roberto-martorana** [comment]
Intanto grazie per aver risposto! 
Mi da errore l'anteprima del tema: ho caricato il tema seguendo la procedura di istallazione pagina Aspetto/Temi; il tema viene visualizzato, ma appena clicco su "Antemprima in tempo reale" per vedere come verrà il sito quando sarà attivato, mi restituisce l'errore di cui parlavo sopra. (v. immagine allegata)
![Immagine1](https://user-images.githubusercontent.com/60501439/73547045-821fba80-443e-11ea-9742-a56c6000e798.png). 
![Immagine2](https://user-images.githubusercontent.com/60501439/73547223-cc08a080-443e-11ea-8964-991101e64ad7.png)

**Comment by webgrafia** [comment]
Ho testato nella mia installazione e non ho riscontrato il problema.
Hai installato il tema con le dipendenze dei moduli, come indicato nel readme, con i seguenti comandi git?

git clone https://github.com/italia/design-scuole-wordpress-theme.git
cd design-scuole-wordpress-theme/
git submodule init
git submodule update --remote

Se riesci a mandarmi l'errore che hai sul log posso indagare meglio

**Comment by roberto-martorana** [comment]
No, ho solo scaricato il file "design-scuole-wordpress-theme-master.zip" e cercato di istallarlo usando l'interfaccia grafica di wordpress. E' sbagliata questa procedura?

**Comment by webgrafia** [comment]
Si è sbagliata, devi eseguire i comandi indicati per compilarti il tema

**Comment by roberto-martorana** [comment]
Ok. Allora mi documenterò su come fare. Grazie per il tuo tempo e buon lavoro!

**Comment by roberto-martorana** [comment]
Problema risolto come da indicazioni! Grazie di nuovo
