### ISSUE TITLE
Bug su custom post - PHP 8.x

### ISSUE THREAD

**Issue by manjaro16** [italia/design-scuole-wordpress-theme#252]
Buongiorno,
abbiamo installato e configurato il tema su server con php 8.1 (o 8.0 in alternativa).
All'interno dei custom post "scheda-progetto" e "documento", compare il seguente errore php

` Warning: Array to string conversion in /home/icparaz1/public_html/wp-includes/general-template.php on line 184`

Abbiamo momentaneamente risolto facendo downgrade a php 7.4, che però ha raggiunto EOL da qualche mese.
È un problema noto?

Grazie

**Comment by astagi** [comment]
Buongiorno @manjaro16 un warning non è un problema bloccante, penso la miglior cosa sia tenere Wordpress aggiornato all'ultima versione e disabilitare i warning da configurazione.
