### ISSUE TITLE
App di valutazione dell’adesione al modello scuole

### ISSUE THREAD

**Issue by Anto886** [italia/design-scuole-wordpress-theme#253]
salve, ho eseguito un test con l'App di valutazione dell’adesione al modello scuole per il sito "https://www.itetgirardi.edu.it/". Dal report sono emersi questi errori:

**C.SC.2.1 - INFORMATIVA PRIVACY** - Il sito della scuola deve presentare l'informativa sul trattamento dei dati personali, secondo quanto previsto dalla normativa vigente. Errore
CONDIZIONI DI SUCCESSO: il sito presenta una voce nel footer che riporta alla privacy policy; MODALITÀ DI VERIFICA: viene verificata la presenza del link nel footer, che riporti a una pagina esistente e con certificato HTTPS valido e attivo, ricercando uno specifico attributo "data-element" come spiegato nella Documentazione delle App di valutazione; RIFERIMENTI TECNICI E NORMATIVI: Documentazione del Modello scuole, GDPR Artt. 13 e 14, Reg. UE n. 2016/679, Documentazione delle App di valutazione.

**C.SC.2.2 - DICHIARAZIONE DI ACCESSIBILITÀ** - Il sito della scuola deve esporre la dichiarazione di accessibilità. Errore
CONDIZIONI DI SUCCESSO: il sito presenta una voce nel footer che riporta alla dichiarazione di accessibilità; MODALITÀ DI VERIFICA: viene verificata la presenza del link nel footer, che riporti a una pagina esistente e che sia quella contenente la dichiarazione di accessibilità (il link deve iniziare con “https://form.agid.gov.it/view/”), ricercando uno specifico attributo “data-element” come spiegato nella Documentazione delle App di valutazione; RIFERIMENTI TECNICI E NORMATIVI: Documentazione del Modello scuole, AgID Linee guida sull’accessibilità degli strumenti informatici, Direttiva UE n. 2102/2016, Legge 9 gennaio 2004 n. 4, Web Content Accessibility Guidelines WCAG 2.1, AgID dichiarazione di accessibilità, Documentazione delle App di valutazione.

**C.SC.2.3 - COOKIE** - Il sito della scuola deve presentare cookie tecnici in linea con la normativa vigente. Errore
CONDIZIONI DI SUCCESSO: il sito presenta solo cookie idonei come definito dalla normativa; MODALITÀ DI VERIFICA: viene verificato che il dominio dei cookie identificati sia corrispondente al dominio del sito web; RIFERIMENTI TECNICI E NORMATIVI: Linee guida cookie e altri strumenti di tracciamento - 10 giugno 2021

mi potete consigliare come risolverli?

Grazie in anticipo

**Comment by Jamielrey** [comment]
C.SC.2.1 - INFORMATIVA PRIVACY
Per risolvere questo errore devi inserire nel menù footer il link all'informativa sulla privacy, ed assicurarti che venga aggiunto il data-element=”privacy-policy-link”.
Perché ciò avvenga il link deve avere o il item->post_name == 'privacy-policy', oppure nel titolo deve essere inserito la parola privacy (se usi il tema aggiornata alla 2.1.8, altrimenti vale solo la prima opzione).

C.SC.2.2 - DICHIARAZIONE DI ACCESSIBILITÀ
Come sopra, con il link sulla dichiarazione di accessibilità, assicurandoti che sia presente il data-element=”accessibility-link”.
Affinché ciò avvenga il link deve avere o item->post_name == 'dichiarazione-di-accessibilita' oppure nel titolo deve essere inserita la parola accessibilità (se usi il tema aggiornata alla 2.1.8, altrimenti vale solo la prima opzione).

C.SC.2.3 - COOKIE
Il sito deve utilizzare i cookie secondo la normativa vigente. Qui il discorso è un po' più complesso.

**Comment by Anto886** [comment]
Grazie alle tue informazioni ho risolto.
Ma ora dal test risultano le senguenti non conformità:

C.SC.1.1 - COERENZA DELL'UTILIZZO DEI FONT (librerie di caratteri) - Il sito della scuola deve utilizzare i font indicati dalla documentazione del modello di sito della scuola.
CONDIZIONI DI SUCCESSO: tutti i titoli (heading) e tutti i paragrafi delle pagine del sito in lingua italiana devono usare esclusivamente i font Titillium Web, Lora e Roboto Mono; MODALITÀ DI VERIFICA: ricercando uno specifico attributo “data-element” come spiegato nella Documentazione delle App di valutazione, viene verificato che i font richiesti abbiano la precedenza tra i font a disposizione all’interno di tutti gli <h> e <p> in una scheda servizio casualmente selezionata; RIFERIMENTI TECNICI E NORMATIVI: [Documentazione del Modello scuole](https://docs.italia.it/italia/designers-italia/design-scuole-docs), [Documentazione delle App di valutazione](https://docs.italia.it/italia/designers-italia/app-valutazione-modelli-docs)
Risultato
Non è stato possibile trovare una scheda servizio su cui condurre il test. Controlla le “Modalità di verifica” per scoprire di più.

C.SC.1.5 - VOCI DI MENÙ DI SECONDO LIVELLO - Il sito presenta le voci di menù di secondo livello come descritto nella documentazione del modello di sito della scuola.
CONDIZIONI DI SUCCESSO: le voci del menù di secondo livello corrispondono a quelle indicate nel documento di architettura dell’informazione del modello scuole; MODALITÀ DI VERIFICA: ricercando uno specifico attributo “data-element” come spiegato nella Documentazione delle App di valutazione, viene verificata la correttezza delle voci del menù di secondo livello riferite alla voce di primo livello “Scuola”; RIFERIMENTI TECNICI E NORMATIVI: Documentazione del Modello scuole, Documentazione delle App di valutazione.
Risultato	% di voci obbligatorie tra quelle usate	Voci di menù obbligatorie identificate	Voci di menù obbligatorie mancanti
Almeno il 30% delle voci usate sono corrette.	86%	presentazione, le carte della scuola, organizzazione, le persone, i numeri della scuola, la storia	i luoghi


grazie ancora dell'aiuto

**Comment by Jamielrey** [comment]
Mi fa piacere esser stato d'aiuto. Vediamo di risolvere anche questi:

C.SC.1.1 - COERENZA DELL'UTILIZZO DEI FONT
Per controllare questa voce l'app prende un servizio a caso, ma non riesce a trovarlo. Assicurati di: 

1) nel menù ci sono le voci "famiglie" e "personale scolastico" ed abbiano entrambi il data-element=”service-type”.
2) devi avere almeno 1 servizio per le famiglie ed almeno 1 servizio per il personale scolastico.

C.SC.1.5 - VOCI DI MENÙ DI SECONDO LIVELLO
Nel menù scuola c'è un piccolo problema. Anche in questo caso le opzioni sono 2: 

1) manca qualche voce.
2) hai aggiunto qualche voce.

Se rendi il menù uguale al 100% alla versione del tema non avrai più problemi.

**Comment by astagi** [comment]
@Anto886 sei riuscito a risolvere con le indicazioni di @Jamielrey ?

**Comment by TlC123789** [comment]
Salve faccio una domanda anche in questo caso inerente alla questione delle voci di meù.
Si pososno aggiungere delle voci di menù in più rispetto a quelle evidenziate nel modello delle scuole? Nel caso in cui non possa farlo, posso usare delle sotto vocie di menù dentro il menù secondario (il menù in alto a destra per intederci)?
Grazie in anticipo per la risposta

**Comment by Anto886** [comment]
Ciao  a  tutti, 
purtroppo ho rifatto il test ed i problemi sono riapparsi. Potete darmi una mano per risolverli.
Sono questi di seguito:

![image](https://github.com/italia/design-scuole-wordpress-theme/assets/121058089/d47a830d-2301-4122-929f-34bfab56d224)

![image](https://github.com/italia/design-scuole-wordpress-theme/assets/121058089/002d2c12-573f-42eb-98f0-e7fe71338eea)

**Comment by loky62** [comment]
Ho lo stesso problema di Anto886 su C.SC 2.2. Dichiarazione di accessibilità. Ho provato inserendo direttamente un url personalizzato al link dell'agid ed anche facendo una pagina ad hoc e mettendo il data-element accessibility-linl. Qualcuno ha suggerimenti ? Grazie.

**Comment by Petrillo96** [comment]
Ciao, ma in merito alla dichiarazione di accessibilità come vi state comportando? il parzialmente conforme alla 2.1 può andare bene ai fini del controllo dell'asseveratore?

**Comment by Petrillo96** [comment]
> Ho lo stesso problema di Anto886 su C.SC 2.2. Dichiarazione di accessibilità. Ho provato inserendo direttamente un url personalizzato al link dell'agid ed anche facendo una pagina ad hoc e mettendo il data-element accessibility-link. Il tema è Wordpress Design Scuole Italia Versione: 2.3.2. Qualcuno ha suggerimenti ? Grazie.

Ciao, ma in merito alla dichiarazione di accessibilità come vi state comportando? il parzialmente conforme alla 2.1 può andare bene ai fini del controllo dell'asseveratore?

**Comment by farapeppe** [comment]
> > Ho lo stesso problema di Anto886 su C.SC 2.2. Dichiarazione di accessibilità. Ho provato inserendo direttamente un url personalizzato al link dell'agid ed anche facendo una pagina ad hoc e mettendo il data-element accessibility-link. Il tema è Wordpress Design Scuole Italia Versione: 2.3.2. Qualcuno ha suggerimenti ? Grazie.
> 
> Ciao, ma in merito alla dichiarazione di accessibilità come vi state comportando? il parzialmente conforme alla 2.1 può andare bene ai fini del controllo dell'asseveratore?

Sì, è sufficiente
