### ISSUE TITLE
Editor Gutemberg

### ISSUE THREAD

**Issue by ricboc** [italia/design-scuole-wordpress-theme#254]
Nella pagina
https://github.com/italia/design-scuole-wordpress-theme#editor-gutenberg
alla voce Editor Gutemberg, leggo

🚨 Attenzione! Il tema non supporta l'editor dei blocchi Gutenberg. È quindi necessario verificare che il plugin Disable Gutenberg sia correttamente installato e attivo. Le schede didattiche, ovvero gli approfondimenti su un argomento specifico, sono l’unico contenuto che può esser scritto liberamente dai docenti, dopo averli fatti iscrivere a WordPress. 

Volevo sapere se questa incompatibilità è dovuta a problemi legati all'accessibilità oppure tecniche e quindi incompatibili al tema rilasciato.

Grazie

**Comment by astagi** [comment]
Buongiorno @ricboc si questa funzionalità non è supportata, decideremo in futuro se integrarla o meno nelle evolutive.
