### ISSUE TITLE
Visibilità circolari

### ISSUE THREAD

**Issue by boazaob** [italia/design-scuole-wordpress-theme#256]
Nella creazione di una circolare, nell'apposita sezione "Visibilità della Circolare sul sito" e attivando la visibilità per il solo "Personale Scolastico (utenti registrati)" non si ottiene l'effetto desiderato di impedire l'accesso ai non docenti.
Inoltre nella spiegazione sottostante viene detto:
"Seleziona se il documento è pubblico o visibile solo agli utenti registrati indicati di seguito"
Ma di seguito non compare nulla.
![immagine](https://user-images.githubusercontent.com/114248388/215274917-2a25c489-ecf2-43b8-869e-a2da66b57c7e.png)

**Comment by boazaob** [comment]
Grazie per la risposta @vcoopcsc,
Il problema non è l'invio delle circolari che tempo fa avevo testato e non c'erano problemi sia per l'invio che per la visibilità nella Bacheca.
La visibilità a cui mi riferisco è quella del front end, in pratica, alcune circolari occorre che siano visibili a tutti (registrati o meno), altre dovrebbero essere visibili solo agli utenti registrati (personale scolastico) dopo aver fatto l'accesso a wordpress.
Questo non accade: se seleziono la visibilità di una circolare per il solo personale scolastico (utente registrato), la stessa sarà visibile a chiunque senza che sia necessario effettuare l'accesso al back end.

**Comment by vcoopcsc** [comment]
Hai ragione, ho testato anche io ed effettivamente compaiono nella sezione circolari in frontend, anche se cliccandole non si aprono ma riportano alla home del sito.

**Comment by boazaob** [comment]
Dipende, con alcuni browser si aprono con altri (es Chrome) mandano alla home

**Comment by vcoopcsc** [comment]
A me Edge e Mozzilla rimandano entrambi alla home, a meno che chiaramente io non sia già loggata. In questo caso mi aprono la circolare e posso inviare il feedback.

**Comment by boazaob** [comment]
Come non detto, hai ragione. (l'altro giorno mi si aprivano ma solo con alcuni browser). Adesso inviano alla home, ma sarebbe più corretto non vedere le circolari in elenco se non loggati. Inoltre, se si è in possesso del link alla circolare riservata, dovrebbe aprirsi una pagina con messaggio di errore.

**Comment by vcoopcsc** [comment]
Buongiorno, 

ho testato le circolari dell'ultima versione disponibile, facendo seguito a quanto segnalato da boazaob i problemi rilevati sono i seguenti: 

1. se si seleziona l'opzione **"visibilità della circolare sul sito"->Personale scolastico** (utenti registrati), a prescindere dalla selezione degli utenti registrati selezionati nel campo "Destinatari della circolare", la circolare è visibile in frontend a tutti.  
--**Se** navigo senza essermi loggato** vedo la circolare in home e nella sezione "Circolari", ma non la posso aprire. Infatti se provo a cliccarla mi ricarica semplicemente la home. 
--**Se** navigo da loggata ** vedo la circolare in home e nella sezione "Circolari" e **la posso sempre aprire** anche se non sono stato selezionato come destinatario della circolare. 
Questo rende problematica la gestione delle circolari perché quelle riservate nel titolo e nel numero sono visibili a tutti. Dovrebbero in realtà poter essere viste e ricercate in frontend solo dagli utenti selezionati come destinatari. 
2. Se seleziono l'opzione "nessun feedback" alla voce "Richiedi un feedback agli utenti" non arriva nessuna mail di notifica, che invece credo dovrebbe arrivare (anche se la scuola non necessita di feedback, gli utenti destinatari della circolare dovrebbero ricevere una notifica via mail che li informa dell'emissione della circolare)
3. Alla voce "Richiedi un feedback agli utenti, nella guida in backend c'è scritto Se la circolare è di tipologia "assemblea sindacale" l'azione richiesta è "Sì/NO. Se la circolare è di tipologia "sciopero" l'azione richiesta è "Adesione sì/no/presa visione". Tuttavia nelle opzioni di feedback selezionabili non c'è "Adesione sì/no/presa visione" ma solo "Sì/no/presa visione".

**Comment by Simsimus** [comment]
Confermo il problema segnalato e, per quanto un navigatore senza account, al click, non riesca ad accedere direttamente alla circolare interessata, il problema in termini privacy è comunque elevato perchè è nelle condizioni di leggere il titolo e la relativa introduzione che dovrebbe restare riservata. L'unica alternativa è quella di selezionare in "Visibilità" il check "Privato" (riquadro relativo al salvataggio) in modo da lasciare visibile solo il titolo ed oscurare almeno il contenuto.

**Comment by MicheleMonza** [comment]
E' stato risolto per caso?

**Comment by boazaob** [comment]
Sembra di no

**Comment by zetareticoli** [comment]
Ciao, questo bug è stato inserito tra le priorità del prossimo rilascio del tema.

**Comment by vcoopcsc** [comment]
Grazie! C'è anche una pull request in bozza su questo, la Circolari view #322
