### ISSUE TITLE
Contatti (numero di telefono/mail) cliccabili

### ISSUE THREAD

**Issue by vcoopcsc** [italia/design-scuole-wordpress-theme#258]
Buongiorno, 

sarebbe comodissimo avere i contatti (numero di telefono e mail) dei servizi cliccabili in modo che il visitatore possa cliccare sul numero e chiamare direttamente e cliccare sulla mail e aprire l'app di posta per inviarla, anche considerando che molti navigano con smartphone. 
Ho notato che nei luoghi e negli eventi è cliccabile solo l'indirizzo mail, mentre nei servizi non sono cliccabili né la mail né il numero di telefono. 

Allego screen

- servizi 
<img width="1128" alt="image" src="https://user-images.githubusercontent.com/92174841/215484005-380b0b70-2422-410c-a03c-fa4772a25c1e.png">

- eventi
<img width="1113" alt="image" src="https://user-images.githubusercontent.com/92174841/215484115-d731676f-8723-4eb6-bfb2-031845107d65.png">

- Luoghi
<img width="1110" alt="image" src="https://user-images.githubusercontent.com/92174841/215484246-7385052d-720e-4bd8-9cdc-d8c1b142645b.png">

**Comment by Jamielrey** [comment]
Ciao, è una cosa molto semplice da aggiungere:

Per aggiungere nei servizi ad esempio ti basta andare in aspetto->editor tema->single-servizio.php

e sostituire le righe 437 e 438 con le seguenti:

<?php if($telefono){ ?><li><strong><?php _e("Telefono", "design_scuole_italia"); ?>:</strong> <?php echo "<a href='tel:+39$telefono'>$telefono</a>"; ?></li><?php } ?>

<?php if($mail){ ?><li><strong><?php _e("Email", "design_scuole_italia"); ?>:</strong> <?php echo "<a href = 'mailto: $mail'>$mail</a>"; ?></li><?php } ?>

Come puoi vedere ho solo aggiunto un href, così si può chiamare, o inviare mail, semplicemente con un click. Questa modifica la puoi fare dove vuoi. Ad esempio se vuoi aggiungere la stessa cosa nelle strutture, che anche è assente ti basta andare in aspetto->editor tema->single-struttura.php

e sostituire le righe 330 e 331 con le seguenti:

<?php if($telefono){ ?><li><strong><?php _e("Telefono", "design_scuole_italia"); ?>:</strong> <?php echo "<a href='tel:+39$telefono'>$telefono</a>"; ?></li><?php } ?>

<?php if($mail){ ?><li><strong><?php _e("Email", "design_scuole_italia"); ?>:</strong> <?php echo "<a href = 'mailto: $mail'>$mail</a>"; ?></li><?php } ?>

**Comment by astagi** [comment]
@Jamielrey se vuoi inviare una PR ben venga! Grazie!!
