### ISSUE TITLE
Fatal error: Uncaught Error: Call to undefined function members_can_user_view_post()

### ISSUE THREAD

**Issue by AndrewBitGit** [italia/design-scuole-wordpress-theme#26]
Ho scaricato il template a Gennaio, funzionava tutto correttamente. Questa mattina ho scaricato nuovamente il tutto, e quando provo ad inserire contenuti come luoghi o indirizzi di studio ottengo questo errore, che vi riporto nella sua completezza:
Fatal error: Uncaught Error: Call to undefined function members_can_user_view_post() in C:\Apache24\htdocs\wordpress\wp-content\themes\design-scuole-wordpress-theme\inc\utils.php:38 Stack trace: #0 C:\Apache24\htdocs\wordpress\wp-content\themes\design-scuole-wordpress-theme\inc\admin\evento.php(503): dsi_get_meta('timestamp_inizi...', '_dsi_evento_', 79) #1 C:\Apache24\htdocs\wordpress\wp-includes\class-wp-hook.php(288): dsi_add_eventi_metaboxes('') #2 C:\Apache24\htdocs\wordpress\wp-includes\class-wp-hook.php(312): WP_Hook->apply_filters(NULL, Array) #3 C:\Apache24\htdocs\wordpress\wp-includes\plugin.php(478): WP_Hook->do_action(Array) #4 C:\Apache24\htdocs\wordpress\wp-content\themes\design-scuole-wordpress-theme\inc\vendor\CMB2\bootstrap.php(34): do_action('cmb2_init') #5 C:\Apache24\htdocs\wordpress\wp-content\themes\design-scuole-wordpress-theme\inc\vendor\CMB2\init.php(165): cmb2_bootstrap() #6 C:\Apache24\htdocs\wordpress\wp-includes\class-wp-hook.php(288): CMB2_Bootstrap_270_Develop->include_cmb('') #7 C:\Apache24 in C:\Apache24\htdocs\wordpress\wp-content\themes\design-scuole-wordpress-theme\inc\utils.php on line 38

**Comment by webgrafia** [comment]
ciao @AndrewBitGit , 
prova a riscaricare l'ultima versione appena aggiornata, dovremmo aver fixato!
In caso ora sia ok chiudi la issue, grazie della segnalazione!
