### ISSUE TITLE
Taggare pagine con argomenti

### ISSUE THREAD

**Issue by vcoopcsc** [italia/design-scuole-wordpress-theme#260]
Buongiorno, 

sto lavorando sugli argomenti e il sistema non mi permette di taggare le pagine. Sarebbe utile poterlo fare perché le pagine compaiono in frontend solo se ricercate tramite il tasto cerca o se linkate da qualche parte. Con la taggatura si fornirebbe una terza modalità con la quale gli utenti possono cercare i contenuti pubblicati attraverso le pagine. 
Taggare le pagine con gli argomenti potrebbe facilitare la ricerca generale dei contenuti sul sito perché gli utenti ragionevolmente si aspettano di trovare nelle pagine di dettaglio di ogni argomento tutto ciò che riguarda quel tema, indipendentemente dalla modalità con la quale i vari contenuti sono stati creati (content type/pagine).

**Comment by zetareticoli** [comment]
Ciao @vcoopcsc, 
è possibile aggiungere gli argomenti tramite il widget da back-office. Allego esempio per Schede Progetto.
![Screenshot 2023-02-20 alle 10 04 46](https://user-images.githubusercontent.com/69706/220061143-b42c12a1-74cc-4e6d-9b83-31145b788d76.png)


O intendi qualcos'altro?

**Comment by vcoopcsc** [comment]
Ciao, esatto intendo questo, non vedo la maschera per selezionare gli argomenti. Per aggiungerla come posso fare?

**Comment by zetareticoli** [comment]
Puoi allegare uno screen della pagina in cui provi ad inserirli?

**Comment by astagi** [comment]
@vcoopcsc io li vedo lateralmente ad esempio per una scheda progetto

<img width="1434" alt="image" src="https://user-images.githubusercontent.com/537363/220575510-4044a8af-7936-46de-a296-bebe59875215.png">

**Comment by vcoopcsc** [comment]
Anche io li vedo lateralmente per le schede progetto (strutture, ecc.) ma per le pagine no, mi manca proprio il box "Argomento" sul quale andare a selezionare l'argomento.
<img width="726" alt="image" src="https://user-images.githubusercontent.com/92174841/220584635-57297bc5-71e4-4ad3-9b90-44fbdc0ed393.png">

**Comment by rcoopcsc** [comment]
Per aggiungere i tags (argomenti) alle pagine lato back end basta aggiungere queste due funzioni nel file functions.php


```
function pages_with_category_and_tag_register(){
  register_taxonomy_for_object_type('category', 'page');
  register_taxonomy_for_object_type('post_tag', 'page');
}
add_action( 'init', 'pages_with_category_and_tag_register');

function pages_with_category_and_tag_register_pre_get( $query ) {
  if ( is_admin() || ! $query->is_main_query() ) {
    return;
  }
  if($query->is_category && $query->is_main_query()){
    $query->set('post_type', array( 'post', 'page'));
  }
  if($query->is_tag && $query->is_main_query()){
    $query->set('post_type', array( 'post', 'page'));
  }
}
add_action( 'pre_get_posts', 'pages_with_category_and_tag_register_pre_get' );

```
Attenzione che lato front end la pagina page.php attuale di designers italia non contiene il codice get_template_part("template-parts/common/badges-argomenti"); che visualizza i tags inseriti, quindi o si inserisce manualmente oppure si può usare il codice usato in single-post.php e copiarlo in page.php (in questo modo le pagine singole ovviamente assomiglieranno a quelle degli articoli)
