### ISSUE TITLE
Testo alternativo CNS, SPID e STS nelle pagine servizi

### ISSUE THREAD

**Issue by vcoopcsc** [italia/design-scuole-wordpress-theme#262]
Buongiorno, 

nelle pagine dei servizi dove sono stati aggiunte le 3 modalità di autenticazione (SPID, CIE, STS), ai rispettivi loghi di SPID, CIE, STS mancano i testi alternativi. 
Grazie in anticipo

**Comment by astagi** [comment]
Risolto nell'ultima release
