### ISSUE TITLE
Mappa presente ma non visibile nella pagina i luoghi della scuola

### ISSUE THREAD

**Issue by vcoopcsc** [italia/design-scuole-wordpress-theme#263]
Buongiorno, 

impostando da configurazione ->luoghi "Visualizza mappa no", nella pagina dei luoghi della scuola (dal menu scuola-> i luoghi) la mappa viene percepita da WAVE e anche navigando tramite tastiera. E' come se ci fosse anche se non risulta visibile.
Allego screen WAVE
<img width="831" alt="image" src="https://user-images.githubusercontent.com/92174841/215494255-80b26f4e-5785-4dae-80e8-9b8f44e31a91.png">
Allego screen navigazione con TAB
![image](https://user-images.githubusercontent.com/92174841/215494815-45035ef4-98a8-4ba1-8558-6ec3121d7d9f.png)
Grazie in anticipo

**Comment by astagi** [comment]
Grazie @vcoopcsc forse la miglior soluzione è tagliare quella parte di template oppure aggiungere un attributo per nasconderlo in termini di a11y

**Comment by astagi** [comment]
Ciao @vcoopcsc ho appena aperto questa PR https://github.com/italia/design-scuole-wordpress-theme/pull/281 dimmi se risolve il problema :) Grazie!!

**Comment by vcoopcsc** [comment]
Ciao Andrea, confermo che risolve il problema!
Ti segnalo che nel backend la questione comparsa/non comparsa della mappa non è chiarissima. 
<img width="617" alt="image" src="https://user-images.githubusercontent.com/92174841/220670283-9f44bdaa-b832-4783-8885-6f2104bed16a.png">
Forse dovrebbe essere "Seleziona NO per non visualizzare la mappa nella pagina di elenco dei luoghi" oppure, forse più semplice, "Seleziona SI per visualizzare la mappa nella pagina di elenco dei luoghi"

**Comment by astagi** [comment]
Grazie @vcoopcsc concordo! Procedo alla modifica della label
