### ISSUE TITLE
Aggiornamento tema 2.1.8

### ISSUE THREAD

**Issue by scal1974** [italia/design-scuole-wordpress-theme#265]
Buongiorno volevo procedere all'aggiornamento del tema dalla Versione attuale 2.0.2 alla 2.1.8. Qual'è la procedura corretta per non avere la perdita di voci o contenuti personalizzati?

**Comment by Simsimus** [comment]
Buongiorno, per sicurezza fai prima una copia integrale (spazio + db) del sito e poi penso sia sufficiente sovrascrivere i files del tema 2.1.8 alla tua versione attuale presente in "wp-content/themes/"

**Comment by scal1974** [comment]
Buongiorno, ho fatto l'aggiornamento eliminando la cartella precedente e poi ho traferito la nuova.  Sembra tutto funzionare

**Comment by Simsimus** [comment]
Il consiglio era sovrascrivere i file nella stessa cartella originaria del tema. Verifica se ora, in wp-content/themes, sono presenti 2 cartelle diverse con lo stesso tema, oppure se la nuova cartella ha un none diverso dalla precedente

**Comment by boazaob** [comment]
Prima di aggiornare, consiglierei di leggere questo #233

**Comment by scal1974** [comment]
Nella directory wp-content/themes, adesso sono presenti 2 cartelle. Il thema precedente l' ho lasciato rinominandolo in - design-scuole-wordpress-theme-main_2.0.2 - e ho trasferito la versione 2.1.8 presente nella directory con il nome originale design-scuole-wordpress-theme-main. Allego screen

**Comment by Simsimus** [comment]
Allora ti basta eliminare la cartella rinominata (meglio farne una copia in locale prima di eliminarla) così da backend in Aspetto > Temi non troverai più il doppio tema.
Saluti

**Comment by astagi** [comment]
Grazie @Simsimus posso chiudere la issue
