### ISSUE TITLE
Bug nella gestione allegati

### ISSUE THREAD

**Issue by Simsimus** [italia/design-scuole-wordpress-theme#266]
Buongiorno,
se si inserisce nei media un documento attraverso la funzione "Carica file" e tale documento ha nel nome un carattere speciale (ad esempio: Graduatoria definitiva 1^ fascia), l'URL viene generato senza carattere speciale ("Graduatoria definitiva 1 fascia") ma il file viene archiviato con il carattere speciale, quindi il risultato è che se si clicca sul file per aprirlo o scaricarlo il sito va in errore pagina 404.

RIEPILOGO:
**file in input:** Graduatoria definitiva 1^ fascia
**url:** Graduatoria definitiva 1 fascia
**nome file archiviato:** Graduatoria definitiva 1^ fascia
**risultato:** al click errore 404

Auspico che tale problema possa essere risolto quanto prima.
Grazie

**Comment by astagi** [comment]
@Simsimus potresti passarmi un file che presenta questo problema? stiamo cercando di riprodurre e risolvere il bug.

**Comment by astagi** [comment]
@Simsimus ho provato a caricare nei Media un file chiamato `Graduatoria definitiva 1^ fascia.png` e la url funziona http://localhost:8081/wp-content/uploads/2023/02/Graduatoria-definitiva-1%5E-fascia.png

**Comment by Simsimus** [comment]
Ecco un file che genera il problema segnalato:
[Graduatoria definitiva 1^ fascia.pdf](https://github.com/italia/design-scuole-wordpress-theme/files/10795868/Graduatoria.definitiva.1.fascia.pdf)
(dopo aver scaricato il file, se diverso, rinominarlo con la descrizione "Graduatoria definitiva 1^ fascia.pdf").

Ho provato a caricarlo sia in un articolo, che in una circolare, che in un documento ed il problema è sempre lo stesso, se si clicca sul file viene fuori errore 404.

Per caricarlo uso la funzione:
![carica-documenti](https://user-images.githubusercontent.com/108821309/220413399-21cdd76f-784d-44d9-ae43-451a8c20c8ed.jpg)

**Comment by astagi** [comment]
@Simsimus questa PR https://github.com/italia/design-scuole-wordpress-theme/pull/283 dovrebbe risolvere il tuo problema. Hai modo di provarla?

**Comment by Simsimus** [comment]
Ho provato ad inserire in uno stesso articolo un file con nome pulito ed uno con carattere speciale. Il file pulito funziona regolarmente, mentre quello con carattere speciale genera l'errore:
Forbidden
You don't have permission to access this resource.

**Comment by astagi** [comment]
Non ho capito @Simsimus questo problema si genera anche con la mia modifica?

**Comment by Simsimus** [comment]
Ho appena approfondito meglio la cosa e ti confermo che con la tua modifica il problema si risolve.
So che magari non è una cosa che può interessare a chi legge, ma a seguito tale modifica, se lascio attivo il plugin firewall e nel nome del file è presente un carattere speciale, l'apertura dello stesso viene bloccata con l'errore "You don't have permission to access this resource". Se invece disattivo il plugin va tutto bene. Mi tocca capire se c'è una soluzione :(

**Comment by astagi** [comment]
@Simsimus si stavo giusto approfondendo anche questa cosa riguardo alla modifica.. a tutti gli effetti i caratteri speciali come "^" vengono di base ripuliti e rimossi. Posso vedere se c'è modo di inserire un alert ma non aggiungerei vulnerabilità quindi la mia modifica non mi ispira per niente fiducia :) guardo cosa posso fare a tal proposito. Per ora il mio consiglio è di ricaricare i file rimuovendo i caratteri speciali.

**Comment by astagi** [comment]
@Simsimus una cosa così dovrebbe andar bene

<img width="804" alt="image" src="https://user-images.githubusercontent.com/537363/220926924-b7107d8e-c90c-48ef-ab19-08c6f0b5d4e0.png">

**Comment by Simsimus** [comment]
@astagi, se ho capito bene l'alert segnala solo che ci sono caratteri non ammessi, ma non ne impedisce il caricamento, quindi se un utente ignora l'avviso il problema verrebbe lo stesso fuori, giusto? Ad ogni modo è meglio utilizzare la versione pre-modifica, che è più tutelante, così anche se viene fuori l'errore 404 almeno l'utente è stato avvisato. Ma questa nuova modifica con l'aggiunta dell'alert l'hai già applicata?

**Comment by astagi** [comment]
Ciao @Simsimus no ancora non l'ho applicata, in realtà questo messaggio viene fuori dopo l'aggiornamento dell'articolo. Dovrei agire lato JavaScript, vedo che posso fare.

**Comment by astagi** [comment]
@Simsimus ho aggiornato la PR guarda se può andare, purtroppo riesco a mettere il messaggio solo dopo il caricamento, meglio che niente.. Ma forse già Wordpress dovrebbe impedire il caricamento di tali file.

**Comment by astagi** [comment]
@Simsimus intanto ho rilasciato con il messaggio di warning dopo il caricamento, non è il massimo ma dobbiamo capire perchè succede questo. Per ora teniamo questo fix. Grazie!

**Comment by Simsimus** [comment]
Ciao @astagi, per il momento meglio che gli operatori vengano avvisati, così hanno modo di correggere. Infatti se su WP viene installato un WAF e al click dovesse essere segnalato un blocco che impedisce l'apertura di file con caratteri speciali, capirebbero come agire grazie al warning che hai implementato. Chi invece non installa WAF nemmeno se ne accorgerà. Grazie e buon lavoro
