### ISSUE TITLE
Impossibile scaricare i file usando il browser Chrome

### ISSUE THREAD

**Issue by CampusDaVinci** [italia/design-scuole-wordpress-theme#267]
Se si provano a scaricare i file dalla sezione documenti del sito es:
https://campusdavinci.edu.it/documento/download/
utilizzando il browser Chrome non succede nulla, mentre usando Edge, Firefox e Safari tutto funziona.
Questo accade sia se usa in un PC che in un device come smartphone o tablet

**Comment by boazaob** [comment]
nei link dei documenti da scaricare, sembra manchi http://

**Comment by CampusDaVinci** [comment]
Si, ma con tutti gli altri browser funziona.
Ma in questo caso, come si fa a far aggiungere https alla url ?
Non è che noi abbiamo fatto cose particolari, semplicemente caricato i documenti e resi disponibili

**Comment by boazaob** [comment]
Per caso, i documenti arrivano da una precedente versione del sito?

**Comment by CampusDaVinci** [comment]
No, nel sito c'è solo roba nuova inserita ad-hoc

**Comment by Jamielrey** [comment]
E' strano, controllando effettivamente i documenti sono inseriti senza protocollo ssl. anche l'immagine principale (PanoramicaFutureLab-scaled.jpg), è richiamata tramite http e non https. Mentre invece altre immagini sono richiamate tramite https. 
Controllando sul mio sito i file, e le immagini, sono tutte caricate in https.
Se i file li hai caricati dopo aver installato il protocollo https dovrebbero andate direttamente in https, in caso contrario il problema potrebbe stare lì: devi modificare il percorso in https. 
Però mi sembra di capire che tutto è stato fatto dopo aver installato il certificato SSL, in questo caso:

1) Potrebbe essere necessario configurare il server per forzare l'HTTPS per tutte le richieste.

2) Il certificato SSL potrebbe essere scaduto o non essere configurato correttamente.

3) Potrebbe esserci un conflitto con un plugin che impedisce il caricamento dei file con HTTPS.

4) C'è altro che ignoro.

**Comment by CampusDaVinci** [comment]
Si, confermo che è stato caricato tutto dopo la configurazione del certificato che non è scaduto ed è forzato a HTTPS.
Non ci sono plug-in "strani", anzi, non ci sono proprio :-)
Potrebbe essere un problema di permalink ?

**Comment by Jamielrey** [comment]
Possibile, basta fare un giro nelle impostazioni per controllare.

**Comment by astagi** [comment]
Non sembra un problema legato al tema, ho fatto un giro di prova su un'installazione staging e tutto sembra funzionare. Chiudo per il momento. Grazie!
