### ISSUE TITLE
Configurazione Home gestione banner

### ISSUE THREAD

**Issue by zompa-zampa** [italia/design-scuole-wordpress-theme#269]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-scuole-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-scuole-wordpress-theme/blob/main/CONTRIBUTING.md)

### Proposta

Proporrei una diversa gestione della sezione banner nella home. Attualmente se ho un banner nuovo lo devo creare nell'ultima posizione e per metterlo al primo posto dovrei slittare gli attuali di un posto. Sarebbe utile avere la stessa possibilità degli articoli in evidenza dove è possibile cambiare l'ordine di apparizione.

Altro cambiamento utile sarebbe quello di avere uno scorrimento dei contenuti della sezione (banner)
Grazie a chi presterà attenzione a queste problematiche.

![Schermata 2023-02-07 alle 16 05 49](https://user-images.githubusercontent.com/122695005/217284072-df9bcdc9-f35b-4255-aeb0-cbd93c3447ff.png)

### Motivazione e contesto

la prima questione sarebbe utile per una gestione più veloce e semplice dei banner. La seconda diventa fondamentale se si hanno molti banner... gli ultimi rimarrebbero nascosti...

**Comment by Simsimus** [comment]
Trovo utile questa proposta (soprattutto per la prima questione) e mi associo alla richiesta.

**Comment by zetareticoli** [comment]
Ciao, la sezione Banner non deve essere intesa come una grande scatola dove poter inserire qualunque cosa (vedo addirittura 13 banner nello screen postato).

La richiesta quindi non sarà presa in gestione nei prossimi rilasci.
