### ISSUE TITLE
Visualizzazione Logo PON

### ISSUE THREAD

**Issue by anitamaccio** [italia/design-scuole-wordpress-theme#27]
Salve, ci è arrivata una nota del MIUR stamattina che richiama gli obblighi di pubblicità del PON in generale e nei siti delle istituzioni scolastiche, nella quale "Si ricorda che la visualizzazione dei loghi, in termini di standard grafici, posizione e dimensione, deve rispettare le caratteristiche tecniche indicate dal Regolamento di esecuzione (UE) n. 821/2014"

"Regolamento di esecuzione (UE) n. 821/2014 della Commissione del 28 luglio 2014, Capo II, articoli 3-5 e Allegato II. In particolare, art. 4, paragrafo 3:
Quando l'emblema dell'Unione, il riferimento all'Unione e al Fondo pertinente sono pubblicati su un sito web: a) quando si accede al sito web, l'emblema dell'Unione e il riferimento all'Unione sono resi visibili all'interno dell'area di visualizzazione di un dispositivo digitale, **senza che l'utente debba scorrere la pagina verso il basso**; b) il riferimento al Fondo pertinente è reso visibile sul medesimo sito web."

Nel vostro modello, è possibile visualizzare il banner, ma rimane decisamente troppo basso perché sia visibile subito, né da mobile né da pc... è possibile spostarlo più in alto?

**Comment by webgrafia** [comment]
ciao @anitamaccio 
per quanto mi sembri surreale questo regolamento, che sembra scritto il secolo scorso e non cita i device da considerare, purtoppo hai ragione.

Abbiamo spostato la posizione banner sotto l'apertura
