### ISSUE TITLE
Nella Configurazione della Home ho inserito si su mostra eventi ma non appaiono

### ISSUE THREAD

**Issue by paolagan** [italia/design-scuole-wordpress-theme#270]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-scuole-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-scuole-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Durante la configurazione della Home su "Mostra gli eventi in Home" ho segnato si, ma nonostante io abbia creato un evento sul post type eventi non compare nella Homepage. C'è qualche altra impostazione da completare? 

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

2.1.8

**Comment by Simsimus** [comment]
Buongiorno,
hai verificato che la data dell'evento sia successiva alla data di pubblicazione?
Più precisamente, la data di inizio evento è una data futura o è già passata?

**Comment by paolagan** [comment]
Buongiorno, 
Sisi, la data è il 15 febbraio 2023 e la pubblicazione è l'8 febbraio 2023.

**Comment by paolagan** [comment]
Niente ho guardato meglio il codice e ho capito che dovevo togliere la selezione automatica e inserire i post type che desidero. Grazie comunque! Buona giornata.
