### ISSUE TITLE
App di valutazione: Raccomandazione progettuali schede informative del servizio

### ISSUE THREAD

**Issue by CampusDaVinci** [italia/design-scuole-wordpress-theme#274]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-scuole-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-scuole-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Ho effettuato l'analisi con l'app e mi viene rilevato un valore del 25% sulla parte di raccomandazioni progettuali di questo tipo
<html>
<body>
<summary style="box-sizing: border-box; cursor: pointer; display: block; border-bottom: 1px solid var(--report-border-color-secondary);"><div class="lh-audit__header lh-expandable-details__summary" style="box-sizing: border-box; display: flex; align-items: center; padding: var(--default-padding);"><span class="lh-audit__title-and-text" style="box-sizing: border-box; flex: 1 1 0%;"><span class="lh-audit__title" style="box-sizing: border-box;"><span style="box-sizing: border-box;"><br class="Apple-interchange-newline">R.SC.1.2 - SCHEDE INFORMATIVE DI SERVIZIO - Tutte le schede informative dei servizi devono mostrare le voci segnalate come obbligatorie all'interno dell'architettura dell'informazione, nell'ordine segnalato dal modello.</span></span><span class="lh-audit__display-text" style="box-sizing: border-box; margin: 0 var(--audit-margin-horizontal); color: var(--color-fail-secondary);"></span></span><div class="lh-chevron-container" style="box-sizing: border-box; margin-top: ; margin-right: 0px; margin-bottom: ; margin-left: ;"><svg class="lh-chevron" viewBox="0 0 100 100"><g class="lh-chevron__lines"><path class="lh-chevron__line lh-chevron__line-left" d="M10 50h40"></path><path class="lh-chevron__line lh-chevron__line-right" d="M90 50H50"></path></g></svg></div></div></summary><slot id="details-content" style="color: rgb(33, 33, 33); font-family: Roboto, Helvetica, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="lh-audit__description" style="box-sizing: border-box; --inner-audit-padding-right: var(--stackpack-padding-horizontal); padding-left: var(--audit-description-padding-left); padding-right: var(--inner-audit-padding-right); padding-top: 8px; padding-bottom: 8px; color: var(--report-text-color-secondary);"><span style="box-sizing: border-box;">CONDIZIONI DI SUCCESSO: nelle schede informative di servizio le voci indicate come obbligatorie sono presenti e sono nell'ordine corretto; MODALITÀ DI VERIFICA: viene verificato se le voci indicate come obbligatorie all'interno del documento di architettura dell'informazione sono presenti. Inoltre viene verificato se le voci obbligatorie presenti nell'indice della pagina sono nell'ordine corretto. La verifica viene effettuata su una scheda servizio casualmente selezionata, ricercando le voci indicate nella Documentazione delle App di valutazione tramite specifici attributi "data-element"; RIFERIMENTI TECNICI E NORMATIVI:<span> </span><a rel="noopener" target="_blank" href="https://docs.italia.it/italia/designers-italia/design-scuole-docs" style="box-sizing: border-box; color: var(--link-color);">Documentazione del Modello scuole</a>,<span> </span><a rel="noopener" target="_blank" href="https://docs.google.com/spreadsheets/d/1MoayTY05SE4ixtgBsfsdngdrFJf_Z2KNvDkMF3tKfc8/edit#gid=0" style="box-sizing: border-box; color: var(--link-color);">Content type: scheda servizio</a>,<span> </span><a rel="noopener" target="_blank" href="https://docs.italia.it/italia/designers-italia/app-valutazione-modelli-docs/" style="box-sizing: border-box; color: var(--link-color);">Documentazione delle App di valutazione</a>.</span></div><div class="lh-audit__stackpacks" style="box-sizing: border-box;"></div>

Risultato | Scheda di servizio ispezionata | Voci obbligatorie mancanti | Voci obbligatorie che non rispettano l'ordine corretto
-- | -- | -- | --
Più di 2 voci obbligatorie non sono presenti o più di 1 voce non è nell'ordine corretto. | https://campusdavinci.edu.it/servizio/segreteria-didattica-famiglie/ | Cosa serve, Tempi e scadenze, Contatti, Ulteriori informazioni, Tassonomie argomenti, A cosa serve

</slot>
</body>
</html>

Ma non riesco a capire dove vadano inserite queste voci che mancano.
Anche perché in altre schede di servizio simili questo errore non viene rilevato.
Cosa sto sbagliando ?

### Includi link o screenshot

https://campusdavinci.edu.it/servizio/segreteria-didattica-famiglie/

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Microsoft Edge

### Che versione del tema stai utilizzando?

2.1.9

**Comment by zetareticoli** [comment]
Ciao @CampusDaVinci , le domane relative all'app di valutazione puoi postarle sul [canale Slack dedicato](https://developersitalia.slack.com/archives/CQ7J0KANT), dove possono risponderti tutte le persone coinvolte sul progetto. 

Grazie
