### ISSUE TITLE
App di valutazione - Test aggiuntivi - Immagini senza alt

### ISSUE THREAD

**Issue by EasyTeamSrl** [italia/design-scuole-wordpress-theme#275]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-scuole-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-scuole-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

L'utilizzo della app di valutazione porta a una segnalazione nel blocco TEST AGGIUNTIVI. L'app segnala che alcuni elementi non hanno l'attributo alt.
Verificando l'errore, si vede che è legato all'immagine avatar del profilo utente:

div.card > div.card-comments-wrapper > div.card-avatar-img > img.lazyloaded
<img data-src="https://secure.gravatar.com/avatar/83db90a7bce29a20b7fe33df52f83813?s=250&amp;…" class=" lazyloaded" src="https://secure.gravatar.com/avatar/83db90a7bce29a20b7fe33df52f83813?

### Includi link o screenshot

<img width="934" alt="Schermata 2023-02-16 alle 17 36 02" src="https://user-images.githubusercontent.com/20112395/219429512-bda3bb3c-b993-4d17-9ee6-4220e0aff6b4.png">

### Su quale sisitema operativo stai riscontrando il problema?

Windows, macOS, Android, iOS, Linux

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

2.1.9

**Comment by astagi** [comment]
Grazie della segnalazione @EasyTeamSrl . Vedo si tratta degli avatar degli utenti, se non mi sbaglio mi puoi dire in quali pagine riscontri il problema?

**Comment by EasyTeamSrl** [comment]
Buongiorno Andrea,

non sono riuscito a risalire al pezzo di template in cui viene definito l’avatar dell’utente, altrimenti avrei provato a suggerire un fix.

Ho guardato nei vari template-parts ma non ho trovato il punto

 
Da: Andrea Stagi ***@***.***>
Risposta: italia/design-scuole-wordpress-theme ***@***.***>
Data: martedì 21 febbraio 2023, 16:08
A: italia/design-scuole-wordpress-theme ***@***.***>
Cc: "Info Easyteam.org SRL" ***@***.***>, Mention ***@***.***>
Oggetto: Re: [italia/design-scuole-wordpress-theme] App di valutazione - Test aggiuntivi - Immagini senza alt (Issue #275)

 
Grazie della segnalazione @EasyTeamSrl <https://github.com/EasyTeamSrl> . Vedo si tratta degli avatar degli utenti, se non mi sbaglio mi puoi dire in quali pagine riscontri il problema?

**Comment by astagi** [comment]
@EasyTeamSrl ho aperto una PR che potrebbe risolvere il vostro problema https://github.com/italia/design-scuole-wordpress-theme/pull/282

riuscite a testarla?

**Comment by EasyTeamSrl** [comment]
Confermo che il fix risolve il problema

**Comment by astagi** [comment]
Grazie @EasyTeamSrl
