### ISSUE TITLE
Rilevazione errori

### ISSUE THREAD

**Issue by AndrewBitGit** [italia/design-scuole-wordpress-theme#28]
Buonasera, utilizzando il template ho rilevato i seguenti problemi:
1) Non ho la possibilità di modificare i ruoli, presumibilmente per problemi legati all'installazione del plugin members:
Fatal error: Cannot redeclare members_can_user_view_post() 
(previously declared in C:\Apache24\htdocs\wordpress\wp-content\themes\design-scuole-wordpress-theme\inc\utils.php:38) in C:\Apache24\htdocs\wordpress\wp-content\plugins\members\inc\template.php on line 29
2) Errore dentro Scuola -> Panoramica mi segnala questo errore nella parte per le strutture:

Warning: Invalid argument supplied for foreach() in
C:\Apache24\htdocs\wordpress\wp-content\themes\design-scuole-wordpress-theme\template-parts\home\strutture.php on line 47
L'errore permane anche avendo inserito sia luoghi, sia strutture.
3) Manca l'export della configurazione
4) Quando effettuo l'import ho rilevato errori nel ripristino di foto
5) Doppi menù dopo l'import da file del database 
6) Nel momento in cui si prova ad accedere (dopo il logout) dà un errore: access-modal.php line 23, invalid argument supplied for foreach()
7) Dentro ad home se abilito il calendario non lo mostra
Grazie in anticipo, buona serata

**Comment by webgrafia** [comment]
ciao Andrea, 
hai una url da mandarmi nella quale posso vedere il problema del calendario?

**Comment by AndrewBitGit** [comment]
buonasera,
no non ho una url da fornirti, lo sto sviluppando su una macchina virtuale
per poi caricarlo appena ha un minimo di contenuti da renderlo verosimile.
Comunque il problema è solo nella Home, nella configurazione ha tre
opzioni, se notificare il prossimo evento, e li non ci sono problemi,
oppure mostrare il calendario, e non lo vedo. Il calendario è regolarmente
presente nella sezione Novità/Eventi/Calendario
Grazie per il supporto e buona serata.

**Comment by webgrafia** [comment]
il punto 1, 2 e 6 dovrebbero essere stati risolti nell'ultima versione appena rilasciata.
Per il calendario non riesco a riprodurre il problema:
https://demoscuola.cloud/

verifica se hai ginger attivo, in caso spegnilo, e se era quello verifica di avere l'ultima versione del plugin ginger installata

Per la duplicazione dei menu in fase di import, è perchè hai importato tutto, menu compresi, quindi ti ha aggiunto le voci a quelle esistenti create all'attivazione del tema. Probabilmente ti ha anche duplicato le tassonomie (argomenti e altri)

l'export della configurazione è una funzionalità che aggiungeremo appena possibile
grazie dei feedback

**Comment by AndrewBitGit** [comment]
Buongiorno,
grazie per il supporto, i problemi 1,2,6 sono stati risolti, però ho anche
altro da riportare:

1) Manca nella lista dei menù principali, la sezione scuola (deve essere
qualcosa che avete introdotto ieri pomeriggio, visto che prima funzionava)
2) Doppi link in fondo alla pagina per scuola
3) Per quanto riguarda il calendario, funziona perfettamente nella sezione
Novità/Calendario Eventi, però è nella Home Page che non appare, ed ora li
non appare neanche il prossimo evento.
Parlo comunque dell'opzione configurabile dentro Configurazione/Home/Mostra
gli Eventi in Home, qualunque cosa metto in home non ho risultati
4) Ora ho di nuovo a disposizione i ruoli, però devo segnalare errori in
fase di installazione dei plugin, vorrei sapere se posso ignorarli oppure
no:

An error occurred while installing ANAC XML Bandi di Gara: Il pacchetto non
può essere installato.
PCLZIP_ERR_BAD_FORMAT (-10) : Invalid archive structure.

Nell'istallazione di questi altri:
Installing Plugin ANAC XML Viewer (2/8),
Installing Plugin Amministrazione Aperta (3/8),
Installing Plugin Contact Form 7 (4/8),
Installing Plugin Contact Form 7 Database Addon – CFDB7 (5/8),
Installing Plugin Disable Gutenberg (6/8),
Installing Plugin Members (8/8)
Invece mi segnala:
Warning: sprintf(): Too few arguments in
C:\Apache24\htdocs\wordpress\wp-admin\includes\class-bulk-upgrader-skin.php
on line 152

Per quanto riguarda invece il Plugin Ginger:
Installing Plugin Ginger - EU Cookie Law (7/8)
An error occurred while installing Ginger - EU Cookie Law: Il pacchetto non
può essere installato.
PCLZIP_ERR_BAD_FORMAT (-10) : Invalid archive structure.

Non mi dà Ginger come pacchetto installato, quindi non dovrebbe essere lui
il responsabile della sparizione del calendario.
Grazie del supporto, buona giornata.

**Comment by AndrewBitGit** [comment]
Buongiorno,
ho risolto il problema dei menù ripetuti, era colpa mia: non utilizzavo
wordpress da anni, ed avevo copiato il tema clonato da git nella directory
dei temi di wordpress, che me lo faceva attivare direttamente senza
segnalarmi alcun errore.
Mi sono documentato meglio ed ho visto che dovevo prima crearne uno zip, e
poi caricare tale zip da wordpress per poi attivarlo. Ora ogni menù è al
suo posto, mi rimane da chiedervi: è giusta la procedura di installazione o
devo fare anche altro?
Grazie per la disponibilità e buona giornata.
