### ISSUE TITLE
L'immagine non appare sulla home page al caricamento di un evento

### ISSUE THREAD

**Issue by scal1974** [italia/design-scuole-wordpress-theme#285]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-scuole-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-scuole-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Buongiorno, quando carico un evento, l'immagine non appare sulla home page. 
![screenshot-www iisolivetipanettalocri edu it-2023 02 23-13_32_18](https://user-images.githubusercontent.com/114990331/220906763-2b89215d-87e5-413f-8b58-85e11b9f2621.png)

### Includi link o screenshot

![screenshot-www iisolivetipanettalocri edu it-2023 02 23-13_32_18](https://user-images.githubusercontent.com/114990331/220907357-4e6d6364-36a8-4536-bafb-6761f515cc7d.png)

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Chrome

### Che versione del tema stai utilizzando?

Versione: 2.1.8

**Comment by astagi** [comment]
@scal1974 l'immagine che si inserisce all'interno dell'evento non viene visualizzata in homepage, non è previsto dal tema
