### ISSUE TITLE
Mappa non funzionante nel post type luoghi"

### ISSUE THREAD

**Issue by paolagan** [italia/design-scuole-wordpress-theme#286]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-scuole-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-scuole-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Salve a tutti, 
Ho un problema con le mappe, in questo momento nei post type "luoghi".
Non si vede la mappa e mi segnala dei problemi con jQuery

### Includi link o screenshot

![image](https://user-images.githubusercontent.com/122269056/220942705-c944fedd-3acb-4c5c-a8bf-9c45863c9925.png)

![image](https://user-images.githubusercontent.com/122269056/220943432-9ae6252c-1eb0-4dd4-a02e-b6ec97f7368b.png)

![image](https://user-images.githubusercontent.com/122269056/220943588-63d1c00b-942f-4554-ac1c-ca2e27c35a04.png)

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Chrome

### Che versione del tema stai utilizzando?

2.1.9

**Comment by astagi** [comment]
Grazie @paolagan , lo stesso problema è anche nell'ultima versione 2.2.1?

**Comment by astagi** [comment]
Grazie @paolagan , segnalo il problema di `idindirizzo` e chiudo qua.
