### ISSUE TITLE
Anno scolastico scheda progetti 

### ISSUE THREAD

**Issue by Cate55** [italia/design-scuole-wordpress-theme#287]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-scuole-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-scuole-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Mi permetto di aprire una issue di segnalazione perchè non so se il mio intervento sia corretto.
Nella Scheda Progetti non viene stampato l'anno scolastico sotto il title, ho inserito nel file single-schede_progetto.php alla riga 51 questa correzione
`<i><?php _e("Anno scolastico", "design_scuole_italia"); ?> <?php echo dsi_convert_anno_scuola(intval($anno_scolastico)) ?></i>`
come riportato nel file "article-scheda_progetto.php (template-parts/list/article-scheda_progetto.php)"
anzichè 
`<i><?php _e("Anno scolastico", "design_scuole_italia"); ?> <?php echo dsi_convert_anno_scuola($anno_scolastico) ?></i>`

Adesso è visibile anche l'anno scolastico. 

Ringrazio per l'attenzione e resto in attesa di un vostro prezioso riscontro.

### Includi link o screenshot

![a s non-stampato](https://user-images.githubusercontent.com/9642253/221339571-62130be8-033d-498b-9cd4-c81cbed6254f.png)
![correzione-single-scheda-prog](https://user-images.githubusercontent.com/9642253/221339573-dfab1562-5d19-47f9-9272-a3b8fa4e3500.png)
![a s visibile](https://user-images.githubusercontent.com/9642253/221339931-027d9a33-4cc3-452b-81e6-72b51fc69677.png)

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Chrome, Firefox, Microsoft Edge

### Che versione del tema stai utilizzando?

2.2.0

**Comment by astagi** [comment]
Grazie @Cate55 fixato qua https://github.com/italia/design-scuole-wordpress-theme/commit/132d6ea76429b0ea717cab2df782387a4214138e rilasceremo in giornata la release 2.2.1

**Comment by astagi** [comment]
Grazie a te @Cate55 rilasciata la nuova versione!
