### ISSUE TITLE
Assicurati che il testo rimanga visibile durante il caricamento dei caratteri web

### ISSUE THREAD

**Issue by GiancarloMancini** [italia/design-scuole-wordpress-theme#289]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-scuole-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-scuole-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

DIAGNOSTICA app valutazione scuole

### Includi link o screenshot

![Cattura](https://user-images.githubusercontent.com/55079732/221432377-fc891031-8131-4ea8-bfcf-7b9c3359a3ac.PNG)

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

2.1.9

**Comment by GiancarloMancini** [comment]
Non sono pratico di github... Comunque nel file assets/css/fonts.css ho aggiunto l'istruzione `font-display:swap;` e l'app di diagnostica non ha più segnalato il problema

**Comment by astagi** [comment]
Grazie @GiancarloMancini ho appena aggiunto il tuo fix qua https://github.com/italia/design-scuole-wordpress-theme/commit/af41e37e713fcee2f5b3f5d413d069f6863344c1
