### ISSUE TITLE
App di valutazione dell’adesione al modello scuole: aumentare percentuale conformità

### ISSUE THREAD

**Issue by romimmo79** [italia/design-scuole-wordpress-theme#290]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-scuole-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-scuole-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Salve a tutti, sto cercando di aumentare la percentuale di conformità del sito web della mia scuola "https://www.icstrebaseleghe.edu.it/". Mi date qualche suggerimento sulle modifiche da apportare?
Grazie mille in anticipo

C.SC.1.1 - COERENZA DELL'UTILIZZO DEI FONT (librerie di caratteri) - Il sito della scuola deve utilizzare i font indicati dalla documentazione del modello di sito della scuola.
CONDIZIONI DI SUCCESSO: tutti i titoli (heading) e tutti i paragrafi delle pagine del sito in lingua italiana devono usare esclusivamente i font Titillium Web, Lora e Roboto Mono; MODALITÀ DI VERIFICA: ricercando uno specifico attributo “data-element” come spiegato nella Documentazione delle App di valutazione, viene verificato che i font richiesti abbiano la precedenza tra i font a disposizione all’interno di tutti gli <h> e <p> in una scheda servizio casualmente selezionata; RIFERIMENTI TECNICI E NORMATIVI: [Documentazione del Modello scuole](https://docs.italia.it/italia/designers-italia/design-scuole-docs), [Documentazione delle App di valutazione](https://docs.italia.it/italia/designers-italia/app-valutazione-modelli-docs)

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Chrome

### Che versione del tema stai utilizzando?

2.0

**Comment by Simsimus** [comment]
Buongiorno, 
il sito da te indicato non utilizza il tema ministeriale Designers Italia, ma è stato sviluppato da azienda privata, pertanto dovrai rivolgerti a loro per l'ottimizzazione della conformità.
Saluti

**Comment by astagi** [comment]
Buongiorno, concordo con @Simsimus .
