### ISSUE TITLE
Menù in posizione "... a piè di pagina" perde le impostazioni di "Apri il link in una nuova scheda" e "Classi CSS (opzionale)"

### ISSUE THREAD

**Issue by vittorio-alfieri** [italia/design-scuole-wordpress-theme#291]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-scuole-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-scuole-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Settando le opzioni "Apri il link in una nuova scheda" e "Classi CSS (opzionale)" del menu posto in posizione "... a piè di pagina (menu-footer)" queste vengono ignorate.

Prove effettuate:
Invertendo di posizione i due menu "top" e "footer" noto che in posizione "Menu secondario (menu-top)" Top il CSS e l'apertura su nuova scheda funzionano, mentre un qualsiasi menu messo in posizione "... a piè di pagina (menu-footer)" ignora tali impostazioni.
Credo che quindi sia un problema di posizione.
Inoltre ispezionando il codice html ho notato che gli elementi in posizione "menu-footer" non hanno il parametro "target" nel tag <a> e il parametro "class" nel tag <li> delle varie voci di menu.

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

2.2.1

**Comment by domenicomadeo** [comment]
idem nell'ultima versione ad oggi 2.3.2
