### ISSUE TITLE
data-element="legal-notes"

### ISSUE THREAD

**Issue by ricboc** [italia/design-scuole-wordpress-theme#293]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-scuole-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-scuole-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Per poter superare il test sulla "Raccomandazione R.SC. 2.2 - LICENZA E ATTRIBUZIONE" per quanto riguarda le note legali, come indicato nei [6. Requisiti tecnici e modalità di verifica per il modello scuole](https://docs.italia.it/italia/designers-italia/app-valutazione-modelli-docs/it/versione-attuale/requisiti-e-modalita-verifica-scuole.html#raccomandazione-r-sc-2-2-licenza-e-attribuzione), alla voce **Requisiti tecnici** viene specificato: All’interno del footer della pagina (tag `<footer>`) deve esserci un tag `<a>` che contiene l’href alla pagina delle note legali. Il tag <a> deve avere l’attributo data-element="legal-notes". L’`<a>` può essere contenuto in altri tag, esempio `<li>`. 

Mi sono allora posto il problema di come aggiungere questo data-element nel footer.
A tal proposito, suggerisco  nelle prossime relase del tema, di aggiungere  l'attributo data-element="legal-notes" dopo la riga 26 nel file walkers/footer-walker.php, inserendo il seguente codice:

} else if ( $item->post_name == 'note-legali' || stripos( $item->title, 'note' ) !== false ) { 
$custom_data = 'data-element="legal-notes"';

Ovviamente va anche creata la pagina "Note legali" con all'interno una sezione intitolata «**Licenza dei contenuti**» riportante la seguente dicitura:
_“In applicazione del principio open by default ai sensi dell’articolo 52 del decreto legislativo 7 marzo 2005, n. 82 (CAD) e salvo dove diversamente specificato (compresi i contenuti incorporati di terzi), i dati, i documenti e le informazioni pubblicati sul sito sono rilasciati con [licenza CC-BY 4.0](https://creativecommons.org/licenses/by/4.0/legalcode.it). Gli utenti sono quindi liberi di condividere (riprodurre, distribuire, comunicare al pubblico, esporre in pubblico), rappresentare, eseguire e recitare questo materiale con qualsiasi mezzo e formato e modificare (trasformare il materiale e utilizzarlo per opere derivate) per qualsiasi fine, anche commerciale con il solo onere di attribuzione, senza apporre restrizioni aggiuntive.”_

Inoltre all’interno della pagina "Note legali" individuata da questo link dovrà essere presente un tag HTML con l’attributo data–element=”legal-notes-section” da inserire nel `<h>` contenente il titolo della sezione da analizzare e uno o più tag `<p>` con attributo data-element=”legal-notes-body” inseriti in ogni `<p>` contenente il testo della sezione da analizzare.

### Includi link o screenshot

![image](https://user-images.githubusercontent.com/9788724/222829303-1cc8a856-3cd8-4fd6-b92f-7b79bbd9ca0f.png)

### Su quale sisitema operativo stai riscontrando il problema?

macOS

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

2.3.0

**Comment by astagi** [comment]
@ricboc grazie, secondo me questo più che un bug credo sia un enhancement.

Ne discuto con il team per la prossima fornitura.

**Comment by Simsimus** [comment]
Confermo che applicando la modifica di @ricboc, il test "Raccomandazione R.SC. 2.2" viene superato.

**Comment by CampusDaVinci** [comment]
Anche io ho questo problema.
Verrà rilasciata una nuova versione con il workaround ?

**Comment by zetareticoli** [comment]
@ricboc puoi aprire una PR con la modifica da te effettuata così la mettiamo nella prossima release?

**Comment by vitolamacchia** [comment]
Con validator 2.2.0 va in ko

**Comment by vitolamacchia** [comment]
Risolto

**Comment by Simsimus** [comment]
Ciao @vitolamacchia posso chiederti come hai risolto? Perchè se controllo con l'app 2.1.1 è tutto ok, invece con la 2.2.0 esce questo errore:
![note legali](https://user-images.githubusercontent.com/108821309/230054666-b578e058-caeb-4516-8148-d72e94546d69.jpg)

**Comment by vitolamacchia** [comment]
Semplicemente con la pagina creata per le note legali: (fai attenzione alle sezioni)
&nbsp;
<h3 class="wp-block-heading"><strong>Premessa</strong></h3>
L'Istituzione scolastica ha realizzato il Sito con l’obiettivo di pubblicare e rendere accessibili a Pubbliche Amministrazioni, imprese e cittadini dati e documenti relativi a struttura organizzativa, attività e provvedimenti.

Nella presente pagina sono riportate le note legali relative all’utilizzo del Sito.

Il presente documento potrà essere modificato in qualsiasi momento e senza preavviso; l’utente è pertanto invitato a prendere regolarmente visione dell’ultima versione aggiornata delle stesse, disponibile e permanentemente accessibile da qualunque pagina del sito, cliccando sul collegamento “Note Legali”.
<div>
<h3 data-element="legal-notes-section">Licenza dei contenuti</h3>
<p data-element="legal-notes-body">In applicazione del principio open by default ai sensi dell’articolo 52 del decreto legislativo 7 marzo 2005, n. 82 (CAD) e salvo dove diversamente specificato (compresi i contenuti incorporati di terzi), i dati, i documenti e le informazioni pubblicati sul sito sono rilasciati con l<a href="https://creativecommons.org/licenses/by/4.0/legalcode.it">icenza CC-BY 4.0</a>. Gli utenti sono quindi liberi di condividere (riprodurre, distribuire, comunicare al pubblico, esporre in pubblico), rappresentare, eseguire e recitare questo materiale con qualsiasi mezzo e formato e modificare (trasformare il materiale e utilizzarlo per opere derivate) per qualsiasi fine, anche commerciale con il solo onere di attribuzione, senza apporre restrizioni aggiuntive.</p>

</div>
&nbsp;
<h3 class="wp-block-heading"><strong>Copyright</strong></h3>
La visualizzazione, il download e qualunque utilizzo dei dati pubblicati sul Sito comporta l’accettazione delle presenti note legali e delle condizioni della licenza con cui sono pubblicati.

In applicazione del principio open by default ai sensi dell’articolo 52 del decreto legislativo 7 marzo 2005, n. 82 (CAD) e salvo dove diversamente specificato (compresi i contenuti incorporati di terzi), i dati, i documenti e le informazioni pubblicati sul sito sono rilasciati con licenza CC-BY 4.0. Gli utenti sono quindi liberi di condividere (riprodurre, distribuire, comunicare al pubblico, esporre in pubblico), rappresentare, eseguire e recitare questo materiale con qualsiasi mezzo e formato e modificare (trasformare il materiale e utilizzarlo per opere derivate) per qualsiasi fine, anche commerciale con il solo onere di attribuzione, senza apporre restrizioni aggiuntive.

Salvo ove diversamente indicato, i dati pubblicati sul Sito sono messi a disposizione con licenza CC-BY 4.0, il cui testo integrale è disponibile al seguente indirizzo: <a href="http://creativecommons.org/licenses/by/4.0/it/legalcode" target="_blank" rel="noreferrer noopener">http://creativecommons.org/licenses/by/4.0/it/legalcode</a> Questo significa che, ove non diversamente specificato, i contenuti del Sito sono liberamente distribuibili e riutilizzabili, a patto che sia sempre citata la fonte e, ove possibile, riportato l’indirizzo web della pagina originale.

&nbsp;
<h3 class="wp-block-heading"><strong>Utilizzo del sito e download</strong></h3>
L'Istituzione scolastica si impegna costantemente per assicurare la qualita delle informazioni pubblicate sul Sito, nonché la loro integrità, aggiornamento, completezza, tempestività, semplicità di consultazione e accessibilità.

Per qualunque segnalazione o suggerimento è possibile scrivere all’indirizzo mail dell'Istituzione scolastica.

In nessun caso l'Istituzione scolastica può essere ritenuta responsabile dei danni di qualsiasi natura causati direttamente o indirettamente dall’accesso al Sito, dall’incapacità o impossibilità di accedervi.

L'Istituzione scolastica non assume alcuna responsabilità per eventuali errori od omissioni di qualsiasi tipo e per qualunque tipo di danno diretto, indiretto o accidentale derivante dalla lettura o dall’impiego delle informazioni pubblicate, o di qualsiasi forma di contenuto presente nel Sito. La presente clausola di esclusione di responsabilità non ha lo scopo di eludere il rispetto di requisiti prescritti dalla legislazione nazionale vigente, né di escludere la responsabilità nei casi per i quali essa sussiste ai sensi della stessa legislazione.

I documenti presenti sul Sito per lo scaricamento (download), quali ad esempio documentazione tecnica e documentazione normativa, salvo diversa indicazione, sono liberamente e gratuitamente disponibili, in caso contrario viene prodotto un avviso come premessa nell’uso degli stessi.
<h3 class="wp-block-heading"><strong>Accesso a siti esterni collegati</strong></h3>
I collegamenti a siti esterni indicati nel Sito sono forniti come semplice servizio agli utenti, con esclusione di ogni responsabilità sulla correttezza e sulla completezza dell’insieme dei collegamenti indicati.

L’indicazione dei collegamenti non implica da parte del MiC alcun tipo di approvazione o condivisione di responsabilità in relazione alla legittimità, alla completezza e alla correttezza delle informazioni contenute nei siti indicati.
<h3 class="wp-block-heading"><strong>Privacy</strong></h3>
La privacy degli utenti è molto importante. Per questo motivo è stata predisposta un’apposita Informativa Privacy che l’utente, utilizzando il Sito, accetta.

**Comment by Simsimus** [comment]
Grazie @vitolamacchia , problema risolto ;)
Avevo già creato una pagina "Note legali" con i data-element previsti dalle linee guida, infatti con l'app 2.1.1 l'esito del controllo è positivo, ma la mia pagina aveva meno contenuto del tuo. Ora che ho applicato il tuo testo il check risulta positivo anche con l'app 2.2.0.
Grazie

**Comment by AlessioPellegrini** [comment]
Salve a tutti, io ho la versione 2.7.0 del tema, nel file  walkers/footer-walker.php è presente il codice delle note legali ( nel mio caso alla riga 31 ) ma nel footer il link alle note legali non appare.  Sapete se devo fare altro per far apparire il link?

**Comment by rosario-pellecchia** [comment]
a me invece sto provando e riprovando non i convalida la pagina di note legali:
https://www.itimedi.edu.it/note-legali/
il validatore è l'ultima versione al 22 giugno 2024
