### ISSUE TITLE
Miglioramento home

### ISSUE THREAD

**Issue by Simsimus** [italia/design-scuole-wordpress-theme#294]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-scuole-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-scuole-wordpress-theme/blob/main/CONTRIBUTING.md)

### Proposta

Sarebbe possibile gestire le notizie/circolari nella seguente forma grafica?
![notizie](https://user-images.githubusercontent.com/108821309/223109320-c70ab214-9c6a-4299-9c27-e2c76e299d0d.jpg)

In pratica nella configurazione si potrebbe lasciare tutto com'è attualmente, con la differenza che invece di mostrare 3 colonne con un solo articolo/circolare, verrebbero mostrate 3 righe ciascuna con gli ultimi 3 articoli/circolari.

In alternativa, solo se più facile tecnicamente, lasciare le tre colonne come sono ora,  ma aggiungere la possibilità di scegliere il numero automatico di articoli/circolari da mostrare in verticale per ogni area/colonna (anche se credo che graficamente sarebbe preferibile la prima ipotesi).

Grazie

### Motivazione e contesto

Ottimizzare la visualizzazione delle notizie presenti sulla home per avere un numero di informazioni maggiori sulle ultime pubblicazioni effettuate dalla scuola.

**Comment by zetareticoli** [comment]
Ciao @Simsimus , terremo in considerazione questa richiesta per i prossimi aggiornamenti. Ti aggiorniamo nel caso in cui sarà inserita nella roadmap. Grazie

**Comment by zetareticoli** [comment]
In ogni caso, la configurazione della home può essere autonomamente presa in carico

**Comment by alessiofilippi** [comment]
Grazie,  ma è complicato? Bisogna modificare un file in particolare? Ho buone conoscenze php MySQL,  ma ho lavorato poco con i template di wordpress...

Inviato da Outlook per Android<https://aka.ms/AAb9ysg>

________________________________
Da: Francesco Improta ***@***.***>
Inviato: Lunedì, Agosto 21, 2023 10:55:43 AM
A: italia/design-scuole-wordpress-theme ***@***.***>
Cc: alessiofilippi ***@***.***>; Comment ***@***.***>
Oggetto: Re: [italia/design-scuole-wordpress-theme] Miglioramento home (Issue #294)


In ogni caso, la configurazione della home può essere presa in carico autonomamente

**Comment by IsabellaTarini** [comment]
Mi unisco alla richiesta di miglioramento della home. Grazie

**Comment by sviluppoRobyone** [comment]
In una PR abbiamo apportato dei miglioramenti che dovrebbero riuscire a risolvere la vostra esigenza.
Se volete provarlo e darci anche un vostro riscontro... grazie!

**Comment by Simsimus** [comment]
Innanzitutto grazie per il supporto che offrite alla comunità con soluzioni puntuali e risolutive.
Nel caso specifico il risultato ottenuto va già bene, ma se fosse possibile, avanzerei due suggerimenti:
1) la visualizzazione degli articoli meglio in orizzontale (con scorrimento se superiore a 3...tipo la pagina Panoramica);
2) se si chiede la visualizzazione delle circolari sulla home, allora, per una questione grafica, il numero delle circolari dovrebbe essere pari a quanto scelto per gli articoli.

Grazie per la vostra disponibilità

**Comment by sviluppoRobyone** [comment]
Attualmente non eravamo intervenuti sulla visualizzazione (verticale o orizzontale) poiché il page-template caricato è vertical-thumb, abbiamo solo corretto il margine per rendere gradevole la visualizzazione (in effetti si potrebbero aprire riflessioni su questo punto).

Abbiamo tenuto la stessa linea (cambiare il meno possibile, rimanendo in continuità con le scelte precedentemente fatte), anche per il numero di eventi e circolari che per ora rimane a 1. Se si valuta di rendere personalizzabile anche queste due parti, forse è il caso di prevedere due ulteriori opzioni?

**Comment by zetareticoli** [comment]
@sviluppoRobyone possiamo considerarlo risolto con #494 come da te segnalato?

**Comment by sviluppoRobyone** [comment]
La nostra PR va a risolvere il numero di articoli ma:
- non ha toccato il numero di eventi e circolari
- non ha toccato la visualizzazione degli articoli in caso di più tipologie di contenuto visualizzate, che attualmente risulta verticale
Rimane da capire se e come intervenire per i due punti lasciati scoperti

**Comment by corrado1975** [comment]
Ragazzi io ho risolto in verticale la questione del numero di avvisi e circolari è necessario però fare una modifica in un file php che si trova nella cartella del tema template-parts\home\articoli-eventi.php ed impostare il numero di articoli da visualizzare bisogna impostare per tutti i 'posts_per_page' che sarà ad 1 ad un numero a piacere 

![avvisi](https://github.com/italia/design-scuole-wordpress-theme/assets/140151788/b90bf738-e851-4e81-a985-949e1da8cfe0)

**Comment by sviluppoRobyone** [comment]
Nella nuova versione del tema 2.6.0 già è stato previsto per gli articoli, rimangono ancora i punti riportati nell'ultimo commento

**Comment by studioalexsa** [comment]
La versione 2.8.0 ha aggiunto la possibilità di scegliere la modalità di visualizzazione di notizie/avvisi in home come richiesto da Simsimus?

**Comment by zetareticoli** [comment]
@studioalexsa le novità introdotte dalla v2.8.0 sono nel [changelog](https://github.com/italia/design-scuole-wordpress-theme/releases/tag/v2.8.0)

**Comment by sviluppoRobyone** [comment]
La PR andrebbe risolvere pienamente la richiesta, chiediamo di testare il miglioramento e ricevere un riscontro
