### ISSUE TITLE
Pannello Configurazione inaccessibile

### ISSUE THREAD

**Issue by dg7dd** [italia/design-scuole-wordpress-theme#295]
Buongiorno. Non so se dipende dall'aggiornamento del tema appena eseguito (v2.3.0), ma non riesco ad entrare nel pannello di Configurazione del sito da backend WP (v6.1.1): permessi negati (v.screenshot). Tutto il resto del backend sembra invece non dare problemi.
Come risolvere? Grazie 

![image](https://user-images.githubusercontent.com/72756285/223414618-6bd6e76b-7900-4479-9fbc-5cf07d9f107b.jpeg)

**Comment by dg7dd** [comment]
Ho controllato. Su Members, il ruolo "Amministratore" ha tutti i permessi impostati su "Concedi" (non avevo apportato alcuna modifica).
Ho provato anche a svuotare e risvuotare cache ma senza successo. Ho provato anche con due account admin diversi, ma niente.
Fino alla v2.2.1 non avevo mai avuto questo problema...

**Comment by astagi** [comment]
Dubito dipenda dall'aggiornamento @dg7dd prova a fare un'installazione pulita del tema per contro prova.

**Comment by dg7dd** [comment]
Non ho ancora rifatto una installazione pulita (ho delle personalizzazioni, e non avendo tema child, quella sarà l'ultima soluzione).
Ho provato a disattivare tutti i plugin, ma il problema persiste.
Ho controllato nel database le stringhe relative a user e capabilities dell'utente in questione: tutto ok.
Ho aggiornato PHP a ultima versione (8.2).
Ho dunque provato ad attivare il debug e ricevo una serie di errori: allego qui i file di log (uno con i vari plugin attivati, l'altro con tutti i plugin disattivati).
PS. La cartella del tema ha il nome 2.0.1 ma la versione in uso è la 2.3.0 (questo perché, per gli aggiornamenti, gestisco gli stessi modificando i singoli file di volta in volta rilasciati, senza installare ogni volta da zero il nuovo tema aggiornato).
Spero possa essere utile a capirne qualcosa di più, anche nel caso in cui qualcun altro dovesse incontrare un problema simile.

**Comment by dg7dd** [comment]
Soluzioni?

**Comment by dg7dd** [comment]
Risolto con reinstallazione del tema.
