### ISSUE TITLE
H1 mancante per "Indirizzi di studio"

### ISSUE THREAD

**Issue by vcoopcsc** [italia/design-scuole-wordpress-theme#298]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-scuole-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-scuole-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Nelle pagine di dettaglio degli indirizzi di studio manca l'H1. Il titolo dell'indirizzo di studio, infatti, è H2

### Includi link o screenshot

<img width="652" alt="image" src="https://user-images.githubusercontent.com/92174841/224747152-1617bffa-843d-47a8-9fc0-f89803f9693e.png">

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

2.3.0

**Comment by astagi** [comment]
Sistemato qua https://github.com/italia/design-scuole-wordpress-theme/commit/7187bb1730c2e54af550de0e4e25fcb03747af7f

Grazie @vcoopcsc
