### ISSUE TITLE
Anno Scolastico in corso

### ISSUE THREAD

**Issue by NicolaTeodori** [italia/design-scuole-wordpress-theme#3]
Premetto che seguo con interesse l'evoluzione del tema ee non posso che fare i complimenti per il lavoro svolto fino ad ora.
Volevo condividere una considerazione che magari avete già fatto.
La struttura orgnaizzativa di una scuola, a parte le posizioni con contratto a tempo indeterminato, si rinnova di anno in anno.
Il lavoro di aggiornamento del sito scolastico è influenzato da questa periodicità.
In questo caso sia gli articoli che le pagine dovrebbero essere corredate dalla proprietà del valore del relativo anno scolastico. Questo al fine di permettere un'agevole gestione di quanto pubblicato e magari così gestire facilmente gli archivi degli a.s. precedenti.
Se può servire.

**Comment by webgrafia** [comment]
@NicolaTeodori grazie del feedback, abbiamo introdotto il concetto di anno scolastico nel tema come attributo dei post type che ne necessitano (al momento le classi e le schede progetto), e stiamo ragionando se estenderlo sugli altri post type. 
Saluti

**Comment by 33tino** [comment]
Complimenti per il lavoro.
Seguo con interesse, ma non ho capito come istallarlo con wordpress.
E' possibile avere il procedimento  per poterlo usare senza errori?
