### ISSUE TITLE
Ingrandimento loghi CIE e SPID 

### ISSUE THREAD

**Issue by vcoopcsc** [italia/design-scuole-wordpress-theme#300]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-scuole-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-scuole-wordpress-theme/blob/main/CONTRIBUTING.md)

### Proposta

I loghi CIE e SPID sono molto piccoli (quasi illeggibili). Suggerirei di ingrandirli almeno tanto quanto il logo STS in modo anche da rendere la pagina più coerente graficamente. 

### Motivazione e contesto

La pagina risulterebbe più leggibile e graficamente coerente.

**Comment by astagi** [comment]
@vcoopcsc non riesco a riprodurre il problema purtroppo.. sembra quasi un problema di cache oppure qualche regola css che modifica le dimensioni dei loghi. Quello che vedo io è questo

<img width="649" alt="image" src="https://user-images.githubusercontent.com/537363/225455737-919fbba5-f860-4146-a47a-bb1b4846b1c5.png">

**Comment by vcoopcsc** [comment]
Provo a verificare col tecnico e vi aggiorno.
