### ISSUE TITLE
Le card in Home hanno diverse altezze

### ISSUE THREAD

**Issue by v2beat** [italia/design-scuole-wordpress-theme#302]
E' possibile assegnare un'altezza fissa diciamo 310px alle .card in home per fare in modo di uniformarle?

Una volta modificato il css sarebbero cosi' visualizzate

![Opera Snapshot_2023-03-16](https://user-images.githubusercontent.com/84638945/225605980-f44d4b20-7e79-46f5-9373-c089cbaba1f4.png)

**Comment by astagi** [comment]
Grazie @v2beat fixato qua https://github.com/italia/design-scuole-wordpress-theme/commit/85154316e2bbf4fe54ea35178bf1f2a5dad3d443

A breve nuovo rilascio del tema
