### ISSUE TITLE
Inserimento immagini di loghi cliccabili e navigabili

### ISSUE THREAD

**Issue by CampusDaVinci** [italia/design-scuole-wordpress-theme#305]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-scuole-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-scuole-wordpress-theme/blob/main/CONTRIBUTING.md)

### Proposta

Dare la possibilità di inserire immagini che rappresentino dei loghi su cui effettuare l'operazione di click per aprire un collegamento.
I loghi potrebbero essere visualizzati sotto la barra di menu oppure a lato della pagina (rimanendo sempre in evidenza quando si scorre la stessa)

### Motivazione e contesto

Spesso il MIM chiede che vengano inseriti loghi (solitamente di forma rettangolare) di progetti come SCUOLA FUTURA, FUTURE LAB, PNSD e altri ancora all'interno del sito.

**Comment by Simsimus** [comment]
La sezione banner presente in Configurazione > Home già svolge quanto richiesto, a meno che tu non abbia esigenze particolari. Il limite di quella attuale, a mio avviso, è la rigidità delle posizioni. Sarebbe molto utile riuscire a scegliere la posizione dei vari banner e non accodare ogni nuovo banner per forza in ultima posizione, perchè nel tempo le esigenze potrebbero cambiare e allo stato attuale per mettere un banner, ad esempio, in seconda posizione bisognerebbe eliminare e ricaricare tutti i successivi.

**Comment by Simsimus** [comment]
Grazie per la dritta, mi era sfuggito il particolare. Concordo che la gestione dei banner non sia ottimale perchè bisogna lavorarli graficamente e farli tutti delle stesse dimensioni, altrimenti esteticamente saranno poco gradevoli. Una buona dimensione è 350 x 100 oppure 350 x 150, dipende da quanto alti si vogliono, ma per un fattore estetico, dopo aver scelto le misure, poi bisogna farli tutti uguali.
