### ISSUE TITLE
Le immagini in evidenza vengono tutte ridimensionate

### ISSUE THREAD

**Issue by ghost** [italia/design-scuole-wordpress-theme#307]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-scuole-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-scuole-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Quando si inserisce una immagine in evidenza in progetti, articoli e altro ancora, questa immagine viene ridimensionata e scalata avendo come effetto che si veda tutta sgranata, a prescindere se sia ad alta o bassa risoluzione.
Come si fa per evitarlo?
Qual 'è la risoluzione che devono avere questo tipo di immagini?

### Includi link o screenshot

Pagina che contiene l'immagine in evidenza
https://campusdavinci.edu.it/scheda-progetto/transizione-digitale/

Immagine utilizzata
https://campusdavinci.edu.it/wp-content/uploads/2023/03/PanoramicaFutureLabPiccola.png

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

2.3.0

**Comment by v2beat** [comment]
Se vedo bene l'immagine utilizzata piccola e' gia' sgranata di suo, prova a caricare un'immagine piu' definita e di dimensioni accettabili

**Comment by CampusDaVinci** [comment]
Ho provato a inserire immagini anche ad alta risoluzione, ma il problema è che viene "ingrandita" solo il centro dell'immagine per farlo stare nella dimensione a prescindere dalle dimensioni originali della stessa
Viene fatto un "ritaglio" e ingrandito fino a portarlo alla dimensione del box

**Comment by v2beat** [comment]
Ho teste' creato una pagina progetto e inserite l'immagine "featured" la quale inizialmente era 300 KB
1640 by 840 pixels, ridimensionata (giustamente) a 730x485, non mi pare sfocata

https://vivee.biz/edu_test/scheda-progetto/progettino-di-test/
