### ISSUE TITLE
I link "visualizza altro" nelle schede della pagina /luoghi non espandono il testo

### ISSUE THREAD

**Issue by v2beat** [italia/design-scuole-wordpress-theme#309]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-scuole-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-scuole-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

accedendo la pagina /luoghi/edificio-scolastico vi sono delle schede "elementi di interesse", dopo aver inserito testo sufficiente definendo il contenuto massimo nel campo "contenuto massimo" questo viene nascosto ma il link "visualizza altro" che dovrebbe aprire una nuova pagina oppure espandere il testo nascosto e' ancorato nella stessa pagina. Credo vi sia un problema di JS associato.
![salva](https://user-images.githubusercontent.com/84638945/228217574-59d4cb93-31ed-4d2c-934e-58d4af96ffc9.jpg)

rif pagina https://vivee.biz/edu_test/luogo/edificio-scolastico/

![image](https://user-images.githubusercontent.com/84638945/228217987-74150304-8666-4e82-9682-b640455c12fb.png)

Sono andato a sostituire il codice in DevTools con questo e vedo che funziona

![image](https://user-images.githubusercontent.com/84638945/228282613-a7b2cffd-992e-4ad3-98bd-c10ce311d4aa.png)

[screen-recorder-tue-mar-28-2023-16-53-56.webm](https://user-images.githubusercontent.com/84638945/228281516-45d5c8ad-73e5-410c-8ebe-1b8a824dcd29.webm)

### Includi link o screenshot

https://vivee.biz/edu_test/luogo/edificio-scolastico/

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

2.3.1

**Comment by sviluppoRobyone** [comment]
Ho cercato eventuali implementazioni JS senza trovarle, condivido la soluzione proposta e creo una pull request in merito

**Comment by v2beat** [comment]
Bene ottimo, grazie Robyone
