### ISSUE TITLE
Aggiornamento Wordpress dopo la  versione  5.0 si riscontrano problemi sia al widget e al footer

### ISSUE THREAD

**Issue by 33tino** [italia/design-scuole-wordpress-theme#31]
Tastando il template sino alla versione ultima di WP ho riscontrato vari problemi.
Forse si tratta solo nel mio caso.
La versione 5.3.3 e 5.4
Il template dava problemi con i widget e nel footer non visualizzava alcuni menu

**Comment by astagi** [comment]
I menù del footer risultano renderizzati. Provare la nuova versione rilasciata (2.0.0)
