### ISSUE TITLE
Pagina dei luoghi da mobile non è scorribile

### ISSUE THREAD

**Issue by danieledexter** [italia/design-scuole-wordpress-theme#310]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-scuole-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-scuole-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Salve,
ho notato che da mobile la pagina in Scuola >I Luoghi non è scorribile. 

Posso spostarmi solo se parto dal banner in alto, ma dalla lista no.
I link però sono cliccabili e funzionanti.

Credo ci sia qualcosa con la mappa che rimane attiva.

Potete verificare?

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Chrome

### Che versione del tema stai utilizzando?

2.3.2

**Comment by attiliopecora** [comment]
il problema si verifica quando è visualizzata la mappa dei luoghi.

**Comment by sviluppoRobyone** [comment]
Il problema riguarda la presenza della classe .ps-container e in particolare della proprietà css 

`   touch-action: none;`

Non avendo ancora compreso l'utilità della presenza di queste configurazioni, rimango anche io in attesa di riscontro

**Comment by astagi** [comment]
@SamuelManca ha risolto il problema, appena si aggiorna il css mergiamo e rilasciamo nuova versione.
