### ISSUE TITLE
Scelta multipla categorie/tipologie

### ISSUE THREAD

**Issue by vaniaweb** [italia/design-scuole-wordpress-theme#311]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-scuole-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-scuole-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Buonasera, ci sarebbe la possibilità di ripristinare la modalità predefinita di wordpress di salvare lo stesso articolo/documento in più categorie? Dalla scheda modifica non si può più fare, mentre si può ancora fare da "modifica rapida", ma in questo caso le categorie rimangono memorizzate solo se non si modifica nuovamente il documento dalla scheda completa di conseguenza ogni volta bisogna selezionare nuovamente da modifica rapida. Con tanti documenti sta diventando difficile da gestire, prima di iniziare a duplicare lo stesso articolo/documento vorrei capire se i button radio nella scheda completa sono voluti e nel caso per quale motivo. Grazie mille. Vania

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

2.3.2

**Comment by Simsimus** [comment]
Concordo con l'osservazione e mi associo.

**Comment by sviluppoRobyone** [comment]
In una issue successiva se ne è parlato...

#333
