### ISSUE TITLE
Dopo update a 2.3.2 i box della sezione notizie sovrappongono il testo all'autore del post

### ISSUE THREAD

**Issue by CampusDaVinci** [italia/design-scuole-wordpress-theme#316]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-scuole-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-scuole-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Dopo aver effettuato l'update dalla versione 2.3.0 alla 2.3.2 i box delle notizie in homepage mostra il testo sovrapposto all'autore del post.
Precedentemente i box erano di dimensione differente in base alla lunghezza del testo ma questo non appariva sovrapposto.
Ora sono tutti della stessa altezza, ma il testo appare sovrapposto, 

### Includi link o screenshot

https://campusdavinci.edu.it
<img width="914" alt="image" src="https://user-images.githubusercontent.com/115779224/229882457-aad5639d-22ca-478a-919e-8e6ac39cdb98.png">

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

2.3.2

**Comment by EasyTeamSrl** [comment]
Confermo.

**Comment by vcoopcsc** [comment]
Confermo. In homepage dovrebbe vedersi il titolo, l'eventuale abstract e l'autore. Ciò che accade è che si vede parte del testo dell'articolo al posto dell'abstract, che anche se viene valorizzato continua a non comparire in home.
Ho visionato il documento di architettura e tra l'altro l'abstract è un campo obbligatorio, cosa che adesso non è nel backend. 
Suggerisco di far comparire l'abstract al posto del testo dell'articolo in modo che assolva alla sua funzione.

**Comment by sviluppoRobyone** [comment]
Abbiamo proposto una soluzione in merito all'abstract... rimaniamo anche noi in attesa di riscontro

#342

**Comment by zetareticoli** [comment]
Resolved by #342
