### ISSUE TITLE
Verifica FONT in app di validazione riporta nomi errati

### ISSUE THREAD

**Issue by CampusDaVinci** [italia/design-scuole-wordpress-theme#319]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-scuole-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-scuole-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Utilizzando l'app di verifica dei font, viene segnalata una non conformità sull'uso degli stessi
Aprendo una issue su quel progetto, la risposta data è stata questa

"Nel criterio dei font la pagina viene segnalata perché il nome del font è in minuscolo, mentre il font stesso richiede delle maiuscole nella verifica. Consiglio di cambiare il nome del font"

### Includi link o screenshot

Commento alla issue aperta sull'app di validazione
https://github.com/italia/pa-website-validator/issues/239#issuecomment-1499290622
Sito su cui è stato effettuato il test
https://campusdavinci.edu.it/

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

2.3.2

**Comment by franzuin** [comment]
Ciao @CampusDaVinci hai risolto il problema. Io ce l'ho analogo.

**Comment by CampusDaVinci** [comment]
Eh no, non si può risolvefe se non cambiano i nomi dei font ...
