### ISSUE TITLE
Nella visualizzazione dei luoghi non riporta i Dati pubblici (Orario, mail, telefono)

### ISSUE THREAD

**Issue by IsabellaTarini** [italia/design-scuole-wordpress-theme#323]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-scuole-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-scuole-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Buongiorno,
stiamo usando Design Scuole Italia Versione: 2.0.3, in WordPress versione 6.2.
Abbiamo inserito un luogo (Biblioteca, facente parte di un luogo Scuola) e compilato i campi nella sezione "Dati pubblici", in particolare "Orari per il pubblico", "Riferimento mail" e "Riferimento telefonico", tuttavia la sezione "Dati pubblici" non compare nel front-end (non compare quindi nessuno dei dati inseriti).

Grazie

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Chrome

### Che versione del tema stai utilizzando?

2.0.3

**Comment by v2beat** [comment]
non riesci a visualizzare così? 
![image](https://user-images.githubusercontent.com/84638945/231233610-261b8673-3e7e-4215-af0e-8e12017972a2.png)

**Comment by IsabellaTarini** [comment]
Ops, sì, francamente non mi ero accorta che fossero riportati accanto alla mappa, mi aspettavo che avessero un visibilità maggiore. Grazie e scusate il falso allarme.

**Comment by v2beat** [comment]
Ninete, figurati, passavo di qui e ho visto il tuo messaggio
