### ISSUE TITLE
Modifica personalizzata banner

### ISSUE THREAD

**Issue by vitolamacchia** [italia/design-scuole-wordpress-theme#325]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-scuole-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-scuole-wordpress-theme/blob/main/CONTRIBUTING.md)

### Proposta

Sarebbe possibile programmare in Configurazione->Home la possibilità di gestire il numero di banner per pagina e la loro grandezza
Non è gradevole avere una grandezza standard e peggio un numero di soli 3 banner per pagina

### Motivazione e contesto

Permetterebbe una facile personalizzazione e accessibilità ai banner richiesti

**Comment by sdi-sw** [comment]
Si questa modifica sarebbe molto utile.

**Comment by sviluppoRobyone** [comment]
Con la PR andiamo ad agire sulla grandezza, non sul numero di banner (il Carousel di Bootstrap Italia che viene attualmente utilizzato per mostrare i banner, supporta solo 1 o 3 banner per pagina).
