### ISSUE TITLE
Come modificare i data-element?

### ISSUE THREAD

**Issue by paologd** [italia/design-scuole-wordpress-theme#327]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-scuole-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-scuole-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Dopo aver letto le linee guida e cercato nelle issue senza aver trovato argomenti in merito,
volevo chiedere alla community una mano su come bisogna gestire e/o modificare i data-element descritti nella guida.
Avendo eseguito ripetuti tentativi di controllo con esito negativo del test effettuato con l'app di valutazione e non trovando soluzioni, faccio appello alla vostra conoscenza.

Grazie in anticipo.

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

2.1.5

**Comment by Simsimus** [comment]
Buongiorno,
basta aggiornare il tema alla versione 2.3.2 e vi troverete i data-element inseriti correttamente.
Saluti

**Comment by paologd** [comment]
Ciao, rispondo a franzuin dicendo che avevo già inserito i data-element elencati nelle guide, all'interno del file header.php e in questo caso volevo avere appunto conferma e me l'hai data. C'è però il problema che non riesco a trovare il file che contiene le voci del menu di terzo livello (come classificato dalla guida dopo La scuola, servizi etc per intenderci), dove appunto indica di dover inserire il data-element=”custom-submenu” per le voci aggiuntive che di fatto sono appunto quelle di terzo livello.
Sapete come si chiamano quei files php? Grazie in anticipo.

Ad ogni modo se simsimus dice che con l'aggiornamento risolvo il problema ci provo, però ho dubbi sull'aggiornamento, non va a sminchiare nulla dei contenuti già inseriti? Non ho fatto nessun tipo di personalizzazione, quindi immagino che sia indolore spero. Chiaramente ho fatto backup sia di wp che di DB. Ho scaricato lo zip per aggiornare perchè forcarlo e fare git pull non sono super confidente.

Cosi spero si risolvano i warning segnalati dopo il test di valutazione.

Intanto grazie per le info ricevute e future.
Buona giornata.

**Comment by franzuin** [comment]
Se non hai personalizzazione particolari non ci sono problemi. 
Occhio ai menu perchè quelli si ripristinano alla versione iniziale, sempre che non sia stato risolto anche questo problema.

**Comment by Simsimus** [comment]
Per aggiornare il tema senza problemi, consigliando di fare prima una copia di sicurezza perchè la prudenza non è mai troppa, basta decomprimere il file zip e fare l'upload degli stessi attraverso FTP sovrascrivendo i file precedenti. In questo modo, a meno che non siano state fatte delle modifiche/personalizzazioni al tema, ci si troverà il tema originale aggiornato senza avere problemi neppure con i menù.

**Comment by paologd** [comment]
Infatti avendo fatto una copia di sicurezza ho potuto ripristinarla subito, perchè purtroppo il caricamento con lo zip ha causato la perdita di riferimento alle pagine. veniva caricata solo la home page ma le pagine non avevano più il puntamento.
Pensi che facendo come mi hai indicato questo problema non si abbia?

**Comment by Simsimus** [comment]
Facendo solo l'upload/sovrascrittura dei file il tema verrà aggiornato ed il database (quindi i menù) non sarà coinvolto. Visto che ormai hai una copia di sicurezza prova a fare quanto suggerito e dovrebbe andare tutto bene.

**Comment by paologd** [comment]
Alla fine è andata tema aggiornato, ma nonostante l'inserimento dei data element nel file header.php (cosa che avevo già fatto con la versione precedente), il controllo non passa e di fatto di tutti i test non passati, segnalano un data element mancante.
Nelle guide dice quali dover utilizzare ma dopo aver cercato in tutti .php, non si capisce in quale file si debbano inserire. 
Mi riferisco a C.SC.1.1; C.SC.1.2; C.SC.2.3; R.SC.1.2
Avete qualche info?

**Comment by Anto886** [comment]
> Ciao,
> 
> nell'editor del tema (o direttamente dal file sorgente sul server) trovi i file php che puoi andare a modificare. L'operazione è di per se banale, il problema è capire quali sono i data-element che ti mancano per individuare il file da andare a modificare. Purtroppo la app non ti restituisce dove ha trovato il problema. L'unica è leggersi la documentazione e andare a impostare i corretti data-element. Lo sto facendo anche io. Non so se qualcuno è già intervenuto e ha la lista completa dei file sui quali intervenire.

Ciao,  puoi farci un esempio di cosa modificare per risolvere questo problema:
<html>
<body>
<summary style="box-sizing: border-box; cursor: pointer; display: block; border-bottom: 1px solid var(--report-border-color-secondary);"><div class="lh-audit__header lh-expandable-details__summary" style="box-sizing: border-box; display: flex; align-items: center; padding: var(--default-padding);"><span class="lh-audit__title-and-text" style="box-sizing: border-box; flex: 1 1 0%;"><span class="lh-audit__title" style="box-sizing: border-box;"><span style="box-sizing: border-box;">C.SC.1.1 - COERENZA DELL'UTILIZZO DEI FONT (librerie di caratteri) - Il sito della scuola deve utilizzare i font indicati dalla documentazione del modello di sito della scuola.</span></span><span class="lh-audit__display-text" style="box-sizing: border-box; margin: 0 var(--audit-margin-horizontal); color: var(--color-fail-secondary);"></span></span><div class="lh-chevron-container" style="box-sizing: border-box; margin-top: ; margin-right: 0px; margin-bottom: ; margin-left: ;"><svg class="lh-chevron" viewBox="0 0 100 100"><g class="lh-chevron__lines"><path class="lh-chevron__line lh-chevron__line-left" d="M10 50h40"></path><path class="lh-chevron__line lh-chevron__line-right" d="M90 50H50"></path></g></svg></div></div></summary><slot id="details-content" style="color: rgb(33, 33, 33); font-family: Roboto, Helvetica, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="lh-audit__description" style="box-sizing: border-box; --inner-audit-padding-right: var(--stackpack-padding-horizontal); padding-left: var(--audit-description-padding-left); padding-right: var(--inner-audit-padding-right); padding-top: 8px; padding-bottom: 8px; color: var(--report-text-color-secondary);"><span style="box-sizing: border-box;">CONDIZIONI DI SUCCESSO: tutti i titoli (heading) e tutti i paragrafi delle pagine del sito in lingua italiana utilizzano esclusivamente i font Titillium Web, Lora o Roboto Mono come font di default; MODALITÀ DI VERIFICA: ricercando specifici attributi "data-element" come spiegato nella Documentazione delle App di valutazione, nelle pagine analizzate viene verificato che i font di default siano quelli richiesti all'interno di tutti gli &lt;h&gt; e &lt;p&gt;; RIFERIMENTI TECNICI E NORMATIVI:<span> </span><a rel="noopener" target="_blank" href="https://docs.italia.it/italia/designers-italia/design-scuole-docs" style="box-sizing: border-box; color: var(--link-color);">Documentazione del Modello scuole</a>,<span> </span><a rel="noopener" target="_blank" href="https://docs.italia.it/italia/designers-italia/app-valutazione-modelli-docs/" style="box-sizing: border-box; color: var(--link-color);">Documentazione delle App di valutazione</a>.</span></div><div class="lh-audit__stackpacks" style="box-sizing: border-box;"></div>

Risultato
--
Uno o più data-element necessari per condurre il test non sono stati trovati. Verifica il capitolo sui Requisiti tecnici nella Documentazione delle App di valutazione per risolvere il problema.

</slot>
</body>
</html>C.SC.1.1 - COERENZA DELL'UTILIZZO DEI FONT (librerie di caratteri) - Il sito della scuola deve utilizzare i font indicati dalla documentazione del modello di sito della scuola.
CONDIZIONI DI SUCCESSO: tutti i titoli (heading) e tutti i paragrafi delle pagine del sito in lingua italiana utilizzano esclusivamente i font Titillium Web, Lora o Roboto Mono come font di default; MODALITÀ DI VERIFICA: ricercando specifici attributi "data-element" come spiegato nella Documentazione delle App di valutazione, nelle pagine analizzate viene verificato che i font di default siano quelli richiesti all'interno di tutti gli <h> e <p>; RIFERIMENTI TECNICI E NORMATIVI: [Documentazione del Modello scuole](https://docs.italia.it/italia/designers-italia/design-scuole-docs), [Documentazione delle App di valutazione](https://docs.italia.it/italia/designers-italia/app-valutazione-modelli-docs/).
Risultato
Uno o più data-element necessari per condurre il test non sono stati trovati. Verifica il capitolo sui Requisiti tecnici nella Documentazione delle App di valutazione per risolvere il problema.

Preciso che ho fatto anche l'aggiornamento del tema.

Grazie in anticipo
