### ISSUE TITLE
Testo vuoto tra virgolette nella sezione "Scuola->Panoramica" in corrispondenza dei luoghi

### ISSUE THREAD

**Issue by CampusDaVinci** [italia/design-scuole-wordpress-theme#328]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-scuole-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-scuole-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Nella pagina dedicata alla panoramica della scuola, nella sezione "Luoghi" è presente uno spazio dove inserire un testo mostrato tra 2 virgolette, ma non è presente nessun modo di impostarlo.

### Includi link o screenshot

https://campusdavinci.edu.it/la-scuola/
![Screenshot 2023-04-14 102003](https://user-images.githubusercontent.com/115779224/231987659-c5aafa2f-3c88-4cfb-b5a8-772fc04bc464.png)

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

2.3.2

**Comment by vcoopcsc** [comment]
Ciao, in realtà quella non è la sezione luoghi di Panoramica, ma è la sezione Organizzazione di Panoramica, che puoi riempire accedendo a Configurazione->Scuola. Qui scorrendo fino ad arrivare nella sezione "Le strutture", nel campo "Descrizione" puoi inserire il testo che apparirà
