### ISSUE TITLE
Avviso "Important Deprecation Reminder & Free Mapbox Swag"

### ISSUE THREAD

**Issue by anitamaccio** [italia/design-scuole-wordpress-theme#33]
Salve, avendo fatto l'access token mapbox per l'erogazione delle mappe di Mapbox, continuo a ricevere regolari avvisi via mail che sarà deprecato il supporto a Mapbox Studio Classic styles il primo giugno 2020, e che il sito utilizza il Classic styles deprecato, mentre dovrebbe passare a modern styles.
Ho provato a guardare le guide proposte (https://docs.mapbox.com/help/troubleshooting/migrate-legacy-static-images-api/#how-to-tell-if-your-current-implementation-uses-a-mapbox-designed-classic-style), in effetti nella pagina delle statistiche http://account.mapbox.com/statistics risultano accessi a mapbox.streets che è deprecato, ma mi pare che bisogna intervenire sulla struttura del sito...
Siete a conoscenza del problema? Lo potete risolvere? Devo fare qualcosa io?
Grazie e cordiali saluti
Anita Macciò

**Comment by webgrafia** [comment]
ciao Anita,
grazie della segnalazione, non ero a conoscenza del problema
indaghiamo

**Comment by webgrafia** [comment]
ciao Anita,
abbiamo aggiornato il tema per evitare l'interruzione della funzionalità di erogazione delle mappe.
(versione 1.0.6)
Aggiornandolo entro il 1 giugno non dovresti avere problemi

Chiudo la issue, grazie del feedback
