### ISSUE TITLE
Tipologia servizi, luoghi e strutture

### ISSUE THREAD

**Issue by EasyTeamSrl** [italia/design-scuole-wordpress-theme#333]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-scuole-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-scuole-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Se ho un servizio o un articolo catalogato in due o più tipologie, nel momento in cui si modifica il servizio vengono perse tutte le tipologie aggiuntive.

### Includi link o screenshot

<img width="765" alt="Screenshot 2023-04-17 alle 18 23 47" src="https://user-images.githubusercontent.com/20112395/232549882-476e8981-8d64-4a0a-b066-c908a09c9b5a.png">

<img width="765" alt="Screenshot 2023-04-17 alle 18 24 07" src="https://user-images.githubusercontent.com/20112395/232549902-64dd992d-5787-49e1-961a-c31541e3e51f.png">

### Su quale sisitema operativo stai riscontrando il problema?

macOS

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

2.3.2

**Comment by sviluppoRobyone** [comment]
Per quanto riguarda luoghi e strutture sarebbe strano avere più tipi, bisognerebbe evitare di dare la possibilità tramite modifica rapida di mettere più valori.

Riguardo i servizi, invece, bisognerebbe permettere la selezione di più tipologie poiché alcuni servizi sono rivolti a più categorie.

**Comment by EasyTeamSrl** [comment]
Confermo che il cambio della riga 134 permette la selezione multipla nella pagina di modifica del servizio.
Allo stato attuale nelle breadcrumb viene presa esclusivamente la prima tipologia.

Per Luoghi e Strutture la modifica non è necessaria, in quanto come osservato da @sviluppoRobyone è un errore pensare a luoghi o strutture con tipologie multiple.

**Comment by sviluppoRobyone** [comment]
Una soluzione potrebbe essere di inserire nello stesso elemento li dell'elenco tutti i link alle categorie abbinate separati da una virgola, non sono però riuscito ad oggi a modificare in tal senso il meccanismo del breadcrumb

![image](https://github.com/italia/design-scuole-wordpress-theme/assets/13221786/ba445f83-084b-44a7-b4b6-26dbee0c6df2)
