### ISSUE TITLE
Problema riguardante R.SC.1.2 - SCHEDE INFORMATIVE DI SERVIZIO

### ISSUE THREAD

**Issue by SebastianoIngalisi** [italia/design-scuole-wordpress-theme#337]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-scuole-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-scuole-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

tramite il tools ufficiale sto cercando di portare tutti i riquadri superiori al 90 come punteggio, e praticamente ci sono quasi, ho solo un problema che non riesco a capire:
[R.SC](http://r.sc/).1.2 - SCHEDE INFORMATIVE DI SERVIZIO
Il tools mi segnala che c'è il campo "ulteriori informazioni" da compilare in uno dei servizi inseriti, che in verità è già compilato esattamente come in tutti gli altri servizi, ma solo in questo da l'errore, avete idea di quale possa essere il problema?

### Includi link o screenshot

(https://www.itcsommeiller.edu.it/servizio/ecdl-icdl-certificazioni-informatiche/)

![r sc 1 2](https://user-images.githubusercontent.com/131443605/233591461-94cc2700-f920-456d-a517-b37fc382fd79.png)

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

2.3.2

**Comment by 1234j9tcswn** [comment]
Anch'io riscontro lo stesso problema: quando eseguo la verifica, le schede informative dei servizi risultano prive di alcune informazioni che invece sono presenti nelle pagine (Tempi e scadenze, Ulteriori informazioni, orari).

SO: windows

Versione tema: 2.3.2
