### ISSUE TITLE
La validazione segnala erroneamente che sito non utilizza il tema CMS del modello

### ISSUE THREAD

**Issue by 1234j9tcswn** [italia/design-scuole-wordpress-theme#338]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-scuole-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-scuole-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Eseguendo la validazione, pur avendo installato e attivato il tema Design scuole v. 2.3.2, ottengo il messaggio:

"Il sito non utilizza il tema CMS del modello."

Potete consigliarmi come risolvere questa criticità che risulta cruciale per la validazione e quindi per l'attribuzione del finanziamento?

### Includi link o screenshot

<img width="609" alt="Screenshot 2023-04-23 19 27 52" src="https://user-images.githubusercontent.com/123419966/233856766-5c3f0c17-a1de-4182-a6d5-a19ea2d4e2f4.png">

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

2.3.2

**Comment by ettoreperri** [comment]
io ho risolto aggiungendo questo a print.css
```

/*!
Theme Name: Design Scuole Italia
Author: Dipartimento per la trasformazione digitale - Presidenza del Consiglio dei Ministri
Description: Design Scuole Italia è il tema di WordPress per i siti delle Scuole Italiane. Rispetta le linee guida di design dell’Agenzia per l’Italia digitale rilasciare dal Team per la Trasformazione Digitale. Utilizza Bootstrap Italia. Basato sul precedente lavoro di Marco Buttarini.
Version: 2.3.2
License: AGPL 3.0 or later
Text Domain: design_scuole_italia
*/
```
@astagi

**Comment by ettoreperri** [comment]
Ciao, io ho risolto aggiungendo a print.css il seguente codice:
/*!
Theme Name: Design Scuole Italia
Author: Dipartimento per la trasformazione digitale - Presidenza del Consiglio dei Ministri
Description: Design Scuole Italia è il tema di WordPress per i siti delle Scuole Italiane. Rispetta le linee guida di design dell’Agenzia per l’Italia digitale rilasciare dal Team per la Trasformazione Digitale. Utilizza Bootstrap Italia. Basato sul precedente lavoro di Marco Buttarini.
Version: 2.3.2
License: AGPL 3.0 or later
Text Domain: design_scuole_italia
*/

@astagi 

Aggiungo che questo workaround risulta utile **solo se stai utilizzando un tema Child**. Infatti, in quel caso la validazione fallisce per la presenza della stringa "Template: ...." non prevista nell'app di valutazione https://docs.italia.it/italia/designers-italia/app-valutazione-modelli-docs/it/versione-attuale/requisiti-e-modalita-verifica-scuole.html

**Comment by danieledexter** [comment]
> 

Ciao Ettore, non ho ben capito, mettendo questo commento nel file print.css del tema child dovrebbe superare la validazione?

**Comment by ettoreperri** [comment]
Si, ma solo se stai usando un tema Child

**Comment by 1234j9tcswn** [comment]
Ho risolto anche forzando https

**Comment by ettoreperri** [comment]
No, ti consiglierei di verificare se print.css viene aggiunto correttamente tra gli stili del tema child. 

https://developer.wordpress.org/themes/advanced-topics/child-themes/

**Comment by danieledexter** [comment]
Si, altra domanda, il commento devo lasciarlo solo in questo file o deve rimanere anche sul style.css ?
Sto cercando di capire l'utilizzo di questo print.css

**Comment by sagredo-dev** [comment]
Ciao,
anche noi abbiamo lo stesso problema con un tema figlio della versione 2.4 (per chi volesse dare uno sguardo https://www.pacinotti.edu.it). 
Ho creato il file print.css e messo dentro il codice, che ho ricontrollato bene più volte. Mi sono anche assicurato che esso venga effettivamente caricato.
Esso viene caricato *prima* del file print.css del tema padre. Mi chiedo cosa faccia la app: per caso viene letto solo l'ultimo print.css, quello del tema padre?
Ho provato quindi a caricare un nuovo file theme_info.css con lo stesso codice (la documentazione dice che la ricerca viene fatta su uno dei file .css del tema), ma niente.
Qualcuno sa se/dove si possa vedere il codice sorgente della app, giusto per capire qual è la logica seguita?
