### ISSUE TITLE
R.SC.1.1 - VOCABOLARI CONTROLLATI - Il sito della scuola deve utilizzare argomenti forniti dal modello di sito scuola

### ISSUE THREAD

**Issue by Plinio2000** [italia/design-scuole-wordpress-theme#339]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-scuole-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-scuole-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Argomenti non presenti nell'elenco del modello: famiglie, studenti, personale a.t.a., docenti. 
Gli argomenti sono regolarmente inseriti nelle sezioni alla voce Argomento. Non capisco se devono essere inseriti in altre sezioni per non segnale l'errore. 
Grazi a tutti

### Includi link o screenshot
![image](https://user-images.githubusercontent.com/131682507/234030651-0ef1aec8-2376-4c78-8950-60dc944f06d6.png)

_No response_

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

2.3.2

**Comment by Jingko** [comment]
Ciao Plinio,
le voci devono essere le stesse contenute nell'elenco degli argomenti del Modello scuole "**Le parole della scuola**".
Puoi visionare i termini seguendo il link "Elenco degli argomenti del Modello scuole" nel messaggio dell'applicazione di validazione.
Non è necessario inserirli tutti ma quelli che inserisci devono essere compresi in quell'elenco.

**Comment by Plinio2000** [comment]
Ciao Jingko,
si avevo capito ciò che scrivi. Ma non so dove collocare o dove è collocato l'elenco "Le parole della scuola" o dove devo inserire le parole. Mi potresti indicare gentilmente?
Grazie

**Comment by Simsimus** [comment]
Buongiorno,
se può essere utile questo è l'elenco ufficiale:
https://docs.google.com/spreadsheets/d/1MoayTY05SE4ixtgBsfsdngdrFJf_Z2KNvDkMF3tKfc8/edit#gid=2135815526

**Comment by Plinio2000** [comment]
Buongiorno,
![image](https://user-images.githubusercontent.com/131682507/236623132-1e73bfa4-7fa8-4ada-bb47-2e21512c6df9.png)
come si può vedere anche da me è uguale. Ma continua a segnalare l'errore. 
Grazi

**Comment by Simsimus** [comment]
Famiglie, studenti, docenti non sono accettati (si lo so, è assurdo). In alternativa usare Genitori, Alunni, Insegnanti. 
Come già suggerito usare solo i vocaboli presenti al seguente link:
https://docs.google.com/spreadsheets/d/1MoayTY05SE4ixtgBsfsdngdrFJf_Z2KNvDkMF3tKfc8/edit#gid=2135815526

**Comment by Plinio2000** [comment]
Grazie Simsimus, 
ho seguito le tue indicazioni cambiando i nomi. Superato il test.
Grazie
