### ISSUE TITLE
Visualizzazione mappe Mapbox

### ISSUE THREAD

**Issue by cesarelam** [italia/design-scuole-wordpress-theme#34]
Salve, ho iniziato a testare il tema per verificare la possibilità di utilizzarlo per il sito della mia scuola. Compilando la scheda dei Luoghi ho creato un Token su Mapbox e credo di aver inserito correttamente i riferimenti. Sul sito di test però mi mostra solo il segnaposto e non la mappa. Cosa ho sbagliato? Grazie sin da ora.
<img width="848" alt="screenshot_01" src="https://user-images.githubusercontent.com/4965116/82565117-29556880-9b7a-11ea-8f00-0ea1dfb42cbe.png">

**Comment by webgrafia** [comment]
E' un problema del tema, che integra le mappe di Mapbox, che ha dismesso proprio in questi giorni il supporto alla mappa classica.
Nei prossimi giorni rilasceremo il fix che corregge questo problema, ti avviso qui

**Comment by webgrafia** [comment]
Riguardando la issue in effetti non sono sicuro sia quello il tuo problema, mi puoi mandare la url del sito?

**Comment by cesarelam** [comment]
Ecco, per questo luogo credo di aver settato le coordinate, ti allego pure uno screenshot dell'interfaccia di gestione

https://www.ioborrelli.edu.it/new/luogo/liceo-classico-diodato-borrelli/

<img width="1043" alt="screenshot_01 2" src="https://user-images.githubusercontent.com/4965116/82577775-ba810b00-9b8b-11ea-8d54-f4576390750d.png">

**Comment by webgrafia** [comment]
Come non detto, non è un problema del tema, credo tu abbia inserito o configurato male l'access token di mapbox

Vedo che il tuo sito fa queste chiamate, che non erogano la mappa:
https://api.tiles.mapbox.com/v4/mapbox.streets/13/4481/3126.png?access_token=pk.eyJ1IjoiY2VzYXJlbGFtIiwiYSI6ImNrYWdzaGI1MTA5aW0yc295cjJ6OG1oeHAifQ.17FvEFOTYq7N9SPV_-65KQ

Se sostituisco a questa url l'accesstoken con quello che ho creato io invece funziona

https://api.tiles.mapbox.com/v4/mapbox.streets/13/4481/3126.png?access_token=pk.eyJ1Ijoid2ViZ3JhZmlhIiwiYSI6ImNqdnMzdnl0azI0c3AzeWxlaThyaG8zN2kifQ.3oRpuS7XbsZp0o1sveLskQ

Controlla se l'hai inserito bene o se non hai messo qualche filtro su mapbox che non lo fa funzionare!

**Comment by cesarelam** [comment]
Che strano... In effetti ho copiato e incollato il tuo token nelle impostazioni del tema e tutto funziona. Ho riprovato a creare su Mapbox un altro token e non va, nel Web Inspector di Safari (ma ho provato pure su Chrome) mi indica un errore 410. Quando ho creato il token non ho fatto che lasciare le spunte come vedi nell'immagine e non ho applicato nessuna restrizione sulla URL...

<img width="838" alt="screenshot_01 3" src="https://user-images.githubusercontent.com/4965116/82591359-844d8680-9b9f-11ea-81a9-b9d9f067be40.png">

**Comment by webgrafia** [comment]
ciao Cesare,
il problema che hai segnalato è legato alla dismissione da parte di mapbox delle mappe classiche, che utilizziamo sul sito.
Abbiamo appena rilasciato un aggiornamento che risolve il problema, se scarichi e aggiorni il tema dovresti vedere le mappe utilizzando la tua key mapbox.
Chiudo la issue, ma se hai altri problemi segnalacelo!

Buon lavoro
