### ISSUE TITLE
Il file manifest o il service worker dell'app web non soddisfano i requisiti di installabilità

### ISSUE THREAD

**Issue by Plinio2000** [italia/design-scuole-wordpress-theme#343]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-scuole-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-scuole-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Buongiorno,
come posso risolvere?
Grazie

### Includi link o screenshot

![image](https://user-images.githubusercontent.com/131682507/236676993-a063dc5e-35dc-452a-ba0f-0aaea1705166.png)

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Chrome

### Che versione del tema stai utilizzando?

2.3.2

**Comment by corrado1975** [comment]
Ciao @Plinio2000 io ho risolto installando questo plugin

![SuperPWA](https://github.com/italia/design-scuole-wordpress-theme/assets/140151788/70bc3ba0-3ff1-49c6-93ef-bb3fcdf58a11)
