### ISSUE TITLE
Personalizzazione tema in base a identità grafica scuola (logo e colore per la pagina iniziale)

### ISSUE THREAD

**Issue by sviluppoRobyone** [italia/design-scuole-wordpress-theme#345]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-scuole-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-scuole-wordpress-theme/blob/main/CONTRIBUTING.md)

### Proposta

Qualora l'Ente scolastico abbia adottato una propria identità grafica,
ci sono delle limitazioni all'utilizzo nel sito web istituzionale?

In particolare, ci riferiamo alla possibilità di:
- personalizzare il logo in intestazione con il proprio
- personalizzare i colori del banner iniziale di presentazione/promozione dell'Ente (ora rosso poiché legato alla sezione Scuola)

### Motivazione e contesto

Gli Enti scolastici che si sono affidati a noi per l'implementazione del modello AGID ci chiedono la possibilità di personalizzare il logo nell'intestazione e il colore del banner iniziale di presentazione (ad oggi corrispondente al rosso poiché legato alla sezione Scuola).

Questo per rendere il sito web più vicino alla loro realtà e tradizione.

**Comment by sviluppoRobyone** [comment]
Mettiamo a disposizione la modifica effettuata per dare la possibilità di personalizzazione del logo, riteniamo importante avere da voi un riscontro in merito ad ulteriori personalizzazioni, anche per capire quanto spingersi per evitare di stravolgere il tema iniziale vanificando uno degli obiettivi del modello, l'uniformità

**Comment by Oxfirm** [comment]
Come è possibile cambiare il il colore del banner iniziale di presentazione (ad oggi corrispondente al rosso poiché legato alla sezione Scuola)? Grazio mille

**Comment by sviluppoRobyone** [comment]
Attualmente non è possibile, chiedevamo di avere un riscontro e un'eventuale via libera per poter inserire ulteriori opzioni di personalizzazione e consentire il cambio dei colori per quel banner, con la certezza di rispettare comunque il modello previsto.

**Comment by Oxfirm** [comment]
Alcune scuole lo hanno fatto. Secondo voi in che modo?

**Comment by sviluppoRobyone** [comment]
Cambiando il codice in _template-parts/hero/home.php_
