### ISSUE TITLE
Elenco firmatari accessibile a chiunque

### ISSUE THREAD

**Issue by robertogasbarro** [italia/design-scuole-wordpress-theme#349]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-scuole-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-scuole-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Salve, ho riscontrato un problema riguardante il download dell'elenco dei firmatari di una circolare, che difatti è accessibile da chiunque, senza che sia necessario essere autenticati, aggiungendo nel link il parametro csv=true.

Suggerisco di modificare il file 'inc\admin\circolari.php' aggiungendo quantomeno il controllo sull'autenticazione dell'utente:

```
    function dsi_csv_generator(){
        if(is_singular("circolare") && isset($_GET) && ($_GET["csv"] == "true") && is_user_logged_in()){ ...
```

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Chrome

### Che versione del tema stai utilizzando?

2.3.2

**Comment by zetareticoli** [comment]
Ciao @robertogasbarro, la modifica da te proposta è stata già verificata?
