### ISSUE TITLE
Indice dei contenuti per post delle novità (articoli, notizie, ...)

### ISSUE THREAD

**Issue by sviluppoRobyone** [italia/design-scuole-wordpress-theme#353]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-scuole-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-scuole-wordpress-theme/blob/main/CONTRIBUTING.md)

### Proposta

In caso siano presenti due o più titoli h2, prevedere l'indice dei contenuti anche nei post delle novità.

### Motivazione e contesto

Alcune notizie, articoli, comunicazioni potrebbero essere più articolati e lunghi.
Indicazioni su accessibilità e usabilità suggerirebbero, oltre ai paragrafi, anche sottotitoli che semplifichino la scansione della pagina e delle informazioni.
La presenza poi di un indice dei contenuti all'inizio della pagina rende tutto più performante e veloce.

Se dal punto di vista tecnico è fattibile riconoscere gli elementi h2 e creare in automatico l'indice, dal punto di vista grafico la pagina è stata realizzata diversamente e quindi richiede ulteriori riflessioni e confronto in merito (in modalità desktop sono presenti azioni e argomenti nel punto dove in altri content-type viene riportato l'indice dei contenuti)

**Comment by vcoopcsc** [comment]
Ciao @sviluppoRobyone la questione mi interessa ma non ho compreso bene. Intendi che nella formattazione in backend ci sarebbe bisogno di avere anche i sottotitoli oltre alle intestazioni?

**Comment by sviluppoRobyone** [comment]
Provo a chiarire la richiesta, il sistema dovrebbe riconoscere in automatico gli h2 inseriti all'interno del contenuto di un articolo

![image](https://github.com/italia/design-scuole-wordpress-theme/assets/13221786/f74dad2c-8585-43ef-98e2-087d100351dd)

e passare da una schermata senza indice dei contenuti

![image](https://github.com/italia/design-scuole-wordpress-theme/assets/13221786/568174b2-853e-4122-9863-e451e5e4e04d)

ad una con indice dei contenuti, come per gli altri 

![image](https://github.com/italia/design-scuole-wordpress-theme/assets/13221786/e3876ba2-352b-4abd-a95f-2e8b8ee75952)
