### ISSUE TITLE
RI-aggiungere post type nel menu

### ISSUE THREAD

**Issue by Petrillo96** [italia/design-scuole-wordpress-theme#370]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-scuole-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-scuole-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Ciao, qualcuno saprebbe dirmi come aggiungere Post Type nei menu? Tra l'altro nel menu servizi non mi riporta la voce "Panoramica" come negli altri. Ho effettuato backup e ripristino del tema ma ottengo lo stesso risultato

### Includi link o screenshot

https://www.icgalileipascoli.edu.it/

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

2.3.2

**Comment by marcoverze93** [comment]
Ciao,
guardando al link che hai allegato sembra tutto corretto. Per reinserire un Post Type nel menù devi seguire i seguenti passaggi: Aspetto->Temi->Personalizza->Menù->Scegli il menù che vuoi sistemare->+ Aggiungi voci->Apri ad esempio "Luoghi" e il primo è proprio il Post Type->  Premi + e lo aggiungi.
Spero di essermi spiegato bene..

**Comment by domenicomadeo** [comment]
> Ciao, guardando al link che hai allegato sembra tutto corretto. Per reinserire un Post Type nel menù devi seguire i seguenti passaggi: Aspetto->Temi->Personalizza->Menù->Scegli il menù che vuoi sistemare->+ Aggiungi voci->Apri ad esempio "Luoghi" e il primo è proprio il Post Type-> Premi + e lo aggiungi. Spero di essermi spiegato bene..

ciao, si conosco questa procedura, ma non è quella che cerco, il problema ce l'ho con le carte della scuola, che per rimetterlo dopo averlo cancellato per sbaglio, ho dovuto farlo come link personalizzato...e non come tipo Post Type...

allego un'immagine per chiarirmi...
[https://postimg.cc/pmt5CRmP](https://postimg.cc/pmt5CRmP)

**Comment by Petrillo96** [comment]
> Ciao, guardando al link che hai allegato sembra tutto corretto. Per reinserire un Post Type nel menù devi seguire i seguenti passaggi: Aspetto->Temi->Personalizza->Menù->Scegli il menù che vuoi sistemare->+ Aggiungi voci->Apri ad esempio "Luoghi" e il primo è proprio il Post Type-> Premi + e lo aggiungi. Spero di essermi spiegato bene..

Ciao, ho poi corretto eliminando pagine pre-esistenti ed eliminandole, per poi ricaricare il tema. Grazie

**Comment by Petrillo96** [comment]
> > Ciao, guardando al link che hai allegato sembra tutto corretto. Per reinserire un Post Type nel menù devi seguire i seguenti passaggi: Aspetto->Temi->Personalizza->Menù->Scegli il menù che vuoi sistemare->+ Aggiungi voci->Apri ad esempio "Luoghi" e il primo è proprio il Post Type-> Premi + e lo aggiungi. Spero di essermi spiegato bene..
> 
> ciao, anch'io ho lo stesso problema, io il problema ce l'ho con le carte della scuola, che per rimetterlo dopo averlo cancellato per sbaglio, ho dovuto farlo come link personalizzato...e non come tipo Post Type...
> 
> allego un'immagine per chiarirmi... https://postimg.cc/pmt5CRmP

Prova eliminando la pagina del link personalizzato,dopo vai su Aspetto-Ricarica dati e infine dovresti visualizzare il corretto post-type.

**Comment by peppeguitar** [comment]
Anche a me è capitato che sparisse la voce "Panoramica" della voce "Didattica". Ho risolto editando la pagina "Didattica" ed impostando negli attributi della pagina il template "Didattica".
