### ISSUE TITLE
Mancanza corrispondenza voci menù secondo livello con l'App di valutazione modello Scuole

### ISSUE THREAD

**Issue by delfuria** [italia/design-scuole-wordpress-theme#372]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-scuole-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-scuole-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Non c'è corrispondenza tra i nomi delle voci dei menù di secondo livello del tema e quelle richieste dall'App di valutazione scuole es:
Circolari vs Le circolari
I Luoghi della scuola vs I Luoghi
questo fa sì che vengono rilevati come non conformi dall'APP che invece ha nel dizionario di valutazione i seguenti dizionari
---------
export const primaryMenuItems = ["Scuola", "Servizi", "Novità", "Didattica"];

export const primaryMenuDataElement = "overview";

export const menuItems = {
  school: {
    label: "SCUOLA",
    data_element: "school-submenu",
    dictionary: [
      "presentazione",
      "i luoghi",
      "le persone",
      "i numeri della scuola",
      "le carte della scuola",
      "organizzazione",
      "la storia",
    ],
  },
  services: {
    label: "SERVIZI",
    data_element: "services-submenu",
    dictionary: [
      "famiglie e studenti",
      "personale scolastico",
      "percorsi di studio",
    ],
  },
  news: {
    label: "NOVITÀ",
    data_element: "news-submenu",
    dictionary: [
      "le notizie",
      "le circolari",
      "calendario eventi",
      "albo online",
    ],
  },
  teaching: {
    label: "DIDATTICA",
    data_element: "teaching-submenu",
    dictionary: [
      "offerta formativa",
      "le schede didattiche",
      "i progetti delle classi",
    ],
  },
};

export const customPrimaryMenuItemsDataElement = "custom-submenu";

### Includi link o screenshot

Ecco il risultato del processo di validazione che rileva errori dovuti a voci non corrispondenti
<img width="604" alt="image" src="https://github.com/italia/design-scuole-wordpress-theme/assets/1910881/f46d1ecc-f692-4cea-ba90-51fee47d6d08">

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

2.3.2

**Comment by praflo** [comment]
Confermo, anche noi abbiamo lo stesso problema.
Wordpress 6.2.2 (linux)
Tema: Design Scuole Italia Versione: 2.3.2 
Browser: Chrome & Firefox (ma penso sia generale per tutti i browser)
Client OS: Windows 10

Esempio: 
Menu Scuola / Organizzazione -> il percorso diventa Home / La scuola / Strutture

**Comment by marcoverze93** [comment]
> ### Prerequisiti
> * [x]  Ho già [cercato](https://github.com/italia/design-scuole-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
> * [x]  Ho letto le [linee guida di contribuzione](https://github.com/italia/design-scuole-wordpress-theme/blob/main/CONTRIBUTING.md)
> 
> ### Descrivi il problema
> ## Non c'è corrispondenza tra i nomi delle voci dei menù di secondo livello del tema e quelle richieste dall'App di valutazione scuole es:
> Circolari vs Le circolari
> I Luoghi della scuola vs I Luoghi
> questo fa sì che vengono rilevati come non conformi dall'APP che invece ha nel dizionario di valutazione i seguenti dizionari
> export const primaryMenuItems = ["Scuola", "Servizi", "Novità", "Didattica"];
> 
> export const primaryMenuDataElement = "overview";
> 
> export const menuItems = { school: { label: "SCUOLA", data_element: "school-submenu", dictionary: [ "presentazione", "i luoghi", "le persone", "i numeri della scuola", "le carte della scuola", "organizzazione", "la storia", ], }, services: { label: "SERVIZI", data_element: "services-submenu", dictionary: [ "famiglie e studenti", "personale scolastico", "percorsi di studio", ], }, news: { label: "NOVITÀ", data_element: "news-submenu", dictionary: [ "le notizie", "le circolari", "calendario eventi", "albo online", ], }, teaching: { label: "DIDATTICA", data_element: "teaching-submenu", dictionary: [ "offerta formativa", "le schede didattiche", "i progetti delle classi", ], }, };
> 
> export const customPrimaryMenuItemsDataElement = "custom-submenu";
> 
> ### Includi link o screenshot
> Ecco il risultato del processo di validazione che rileva errori dovuti a voci non corrispondenti <img alt="image" width="604" src="https://user-images.githubusercontent.com/1910881/244961731-f46d1ecc-f692-4cea-ba90-51fee47d6d08.png">
> 
> ### Su quale sisitema operativo stai riscontrando il problema?
> Windows
> 
> ### Su quale browser stai riscontrando il problema?
> Qualsiasi
> 
> ### Che versione del tema stai utilizzando?
> 2.3.2

Ciao,
il tuo problema è dovuto dal fatto che nel sito avete modificato le voci del menù servizi e novità (in questo caso aggiungendone), per quanto riguarda gli altri (scuola, didattica) il fatto che il nome è leggermente diverso non è un problema.
