### ISSUE TITLE
 Non usa listener passivi per migliorare le prestazioni dello scorrimento 

### ISSUE THREAD

**Issue by databit** [italia/design-scuole-wordpress-theme#373]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-scuole-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-scuole-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Il file js (_assets\js\components\perfect-scrollbar-master\perfect-scrollbar\js\perfect-scrollbar.jquery.js_) del tema scatena questa criticità.
Ho risolto sostituendo la stringa **_this.element.addEventListener(t,e,!1)_** con **_this.element.addEventListener(t,e,{'passive':false})_**

### Includi link o screenshot

![immagine](https://github.com/italia/design-scuole-wordpress-theme/assets/7859955/f182f807-ca02-4c41-b6a8-b9102282ba04)

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Qualsiasi, Firefox

### Che versione del tema stai utilizzando?

2.3.2

**Comment by databit** [comment]
Ciao @zetareticoli , non posso, non sono un collaboratore. Appena provo a creare una pull request git mi blocca

**Comment by zetareticoli** [comment]
@databit puoi farlo tramite un _fork_

**Comment by databit** [comment]
Ah, nella mia fork ho fatto altre modifiche molto più pesanti.
Qui trovi il file completamente modificato
[assets/js/components/perfect-scrollbar-master/perfect-scrollbar/js/perfect-scrollbar.jquery.js](https://github.com/italia/design-scuole-wordpress-theme/commit/beb003d50ea760bb7a90f3bc6a7c09620233481d#diff-1fd3ea660086d04aa3721a22ba297106daf14e2d6b0b94c50f303c342c197c0e)
