### ISSUE TITLE
Uniformità dei font

### ISSUE THREAD

**Issue by aletrento** [italia/design-scuole-wordpress-theme#374]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-scuole-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-scuole-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

I font in uso nel tema Wordpress non sono uniformi. Quando si crea una pagina o un articolo il testo appare in font diversi (titolo, paragrafo, ...).
E' possibile uniformarli?

### Includi link o screenshot

![Istantanea_2023-06-19_12-42-35](https://github.com/italia/design-scuole-wordpress-theme/assets/4952814/f4ce46dd-b32c-4352-ad80-a81ebf5d60ff)

### Su quale sisitema operativo stai riscontrando il problema?

Linux

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

Design Scuole Italia Versione: 2.3.2

**Comment by zetareticoli** [comment]
Ciao @aletrento, non è un bug, vengono utilizzati due font: Titillium Web per titoli, sottotitoli e testi brevi, Lora per i paragrafi di testo più lunghi.
