### ISSUE TITLE
Collegamento bidirezionale tra struttura e documento

### ISSUE THREAD

**Issue by orporick** [italia/design-scuole-wordpress-theme#375]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-scuole-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-scuole-wordpress-theme/blob/main/CONTRIBUTING.md)

### Proposta

Sarebbe molto utile poter associare, in modo bidirezionale, documenti ad una struttura. Al momento è possibile indicare di un documento la struttura di riferimento, semplificherebbe il flusso di navigazione se dalla struttura fosse possibile vedere (e aggiungere) tali documenti. 

### Motivazione e contesto

Un esempio: nella mia scuola ogni dipartimento disciplinare (struttura) è responsabile di un curricolo disciplinare (documento). Sarebbe utile poter aggiungere un documento alla struttura.

Altro esempio: la segreteria didattica (struttura) potrebbe aggiungere la modulistica (documenti) da scaricare per studenti e studentesse o famiglie. In questo caso si può in realtà risolvere aggiungendo un servizio, per esempio "Modulistica Online", di cui la segreteria didattica è la struttura di riferimento e aggiungere i documenti al servizio. Ma a volte sarebbe più comodo un'associazione diretta bidirezionale documento <-> struttura.

**Comment by vcoopcsc** [comment]
Mi unisco alla richiesta
