### ISSUE TITLE
Come posso modificare la descrizione presente nella pagina login? (Entra nel sito della scuola con le tue credenziali per gestire contenuti, visualizzare circolari e altre funzionalità)

### ISSUE THREAD

**Issue by assistenzatecnica94** [italia/design-scuole-wordpress-theme#376]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-scuole-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-scuole-wordpress-theme/blob/main/CONTRIBUTING.md)

### Proposta

Come posso modificare la descrizione presente nella pagina login? (Entra nel sito della scuola con le tue credenziali per gestire contenuti, visualizzare circolari e altre funzionalità)

### Motivazione e contesto

Mi servirebbe aggiungere una frase

**Comment by vcoopcsc** [comment]
Mi unisco alla richiesta, soprattutto perché alcune scuole tengono un sistema diverso per la lettura delle circolari che è al di fuori del tema e il fatto che il testo introduttivo abbia le circolari è un po' fuorviante.

**Comment by marcoverze93** [comment]
Ciao, 
il file da modificare è: common/acces-modal.php riga 37 puoi cambiare il testo.
