### ISSUE TITLE
Errori Clriteri di conformità C.SC.1.1 - C.SC.1.2 - C.SC.2.3 nonostante certo rispetto delle linee guida

### ISSUE THREAD

**Issue by domenicomadeo** [italia/design-scuole-wordpress-theme#377]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-scuole-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-scuole-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Buongiorno, ad oggi 21/06/2023, rilevo i seguenti errori sulla valutazione dei criteri di conformità, nonostante da analisi del codice sorgente del sito, tutte le linee guida sono rispettate.

C.SC.1.1 - COERENZA DELL'UTILIZZO DEI FONT (librerie di caratteri) - Il sito della scuola deve utilizzare i font indicati dalla documentazione del modello di sito della scuola.

C.SC.1.2 - LIBRERIA DI ELEMENTI DI INTERFACCIA - Il sito della scuola deve utilizzare la libreria Bootstrap Italia in una versione più recente di 1.6.

C.SC.2.3 - COOKIE - Il sito della scuola deve presentare cookie tecnici in linea con la normativa vigente.

URL: https://itisdalmine.edu.it/padigitale2026/
APP di verifica: scuole-2.3.4-Windows-x64
TEMA ATTIVO: Design Scuole ItaliaVersione: 2.3.2

allego screen che potrebbero aiutare all'analisi.

probabile problema di scansione sull'app o sul tema.

grazie per il supporto.

### Includi link o screenshot

![1](https://github.com/italia/design-scuole-wordpress-theme/assets/137275061/a296155a-5ca6-4b9d-b095-45ce213d46e1)

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

2.3.2

**Comment by marcoverze93** [comment]
Ciao,
se apri i singoli problemi ti indica le pagine del sito che hanno problemi ed è più facile aiutarti nel risolvere.
Guardando il sito della scuola non ho trovato l'informatica dei cookie tecnici, non so se quella vi manca.

**Comment by domenicomadeo** [comment]
Ciao grazie per la risposta,
adesso abbiamo passato il sito sotto il dominio principale e la pagina cookie è https://itisdalmine.edu.it/note-legali/cookie-policy/
dove spiego il tutto.
ora l'app mi da 100 :)

**Comment by domenicomadeo** [comment]
> Ciao, se apri i singoli problemi ti indica le pagine del sito che hanno problemi ed è più facile aiutarti nel risolvere. Guardando il sito della scuola non ho trovato l'informatica dei cookie tecnici, non so se quella vi manca.

Ciao grazie per la risposta,
adesso abbiamo passato il sito sotto il dominio principale e la pagina cookie è https://itisdalmine.edu.it/note-legali/cookie-policy/
dove spiego il tutto.
ora l'app mi da 100 :)
