### ISSUE TITLE
Rendere cliccabile tutto il contenuto della card dei "servizi"

### ISSUE THREAD

**Issue by vcoopcsc** [italia/design-scuole-wordpress-theme#378]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-scuole-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-scuole-wordpress-theme/blob/main/CONTRIBUTING.md)

### Proposta

Buongiorno, la proposta è quella di rendere cliccabile tutto il contenuto della card servizi e non sono il titolo come succede adesso.

### Motivazione e contesto

Abbiamo notato che le card dei servizi sono cliccabili solo nel titolo, mentre per altri contenuti, come ad esempio i documenti, i contenuti all'interno della card sono tutti cliccabili (titolo, immagine, ecc.). 
Per rendere più coerente la navigazione e più usabile il sito sarebbe meglio che anche per le card dei servizi accadesse come per le card dei documenti. 
![image](https://github.com/italia/design-scuole-wordpress-theme/assets/92174841/262bd5ae-51e6-4a8c-9f64-d2a837619d95)
![image](https://github.com/italia/design-scuole-wordpress-theme/assets/92174841/3b797360-d907-43b4-94b7-ce9a86509499)
Grazie in anticipo

**Comment by domenicomadeo** [comment]
sarebbe utile anche rendere un servisio selezionabile sia per famiglie che per il personale, ci sono servizi destinati ad entrambi!
