### ISSUE TITLE
Problema con icona Dirigenza Scolastica 

### ISSUE THREAD

**Issue by orporick** [italia/design-scuole-wordpress-theme#381]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-scuole-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-scuole-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Nella tipologia delle strutture viene usata "Dirigenza Scolastica", ma nell'associazione con l'icona svg viene cercata icona-dirigenza. Questo implica che nell'organizzazione le strutture Dirigenza Scolastica usano l'icona generale (la porta) invece di  quella specifica (la sedia).

### Su quale sisitema operativo stai riscontrando il problema?

Linux

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

2.3.2

**Comment by marcoverze93** [comment]
Ciao,
Noi abbiamo risolto creando una nuova tipologia struttura "Dirigenza" e questa usa come simbolo la sedia.
