### ISSUE TITLE
Richiesta sorgenti scss

### ISSUE THREAD

**Issue by giuseppemastrandrea** [italia/design-scuole-wordpress-theme#385]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-scuole-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-scuole-wordpress-theme/blob/main/CONTRIBUTING.md)

### Proposta

Ciao, avrei bisogno di personalizzare un po'gli stili (soprattutto i colori) del sito della mia scuola. Piuttosto che agire direttamente sul file minificato scuole.css vorrei sapere se ci sono dei file sorgenti che vengano poi buildati in qualche modo. Dove posso trovarli? Li potete pushare?

### Motivazione e contesto

È assolutamente necessaria per consentire un update consistente e pulito degli stili di partenza senza dover ricorrere per forza a degli override.

**Comment by marcoverze93** [comment]
Ciao
per personalizzare i colori noi abbiamo seguito questa strada: Aspetto->temi->personalizza->CSS aggiuntivo e abbiamo inserito le personalizzazioni dei colori.

**Comment by sviluppoRobyone** [comment]
Gli stili vengono ripresi dal repository https://github.com/italia/design-scuole-pagine-statiche
