### ISSUE TITLE
Impossibile caricare gli stylesheet da richiesta HTTPS

### ISSUE THREAD

**Issue by Downlosc** [italia/design-scuole-wordpress-theme#39]
Salve, mi sono reso conto che non vengono caricati i css e i js tramite richieste https. 

Ho questo errore "The page at '<URL>' was loaded over HTTPS, but requested an insecure script '<URL>'. This request has been blocked; the content must be served over HTTPS" 

Idee?

**Comment by webgrafia** [comment]
Puoi girarmi il link dell'ambiente in cui hai questo problema?
Qui siamo in https e non lo riscontriamo:
https://demoscuola.cloud/

**Comment by Downlosc** [comment]
Chiudo perchè risolto, un plugin andava in conflitto.
