### ISSUE TITLE
Come memorizza le informazioni il tema

### ISSUE THREAD

**Issue by mrcmarco90** [italia/design-scuole-wordpress-theme#393]
Vorrei capire come funziona la memorizzazione delle informazioni, quali ad esempio i dati inseriti nella scheda configurazione della scuola, le schede progetto o le schede dei servizi. Nello specifico volevo capire se fossero memorizzate a livello di database o in qualche file specifico.

**Comment by attiliopecora** [comment]
è tutto su database
