### ISSUE TITLE
Descrizione per la pagina Presentazione modificabile.

### ISSUE THREAD

**Issue by orporick** [italia/design-scuole-wordpress-theme#394]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-scuole-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-scuole-wordpress-theme/blob/main/CONTRIBUTING.md)

### Proposta

La pagina di Presentazione della Scuola ha una descrizione (La nostra scuola: identità, insegnamenti e storia) hard coded, non e' possibile cambiarla. 

### Motivazione e contesto

Tutte le sezioni del Menu scuola (luoghi, documenti, strutture etc) hanno una descrizione che puo' essere cambiata nell'interfaccia di configurazione, sarebbe utile per uniformita' che lo fosse anche la descrizione della pagina presentazione.

**Comment by marcoverze93** [comment]
Ciao
La modifica può essere fatta solo cambiando il codice del tema. Il file da modificare è template-parts/hero/page.php riga 14.

**Comment by sviluppoRobyone** [comment]
Confermiamo che nell'interfaccia di configurazione non c'è il campo. 
Risulta già possibile effettuare la variazione tramite la pagina Presentazione in Pagine, senza variare codice sorgente.
