### ISSUE TITLE
Breadcrumb non coerente

### ISSUE THREAD

**Issue by sviluppoRobyone** [italia/design-scuole-wordpress-theme#395]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-scuole-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-scuole-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Il consulente di una scuola ha segnalato difformità riguardo parte delle breadcrumb, ritenute non coerenti, riporto alcuni esempi ricevuti:

**Pagina "I luoghi della scuola"**
Al posto di "Home > Scuola > I luoghi" attualmente risulta "Home > Scuola"

**Pagina "Le carte della scuola"**
Al posto di "Home > Scuola > Le carte della scuola" attualmente risulta "Home > Scuola"

**Pagina "Organizzazione"**
Al posto di "Home > Scuola > Organizzazione" attualmente risulta "Home > Scuola"

**Pagina della singola persona**
Al posto di "Home > Scuola > Le persone > _Nome cognome_" attualmente risulta "Home > _Nome cognome_"

**Pagina della singola notizia**
Al posto di "Home > Novità > _Tipo post_ > _Titolo notizia_" attualmente risulta "Home > Novità > _Anno_ > _Mese_ > _Giorno_ > _Tipo post_ > _Titolo notizia_"

**Pagina del singolo progetto**
Al posto di "Home > Didattica > I progetti delle classi > _Tipologia progetto_ > _Titolo progetto_" attualmente risulta "Home > Didattica > Schede Progetti > _Tipologia progetto_ > _Titolo progetto_"

Attendiamo un riscontro

### Su quale sisitema operativo stai riscontrando il problema?

Windows, macOS, Android, iOS, Linux

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

2.3.3

**Comment by sviluppoRobyone** [comment]
Grazie mille @milesimarco, grazie alla tua pull request parte dei problemi riscontrati sono risolti! 

Che si riesca a trovare una soluzione anche riguardo i problemi di seguito riportati?

**Pagina "Le carte della scuola"**
Al posto di "Home > Scuola > Le carte della scuola" attualmente risulta "Home > Scuola > Documenti"
_(qui da punto di vista tecnico si sa che il content-type è documenti e non carte della scuola... come risolvere la questione?)_

**Pagine di archivio come quella dei tipi luogo**
Al posto di "Home > Scuola > Luoghi > _Tipo luogo_" attualmente risulta "Home > Luoghi > _Tipo luogo_"
_(questo accade anche per i tipi strutture, i tipi documenti, le categorie dei progetti)_

Pagina della singola persona
Al posto di "Home > Scuola > Le persone > _Nome cognome_" attualmente risulta "Home > _Nome cognome_"

**Pagina del singolo progetto**
Al posto di "Home > Didattica > I progetti delle classi > _Tipologia progetto_ > _Titolo progetto_" attualmente risulta "Home > Didattica > Schede Progetti > _Tipologia progetto_ > _Titolo progetto_"

**Comment by orporick** [comment]
Segnalo che alcune pagine della Scuola compaiono adesso nel breadcrumb in modo diverso, qualcuna come "La Scuola" qualcuna come "Scuola". Per esempio

Home/Scuola/Documenti
Home/La Scuola/La Storia

**Comment by sviluppoRobyone** [comment]
Avevo visto anche io, è necessario ricontrollare anche i titoli delle pagine in tal senso, perché alcune hanno bisogno di un ritocco, ho fatto una pull request in tal senso, anche se non va a risolvere tutto

**Comment by emanueleempix** [comment]
Problema da risolvere anche per la struttura interna a organizzazione.
Vi riporto una delle richieste del team del Dipartimento della trasformazione digitale: 
**Dalla voce del menù Scuola/Organizzazione si raggiunge una pagina con percorso diverso(Home/La
Scuola/Strutture), in cui ci sono dei link a pagine con percorso costruito differentemente.**
Quindi ad esempio in questo caso dovremmo avere le **url** e le **breadcrumb** con "**/organizzazione/**" al posto di "/struttura/".
Per gli url delle pagine interne ("tipologia-struttura" e "strutture") ho risolto con plugin "Permalink Manager", ma non riesco a cambiare url della pagina "/strutture". Anche per le breadcrumb non ho trovato ancora una soluzione.

**Comment by orporick** [comment]
Non sono sicuro di lavorare nella direzione giusta, ma facendo alcune prove sul mio sito sono andato a modificare le labels in inc/admin/documento.php e in inc/admin/struttura.php cambiando 'name' in modo opportuno ("Le carte della scuola" per i documenti e "Organizzazione" per le strutture. Questo sistema i breadcrumb, pero' cambia anche le etichette nel menu backend, anche se non credo sia un problema. Ho dovuto fare anche una piccola modifica a inc/breadcrumb.php.

Il problema probabilmente non e' risolto perche' cambiano solo le breadcrumb, non gli url delle pagine (che comunque non sempre possono essere allineati alla breadcrumb, o sbaglio? In diversi siti che vedo in giro per esempio compare nell'url tipologa-struttura e non strutture).

Non essendo per niente sicuro della soluzione non mi arrischio a proporre il codice, ma se volete dare un'occhiata il risultato e' temporaneamente sul sito

https://liceomarinelli.edu.it

Attendo anche io una soluzione al problema.

**Comment by Freegris** [comment]
Aggiungo a quanto indicato sopra queste segnalazioni relative ai breadcrumbs che ho ricevuto dal team territoriale per mancata validazione.

Mi viene segnalato che la pagina "/tipologia-circolare/circolari-per-alunni-e-famiglie/" non rispetta il criterio Buone pratiche
in quanto la posizione indicata dalla breadcrumb non è coerente con il contenuto della pagina, ad esempio dovrebbe essere
Home/Novità/Circolari/Circolari per alunni e famiglie/[pagina]. **La pagina relativa alla tipologia però risulta sotto Home/Circolari/Circolari per alunni e famiglie/**

Stesso problema per quanto riguarda le tipologie di servizi. Per esempio, la pagina "/percorsi-di-studio/scuola-primaria/" non rispetta il criterio Buone pratiche in quanto la posizione indicata dalla breadcrumb non è coerente con il contenuto della pagina, ad esempio dovrebbe essere Home/Servizi/Percorsi di studio/[pagina].  **La pagina relativa alla tipologia però risulta sotto Home/Scuola Primaria/**

Inoltre mi segnalano questo problema, che non sono riuscito a decifrare: la pagina '/la-scuola/" non rispetta il criterio Buone pratiche in quanto la posizione indicata dalla breadcrumb non è coerente con il contenuto della pagina, ad esempio dovrebbe essere Home/Scuola/[Storia]; inoltre, il titolo non è coerente con la sezione di riferimento ed il testo è quello relativo alla sezione "Panoramica".

Resto anche io in attesa di una risoluzione del problema o suggerimenti su come procedere.

**Comment by leosamuele221** [comment]
Aggiornato alla 2.5.1 il problema rimane delle pagine con scritto "Scuola" rimane
Anzi alla 2.4.0 in alcune pagine compariva "La Scuola" e in altre "Scuola" e basta, ora proprio in tutte "Scuola"
Non sarebbe nemmeno un problema se non fosse che in certe pagine il link di "Scuola" è rotto

Per esempio:
Qui il link è rotto: https://www.icsantamargheritame.edu.it/index.php/luogo/
Qui invece funziona: https://www.icsantamargheritame.edu.it/index.php/la-scuola/i-numeri-della-scuola/

Bisogna cercare di risolvere il prima possibile, non si riesce a chiudere il progetto
