### ISSUE TITLE
Breadcrumb eventi

### ISSUE THREAD

**Issue by vcoopcsc** [italia/design-scuole-wordpress-theme#399]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-scuole-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-scuole-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Se entro in un singolo evento mi aspetto di trovare nella breadcrumb prima del titolo dell'evento la sua tipologia, come avviene per gli altri content type

### Includi link o screenshot

Breadcrumb corretto nella pagina elenco degli eventi
<img width="1075" alt="image" src="https://github.com/italia/design-scuole-wordpress-theme/assets/92174841/cb7f53a8-d066-498c-94de-e9e5920c29b4">

Breadcrumb incompleto nella pagina del singolo evento, dove sparisce la tipologia e compare il nome del menu "Novità" che nello screen sopra non è presente
<img width="1062" alt="image" src="https://github.com/italia/design-scuole-wordpress-theme/assets/92174841/22b70310-bbdc-4435-bf40-f347d92e12c2">

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Microsoft Edge

### Che versione del tema stai utilizzando?

2.3.3.

**Comment by dersew88** [comment]
Confermo il medesimo problema, qualche soluzione è stata trovata??

**Comment by camillo860** [comment]
Io mi sono salvato in sessione il nome della sottocategoria, quando vado ad aprire l'evento posiziono il nome in modo corretto nella breadcrumb.

**Comment by camillo860** [comment]
Questo problema lo si trova pure nelle Circolari nel caso in cui si hanno più tipologie che non sono figlie di "Circolari".

**Comment by marcorubin** [comment]
Applicando gli aggiornamenti, il problema dovrebbe essere risolto... o quantomeno la mancanza del "pezzetto" Novità in Eventi

**Comment by feddar** [comment]
> Applicando gli aggiornamenti, il problema dovrebbe essere risolto... o quantomeno la mancanza del "pezzetto" Novità in Eventi

Ciao @marcorubin, io continuo a riscontrare il problema che "Novità" sparisce, anche nel sotto-menù "Notizie". Wordpress non segnala aggiornamenti del tema.
Secondo te/coi come posso fare?
Grazie.
