### ISSUE TITLE
live del tema 

### ISSUE THREAD

**Issue by zerooverflow** [italia/design-scuole-wordpress-theme#4]
Ciao Marco,
volevo sapere se sul tema sono in corso modifiche importanti.  Mi hanno riferito che la deadline è fine Novembre ma prima di iniziare a lavorarci su preferisco chiedere direttamente a te. Grazie.
Saluti.

**Comment by webgrafia** [comment]
ciao, ci siamo concentrati per chiudere in questi giorni i punti che, se modificati in seguito, hanno un impatto sui contenuti eventualmente inseriti.
Al momento modifiche importanti all'orizzonte non ce ne sono, ma sicuramente dopo la deadline  ci saranno ulteriori commit per bug fix / ottimizzazioni
