### ISSUE TITLE
Barra rosa priva di contenuti alla voce "contatti" in "Servizi"

### ISSUE THREAD

**Issue by vcoopcsc** [italia/design-scuole-wordpress-theme#400]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-scuole-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-scuole-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Se non inserisco i contatti in un servizio mi compare comunque la voce in frontend e una barra rosa priva di contenuti. 

### Includi link o screenshot

<img width="987" alt="image" src="https://github.com/italia/design-scuole-wordpress-theme/assets/92174841/ba470723-7d61-43e2-afc9-bd3c4cd26592">

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Microsoft Edge

### Che versione del tema stai utilizzando?

2.3.3

**Comment by sviluppoRobyone** [comment]
Essendo i contatti un campo obbligatorio nel modello, dovrebbero essere compilati.
Abbiamo proposto una modifica con un'opzione che evita la ripetizione dei contenuti

#367

**Comment by vcoopcsc** [comment]
@sviluppoRobyone è un campo obbligatorio ma se si aggancia il luogo i contatti sono già contenuti all'interno della card del luogo agganciato (se i campi sono valorizzati adeguatamente) quindi sarebbe una ripetizione.

**Comment by sviluppoRobyone** [comment]
I contatti della sede potrebbero essere diversi rispetto ai contatti della struttura, penso che per questo abbiano previsto i campi dedicati

**Comment by vcoopcsc** [comment]
Sono d'accordo, ci potrebbero essere dei contatti specifici per quel servizio (es. orientamento@, ecc.) come potrebbero essere gli stessi della struttura e della sede, nel qual caso secondo me il campo non dovrebbe comparire perché ridondante.
