### ISSUE TITLE
Disallineamento servizi correlati nella scheda servizi

### ISSUE THREAD

**Issue by vcoopcsc** [italia/design-scuole-wordpress-theme#401]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-scuole-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-scuole-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Se si correlano più servizi all’indirizzo di studi con diversi abstract i servizi correlati escono disallineati e non impaginati correttamente

### Includi link o screenshot

<img width="1113" alt="image" src="https://github.com/italia/design-scuole-wordpress-theme/assets/92174841/c564409d-3b6e-4c7a-bd50-6316eca6c616">

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Microsoft Edge

### Che versione del tema stai utilizzando?

2.3.3

**Comment by marcoverze93** [comment]
Ciao
noi abbiamo risolto così per il nostro sito: abbiamo modificato il file template-parts/servizio/card.php alla riga 5 togliendo h-100. In questo modo si allineano come vuoi te.

**Comment by marcoverze93** [comment]
Certo, la creo subito
