### ISSUE TITLE
Permettere citazioni più brevi di 70 caratteri

### ISSUE THREAD

**Issue by sviluppoRobyone** [italia/design-scuole-wordpress-theme#408]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-scuole-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-scuole-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Il tema prevede l'inserimento di una citazione breve (compresa tra 70 e 140 caratteri spazi inclusi) mentre le scuole con le quali collaboriamo ci forniscono descrizioni con lunghezza minore di 70 caratteri.

Da nostri test non sembrerebbero esserci controindicazioni a permettere valori più brevi (min 20 caratteri).
Si può allentare questo vincolo o ci sono delle problematiche a noi ignote al momento del test?

Ringrazio anticipatamente

### Su quale sisitema operativo stai riscontrando il problema?

Windows, macOS, Android, iOS, Linux

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

2.3.3

**Comment by zetareticoli** [comment]
Ciao, non ci sono problemi a ridurre il numero di caratteri minimo, potresti proporre la modifica con una PR?

**Comment by mrnooz** [comment]
nella 2.6.0. il limite è sempre 70 ma fortunatamente accetta tanti colpi di barra spazio
