### ISSUE TITLE
Struttura responsabile di un documento non e' necessariamente un ufficio

### ISSUE THREAD

**Issue by orporick** [italia/design-scuole-wordpress-theme#409]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-scuole-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-scuole-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Nel tipo Documenti sotto Contatti viene riportato "Ufficio responsabile del documento" laddove nella compilazione della scheda del documento si parla di "Strutture organizzative responsabili del Documento". In effetti non tutte le strutture sono Uffici (Dipartimenti, Commissioni etc). 

Credo si debba cambiare la dicitura in "Struttura responsabile del documento" in modo da rendere uniforme anche ad altri tipi (per esempio nei servizi l'etichetta e' proprio "Struttura responsabile del servizio")

### Su quale sisitema operativo stai riscontrando il problema?

Linux

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

2.4.0

**Comment by sviluppoRobyone** [comment]
Buongiorno,
condivido l'osservazione, segnalo però che questa etichetta è richiesta dall'architettura, nella scheda del content type documento [https://designers.italia.it/modelli/scuole/adotta-il-modello-di-sito-scolastico/definisci-architettura-e-contenuti/](url)
quindi più che cambiare in struttura bisognerebbe capire se è possibile filtrare in fase di selezione le strutture per mostrare solo gli uffici...

**Comment by orporick** [comment]
Grazie infinite, mi era sfuggito. Per la mia scuola sarebbe un problema limitare i documenti agli uffici, ci sono molte strutture organizzative che producono documenti (commissioni, dipartimenti, dirigente etc) ed è bene che rimanga l'associazione (anzi, sarebbe utile bidirezionale). A questo punto preferirei un'etichetta non del tutto corretta piuttosto che filtrare solo gli uffici. Grazie ancora per la segnalazione. (Domanda tecnica: devo ritirare il pull request in questo caso e chiudere il bug visto che non è un bug?)

**Comment by zetareticoli** [comment]
Esatto @orporick
