### ISSUE TITLE
Problema nella visualizzazione delle mappe

### ISSUE THREAD

**Issue by cesarelam** [italia/design-scuole-wordpress-theme#41]
Da un paio di giorni (la cosa è avvenuta dopo l'upgrade a Wordpress 5.5. ma non vedo come possa essere correlata) non visualizzo più le mappe sul sito della scuola (https://www.ioborrelli.edu.it/luogo/). Ho ispezionato il tutto in Google Chrome e in effetti mi segnala un problema. Posto gli screenshot:

<img width="556" alt="screenshot_01" src="https://user-images.githubusercontent.com/4965116/91703245-2e16b900-eb7a-11ea-81ba-9589966a82a7.png">

<img width="555" alt="screenshot_02" src="https://user-images.githubusercontent.com/4965116/91703260-31aa4000-eb7a-11ea-94d1-ccd655325c21.png">

Nell'interfaccia di amministrazione, nelle schede dei luoghi, la mappa viene correttamente visualizzata.

**Comment by webgrafia** [comment]
Hai scaricato l'ultimissima versione? prima dell'estate avevamo rilasciato dei fix per la mappa

**Comment by cesarelam** [comment]
Si Marco, funzionava tutto bene fino a un paio di giorni fa; avevo avuto un problema con il caricamento delle immagini/mappa ma con quel fix avevo risolto. Provo comunque a controllare.

**Comment by cesarelam** [comment]
Tra l'altro, sul sito di test che avevo messo su, tutto funziona regolarmente (https://www.ioborrelli.edu.it/new/luogo/)

**Comment by cesarelam** [comment]
Ho risolto Marco. Dipendeva dal plugin Contact Form 7 appena aggiornato, dato che ho verificato ieri un rallentamento pesante del sito, lo avevo disattivato, appena l'ho riattivato è tornato tutto a posto.

**Comment by astagi** [comment]
Nuova versione del tema disponibile (2.0.0)
