### ISSUE TITLE
Breadcrumb "Indirizzo di Studio" non coerente alla navigazione

### ISSUE THREAD

**Issue by AngelaMW04** [italia/design-scuole-wordpress-theme#411]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-scuole-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-scuole-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Utilizzando il tema WP riscontro il seguente problema:
Breadcrumb non coerente alla navigazione.
è Home / Indirizzo di Studio / Scuola dell'Infanzia / Indirizzo scuola dell’infanzia tempo pieno
Dovrebbe essere Home/Servizi/Percorsi di Studio/Indirizzo scuola dell’infanzia tempo pieno

Come posso risovere?

### Su quale sisitema operativo stai riscontrando il problema?

Windows, macOS, Android, iOS, Linux

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

2.4.0

**Comment by sviluppoRobyone** [comment]
Dovrebbero essere indirizzi, non percorsi di studio, giusto?

Poi, effettivamente condividiamo la domanda, qui si pone la questione di quale sia l'indirizzo principale di questi contenuti, poiché gli indirizzi di studio sono raggiungibili anche da didattica > offerta formativa.

Anche in questo caso la breadrumb è sbagliata:
è Home / Indirizzo di Studio / Scuola dell'Infanzia / Indirizzo scuola dell’infanzia tempo pieno
Dovrebbe essere Home / Offerta Formativa / Indirizzi di Studio / Indirizzo scuola dell’infanzia tempo pieno

Contando che le pagine sono le stesse, qual è la soluzione?

**Comment by orporick** [comment]
Ammetto di essere confuso. Nella struttura ci sono due tipi, gli Indirizzi e i Percorsi. 

Nel menu Servizi c'e' la voce "Percorsi di studio" che in realta' punta a "Indirizzi di studio". E' giusto cosi'?

**Comment by sviluppoRobyone** [comment]
Confermo, attualmente è così...

**Comment by orporick** [comment]
Grazie. Penso di aver risolto la maggior parte dei problemi di breadcrumb (anche relativi a #395) con una funzione filtro in breadcrumb.php che sostituisce alcune parole (Documenti con Carte della Scuola, per esempio). Non so se fare una pull request pero' perche' la mia piccola modifica sistema solo i breadcrumb, non si occupa dei permalink e sinceramente non ho capito se devono coincidere oppure no.

**Comment by camillo860** [comment]
@orporick ho lo stesso tuo problema, ti va di condividere la soluzione che hai fatto ?

**Comment by luigibugliani** [comment]
Mi accodo @orporick ; se la pubblichi o la comunichi te ne sarei grato.

**Comment by orporick** [comment]
Pulisco un po' il codice stasera e faccio una pull request in modo che siano visibili le modifiche che ho fatto ai due file breadcrumb.php e functions.php
