### ISSUE TITLE
Schede progetto non rispettano l'ordine annuale

### ISSUE THREAD

**Issue by carlettone96** [italia/design-scuole-wordpress-theme#417]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-scuole-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-scuole-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Quando clicco sulla voce "I progetti delle classi" i progetti vengono visualizzati nell'ordine errato.
Se provo ad inserire un progetto appartenente all'anno scolastico 23-24 questo non viene visualizzato nella pagina principale dei "I progetti delle classi" ma viene mostrato solamente dopo aver cliccato "Consulta i progetti degli scorsi anni".
La pagina principale dei "I progetti delle classi" mostra solo i progetti dell'anno scolastico 22-23.

### Includi link o screenshot

vedi https://www.ictrento1.it/scheda-progetto/

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Firefox

### Che versione del tema stai utilizzando?

2.4.0

**Comment by 1234j9tcswn** [comment]
Anch'io ho riscontrato lo stesso problema. Inoltre non viene letto l'anno scolastico nella pagina Panoramica del menu Didattica.

**Comment by Freegris** [comment]
Verificate se la pull #425 risolve. Ciao

**Comment by carlettone96** [comment]
Risolto.
Grazie mille.
