### ISSUE TITLE
Gli elementi immagine degli avatar di default non hanno l'attributo ALT

### ISSUE THREAD

**Issue by luigibugliani** [italia/design-scuole-wordpress-theme#418]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-scuole-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-scuole-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Ho notato dal controllo che gli elementi immagine degli avatar di default non hanno l'attributo ALT; anche se si tratta di elementi decorativi, in cui non va scritto alcun testo all'interno, però dovrebbero avere l'attributo da lasciare vuoto. Questo sarebbe sintatticamente corretto e inoltre migliorerebbe la valutazione del test.

### Includi link o screenshot

![immagine](https://github.com/italia/design-scuole-wordpress-theme/assets/119619030/32b6d666-f56f-48a4-a2dd-b33c83f6cb38)

### Su quale sisitema operativo stai riscontrando il problema?

Windows, macOS

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

2.4.0

**Comment by Simsimus** [comment]
Mi associo alla richiesta e confermo l'assenza dell'attributo ALT.

**Comment by zetareticoli** [comment]
ciao @luigibugliani, la funzione `dsi_get_img_from_id_url` accetta un parametro `$image_alt` quindi è possibile specificarlo dove serve nei templates
