### ISSUE TITLE
Spostamento della sezione Selezione Notizie dalla Configurazione

### ISSUE THREAD

**Issue by luigibugliani** [italia/design-scuole-wordpress-theme#419]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-scuole-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-scuole-wordpress-theme/blob/main/CONTRIBUTING.md)

### Proposta

Dalla configurazione della Home Page, posso scegliere come visualizzare le notizie, se in modo automatico, oppure sceglierle per metterle in evidenza, selezionando gli articoli che desidero.
Ora, in fase di produzione, immagino che se scelgo la selezione manuale, questa verrà fatta dal personale della Scuola, generalmente personale di segreteria, in quanto si tratta di attività corrente .

Il fatto che sia nella sezione configurazione, però, fa si che io debba dare l'accesso a tale sezione ( delicata per la gestione di tutto il sito) ad operatori che spesso non hanno grandi competenze informatiche. 

Non sarebbe meglio dividere dalla configurazione la possibilità di scelta degli articoli in evidenza?

Grazie

### Motivazione e contesto

Ridurre il rischio di errate modifiche alla configurazione del sito web da personale incaricato solo alla pubblicazione di notizie

**Comment by zetareticoli** [comment]
Ciao @luigibugliani, la tua segnalazione è sicuramente interessante e valida. Purtroppo, al momento, non ci è possibile modificare la parte di configurazione del tema, quindi devo chiudere questa issue.
