### ISSUE TITLE
Breadcrumb: gerarchia persone controintuitiva

### ISSUE THREAD

**Issue by LucaDiba** [italia/design-scuole-wordpress-theme#42]
Per visualizzare i dettagli di una persona è possibile accedervi mediante la pagina "Le persone", nella quale la breadcrumb è "Home / La Scuola / Persone".

Mi aspetterei, una volta aperta la pagina relativa ad una specifica persona, di ritrovarmi in "Home / La Scuola / Persone / Nome Cognome", tuttavia la breadcrumb mostra "Home / Nome Cognome".

**Comment by webgrafia** [comment]
Hai ragione, la mettiamo in coda di risoluzione, grazie del feedback
