### ISSUE TITLE
Errore nei pulsanti all'interno della sezione offerta formativa

### ISSUE THREAD

**Issue by Braswer** [italia/design-scuole-wordpress-theme#426]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-scuole-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-scuole-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Premetto che all'interno di configurazione/didattica ho scelto l'opzione: Indirizzi / Scuole

Nella sezione Offerta Formativa mi si presenta il seguente errore:
Per gli indirizzi scuola dell'infanzia e scuola primaria, cliccando sul più accanto al nome della scuola mi apre un pulsante rosso con il nome dell'indirizzo di studio e mi rimanda all'indirizzo di studio generico.
Mentre per la scuola secondaria si apre un pulsante blu con scritto "Per saperne di più" e mi manda correttamente alla pagina della scuola specifica.
Io vorrei che anche all'interno di scuola primaria e secondaria i pulsanti rimandassero alla scuola specifica.
Allego screenshot

### Includi link o screenshot

![screen1](https://github.com/italia/design-scuole-wordpress-theme/assets/46053465/82c0296f-85c6-48b1-98d2-8ed6e9be6f2f)
![screen2](https://github.com/italia/design-scuole-wordpress-theme/assets/46053465/2ecffdd3-49e9-46c4-81e7-70b9c04e4fa4)
![screen3](https://github.com/italia/design-scuole-wordpress-theme/assets/46053465/b01d4bcd-9349-49aa-ab48-57c549bf1c56)

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

2.3.2

**Comment by zetareticoli** [comment]
Ciao @Braswer, per funzionare correttamente devi associare un indirizzo di studio al relativo percorso, così che il pulsante rosso riporti il nome dell'indirizzo per poter accedere alla scheda associata.

**Comment by Braswer** [comment]
Grazie @zetareticoli , in realtà io avevo bisogno di ottenere il risultato opposto ma è tutto chiaro. Riporto però un piccolo bug, il percorso "scuola secondaria" è possibile cliccarlo solo da modifica rapida, altrimeti nella scheda dell'indirizzo di studio ti fa scegliere solo se standard o musicale e ciò porta al problema che vedete in foto per cui scuola secondaria non risulta collegato
