### ISSUE TITLE
Discordanza versione della licenza creative common

### ISSUE THREAD

**Issue by renatadurighello** [italia/design-scuole-wordpress-theme#428]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-scuole-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-scuole-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Le linee guida prevedono che nelle note legali sia dichiarata la licenza Creative Common 4.0, ma nei files del tema (nello specifico template-parts/single/bottom.php) è riportato 3.0.

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

2.4.0

**Comment by Freegris** [comment]
la #420 già riporta il refuso che stai segnalando.

**Comment by renatadurighello** [comment]
Grazie Giovanni. E avevo pure cercato prima di segnalare. Chiudo questa.
