### ISSUE TITLE
Formattazione dei link: sono uguali al resto del testo anziché sottolineati e colorati

### ISSUE THREAD

**Issue by IsabellaTarini** [italia/design-scuole-wordpress-theme#429]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-scuole-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-scuole-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Il testo dei link, anziché essere differenziato dal resto del testo in modo tipico, ovvero sottolineato e colorato, rimane uniforme al testo normale, differenziandosi da esso solo al passaggio del mouse.

Questo problema era già stato segnalato nell'[issue 143](https://github.com/italia/design-scuole-wordpress-theme/issues/143), e quindi risolto nella versione 2.1.4 del tema, ma adesso si ripresenta (almeno dalla versione 2.3.2, forse da prima, sicuramente  anche nella 2.4.0).

Mi pare succeda ovunque (per certo: nelle notizie, nei servizi e nei percorsi di studio).

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Chrome

### Che versione del tema stai utilizzando?

2.4.0

**Comment by Simsimus** [comment]
Mi associo alla richiesta e confermo il problema.

**Comment by sviluppoRobyone** [comment]
Abbiamo richiesto sottolineatura link a testo di contenuto pagine tramite pull request, non so se sia sufficiente a chiudere questa issue

**Comment by zetareticoli** [comment]
@sviluppoRobyone ogni modifica al file CSS deve passare per il [repository dei templates statici](https://github.com/italia/design-scuole-pagine-statiche), in quanto gli assets vengono presi da lì.

Puoi aprirne una in contemporanea?

**Comment by sviluppoRobyone** [comment]
Già aperta anche lì la pull request

**Comment by zetareticoli** [comment]
Solved by #444

**Comment by IsabellaTarini** [comment]
Gentilissimi, 
vedo che la richiesta è stata chiusa e marcata come "Solved by[ #444](https://github.com/italia/design-scuole-wordpress-theme/pull/444)" circa 1 mesa fa, ma io, utente con una leggera infarinatura di WordPress ma privo di competenze tecniche, ho installato l'ultima versione disponibile del tema, Versione 2.5.1, e continuo ad avere lo stesso problema segnalato.

Qualche volenteroso mi potrebbe rassicurare sul fatto che prima o poi (spero a breve) uscirà una versione del tema che includa il miglioramento che avete creato?
Grazie
