### ISSUE TITLE
Dichiarazione di Accessibilità per i siti web delle Istituzioni scolastiche

### ISSUE THREAD

**Issue by anitamaccio** [italia/design-scuole-wordpress-theme#43]
Salve, dobbiamo come Istituzione scolastica compilare il form Agid di cui all'oggetto, mi viene richiesto se le specifiche tecniche di riferimento utilizzate sono WCAG 2.0 o WCAG 2.1 e se è conforme alla Decisione di esecuzione UE 2018/1523.
Potete aiutarmi? Non ho trovato nessuna indicazione sulle WCAG utilizzate nel sito...
Grazie e cordiali saluti
Anita Macciò

**Comment by anitamaccio** [comment]
Aggiungo che ho provato a fare un check su http://www.validatore.it/vamola_validator/checker/index.php ma con qualsiasi pagina mi dice che La memoria disponibile non è sufficiente a processare una pagina di queste dimensioni.
Ho provato alcune pagine su su https://validator.w3.org/ e mi appaiono tutta una serie di warning e di error, che non mi sembrano dovuti alla redazione ma alla progettazione...

**Comment by anitamaccio** [comment]
La dichiarazione è da fare entro domani, 23 settembre: https://www.agid.gov.it/it/design-servizi/accessibilita/dichiarazione-accessibilita
Io ho trovato anche questo https://achecker.ca/checker/index.php ma mi dà comunque errori anche su WCAG 2.0 A, per cui metterò che il sito non è conforme e che abbiamo in programma di metterlo a posto, se non mi date altre indicazioni in tempi utili.

**Comment by webgrafia** [comment]
Buondì, 
abbiamo rilasciato alcuni fix che risolvono i problemi accessibilità (Linee Guida: WCAG 2.0 (Level AA)).
Prova ad aggiornare il tema
Ho testato l'ambiente demo presente su  https://demoscuola.cloud/ con achecker e viene validato

**Comment by anitamaccio** [comment]
Ho aggiornato il tema, ma su https://achecker.ca/checker/index.php permane un errore sulla nidificazione degli header nel titolo del post:

2.4 Navigable: Provide ways to help users navigate, find content, and determine where they are.
Success Criteria 2.4.6 Headings and Labels (AA)
Check 37: Header nesting - header following h1 is incorrect.
Repair: Modify the header levels so only an h1 or h2 follows h1.
Error Line 354, Column 25:
<h1>Pubblicazione Graduatorie d&rsquo;Istituto definitive personale docente</h1>

Ho provato a testare il sito demo, e dà gli stessi errori di nidificazione degli header:
https://demoscuola.cloud/evento/feste-pasquali/

non ci sono errori solo con le specifiche WCAG 2.0 (Level A)

**Comment by webgrafia** [comment]
RIsolta la nidificazione nella pagina evento, ci sono sicuramente altri fix in pagine interne che faremo nei prossimi giorni

**Comment by anitamaccio** [comment]
ok, grazie!
Anita
