### ISSUE TITLE
Richiesta inserimento in publiccode.yml

### ISSUE THREAD

**Issue by giuseppemastrandrea** [italia/design-scuole-wordpress-theme#433]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-scuole-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-scuole-wordpress-theme/blob/main/CONTRIBUTING.md)

### Proposta

Ciao, vorrei inserire il nominativo della mia scuola nel file publiccode.yml. Il nome è ITT Panetti Pitagora, il codice meccanografico è batf230001. 

### Motivazione e contesto

Non faccio una pull request perchè ho forkato e modificato un po'di roba sul repo originario. Qui il repo forkato: https://github.com/giuseppemastrandrea/design-scuole-wordpress-theme

**Comment by astagi** [comment]
Aggiunto con piacere @giuseppemastrandrea grazie mille.
