### ISSUE TITLE
R.SC.1.1 - VOCABOLARI CONTROLLATI - Il sito della scuola deve utilizzare argomenti forniti dal modello di sito scuola. - Errore

### ISSUE THREAD

**Issue by delta-informatica** [italia/design-scuole-wordpress-theme#437]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-scuole-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-scuole-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

R.SC.1.1 - VOCABOLARI CONTROLLATI - Il sito della scuola deve utilizzare argomenti forniti dal modello di sito scuola. Errore

Durante il test di validazione mi continua a fare errore sui vocabolari, ma non riesco a capire il motivo di questo errore. 
Il sito è https://icsavona3.edu.it/ 
Ho verificato e i data element che richiede nella documentazione ci sono e le parole della scuola negli argomenti sono presenti. 

### Includi link o screenshot

![errore](https://github.com/italia/design-scuole-wordpress-theme/assets/142393845/e182e187-43ce-4066-a80f-fb8b175dcd85)

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Chrome

### Che versione del tema stai utilizzando?

2.4.0

**Comment by camillo860** [comment]
c'è un glossario da rispettare 
https://docs.google.com/spreadsheets/d/1MoayTY05SE4ixtgBsfsdngdrFJf_Z2KNvDkMF3tKfc8/edit#gid=2135815526

**Comment by delta-informatica** [comment]
Ma questi termini devono essere utilizzati anche sui titoli delle notizie? Perchè io li ho inseriti nei servizi, e negli argomenti come tag.

**Comment by delta-informatica** [comment]
Mi da questo errore qui nel validatore ERROR https://icsavona3.edu.it/: TimeoutError: Navigation timeout of 30000 ms exceeded

**Comment by camillo860** [comment]
Se ho capito bene, devi usarli nei tag.  L'errore di Timeout forse è dovuto alla tua connessione?

**Comment by Braswer** [comment]
Ciao @delta-informatica , praticamente devi fare in modo che tutti gli argomenti nella lista dei tag (che puoi trovare sotto la voce Argomento) appartengano alla lista indicata prima da camillo. Puoi usarne di meno ma non puoi usarne diversi da quelli nella lista.
