### ISSUE TITLE
#Socialmedia

### ISSUE THREAD

**Issue by Cate55** [italia/design-scuole-wordpress-theme#45]
Buongiorno anche se disabilito la visualizzazione delle icone social, queste vengono mostrate ugualmente. Per non farle visualizzare elimino i link, ma la scritta "Seguici su:" rimane ugualmente nel footer.
Devo intervenire sulla variabile if($show_socials)?
Grazie sempre per il prezioso supporto.
![socialmedia1](https://user-images.githubusercontent.com/9642253/96546808-3900e680-12ab-11eb-8b04-2da24f333b26.png)
![socialmedia2](https://user-images.githubusercontent.com/9642253/96546811-3a321380-12ab-11eb-8ab5-635ca15f7aeb.png)

**Comment by webgrafia** [comment]
ciao Caterina, grazie della segnalazione, ho corretto il bug. (header.php e footer.php)
