### ISSUE TITLE
Breadcrumb e validazione sito

### ISSUE THREAD

**Issue by camillo860** [italia/design-scuole-wordpress-theme#450]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-scuole-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-scuole-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Buongiorno durante la fase di validazione della PA mi stanno contestando i "Breadcrumb", alcuni sono stati già risolti come ad esempio "La scuola" o "Organigramma" .
Adesso mi hanno contestato i breadcrumb:

- delle sottocategorie delle circolari, ad esempio "Home/ Le Circolari / Sede XX " quando dovrebbe essere "Home / Notizie / Le Circolari / Sede XX "
- dei percorsi di studi  da Home/Percorsi di studio/Scuola dell'infanzia/ABC" quando dovrebbe essere "Home/Servizi/Percorsi di studio/Scuola dell'infanzia/ABC "
- le sottocategorie delle notizi ad esempio "Home / Notizie / Sede XX " quando dovrebbe essere "Home/Novità/Le Notizie/Sede XX "
Controllando la parte della Didattica => Offerta formativa  anche li il Breadcrumb è sbagliato ma riflettendo su quel percorso
"Home/ percorsi di studio / Scuola secondaria di primo  grado / ABC " non è sbagliato perché a quella pagina si può arrivare anche dalla tipologia di scuola. 

Come avete risolto il problema? Io ho seguito Breadcrumb fix #421 . Avete avuto problemi di validazione? 

### Su quale sisitema operativo stai riscontrando il problema?

macOS

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

2.4.0

**Comment by astagi** [comment]
@camillo860 sulla 2.5.0 questo problema dovrebbe essere risolto

**Comment by Alfredo3D** [comment]
Buongiorno,
come è stato risolto questo problema segnalato?

Didattica => Offerta formativa => Per saperne di più,  gli asseveratori segnalano il problema che viene rimandato ai percorsi di studio ritrovandosi la breadcrumb tipo:

Home / percorsi di studio / scuola primaria

come si puo risolvere? 
Grazie
