### ISSUE TITLE
Versione di php consigliata

### ISSUE THREAD

**Issue by sagredo-dev** [italia/design-scuole-wordpress-theme#451]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-scuole-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-scuole-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Vorrei sapere qual è la versione di php consigliata, non avendo trovato l'informazione da nessuna parte. E' necessario restarre sulla 7.4 oppure la piattaforma è compatibile anche con la 8.2?

grazie per ogni risposta

### Su quale sisitema operativo stai riscontrando il problema?

Windows, Linux

### Su quale browser stai riscontrando il problema?

Chrome

### Che versione del tema stai utilizzando?

2.4

**Comment by leosamuele221** [comment]
Io uso la 8.0 senza nessun problema
Versione tema: 2.5.1
