### ISSUE TITLE
Errore visualizzazione luoghi

### ISSUE THREAD

**Issue by Cyberciro** [italia/design-scuole-wordpress-theme#452]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-scuole-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-scuole-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Cliccando sui luoghi creati sia da backend che lato sito viene riportato errore wp

### Includi link o screenshot

![Immagine 2023-09-02 192751](https://github.com/italia/design-scuole-wordpress-theme/assets/143355503/f72145e5-023f-4c5f-b254-a6e72bda0319)

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Chrome

### Che versione del tema stai utilizzando?

2.4.0

**Comment by sviluppoRobyone** [comment]
Abbiamo analizzato e corretto un bug che impediva il caricamento delle informazioni, creata PR
