### ISSUE TITLE
Visualizzazione non corretta della voce "Strutture dipendenti"

### ISSUE THREAD

**Issue by duidot** [italia/design-scuole-wordpress-theme#455]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-scuole-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-scuole-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Buongiorno a tutti, nel file single-struttura.php alla riga 265 c'è un errore che non fa visualizzare correttamente la voce "Strutture dipendenti" `echo '<h3 class="h6">".__("Strutture dipendenti", "design_scuole_italia")."</h3>';` le doppie virgolette dopo il > e prima del < dovrebbero essere singoli apici `echo '<h3 class="h6">'.__("Strutture dipendenti", "design_scuole_italia").'</h3>';`

### Su quale sisitema operativo stai riscontrando il problema?

Windows, macOS, Android, iOS, Linux

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

2.4.0

**Comment by astagi** [comment]
Grazie @duidot intanto il fix è presente su main, rilasceremo a breve una versione nuova.
