### ISSUE TITLE
Visualizzazione spezzata - errore in template-parts/home/didattica-cicli-indirizzi.php

### ISSUE THREAD

**Issue by IronRunes** [italia/design-scuole-wordpress-theme#456]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-scuole-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-scuole-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

A linea 27 del suddetto file c'è una porzione di codice duplicato che "rompe" la visualizzazione, sia in homepage che nella pagina "Didattica". 
All'apparenza, la porzione di codice duplicato termina a linea 32.

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

2.5.0

**Comment by astagi** [comment]
Grazie @IronRunes indaghiamo sulla porzione di codice, in effetti è molto strano.

**Comment by astagi** [comment]
@IronRunes su main adesso è presente il fix, se può confermarmi che funziona chiudiamo il bug. Grazie mille!

**Comment by IronRunes** [comment]
@astagi tutto perfetto, grazie!

**Comment by astagi** [comment]
di niente @IronRunes grazie della segnalazione.
