### ISSUE TITLE
Fornire un riepilogo generale del problema

### ISSUE THREAD

**Issue by SCLService** [italia/design-scuole-wordpress-theme#462]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-scuole-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-scuole-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Nei controlli viene segnalato l'errore 
La pagina “https://SITOSCUOLA.edu.it/indirizzo-di-studio/musicale/” non rispetta il criterio Buone pratiche in quanto la posizione indicata dalla breadcrumb non è coerente con il contenuto della pagina, ad esempio dovrebbe essere Home/Servizi/Percorsi di studio/[pagina].

In pratica c'è una discrepanza nella nuova denominazione del sistema come "Percorsi di Studio" prima nota come "indirizzi di studio"
Andrebbe aggiornato il sistema in modo che gli "indirizzi di studio" diventino tutti come "percorsi di studio"

### Includi link o screenshot

![percorsi-studio](https://github.com/italia/design-scuole-wordpress-theme/assets/144935179/80259b8a-fa97-48ba-aa43-20d5acb01553)

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

2.5.1

**Comment by Freegris** [comment]
Questo errore l'avevo segnalato, io l'ho risolto così come ho proposto nella pull request #463
modifica manualmente e verifica. Per me ora è ok.

**Comment by zetareticoli** [comment]
Resolved in #463
