### ISSUE TITLE
Breadcrumb Novità > Le notizie

### ISSUE THREAD

**Issue by Simsimus** [italia/design-scuole-wordpress-theme#465]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-scuole-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-scuole-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Diversi asseveratori riportano come errore "non rispettano il criterio Buone pratiche" tutti gli articoli che sono collegati ad una tipologia diversa da "Notizie".
Ad esempio se si pubblica un articolo nella tipologia "Avvisi" nel breadcrumb comparirà:
Home > Novità > Avvisi > titolo articolo
invece per loro dovrebbe comparire
Home > Novità > Le notizie > Avvisi > titolo articolo
In pratica tutti gli articoli devono riportare nel breadcrumb la prima parte fissa "Home > Novità > Le notizie" e poi il dettaglio della tipologia di appartenenza dell'articolo stesso.

Auspico che tale problema possa essere risolto quanto prima altrimenti le scuole non potranno avere un sito approvato.
Grazie

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

2.5.1

**Comment by Freegris** [comment]
Ciao, non è un bug questo che segnali ma un errore nell'impostazione delle tipologie articoli che devono essere in questo caso della categoria "Le notizie".

**Comment by Freegris** [comment]
Corretto, il tema non c’entra, toglierei quindi l’etichetta bug, metti magari help wanted. Ciao

**Comment by Simsimus** [comment]
Già che ci sono approfitto della tua disponibilità per chiederti un altro chiarimento. 
Nella fase dei controlli spesso viene rilevato come errore il fatto che nelle Circolari il tema non mostra se quella circolare appartiene alla tipologia "Circolari per alunni e famiglie" oppure "Circolari per docenti e personale ATA".
In effetti anche se viene flaggata la tipologia, andando poi nel frontend nell'elenco delle circolari o in una circolare specifica, non si evince a nessuna parte la tipologia di appartenenza. Per caso hai una soluzione anche per questo?
Grazie per la tua disponibilità

**Comment by Freegris** [comment]
a mio parere la parola furbizia non c'entra tanto, è questione di assolvere alle buone pratiche indicate e trovare soluzioni pratiche ed efficaci. Il dato ci deve essere ed essere visibile, non importa dove, quello è uno dei posti migliori anche perchè così subito sono individuabili nella sezione tipologie prima di entrare nella circolare. All'interno la posizione nella pagina è ideale.

**Comment by Simsimus** [comment]
Sono pienamente d'accordo con te, al punto che metterei in abstract automaticamente la tipologia selezionata al check (magari si potesse automatizzare).
Chiedo scusa qualora il temine "furba" fosse stato interpretato in maniera diversa da quello che intendevo, in quanto io mi riferivo al fatto la che tua soluzione fosse intelligente e di sicuro risolutiva.
Grazie ancora ;)
