### ISSUE TITLE
Problema elenco firmatari

### ISSUE THREAD

**Issue by Riccardocici** [italia/design-scuole-wordpress-theme#47]
Ciao, grazie alla community per aver rilasciato il tema.
Ho riscontrato un problema con lo scaricamento del file csv dell'elenco dei firmatari, una volta scaricato e aperto il file con excel, il documento presenta il solo titolo "Firmatari" ma il resto del foglio è vuoto. Avete soluzioni?

Grazie mille per la disponibilità.

**Comment by sdi-sw** [comment]
Ciao, mi associo alla segnalazione del collega.
In tutte le prove che ho condotto l'elenco dei firmatari visualizzato è corretto mentre il documento che viene scaricato presenta il solo titolo "Firmatari".

Aggiungo il suggerimento di inserire nell'elenco che viene prodotto (possibilmente in ordine alfabetico) tutti i destinatari della circolare per visualizzare non solo chi e quale feedback è stato dato ma anche - e soprattutto - chi non ha dato alcun feedback !!!
Ringrazio gli sviluppatori per l'ottimo lavoro svolto.
