### ISSUE TITLE
Mostrare la tipologia delle Circolari (criterio Buone Pratiche)

### ISSUE THREAD

**Issue by Simsimus** [italia/design-scuole-wordpress-theme#471]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-scuole-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-scuole-wordpress-theme/blob/main/CONTRIBUTING.md)

### Proposta

Nella fase dei controlli spesso viene segnalato come errore il fatto che nelle Circolari il tema non mostra se una circolare appartiene alla tipologia "Circolari per alunni e famiglie" oppure "Circolari per docenti e personale ATA".
In effetti, anche se viene flaggata la tipologia, andando nel frontend nell'elenco delle circolari o in una circolare specifica, non si evince la tipologia di appartenenza. 
Attualmente l'unica soluzioni fattibile, suggerita da @Freegris, è quella di inserire manualmente nell'abstract la tipologia.
Sarebbe possibile creare un automatismo come da screen allegato? In pratica se un utente seleziona una o più tipologie, quest'ultime potrebbero comparire sia all'interno della circolare che nell'anteprima.
Dite che è fattibile?

![Circolare con tipologia](https://github.com/italia/design-scuole-wordpress-theme/assets/108821309/fe5c03ff-f07c-460b-a811-396a85421c70)

### Motivazione e contesto

Risoluzione delle segnalazioni fatte dagli asseveratori in base ai criteri "Buone Pratiche".

**Comment by Cyberciro** [comment]
Ho avuto la stessa contestazione ed ho risulto anche io scrivendo nell'abstract
