### ISSUE TITLE
link rotti breadcrumbs

### ISSUE THREAD

**Issue by leosamuele221** [italia/design-scuole-wordpress-theme#473]
**Prerequisiti**
 Ho già [cercato](https://github.com/italia/design-scuole-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
 Ho letto le [linee guida di contribuzione](https://github.com/italia/design-scuole-wordpress-theme/blob/main/CONTRIBUTING.md)
 
**Descrivi il problema**
In alcune pagine dei sottomenu Scuola, Servizi, Novità, Didattica i link nelle breadcrumbs portano a errore 404
Per esempio nel menu Scuola gli errori si presentano in Luoghi, Organizzazione e Le carte della scuola

Qui il link è rotto: https://www.icsantamargheritame.edu.it/index.php/luogo/
Qui invece funziona: https://www.icsantamargheritame.edu.it/index.php/la-scuola/i-numeri-della-scuola/

**Includi link o screenshot**
No response

**Su quale sisitema operativo stai riscontrando il problema?**
Windows, macOS, Android, iOS, Linux

**Su quale browser stai riscontrando il problema?**
Qualsiasi

**Che versione del tema stai utilizzando?**
2.5.1

**Comment by zetareticoli** [comment]
Ciao @leosamuele221 ,

il link che tu definisci "rotto" lo visualizzo correttamente 🤔

Piuttosto la URL è un po' strana: `/index.php/luogo/` non è proprio ottimale (anche per il SEO)

**Comment by zetareticoli** [comment]
Ho provato i due links da te citati, ma funzionano entrambi.
