### ISSUE TITLE
Destinatari circolari

### ISSUE THREAD

**Issue by xam8re** [italia/design-scuole-wordpress-theme#487]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-scuole-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-scuole-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Il problema che dovrebbe essere risolto con questo pull: https://github.com/italia/design-scuole-wordpress-theme/pull/467 
si ripresenta con versione 2.5.1.
Da utente admin ora (a differenza della versione 2.3.3) vedo comunque la circolare ma, da utente loggato (sottoscrittore) in bacheca non e'presente la circolare ed andando sul sito vengo automaticamente sloggato. 
Vorrei segnalare anche, verificato anche su altre scuole con lo stesso tema, che le circolari private sono visibili a chiunque semplicemente premendo "genera pdf". 

![WhatsApp Image 2023-10-16 at 18 45 26](https://github.com/italia/design-scuole-wordpress-theme/assets/8983338/3cc47d86-4bae-45c0-a6f7-161fddb9ace5)
questi sono i ruoli associati alla circolare: 
![image](https://github.com/italia/design-scuole-wordpress-theme/assets/8983338/6db3b032-9282-4996-b135-e0224949fe80)

### Su quale sisitema operativo stai riscontrando il problema?

Windows, macOS, Linux

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

2.5.1

**Comment by rcoopcsc** [comment]
@xam8re la versione 2.5.1 che stai utilizzando non ha il fix a cui ti riferisci, per testarne le funzionalità devi installare dal [main](https://github.com/italia/design-scuole-wordpress-theme/archive/refs/heads/main.zip) oppure attendere la prossima release.

**Comment by xam8re** [comment]
> @xam8re la versione 2.5.1 che stai utilizzando non ha il fix a cui ti riferisci, per testarne le funzionalità devi installare dal [main](https://github.com/italia/design-scuole-wordpress-theme/archive/refs/heads/main.zip) oppure attendere la prossima release.

Ok. Riguardo il fatto del pdf che scavalca le permission? Apro un altro ticket?

**Comment by rcoopcsc** [comment]
> > @xam8re la versione 2.5.1 che stai utilizzando non ha il fix a cui ti riferisci, per testarne le funzionalità devi installare dal [main](https://github.com/italia/design-scuole-wordpress-theme/archive/refs/heads/main.zip) oppure attendere la prossima release.
> 
> Ok. Riguardo il fatto del pdf che scavalca le permission? Apro un altro ticket?

@xam8re ho corretto il codice nella PR. Grazie per la segnalazione del problema!
