### ISSUE TITLE
Ordine di visualizzazione delle strutture

### ISSUE THREAD

**Issue by scal1974** [italia/design-scuole-wordpress-theme#497]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-scuole-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-scuole-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Buongiorno, vorrei sapere se è possibile stabilire l’odine di visualizzazione delle strutture. Mi spiego meglio nella voce organizzazione - Scuole/Istituti posso decidere l’ordine di visualizzazione dei plessi?

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Chrome

### Che versione del tema stai utilizzando?

2.5.1

**Comment by marcoverze93** [comment]
Ciao,
dopo alcuni test abbiamo capito che l'ordine è cronologico secondo la data con cui aggiungi la struttura (e quella di pubblicazione) dalla prima creata all'ultima. Pertanto per riordinarle ti conviene crearne nuove tenendo conto questo criterio.

**Comment by scal1974** [comment]
Grazie per il contributo.
