### ISSUE TITLE
Linee guida all'istallazione su wordpress tema design scuola

### ISSUE THREAD

**Issue by 33tino** [italia/design-scuole-wordpress-theme#5]
Seguo il vostro lavoro, complimenti sinceri.
Avrei bisogno di capire come istallare il tema design scuola.
Ho provato ad istallarlo come nuovo tema, ma mi restituisce degli errori. 
Sicuramente tralascio qualcosa, ma con qualche indicazione precisa forse risolvo.
Grazie!

**Comment by francescozaia** [comment]
Ciao @33tino, la documentazione è in fase di stesura in questi giorni, se c'è qualcosa che non è chiaro è il momento migliore per farcelo sapere, così che la miglioriamo per tutta la comunità. Se ci fai sapere che errori hai, possiamo magari darti una mano. cc. @webgrafia

**Comment by 33tino** [comment]
*Grazie per la risposta veloce.*
*La procedura che ho adottato:*
*da wordpress ho istallato il nuovo thema la cosa strana è che Wordpress mi
dice *Scompattamento del pacchetto…Installazione del tema…Tema installato
correttamente.
Ma quando vado a vedere l'anteprima mi esce questo errore:

*Warning*: require(vendor/CMB2/init.php): failed to open stream: No such
file or directory in
*/home/mhd-01/www.tino33.net/htdocs/wp-content/themes/design-scuole-wordpress-theme-master/inc/cmb2.php
<http://www.tino33.net/htdocs/wp-content/themes/design-scuole-wordpress-theme-master/inc/cmb2.php>*
on
line *3*

*Fatal error*: require(): Failed opening required 'vendor/CMB2/init.php'
(include_path='.:/usr/share/php') in
*/home/mhd-01/www.tino33.net/htdocs/wp-content/themes/design-scuole-wordpress-theme-master/inc/cmb2.php
<http://www.tino33.net/htdocs/wp-content/themes/design-scuole-wordpress-theme-master/inc/cmb2.php>*
on
line *3*

Il sito sta avendo problemi tecnici. Controlla la casella di posta
dell'amministratore del sito per istruzioni.

il link:www.tino33.net

Lascio l'errore per un paio di giorni.

WP versione 5.2

PHP  7.0

Grazie!

Il giorno mer 4 dic 2019 alle ore 20:35 Francesco Zaia <
notifications@github.com> ha scritto:

**Comment by webgrafia** [comment]
ciao @33tino 
il problema che hai è legato al fatto che non hai scaricato i submoduli del tema.
Puoi farlo eseguendo questi comandi git:

git clone https://github.com/italia/design-scuole-wordpress-theme.git
cd design-scuole-wordpress-theme/
git submodule init
git submodule update

fatto questo avrai il tema completo, e non dovrebbe darti problemi

**Comment by 33tino** [comment]
scusa la mia ignoranza ,ma non ho capito come utilizzarle e come mai non si
trovano nella cartella del thema?

Il giorno gio 5 dic 2019 alle ore 09:53 Marco Buttarini <
notifications@github.com> ha scritto:

**Comment by webgrafia** [comment]
Il tema ha una dipendenza con un repository esterno (CMB2) che permette la gestione dei campi custom dei diversi post type.
Essendo questo un repository in evoluzione, invece di scaricare CMB2 sul tema abbiamo collegato il tema al github del repository CMB2, così da avere sempre l'ultima versione di CMB2 aggiornata.
In questo modo ogni fix aggiunto a CMB2 è automaticamente incluso anche nel tema.

Il problema di questo approccio è che cliccando su "scarica" nella pagina github del tema non viene scaricato anche quel modulo.
Al momento quindi l'unico modo è usare git per scaricare il tema con le sue dipendenze.
Esistono diversi client git che ti permettono di farlo, dipende dal sistema operativo che utilizzi e dalla tua dimesticheza con la riga di comando.
https://www.hostinger.com/tutorials/best-git-gui-clients/

Stiamo nel frattempo lavorando per automatizzare la creazione di uno zip che includa automaticamente tutto, ma ci vorrà ancora qualche giorno

**Comment by 33tino** [comment]
E se provassi ad istallare il plug in Description CMB2  e successivamente il thema in questione?

**Comment by 33tino** [comment]
Comunque, preferisco aspettare  istruzioni dettagliate in merito.

**Comment by WebmasterAlmerico** [comment]
Buongiorno Signori,
vorrei precisare agli sviluppatori che, contrariamente a quanto accade in azienda o nelle PA tradizionali, nelle scuole non sempre la gestione dei siti web è affidata a professionisti, ma, spesso, al buon cuore di docenti (anche di Italiano) che, tra le mille cose, hanno anche l'onore/onere di gestire il sito scolastico.
Chiedo, con la massima cortesia del caso, di far sì che l'installazione del template non si discosti troppo dalle installazioni tradizionali.
Ringrazio
Carlo Posenato

**Comment by 33tino** [comment]
Buongiorno,
sono curioso di testare il thema, attendo con pazienza le istruzioni.
Grazie!

**Comment by 33tino** [comment]
Sono riuscito ad istallarlo!
Sto testando...ben fatto!
https://www.tino33.net

**Comment by webgrafia** [comment]
Bene ;)

**Comment by Pino2016** [comment]
buongiorno, ma esiste una guida , istruzione per uso del template per la scuola?

**Comment by 33tino** [comment]
Buongiorno, cosa devi fare esattamente?

Il dom 26 feb 2023, 09:23 Pino2016 ***@***.***> ha scritto:

**Comment by Pino2016** [comment]
in pratica io ho un sito della scuola su joomla, ma ora vorrei usare il template ministeriale wordpress per me è una novità, avrei bisogno di una guida pratica, qualcosa ho gia fatto , ma vorrei maggiori istruzioni, se esiste una guida passo passo. Grazie

**Comment by 33tino** [comment]
Di solito non lo faccio, chiamami 3386569076

Il dom 26 feb 2023, 10:08 Pino2016 ***@***.***> ha scritto:
