### ISSUE TITLE
Problema aggiornamento - Versione 2.6.0 

### ISSUE THREAD

**Issue by scal1974** [italia/design-scuole-wordpress-theme#507]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-scuole-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-scuole-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Buongiorno ho installato un tema child con il nuovo aggiornamento 2.6.0 ma l'anteprima in tempo reale è incompleta. Allego screen
![screenshot-www iisolivetipanettalocri edu it-2023 10 28-10_46_59](https://github.com/italia/design-scuole-wordpress-theme/assets/114990331/f4f30adf-cb6d-46c0-88cc-20e687e798de)

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Chrome

### Che versione del tema stai utilizzando?

2.5.1

**Comment by Simsimus** [comment]
Buongiorno,
credo che il problema sia causato dalla stessa issue #508 che ho aperto poco fa'.
Saluti

**Comment by scal1974** [comment]
Buongiorno cosa posso fare per risolvere il problema e poter installare l'aggiornamento?

**Comment by Simsimus** [comment]
Fin quando non verrà posto rimedio all'errore segnalato nella issue #508, non ti conviene fare l'aggiornamento visto che nel tuo caso le ripercussioni sono direttamente in home e credo dipendano da qualche circolare (con errore) che il sistema vorrebbe visualizzare sulla home.
