### ISSUE TITLE
Creazione di un luogo con l'inserimento di una mappa

### ISSUE THREAD

**Issue by emmeellebi** [italia/design-scuole-wordpress-theme#509]
### Prerequisiti

- [x] Ho già [cercato](https://github.com/italia/design-scuole-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-scuole-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Quando creo un nuovo luogo, alla voce Posizione GPS mi viene chiesto di cliccare sulla lente d'ingrandimento e cercare l'indirizzo del nuovo luogo. Ho provato, ma non parte la ricerca dell'indirizzo e nella pagina del luogo non viene visualizzata nessuna mappa. Forse in Configurazione->Altro->Access Token MapBox devo inserire il token? Ma per la sua creazione viene chiesto l'inserimento della carta di credito, anche se ti avverte che pagherai solo per quello che userai. E' così? Grazie.

### Includi link o screenshot

![image](https://github.com/italia/design-scuole-wordpress-theme/assets/149438682/5ea8a57f-71a1-4f31-ab13-1f5ed9679307)

### Su quale sistema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

versione 2.6.0

**Comment by Simsimus** [comment]
Fai così:
1) vai su google maps
2) cerca il luogo che ti interessa
3) destro del mouse sul luogo
4) copia le coordinate cliccandoci sopra
5) incolla le coordinate nella lente
