### ISSUE TITLE
Visualizzazione della mappa nella pagina "I luoghi della Scuola"

### ISSUE THREAD

**Issue by Kec0de** [italia/design-scuole-wordpress-theme#52]
Forse a causa dell'aggiornamento di Wordpress alla versione 5.6, sono sparite le mappe dalla pagina suddetta di tutti i siti con il vostro tema, visualizzando soltanto i "marker" dei luoghi su sfondo grigio.

A tal proposito, nel template "Luoghi", nella cartella "template-parts" del tema, sono presenti 6 file php. Leggendo il codice dei vari file, ho notato che il codice nella sezione <script>

`<script>
    jQuery(function() {
        var mymap = L.map('map_<?php echo $c; ?>', {
            zoomControl: false,
            scrollWheelZoom: false
        }).setView([<?php echo $posizione_gps["lat"]; ?>, <?php echo $posizione_gps["lng"]; ?>], 15);
        L.marker([<?php echo $posizione_gps["lat"]; ?>, <?php echo $posizione_gps["lng"]; ?>]).addTo(mymap);
        // add the OpenStreetMap tiles
        L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
            attribution: '',
            maxZoom: 18,
        }).addTo(mymap);
    });
</script>`

è diventato

`<script>
    var mymap = L.map('map_<?php echo $c; ?>', {
        zoomControl: false,
        scrollWheelZoom: false
    }).setView([<?php echo $posizione_gps["lat"]; ?>, <?php echo $posizione_gps["lng"]; ?>], 15);
    var marker = L.marker([<?php echo $posizione_gps["lat"]; ?>, <?php echo $posizione_gps["lng"]; ?>]).addTo(mymap);
    L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token={accessToken}', {
        attribution: '',
        maxZoom: 18,
        id: 'mapbox.streets',
        accessToken: '<?php echo dsi_get_mapbox_access_token(); ?>'
    }).addTo(mymap);
</script>`

Mi domando come sia possibile?!? Ho comunque risolto ripristinando i corretti riferimenti alle mappe di www.openstreetmap.org.

A parte questo, nella visualizzazione delle mappe in primo piano, che si ottiene nell'amministrazione del sito alla sezione "Luoghi" della Configurazione in back office (vedere screenshot a piè di pagina), quando seleziono Sì a "Mappa in primo piano", ottengo sempre mappa grigia, e quindi, son costretto a  selezionare No (anche se preferirei avere la mappa in primo piano con i riferimenti ai luoghi sulla destra).
Questo è indipendente tuttavia dal codice che causava la non visualizzazione al punto precedente.

Per visualizzare quanto sopra descritto, questo il link: [https://www.easyteam.org/testsitoagid/luogo/](url)

![screenshot sezione luoghi](https://user-images.githubusercontent.com/50196803/104435354-934cd300-558c-11eb-9c87-de2381a8cfea.PNG)

**Comment by webgrafia** [comment]
ciao, 
intanto in merito alle url che trovi nello script, il riferimento corretto è quello di openstreetmap, che è nell'ultima versione ad esempio qui:
https://github.com/italia/design-scuole-wordpress-theme/blob/master/template-parts/luogo/card.php

Poi nel link di esempio che hai mandato vedo questo nel console-log:
Cannot read property 'lat' of null
che mi fa pensare tu abbia inserito dei luoghi ai quali non hai inserito le coordinate geo

**Comment by Kec0de** [comment]
Ciao Marco, 
grazie della celere risposta.

Le coordinate geo sono correttamente inserite, tant'è che, nella visualizzazione della mappa con la scelta dell'opzione di NON visualizzare la mappa in primo piano, tutto funziona a dovere (vedi altro esempio qui [http://scuole.easyteam.org/agid/luogo/](url)

**Comment by alessandroguerci** [comment]
Ciao, 
scusate
quindi per far tornare le mappe devo sostituire con questo codice:
<script> var mymap = L.map('map_<?php echo $c; ?>', { zoomControl: false, scrollWheelZoom: false }).setView([<?php echo $posizione_gps["lat"]; ?>, <?php echo $posizione_gps["lng"]; ?>], 15); var marker = L.marker([<?php echo $posizione_gps["lat"]; ?>, <?php echo $posizione_gps["lng"]; ?>]).addTo(mymap); L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token={accessToken}', { attribution: '', maxZoom: 18, id: 'mapbox.streets', accessToken: '<?php echo dsi_get_mapbox_access_token(); ?>' }).addTo(mymap); </script>

Grazie

**Comment by astagi** [comment]
Risolto nella nuova versione del tema disponibile (2.0.0)
