### ISSUE TITLE
Campi "Cosa serve (testo introduttivo) e Cosa serve (lista)" del Content type Indirizzi di studio non compaiono in frontend

### ISSUE THREAD

**Issue by vcoopcsc** [italia/design-scuole-wordpress-theme#522]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-scuole-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-scuole-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Nel content type indirizzi di studio ho compilato i campi "Cosa serve (testo introduttivo) e cosa serve (lista),. Le due sezioni dovrebbero comparire in frontend sotto la sezione libri di testo, ma questo non succede. 

### Includi link o screenshot

<img width="774" alt="image" src="https://github.com/italia/design-scuole-wordpress-theme/assets/92174841/8ae16554-74de-44b7-a138-ea27c8186936">

<img width="841" alt="image" src="https://github.com/italia/design-scuole-wordpress-theme/assets/92174841/6e671c2a-4043-43ed-a07c-34c34131973f">

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

2.6.0

**Comment by marcoverze93** [comment]
Ciao, ho trovato la soluzione. A breve apro la pull request.

**Comment by vcoopcsc** [comment]
Ti ringrazio!
