### ISSUE TITLE
Estensioni protette dall'accesso esterno non funziona

### ISSUE THREAD

**Issue by ricboc** [italia/design-scuole-wordpress-theme#526]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-scuole-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-scuole-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

In Configurazione-->Altro, alla voce "Estensioni protette dall'accesso esterno", ho inserito l'estensione ".pdf" 
![image](https://github.com/italia/design-scuole-wordpress-theme/assets/9788724/7c72bbcd-12ec-4c80-b51f-ae0173443ea3)
per poter proteggere all'occorrenza i file dall'accesso esterno (selezionabile in Media)
![image](https://github.com/italia/design-scuole-wordpress-theme/assets/9788724/8aeac9c3-7743-43f2-a25f-1d60eacc3745)
Nonostante la selezione sia presente, il file si apre ugualmente.
L'ho testato con accesso anonimo

### Su quale sisitema operativo stai riscontrando il problema?

Qualsiasi

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

2.6.0

**Comment by marcorubin** [comment]
Ho provato in ambiente di prova la funzionalità (prediposto Wordpress con tema pulito, senza plugin di ottimizzazione che attivano cache ad esempio) e non sembrano esserci comportamenti diversi da quelli previsti.

Posso chiederle di riprovare ancora una volta seguendo di nuovo i passaggi?
- configurare l'estensione da proteggere in Configurazione > Altro (ad esempio: .pdf)
- all'interno di media, impostare "Proteggi dall'accesso esterno" al documento desiderato (dovrà essere .pdf in questo caso)
- copiare l'URL negli appunti e aprirlo con schermata in incognito
Il risultato dovrebbe essere la pagina bianca senza lo scaricamento del file.

**Comment by ricboc** [comment]
Ho scaricato la versione 2.7.0 del tema
ho inserito In Configurazione-->Altro, alla voce "Estensioni protette dall'accesso esterno", l'estensione ".pdf"
![image](https://github.com/italia/design-scuole-wordpress-theme/assets/9788724/54e99b0f-0645-4cf3-9080-2f7e602c9f3a)
ho protetto il file "provafileaccessoriservato" con estensione pdf inserendo la spunta
![image](https://github.com/italia/design-scuole-wordpress-theme/assets/9788724/84e80305-5641-4dc8-96cb-5c13ab255a6e)
ho aggiornato la pagina di prova e inserito il link in una finestra anonima in mozilla firefox senza effettuare il login
![image](https://github.com/italia/design-scuole-wordpress-theme/assets/9788724/f3b4d609-7359-4ec9-a02c-2f2e4104c928)
ma il file si vede e si apre

**Comment by sviluppoRobyone** [comment]
La miglioria che abbiamo pensato interessa solamente il percorso del file, non gli articoli in cui è inserito (che vanno protetti con le altre funzionalità di permesso / visibilità) messe a disposizione. 
Il link diretto al file nel suo caso funziona comunque e il file si scarica o restituisce schermata bianca?

**Comment by ricboc** [comment]
Ok, ho capito. Per rispondere alla domanda, Il link diretto al file funziona comunque (caricato su finestra anonima) e il file si visualizza e si scarica.

**Comment by vincenzoargese** [comment]
Confermo

**Comment by vincenzoargese** [comment]
Ho risolto il problema, il sistema genera un file .htaccess sbagliato nel percorso wp-content/ il file generato è "uploads\.htaccess". 

Basta rinominare il file da "uploads\.htaccess" in .htaccess senza la parte iniziale "uploads\" oppure copiare il contenuto nel file .htaccess corretto.

![ksnip_20231120-115124](https://github.com/italia/design-scuole-wordpress-theme/assets/7203837/d1a0268e-af73-4823-b32e-df92529aa978)

![ksnip_20231120-115227](https://github.com/italia/design-scuole-wordpress-theme/assets/7203837/4a84b1aa-dc71-4222-aa9e-fd3470c45782)

Codice generico per modifica in manuale (file .pdf):
RewriteRule \d{4}/(.*)[.pdf]$ /path sito web/?action=reservedfilecheck&file=$0

**Comment by sviluppoRobyone** [comment]
Abbiamo provveduto a inserire una pull che va a correggere il bug.
Il file htaccess, per come è stata pensata la soluzione, dovrebbe essere all'interno della cartella uploads (file caricati nella sezione media), anche per non andare a interessare altre funzionalità che potrebbero andare in conflitto.
Essendo la modifica molto ridotta, potete direttamente apportarla per svolgere un veloce ulteriore test.

**Comment by vincenzoargese** [comment]
Grazie

**Comment by ricboc** [comment]
> Abbiamo provveduto a inserire una pull che va a correggere il bug. Il file htaccess, per come è stata pensata la soluzione, dovrebbe essere all'interno della cartella uploads (file caricati nella sezione media), anche per non andare a interessare altre funzionalità che potrebbero andare in conflitto. Essendo la modifica molto ridotta, potete direttamente apportarla per svolgere un veloce ulteriore test.

Ho testato, ma con la modifica effettuata, il file .htaccess che viene salvato all'interno della cartella uploads sovrascrive eventuali altri file .htaccess presenti. Io per esempio ho installato il plugin Converter for Media che inserisce nella cartella uploads un file .htaccess che è stato sovrascritto con la modifica suggerita.
