### ISSUE TITLE
Correzione alla documentazione

### ISSUE THREAD

**Issue by AlessioPellegrini** [italia/design-scuole-wordpress-theme#533]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-scuole-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-scuole-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

La documentazione del tema su github, alla voce "Come aggiornare il tema" raccomanda di sovrascrivere il tema child con lo zip del tema aggiornato. Andrebbe corretta, in quanto credo che l'idea sia di dire che bisogna sovrascrivere il tema principale e non il child.

### Includi link o screenshot

![FireShot Capture 047 - italia_design-scuole-wordpress-theme_ Tema Wordpress dedicato al prog_ - github com](https://github.com/italia/design-scuole-wordpress-theme/assets/9336026/33a33493-93e3-4739-8946-56f4d3853748)

### Su quale sisitema operativo stai riscontrando il problema?

Linux

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

260

**Comment by zetareticoli** [comment]
Ciao @AlessioPellegrini , grazie della segnalazione, provvedo a correggere subito
