### ISSUE TITLE
Contenuti homepage non visibili

### ISSUE THREAD

**Issue by PhilFiddler** [italia/design-scuole-wordpress-theme#534]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-scuole-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-scuole-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Buonasera, riscontro un problema alla home del sito https://www.icbalabanoff.edu.it/

Lato server non riscontro problemi ne errori, di punto in bianco da qualche giorno il contenuto del tag "main" della home non viene caricato (mentre le altre pagine funzionano correttamente).

### Includi link o screenshot

![Balabanoff home](https://github.com/italia/design-scuole-wordpress-theme/assets/150704818/041a5c90-4db4-4742-9bb5-cca799b6b0fb)

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

2.6.0

**Comment by Simsimus** [comment]
Ciao, prova a caricare almeno un articolo e dovrebbe risolversi...

**Comment by PhilFiddler** [comment]
È l'unica cosa tra le 10000 mila che non ho provato, ma funziona 😀
Grazie!
