### ISSUE TITLE
Dov'è l'albo sindacale?

### ISSUE THREAD

**Issue by Karolus81** [italia/design-scuole-wordpress-theme#54]
Buongiorno,
non trovo riferimenti relativi all'Albo sindacale. E' una mia svista o manca? E, in questo caso, qualche consiglio?
Ringrazio anticipatamente.

**Comment by webgrafia** [comment]
L'albo è gestito tramite i documenti.
Selezionando "Albo online" nella tipologia del documento, compaiono i campi aggiuntivi richiesti
![image](https://user-images.githubusercontent.com/9932389/105468276-1b229380-5c97-11eb-9b9c-99ae90a2aef0.png)

**Comment by Karolus81** [comment]
Ringrazio!

**Comment by Karolus81** [comment]
Tra un mese, circa, ho intenzione di pubblicare il nuovo sito della scuola... abbiate pazienza, sono un animatore digitale, (laurea: Lettere antiche) con tutti i miei limiti.
Vedendo, comunque, i siti delle altre scuole, noto che si sta usando il template rivolto alle istituzioni non scolastiche...
