### ISSUE TITLE
Didattica - La nostra offerta formativa - Indirizzi di studio non cliccabili (Accordion non funzionante)

### ISSUE THREAD

**Issue by allenive90** [italia/design-scuole-wordpress-theme#542]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-scuole-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-scuole-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Gli indirizzi di studio presenti nella sezione Didattica/La nostra offerta formativa della Home Page non risultano cliccabili.

### Includi link o screenshot

<img width="1215" alt="Screenshot 2023-11-13 alle 14 36 12" src="https://github.com/italia/design-scuole-wordpress-theme/assets/46575972/42b11f03-6c85-4627-aa92-2461a31e6714">
<img width="826" alt="Screenshot 2023-11-18 alle 12 10 19" src="https://github.com/italia/design-scuole-wordpress-theme/assets/46575972/99d05571-dd44-4453-9d5f-e00235b9b7bc">

### Su quale sisitema operativo stai riscontrando il problema?

macOS

### Su quale browser stai riscontrando il problema?

Chrome

### Che versione del tema stai utilizzando?

2.7.0

**Comment by zetareticoli** [comment]
Ciao @allenive90 , pare ci sia un problema con il JS dell'accordion. Hai inizializzato correttamente la libreria?

**Comment by allenive90** [comment]
Ciao @zetareticoli. Sulle librerie non ho toccato nulla. Cosa bisogna fare nello specifico? Grazie

**Comment by allenive90** [comment]
Ciao @zetareticoli, potresti darmi supporto nella risoluzione di questo problema? Grazie

**Comment by allenive90** [comment]
Ciao @zetareticoli, potresti darmi supporto nella risoluzione di questo problema? Grazie

**Comment by allenive90** [comment]
<img width="1128" alt="Screenshot 2023-12-05 alle 16 40 38" src="https://github.com/italia/design-scuole-wordpress-theme/assets/46575972/a281064d-f40f-41bd-a6b2-9e12203e8ed8">

**Comment by zetareticoli** [comment]
Non saprei dirti con certezza cosa sia, devi fare un po' di _reverse engineering_ e capire cosa causa il malfunzionamento, rispetto al template statico originale.

**Comment by allenive90** [comment]
La segnalazione era un bug. Infatti con la versione 2.9.0 non si presenta più il problema.

**Comment by allenive90** [comment]
La segnalazione era un bug. Infatti con la versione 2.9.0 non si presenta più il problema.
