### ISSUE TITLE
Problemi motore di ricerca interno al sito

### ISSUE THREAD

**Issue by vcoopcsc** [italia/design-scuole-wordpress-theme#547]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-scuole-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-scuole-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Se cerco qualcosa col tasto cerca, prendendolo dall'elenco "Potrebbero interessarti", ad esempio " Sedi", la pagina che mi restituisce i risultati comprende tutti i content type  collegati alla parola "Sedi": eventi, circolari, servizi, luoghi, ecc.
Nel momento in cui imposto dei filtri e quindi chiedo al sistema di farmi vedere solo (ad esempio) gli eventi collegati alla parola "Sedi" il sistema mi restituisce zero risultati, nonostante nella pagina coi risultati della ricerca senza filtri impostati apparivano gli eventi. 

### Includi link o screenshot

Pagina di ricerca
<img width="920" alt="image" src="https://github.com/italia/design-scuole-wordpress-theme/assets/92174841/aef62e50-dc0f-4c90-94c1-13b65dc56caf">
Pagina coi risultati della ricerca 
<img width="1098" alt="image" src="https://github.com/italia/design-scuole-wordpress-theme/assets/92174841/18073ee9-0bad-44bc-a96d-fd29340a3401">
Pagina dopo aver selezionato il filtro "calendario eventi"
<img width="1098" alt="image" src="https://github.com/italia/design-scuole-wordpress-theme/assets/92174841/0405acc2-1b33-413f-82ac-6d306ce4124b">

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Microsoft Edge

### Che versione del tema stai utilizzando?

2.7.0

**Comment by zetareticoli** [comment]
Ciao @vcoopcsc , nel report del problema vedo allegato lo stesso screen, è corretto?

**Comment by marcoverze93** [comment]
Ciao,
il problema è il seguente: gli eventi sono visti come articoli nel menù laterale. Nei prossimi giorni provo a vedere di risolverlo

**Comment by vcoopcsc** [comment]
> Ciao @vcoopcsc , nel report del problema vedo allegato lo stesso screen, è corretto?
<img width="792" alt="image" src="https://github.com/italia/design-scuole-wordpress-theme/assets/92174841/a13c6f0b-c178-42a7-ad02-6ca20488872e">

Ecco lo screen scusami l'errore

**Comment by vcoopcsc** [comment]
@marcoverze93 in realtà no, capita con tutti i filtri, anche se metto come filtro "Organizzazione" il problema è identico

<img width="742" alt="image" src="https://github.com/italia/design-scuole-wordpress-theme/assets/92174841/3ea724cd-1f6b-48b8-8f6b-2e38764a7ce7">

**Comment by vcoopcsc** [comment]
Chiarissimo, ti ringrazio!

**Comment by vcoopcsc** [comment]
@marcoverze93 sei poi riuscito a lavorare su questo problema?

**Comment by marcoverze93** [comment]
Ciao, ho avuto poco tempo per metterci mano ma per ora la soluzione che penso sia più plausibile è creare una ricerca con quel termine associato più che una pagina con l'argomento. Nelle vacanze spero di poterci mettere mano con calma.

**Comment by vcoopcsc** [comment]
Buongiorno, confermo che il problema è ancora presente anche nella versione 2.9.0
