### ISSUE TITLE
problemi con asseverazione pagina presentazione

### ISSUE THREAD

**Issue by attiliopecora** [italia/design-scuole-wordpress-theme#554]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-scuole-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-scuole-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

un asseveratore mi manda questo: 

2.   La pagina https://xxxxxyyyyy.edu.it/la-scuola/presentazione/ non rispetta il criterio Buone pratiche in quanto non riporta un testo di presentazione dell’Istituto

pur contenendno la pagina, rimandi a tutto ciò che può essere utile documenti strutture, ptof etc etc .... 
ma secondo voi cosa vuole ?

 

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

2.7.0

**Comment by Cate55** [comment]
@attiliopecora la pagina Presentazione è un template editabile, scrivi un breve testo, significativo della tua scuola, nel box editor.
Questo testo andrà a popolare la sezione redbrown, credo sia questa la richiesta dell'asseveratore, ma non vorrei aver frainteso.
![presentazione](https://github.com/italia/design-scuole-wordpress-theme/assets/9642253/fdc694b2-efa8-4c13-91f3-7b467d1c5d95)

**Comment by attiliopecora** [comment]
avevo visto anche io l'editabilità del template di pagina ma, onde evitare fraintendimenti (perchè non è stato chiaro), ho creato una pagina di presentazione con qualche dato in più.
grazie comunque
