### ISSUE TITLE
Problema breadcrumb Albo online

### ISSUE THREAD

**Issue by marinogianni** [italia/design-scuole-wordpress-theme#555]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-scuole-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-scuole-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Durante la fase di asseverazione viene riportato il seguente problema:

Inoltre si segnala che sono rilevate alcune pagine non rispettano il criterio Buone pratiche come ad esempio: La pagina https://xxxxxxxxxxxxxx/tipologia-documento/albo-online/ non risulta coerente con il menu e l’architettura del sito in quanto lo stesso riporta la seguente collocazione (come espressa dalla breadcrumb): “Home\Scuola\Le carte della scuola\Albo online” .Tale aspetto incide inoltre sulla sezione Scuola che risulta a sua volta incoerente con il il percorso sopraindicato.

La pagina "Albo online" si trova all'interno del menù "Notizie", l'asseveratore richiede che la breadcrumb sia coerente con tale menù
 

### Includi link o screenshot

<img width="323" alt="1" src="https://github.com/italia/design-scuole-wordpress-theme/assets/147064791/d7b004a9-ac02-4e1f-8759-9daa9b098e53">
<img width="413" alt="2" src="https://github.com/italia/design-scuole-wordpress-theme/assets/147064791/5306d67b-0907-426e-a9ec-a41c6a8530ea">

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

2.7

**Comment by fabricius4** [comment]
ha dato la stessa segnalazione anche a me. Vedo, però, che ancora non c'è stata risposta a questa tua issue. Sei riuscito a risolvere?

**Comment by marinogianni** [comment]
Ancora nessuna soluzione

**Comment by marinogianni** [comment]
Buonasera, ho risolto il problema ed il sito ha avuto esito positivo. Ho eliminato la voce "Albo online" dal menù "Novità" ed inserito un banner centrale con il link al nostro sistema interno di albo online legato al registro elettronico, nella richiesta dell'asseveratore ho spiegato che la nostra scuola utilizza già un albo esterno legato proprio al registro elettronico. Il link al sito è [https://www.iiseuclide.edu.it]

**Comment by Petrillo96** [comment]
Buongiorno, io invece avevo il banner in home che lo riportava dal "Servizio" al link esterno e poi una voce sul menù "Novità". 
Contato come errore, ho creato una pagina nel menù sottostante. Spero vada bene oppure devo annotarlo all'asseveratore?
