### ISSUE TITLE
Pagine persone e spazio bianco sul fondo

### ISSUE THREAD

**Issue by vcoopcsc** [italia/design-scuole-wordpress-theme#558]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-scuole-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-scuole-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Se non ci sono utenti con ruolo nell'organizzazione "Personale docente" o "Personale non docente", le tipologie "personale docente" e "personale non docente" correttamente scompaiono ma la pagina non si "riaggiusta" e c'è tanto spazio bianco inutile

### Includi link o screenshot

<img width="1127" alt="image" src="https://github.com/italia/design-scuole-wordpress-theme/assets/92174841/0a8f37f4-20a1-4a20-b78a-8392b3056aa0">

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

2.7.0

**Comment by zetareticoli** [comment]
ciao @vcoopcsc, penso dipenda dalla visualizzazione dei tag `html` vuoti. Portli sotto condizione `if` dovrebbe essere la soluzione
