### ISSUE TITLE
Le carte della scuola

### ISSUE THREAD

**Issue by Karolus81** [italia/design-scuole-wordpress-theme#56]
Buongiorno, riscontro problemi nella visualizzazione de "Le carte della scuola".
Anche selezionando in configurazione i documenti (tipologia "modulistica") da visualizzare, in anteprima vedo sempre 6 documenti non scelti da me.

**Comment by vcoopcsc** [comment]
Seguo: è esigenza di molte scuole poter scegliere quali documenti far vedere prima nella pagina "Le carte della scuola". Al momento è possibile solo ordinare le tipologie di documenti, ma non ordinare i vari documenti della stessa tipologia. Alcuni istituti caricano prima i documenti più importanti e dopo quelli meno prioritari. In questa maniera però verranno visualizzati sempre prima quelli meno importanti senza alcuna possibilità di modifica se non cancellare il contenuto inserito e ricaricarlo per ultimo.

**Comment by vcoopcsc** [comment]
Buongiorno, anche con la versione nuova non è comunque possibile scegliere l'ordine con il quale mostrare i documenti nella sezione le carte della scuola.
