### ISSUE TITLE
come si fa a non esporre il nome dell'utente sulle card notizie ?

### ISSUE THREAD

**Issue by attiliopecora** [italia/design-scuole-wordpress-theme#562]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-scuole-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-scuole-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

come si fa a non esporre il nome dell'utente sulle card notizie ?

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

2.7.0

**Comment by marcoverze93** [comment]
Ciao
l'unico modo è cambiare il codice manualmente: nel template-parts/single/card-vertical-thumb.php devi togliere la riga 36.

**Comment by attiliopecora** [comment]
si a questa soluzione ero giunto anche io marco ... grazie :-)
