### ISSUE TITLE
Problema urgente Amministrazione Trasparente

### ISSUE THREAD

**Issue by Simsimus** [italia/design-scuole-wordpress-theme#569]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-scuole-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-scuole-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Buongiorno,
i revisori dei conti stanno segnalando alle scuole che alcune sezioni dell'Amministrazione Trasparente non sono presenti in elenco.
Il bug consiste nel fatto che, anche se tali sezioni vengono aggiunte correttamente nel backend, poi nel frontend non sono visibili.
Auspico vivamente che tale problema possa essere risolto in tempi rapidi, altrimenti le scuole subiranno esiti negativi.
Grazie

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

2.7.0

**Comment by yfxkp** [comment]
Di quali sezioni stai parlando puoi fornire qualche esempio? E giusto per essere sicuri chi è a segnalare il problema gli asseveratori del pnrr o i revisori contabili interni della scuola?

**Comment by Simsimus** [comment]
A segnalare il problema sono i revisori contabili che, nell'ambito delle attestazioni OIV, devono valutare la % raggiunta  dalle scuole in termini di pubblicazione in Amministrazione Trasparente e se non trovano tutte le sezioni con i relativi documenti penalizzano la scuola abbassando la percentuale di conformità. Ad esempio (vedere allegato) in Disposizioni generali > Atti generali si dovrebbero inserire ulteriori sotto sezioni. 
Ma non è tanto importante quale specifica sezione deve essere attualmente presente o meno, perchè nel tempo potrebbero cambiare, ma far corrispondere ciò che si inserisce nel backend a quello che si vede nel frontend. 
Se, ad esempio, si va da backend su Documenti > Amministrazione trasparente e si inserisce una nuova sezione, il sistema la fa aggiungere e gestire, ma poi tale nuova sezione non compare nel fronted e quindi i revisori la annotano come inadempienza.

Spero sia chiaro quello che intendo e che si possa risolvere il problema quanto prima.
Grazie

Allegato:
![AT](https://github.com/italia/design-scuole-wordpress-theme/assets/108821309/c8cd418e-a3b0-45a9-93ed-3ba298deb9f1)

**Comment by Prancingkiller** [comment]
credo sia lo stesso problema di un'altra issue, ho risolto temporaneamente con questo fix
https://github.com/italia/design-scuole-wordpress-theme/issues/485#issuecomment-1795321850

**Comment by Prancingkiller** [comment]
> Però nel mio caso la pagina Amministrazione Trasparente si apre regolarmente senza errori, solo che non mostra le nuove sezioni create, ma solo quelle presenti di default.

Nelle sezioni nuove che non vengono visualizzate hai inserito dei documenti?

**Comment by Simsimus** [comment]
Si ho provato ed i documenti vengono visualizzati come appartenenti ai livelli superiori, ad esempio se viene inserito in Disposizioni generali > Atti generali > Atti amministrativi generali, lo mostrerà nei primi due livelli, ma non nel terzo che non compare proprio in elenco...

**Comment by Prancingkiller** [comment]
> Si ho provato ed i documenti vengono visualizzati come appartenenti ai livelli superiori, ad esempio se viene inserito in Disposizioni generali > Atti generali > Atti amministrativi generali, lo mostrerà nei primi due livelli, ma non nel terzo che non compare proprio in elenco...

Perché le categorie vengono caricate da un array fisso, non dal db come dovrebbe essere, credo che l'errore dell'altro post dipenda dal fatto che l'utente ha cancellato una categoria dal db tramite il backend, e quindi lo script che cerca le sottosezioni non trovandola (non dovrebbe cercarla, ma lo fá perché parte dalle categorie nell'array fisso) 
dà errore.

**Comment by Prancingkiller** [comment]
> Quindi come risolviamo? Il risultato finale deve essere:
> 
> 1. possibilità di inserire e gestire nuove sezioni da backend;
> 2. visualizzare da frontend tutto l'albero dell'Amministrazione Trasparente, comprese sia le sezioni vuote che quelle nuove.
>    In caso contrario la scuole viene segnalata come inadempiente o parzialmente inadempiente.

Sono stato nella tua stessa situazione ed ho implementato io una funzione temporaneamente, leggi quella risposta che ti avevo linkato prima, altrimenti devi aspettare che rilasciano un aggiornamento immagino.

**Comment by Simsimus** [comment]
Ho visto la tua funzione, ma tu specifichi che con tale funzione si vedranno solo le categorie con dei documenti al suo interno, invece il revisore dei conti, oltre ai documenti, verifica la presenza di tutte le categorie (anche quelle vuote), quindi il problema non verrebbe risolto pienamente :(

**Comment by Prancingkiller** [comment]
> Ho visto la tua funzione, ma tu specifichi che con tale funzione si vedranno solo le categorie con dei documenti al suo interno, invece il revisore dei conti, oltre ai documenti, verifica la presenza di tutte le categorie (anche quelle vuote), quindi il problema non verrebbe risolto pienamente :(

Per questo dovrebbe bastare aggiungere alla funzione get_terms il parametro 'hide_empty' => false
quindi:
`function testA(){
	$myterms = get_terms( array( 'taxonomy' => 'amministrazione-trasparente', 'parent' => 0,'hide_empty' => false ) );
	$data = [];
	foreach($myterms as $term){
		$inner = [];
		$inner[]=$term->name;
		$inner["count"]=$term->count;
		$sub=[];
		foreach(get_terms( array( 'taxonomy' => 'amministrazione-trasparente', 'parent' => $term->term_id,'hide_empty' => false ))as $subT){
			$sub[] = $subT->name;
			$inner["count"] += $subT->count;
		}
		$inner[]=$sub;
		$data[] = $inner;
	}
	return $data;
}`

**Comment by Simsimus** [comment]
Ho inserito la funzione da te indicata in "inc/vocabolario.php" e poi ho chiamato questa funzione testA() al posto di "dsi_amministrazione_trasparente_array()" nei files:
"/page-templates/amministrazione-trasparente.php"
"/template-parts/search/filters-amministrazione.php"
ma se apro l'amministrazione trasparente il sito va in errore.
Sbaglio qualcosa?
Potresti condividere i file modificati così faccio dei test?
Grazie

**Comment by Prancingkiller** [comment]
Ecco i files, provato ora con o senza l'hide_empty e funziona correttamente, la versione del mio tema è 2.5.1, potrebbe essere questo.. prova

[amministrazione-trasparente.zip](https://github.com/italia/design-scuole-wordpress-theme/files/13672837/amministrazione-trasparente.zip)

**Comment by Simsimus** [comment]
Niente da fare, segnala il seguente errore:
Fatal error : Uncaught Error: Call to undefined function testA() in \wp-content\themes\design-scuole-wordpress-theme-main-child\page-templates\amministrazione-trasparente.php:47 Stack trace: 
0 \wp-includes\template-loader.php(106): include() 
1 \wp-blog-header.php(19): require_once('\htd...') 
2 \index.php(17): require('\htd...') 
3 {main} thrown in \wp-content\themes\design-scuole-wordpress-theme-main-child\page-templates\amministrazione-trasparente.php on line 47

Però io io uso l'ultima versione del tema 2.7.0 ed anche l'ultima versione di wordpress.

**Comment by Simsimus** [comment]
Ora funziona, ma comunque non si ottiene quanto necessario, per due motivi:
1) l'ordine delle sezioni diventa alfabetico, quindi diverso da quello previsto;
2) i livelli visualizzati restano solo 2, quindi se bisogna inserire un terzo livello (ad esempio Disposizioni generali > Atti generali > Atti amministrativi generali) il sistema continua a mostrare solo i primi due, nonostante sia presente un terzo livello con al suo interno un documento, di conseguenza il revisore dei conti non troverebbe i livelli previsti da controllare.

**Comment by Prancingkiller** [comment]
> Ora funziona, ma comunque non si ottiene quanto necessario, per due motivi:
> 
> 1. l'ordine delle sezioni diventa alfabetico, quindi diverso da quello previsto;
> 2. i livelli visualizzati restano solo 2, quindi se bisogna inserire un terzo livello (ad esempio Disposizioni generali > Atti generali > Atti amministrativi generali) il sistema continua a mostrare solo i primi due, nonostante sia presente un terzo livello con al suo interno un documento, di conseguenza il revisore dei conti non troverebbe i livelli previsti da controllare.

Vero vero, dovresti modificare la funzione per includere un ulteriore ciclo per cercare i terzi livelli, o comunque fare in modo che continui a fare cicli se esistono ancora sottosezioni, e cambiare l'ordinamento con quello del sorting nel backend

**Comment by Simsimus** [comment]
Purtroppo non sono un programmatore quindi non saprei come aggiungere un ulteriore ciclo. In linea di massima, se il sorting è complicato, potrebbe andar bene, almeno per il momento, anche aggiungere solo un terzo livello di ciclo.
Se non ti comporta troppo tempo/lavoro, questa è una modifica che riusciresti a fare e condividere?
Grazie

**Comment by Prancingkiller** [comment]
Non dovrebbe essere un problema, ci do un'occhiata stasera e ti aggiorno quì

**Comment by zetareticoli** [comment]
Come segnalato nella [documentazione](https://docs.italia.it/italia/designers-italia/design-scuole-docs/it/versione-corrente/risorse/amministrazione-trasparente.html) del modello, sono presenti solo alcuni dei contenuti obbligatori. È lasciato ad ogni ente lo sviluppo e implementazione completa.

**Comment by Prancingkiller** [comment]
> Come segnalato nella [documentazione](https://docs.italia.it/italia/designers-italia/design-scuole-docs/it/versione-corrente/risorse/amministrazione-trasparente.html) del modello, sono presenti solo alcuni dei contenuti obbligatori. È lasciato ad ogni ente lo sviluppo e implementazione completa.

Forse non è chiaro qual'è il problema, i contenuti non possono essere caricati, anche solo modificando il nome di una categoria il sito va in errore, questo perchè le categorie dell'amministrazione trasparente sono caricate come Terms all'interno di Wordpress, questo fà sì che siano gestibili facilmente tramite il backend (come le categorie degli articoli per capirci), ma la funzione che stampa le categorie nella pagina del frontend non le legge dal db come dovrebbe fare, ma le legge da un array fisso, quindi non solo si perde qualsiasi aggiunta, ma se non ci sono nel db tutte le categorie esattamente come nell'array, il sito và ovviamente in crash perchè non trova i Terms. Quindi sì è un bug.
@Simsimus  comunque, ti allego uno zip come prima, sempre come prima, se ti dà quell'errore in cui non trova la funzione (che ho rinominato in get_amministrazione_array), toglila dal vocabolario e mettila all'inizio degli altri due files, il risultato dovrebbe essere come avevi detto, e dovresti poter inserire x "livelli" di sottocategorie e dovrebbe comunque andare.
[FIX.zip](https://github.com/italia/design-scuole-wordpress-theme/files/13677809/FIX.zip)

**Comment by Simsimus** [comment]
Buongiorno @Prancingkiller ,
innanzitutto grazie per la disponibilità e competenza che stai dimostrando.
Ho provato la tua soluzione e posso dire che è quasi perfetta, tranne due aspetti:
1) non è più visibile il contatore (vedere allegato 1);
2) il terzo livello non è annidato correttamente (vedere allegato 2).

Risolti questi aspetti sarà perfetto ;)
Grazie di tutto



**Allegato 1 (esempio il 56):**
![contatore](https://github.com/italia/design-scuole-wordpress-theme/assets/108821309/805316b0-1a42-4217-ba7e-8fd4e74a0b61)


**Allegato 2 (esempio "Atti amministrativi generali" dovrebbe essere all'interno di "Atti generali"):**
![at](https://github.com/italia/design-scuole-wordpress-theme/assets/108821309/9d5d8a56-0be9-4761-800f-388c6138e93f)

**Comment by Prancingkiller** [comment]
Buongiorno, sicuro che sia impostato correttamente come child di Atti generali? 
![atti 2](https://github.com/italia/design-scuole-wordpress-theme/assets/68690184/5ba1c70e-aefe-4661-bd0d-9f6371f9c590)
![atti](https://github.com/italia/design-scuole-wordpress-theme/assets/68690184/cac6fb18-11f1-4e4d-8286-f0de45d4307d)
dovrebbe apparire così backend/frontend

**Comment by Prancingkiller** [comment]
Buongiorno, sicuro che sia impostato correttamente come sottosezione?
![atti 2](https://github.com/italia/design-scuole-wordpress-theme/assets/68690184/a2b047d7-2065-45c4-a7f1-2726fde7fbce)
![atti](https://github.com/italia/design-scuole-wordpress-theme/assets/68690184/f74c5907-e5cc-42ef-997c-4cd80c5af861)
dovrebbe apparire così

**Comment by Simsimus** [comment]
Hai ragione, mi ero dimenticato di averla spostata per fare dei test.
Confermo che l'annidamento funziona correttamente, quindi resta solo il contatore dei documenti suddiviso per sezione.
Quest'ultimo è un dato utile per far capire subito se in una sezione sono presenti o meno dei documenti, ma se non dovesse essere possibile o dovesse risultare complicato, va benissimo lo stesso così. L'unica cosa è che le scuole potrebbero lamentare il fatto che prima il contatore era visibile ed ora non c'è più.
Grazie per l'ottimo lavoro svolto ;)

**Comment by Prancingkiller** [comment]
Ecco con i counter
[FIX2.zip](https://github.com/italia/design-scuole-wordpress-theme/files/13689185/FIX2.zip)

**Comment by Simsimus** [comment]
Sei magnifico e grazie davvero tanto per il lavoro che stai facendo.
Ti volevo segnalare due anomalie:
1) il contatore non conta bene, come vedi in allegato, ci sono 2 documenti in "Atti amministrativi generali" ma lui ne conta 3;
2) i titoli in MAIUSCOLO (per capirci) non sono cliccabili (prima lo erano), ora sono cliccabili solo quelli in minuscolo.

Grazie per il tempo che vorrai dedicarci

Allegato:
![AT](https://github.com/italia/design-scuole-wordpress-theme/assets/108821309/2d567a34-c6b7-4dcd-b136-157842258246)

**Comment by Prancingkiller** [comment]
> Sei magnifico e grazie davvero tanto per il lavoro che stai facendo. Ti volevo segnalare due anomalie:
> 
> 1. il contatore non conta bene, come vedi in allegato, ci sono 2 documenti in "Atti amministrativi generali" ma lui ne conta 3;
> 2. i titoli in MAIUSCOLO (per capirci) non sono cliccabili (prima lo erano), ora sono cliccabili solo quelli in minuscolo.
> 
> Grazie per il tempo che vorrai dedicarci
> 
> Allegato: ![AT](https://private-user-images.githubusercontent.com/108821309/291195986-2d567a34-c6b7-4dcd-b136-157842258246.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5MDUzNDYsIm5iZiI6MTcwMjkwNTA0NiwicGF0aCI6Ii8xMDg4MjEzMDkvMjkxMTk1OTg2LTJkNTY3YTM0LWM2YjctNGRjZC1iMTM2LTE1Nzg0MjI1ODI0Ni5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxOFQxMzEwNDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wODlkYTc4YjBiN2UwMTc2YTI3ZDk0YjI3NjYyODY4NzJkNGQ4N2E5ZGUzODJmMWRjZTk5NzBiMGIwM2U3NTMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Lfd_Yr-_-3CskFl_PsDLph8VdTbevnF-H7oVPCICfkk)

Per il contatore controlla di aver aggiornato la funzione get_amministrazione_array(), che nello zip è nel file vocabolario, per i link dei titoli in maiuscolo ecco quì solo il file amministrazione-trasparente al quale ho rimesso i links.
[FIX3.zip](https://github.com/italia/design-scuole-wordpress-theme/files/13704179/FIX3.zip)

**Comment by Simsimus** [comment]
Ora i links sono nuovamente operativi, ma il contatore, nonostante abbia aggiornato la funzione get_amministrazione_array(), si comporta come segue:
- se si mette un documento in una sezione che ha solo il primo e secondo livello allora conta correttamente;
- se invece si mette in una sezione che ha pure i terzi livelli conta male...in pratica fa +1 per ogni terzo livello che esiste in quella sezione.

Ad esempio se esiste:
.Livello A
...Livello Ab
......Libello Abc
e metti un documento in uno dei tre livelli, il contatore conta 2 anche con un solo documento.
Se poi aggiungi Livello Abcd allora conta 3 nonostante il documento sia sempre uno.
Spero possa esserti utile tale esempio.
Grazie come sempre

**Comment by Prancingkiller** [comment]
> Ora i links sono nuovamente operativi, ma il contatore, nonostante abbia aggiornato la funzione get_amministrazione_array(), si comporta come segue:
> 
> * se si mette un documento in una sezione che ha solo il primo e secondo livello allora conta correttamente;
> * se invece si mette in una sezione che ha pure i terzi livelli conta male...in pratica fa +1 per ogni terzo livello che esiste in quella sezione.
> 
> Ad esempio se esiste: .Livello A ...Livello Ab ......Libello Abc e metti un documento in uno dei tre livelli, il contatore conta 2 anche con un solo documento. Se poi aggiungi Livello Abcd allora conta 3 nonostante il documento sia sempre uno. Spero possa esserti utile tale esempio. Grazie come sempre

Strano, dovrebbe apparire così:
![Senza titolo](https://github.com/italia/design-scuole-wordpress-theme/assets/68690184/31d851b4-5ded-4cce-b86c-851aade53aa1)
Controlla di non avere un terzo documento caricato nella categoria Atti Generali (padre di Atti amministrativi generali)

**Comment by Simsimus** [comment]
Prova a spostare uno dei due documenti in "Atti generali" e dovrebbe venir fuori il problema, ovvero conta 3, almeno da me fa così. Se invece li lascio entrambi in "Atti amministrativi generali" va tutto bene.
Da come ho capito se si mette un documento al livello principale lui lo conta tante volte quanti sono i sotto livelli...ma potrei sbagliarmi

**Comment by Prancingkiller** [comment]
> Prova a spostare uno dei due documenti in "Atti generali" e dovrebbe venir fuori il problema, ovvero conta 3, almeno da me fa così. Se invece li lascio entrambi in "Atti amministrativi generali" va tutto bene. Da come ho capito se si mette un documento al livello principale lui lo conta tante volte quanti sono i sotto livelli...ma potrei sbagliarmi

Hai ragione, prova a cambiare la funzione get_amministrazione_array() in:
```
function scanInner($term,$starting){
	$inner[]=$term->name;
	$inner["count"]=$starting+$term->count;
	$sub=[];
	if(count(get_term_children($term->term_id,'amministrazione-trasparente'))>0){
		foreach(get_terms( array( 'taxonomy' => 'amministrazione-trasparente', 'orderby'=>'term_order', 'parent' => $term->term_id,'hide_empty' => false ))as $subT){
			$sub[]=scanInner($subT,0);
		}
	}
	$inner[]=$sub;
	foreach($sub as $s){
		$inner["count"] += $s["count"];
	}
	return $inner;
}
```

**Comment by Simsimus** [comment]
Ora è assolutamente perfetta!!!
Grazie per la professionalità, competenza e disponibilità che hai dimostrato.
Chiudo questo post come risolto e ti consiglio di segnalare al Team Digitale questo tuo prezioso lavoro, che risolve un bug in un comparto importante per le PA, in modo che possano aggiungerlo nella prossima release per tutta la community.
Grazie ancora

**Comment by zetareticoli** [comment]
C'è una PR aperta in merito?

**Comment by Prancingkiller** [comment]
@Simsimus  ottimo! figurati è stato un piacere.
@zetareticoli  non ancora, nei prossimi giorni smusso qualcosa quà e là e poi la apro

**Comment by zetareticoli** [comment]
Ok, allora riapro la issue e quando apri la PR non dimenticare di collegarla a questa issue

**Comment by Simsimus** [comment]
Mi permetto solo di precisare che per la versione del tema 2.7.0 la funzione l'ho inserita nei file amministrazione-trasparente.php e  filters-amministrazione.php perchè se la lasciavo in vocabolario.php andava in errore

**Comment by vaniaweb** [comment]
Buonasera, ho aggiornato il template all'ultima versione 2.9.0, sperando di trovare già le modifiche proposte in questo post, ma purtroppo nulla è cambiato sulla questione. Sarebbe possibile avere insieme tutti i file da modificare in un'unica cartella con l'ultima versione? Dalla chat sopra non ho capito bene cosa e come modificare per avere  la possibilità di aggiungere le categorie (anche di terzo livello) e i contatori per ogni singola voce. Grazie mille!

**Comment by Prancingkiller** [comment]
> Buonasera, ho aggiornato il template all'ultima versione 2.9.0, sperando di trovare già le modifiche proposte in questo post, ma purtroppo nulla è cambiato sulla questione. Sarebbe possibile avere insieme tutti i file da modificare in un'unica cartella con l'ultima versione? Dalla chat sopra non ho capito bene cosa e come modificare per avere la possibilità di aggiungere le categorie (anche di terzo livello) e i contatori per ogni singola voce. Grazie mille!

Ciao, purtroppo ho avuto poco tempo negli ultimi mesi, ho mandato ora una PR, in ogni caso, i files sono allegati in questo messaggio, vanno nelle cartelle (percorso relativo alla root del tema):

amministrazione-trasparente.php -> page-templates
filters-amministrazione.php -> template-parts/search
vocabolario.php -> inc

per qualche motivo @Simsimus aveva un problema nel richiamare le funzioni che sono definite nel file vocabolario.php negli altri due files, ma ho provato su una nuova versione del tema e non sono riuscito a ricreare questo errore, quindi ti direi che dovrebbe funzionare semplicemente sostituendo i files come ti ho indicato.

[amministrazione-trasparente.zip](https://github.com/italia/design-scuole-wordpress-theme/files/14297678/amministrazione-trasparente.zip)

**Comment by vaniaweb** [comment]
Grazie @Prancingkiller, ho sostituito i file come da indicazioni. 
Subito non funzionava, ma stavo usando una cartella del tema che avevo rinominato per crearne una copia. Inserendo invece i file nella cartella del tema aggiornato sovrascrivendo i file, e attivandolo, non ricevo più il messaggio di errore. L'unica cosa che ho notato è che nel filters-amministrazione.php se ci sono menu di terzo livello, il secondo livello non apre più la pagina contenente gli articoli, ma solo il menu sotto, è una cosa che capita solo a me?
Intanto grazie ancora per la risposta e per il prezioso contributo per la sistemazione di questa sezione del sito.

**Comment by Prancingkiller** [comment]
> Grazie @Prancingkiller, ho sostituito i file come da indicazioni. Subito non funzionava, ma stavo usando una cartella del tema che avevo rinominato per crearne una copia. Inserendo invece i file nella cartella del tema aggiornato sovrascrivendo i file, e attivandolo, non ricevo più il messaggio di errore. L'unica cosa che ho notato è che nel filters-amministrazione.php se ci sono menu di terzo livello, il secondo livello non apre più la pagina contenente gli articoli, ma solo il menu sotto, è una cosa che capita solo a me? Intanto grazie ancora per la risposta e per il prezioso contributo per la sistemazione di questa sezione del sito.

Ciao, intendi che nel caso una categoria abbia sia documenti che sottocategorie associate allora nella pagina con i filtri sulla sinistra, premendo sulla categoria non si vedono gli articoli associati direttamente alla categoria stessa ma si apre solo la tendina con le sottocategorie?

**Comment by vaniaweb** [comment]
> > Grazie @Prancingkiller, ho sostituito i file come da indicazioni. Subito non funzionava, ma stavo usando una cartella del tema che avevo rinominato per crearne una copia. Inserendo invece i file nella cartella del tema aggiornato sovrascrivendo i file, e attivandolo, non ricevo più il messaggio di errore. L'unica cosa che ho notato è che nel filters-amministrazione.php se ci sono menu di terzo livello, il secondo livello non apre più la pagina contenente gli articoli, ma solo il menu sotto, è una cosa che capita solo a me? Intanto grazie ancora per la risposta e per il prezioso contributo per la sistemazione di questa sezione del sito.
> 
> Ciao, intendi che nel caso una categoria abbia sia documenti che sottocategorie associate, trovandosi nella pagina con i filtri sulla sinistra, premendo sulla categoria non si vedono gli articoli associati direttamente alla categoria stessa ma si apre solo la tendina con le sottocategorie?

Ciao, sì esatto, proprio quello

**Comment by Prancingkiller** [comment]
> > > Grazie @Prancingkiller, ho sostituito i file come da indicazioni. Subito non funzionava, ma stavo usando una cartella del tema che avevo rinominato per crearne una copia. Inserendo invece i file nella cartella del tema aggiornato sovrascrivendo i file, e attivandolo, non ricevo più il messaggio di errore. L'unica cosa che ho notato è che nel filters-amministrazione.php se ci sono menu di terzo livello, il secondo livello non apre più la pagina contenente gli articoli, ma solo il menu sotto, è una cosa che capita solo a me? Intanto grazie ancora per la risposta e per il prezioso contributo per la sistemazione di questa sezione del sito.
> > 
> > 
> > Ciao, intendi che nel caso una categoria abbia sia documenti che sottocategorie associate, trovandosi nella pagina con i filtri sulla sinistra, premendo sulla categoria non si vedono gli articoli associati direttamente alla categoria stessa ma si apre solo la tendina con le sottocategorie?
> 
> Ciao, sì esatto, proprio quello

Ciao, penso che la pagina sia intesa per funzionare così, se ho delle sottocategorie non ho anche dei documenti all'interno della categoria genitore, non è complicato fare in modo che cliccando sulla categoria genitore si ricarichi la pagina visualizzando sulla destra tutti i documenti associati, però poi risulterebbe fastidioso nel caso in cui non ci sono documenti caricati nella categoria genitore e tutto quello che vuoi vedere sono le sottocategorie sulla sinistra

**Comment by vaniaweb** [comment]
> > > > Grazie @Prancingkiller, ho sostituito i file come da indicazioni. Subito non funzionava, ma stavo usando una cartella del tema che avevo rinominato per crearne una copia. Inserendo invece i file nella cartella del tema aggiornato sovrascrivendo i file, e attivandolo, non ricevo più il messaggio di errore. L'unica cosa che ho notato è che nel filters-amministrazione.php se ci sono menu di terzo livello, il secondo livello non apre più la pagina contenente gli articoli, ma solo il menu sotto, è una cosa che capita solo a me? Intanto grazie ancora per la risposta e per il prezioso contributo per la sistemazione di questa sezione del sito.
> > > 
> > > 
> > > Ciao, intendi che nel caso una categoria abbia sia documenti che sottocategorie associate, trovandosi nella pagina con i filtri sulla sinistra, premendo sulla categoria non si vedono gli articoli associati direttamente alla categoria stessa ma si apre solo la tendina con le sottocategorie?
> > 
> > 
> > Ciao, sì esatto, proprio quello
> 
> Ciao, penso che la pagina sia intesa per funzionare così, se ho delle sottocategorie non ho anche dei documenti all'interno della categoria genitore, non è complicato fare in modo che cliccando sulla categoria genitore si ricarichi la pagina visualizzando sulla destra tutti i documenti associati, però poi risulterebbe fastidioso nel caso in cui non ci sono documenti caricati nella categoria genitore e tutto quello che vuoi vedere sono le sottocategorie sulla sinistra

Ciao, sì hai ragione. Io eviterei proprio di inserire il terzo livello per un discorso anche di accessibilità, ma se la normativa lo richiede non rimane che adeguarsi. Ho fatto qualche tentativo e sono riuscita ad inserire il link però poi verrebbe voglia di cambiare anche il formato e rendere il secondo livello un radio button come per la categoria sotto. Per adesso non ho riportato le modifiche nel sito ufficiale, ma ho solo provato in un ambiente di test. Oltre all'aspetto tecnico ci sono altre considerazioni di cui tenere conto sicuramente. Grazie ancora per il confronto e per tutto il lavoro fatto
