### ISSUE TITLE
notizie in home non si dispongono in orizzontale quando sono disabilitate circolari ed eventi

### ISSUE THREAD

**Issue by mrnooz** [italia/design-scuole-wordpress-theme#570]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-scuole-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-scuole-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

se io NON mostro in home circolari ed eventi ma solo novità e magari ne metto ad esempio 6  tutte le news vengono mostrate in un unica colonna tutta sulla sinistra. Sarebbe logico invece mostrarle in orizzontale come hanno fatto ad esempio in https://comprensivocarugate.edu.it/ ma senza dover andare a modificare il loop del template come hanno fatto loro

### Includi link o screenshot

https://comprensivocarugate.edu.it/

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

2.7.0

**Comment by sviluppoRobyone** [comment]
Chiediamo di testare il miglioramento e ricevere un riscontro

**Comment by mrnooz** [comment]
testato pocanzi e funziona perfettamente !
grazie @sviluppoRobyone  avete fatto un ottimo lavoro
