### ISSUE TITLE
Breadcrumb organizzazione

### ISSUE THREAD

**Issue by leosamuele221** [italia/design-scuole-wordpress-theme#573]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-scuole-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-scuole-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Salve,
gli assertori hanno contestato che andando (dalla pagina principale) nel menu scuola > organizzazione > dirigente scolastico la breadcrumb non corrisponde con la pagina visitata https://www.icsantamargheritame.edu.it/struttura/i-c-santa-margherita/dirigente-scolastico/

### Includi link o screenshot

![image](https://github.com/italia/design-scuole-wordpress-theme/assets/81746302/4a0d72e4-ed51-48f1-905e-a0437073c9f6)

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

2.7.0

**Comment by vcoopcsc** [comment]
Il rapporto di dipendenza tra i content type organizzazione crea quel tipo di breadcrumb, se non vuoi metterci mano a livello tecnico, puoi anche provvedere a modificare tu andando nel backend e alla voce La struttura dipende da un'altra struttura mettere "Nessuno"

**Comment by leosamuele221** [comment]
Perfetto grazie
