### ISSUE TITLE
Tipologia content type documenti non presente nella pagina del documento

### ISSUE THREAD

**Issue by vcoopcsc** [italia/design-scuole-wordpress-theme#575]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-scuole-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-scuole-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Gli asseveratori contestano la mancanza della tipologia del content type "Documento" nella pagina singola del contenuto. 
Bisognerebbe aggiungerla

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

2.7.0

**Comment by Simsimus** [comment]
Mi associo alla richiesta
