### ISSUE TITLE
Ricerca in "Tutto il sito" premendo invio

### ISSUE THREAD

**Issue by LucaDiba** [italia/design-scuole-wordpress-theme#58]
Effettuando una ricerca, se invece di premere il pulsante "Cerca in tutto il sito" si preme il tasto invio, la ricerca viene effettuata soltanto nella sezione "scuola".
Suppongo che questo avvenga perché il primo pulsante è quello relativo alla scuola, quindi non escludo che il risultato possa essere differente a seconda del browser utilizzato.
Intuitivamente, se effettuassi una ricerca e premessi invio, mi aspetterei una ricerca completa in tutte le sezioni del sito.

**Comment by vcoopcsc** [comment]
Seguo!

**Comment by astagi** [comment]
Risolto nella nuova versione del tema disponibile (2.0.0)
