### ISSUE TITLE
Errore critico Wordpress welcome.php on line 21

### ISSUE THREAD

**Issue by Cate55** [italia/design-scuole-wordpress-theme#584]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-scuole-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-scuole-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Buongiorno vorrei segnalare che con l'aggiornamento ultima release 2.8.0 viene generato un errore critico con irraggiungibilità del sito.
A mio avviso il problema credo sia nel file welcome.php rigo 21 modificato con la PR "Aggiunta menu utente in bacheca #548"  Viene  utilizzato l'argomento denominato "context" in modo errato nella chiamata alla funzione wp_add_dashboard_widget. L'errore specifico è causato dalla parte context: 'side'. Invece di usare un'etichetta di contesto come argomento, avrei impostato il contesto direttamente come uno dei parametri accettati dalla funzione.
`function dsi_add_dashboard_widget() {

    wp_add_dashboard_widget('dsi_circolari_widget', 'Circolari da Leggere / Firmare', 'dsi_circolari_dashboard_widget');

    wp_add_dashboard_widget('dsi_circolari_signed_widget', 'Circolari Firmate', 'dsi_circolari_signed_dashboard_widget');

    wp_add_dashboard_widget('dsi_menu_utente_widget', 'Menu utente', 'dsi_menu_utente_dashboard_widget', 'side');
}
`
Ho verificato in un ambiente di test e otteniamo in bacheca il messaggio di aiuto se il Menu Utente non viene creato, mentre se è creato abbiamo il widget come riportato nelle schermate presenti qui
https://github.com/italia/design-scuole-wordpress-theme/pull/548
![welcome-php](https://github.com/italia/design-scuole-wordpress-theme/assets/9642253/acb96bc5-3583-402b-b516-b0e8540e2c21)

### Includi link o screenshot

Prima della correzione
![screenshot-errore-welcome](https://github.com/italia/design-scuole-wordpress-theme/assets/9642253/69b6fb7e-93f4-4f02-b67e-dabb1c91fa19)
Dopo la correzione: in bacheca widget con le indicazioni
![messaggio di aiuto](https://github.com/italia/design-scuole-wordpress-theme/assets/9642253/16477555-2b92-4c65-bed3-a89d1a4fc600)
Dopo la creazione del menu
![menu-utente](https://github.com/italia/design-scuole-wordpress-theme/assets/9642253/0f94f178-b28e-434b-8e92-392c3b4c285c)

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Chrome, Firefox, Microsoft Edge

### Che versione del tema stai utilizzando?

2.8.0

**Comment by rcoopcsc** [comment]
Ciao oltre alle modifiche che suggerisce @Cate55 ho fatto alcuni test anche io e mi sembra ci sia un altro problema in /inc/utils.php. Alla linea 526.  la funzione `dsi_get_post_types_grouped` per come è scritta nella versione 2.8.0 genera un fatal error: _Call to undefined function is_plugin_active()_  nel frontend.
Se rimetto tutta quella funzione come era fino alla versione 2.7.0  (la ricopio sotto per comodità) mi sembra andare senza ulteriori problemi. 

` ` ` 
function dsi_get_post_types_grouped($type = "", $tag = false){
	if($type == "")
		$type = "any";
	if($type === "school")
		$post_types = array("documento", "luogo", "struttura", "page", "amm-trasparente");
	else if($type === "news")
		$post_types = array("evento", "post", "circolare");
	else if($type === "education")
		$post_types = array("scheda_didattica", "scheda_progetto"); // todo: programma materia 		$post_types = array("programma_materia", "scheda_didattica", "scheda_progetto");
	else if($type === "service")
		$post_types = array("servizio", "indirizzo");
	else
		$post_types = array("evento", "post","circolare", "documento", "luogo", "scheda_didattica", "scheda_progetto", "servizio", "indirizzo", "struttura", "page", "amm-trasparente"); // todo: programma materia $post_types = array("evento", "post","circolare", "documento", "luogo", "materia", "programma_materia", "scheda_didattica", "scheda_progetto", "servizio", "struttura", "page");

	// rimuovo post types che non hanno la categoria
	if($tag){
		if (($key = array_search("page", $post_types)) !== false) {
			unset($post_types[$key]);
		}

	}
	return $post_types;

}
` ` `

**Comment by Simsimus** [comment]
Anche nel mio caso si è verificato lo stesso problema... Per il momento sono ritornato alla versione 2.7.0

**Comment by studioalexsa** [comment]
Chiedo scusa, in attesa delle correzioni della release 2.8.0, qualcuno ha testato il tema su MariaDB 10.6 o su MySQL 8?
Attualmente sto usando MySQL 5.7 ma vorrei fare il passaggio (tra poco sarà obbligato...).
Grazie

**Comment by rcoopcsc** [comment]
Se non ci sono altre correzioni suggerite o errori da segnalare, preparo la PR. @Cate55 avvisami se va bene così o serve altro, grazie.

**Comment by Cate55** [comment]
> Se non ci sono altre correzioni suggerite o errori da segnalare, preparo la PR. @Cate55 avvisami se va bene così o serve altro, grazie.

Per me va benissimo, al momento non ho riscontrato problemi con la 2.8.0! Grazie mille

**Comment by luigibugliani** [comment]
Passando dalla versione 2.7.0 a 2.8.0, rilevo anch'io un problema. Le pagine mostrano solo l'header come da immagine.
![immagine](https://github.com/italia/design-scuole-wordpress-theme/assets/119619030/eb6f8b64-6838-46a0-8395-09019daff514)
