### ISSUE TITLE
Calendario sparito di nuovo

### ISSUE THREAD

**Issue by anitamaccio** [italia/design-scuole-wordpress-theme#59]
Salve, mi sono accorta stamattina, purtroppo non mi sono resa conto del momento esatto in cui è successo, che il calendario è sparito dalla homepage, si vede solo il link 'Vedi tutti'.
Se in configurazione metto di visualizzare l'ultimo evento, si visualizza regolarmente, ma se metto mostra il calendario, si vede solo quel link, il calendario non si vede più.
Ho provato a disattivare  e riattivare il modulo Ginger, la volta scorsa il problema era quello, ma stavolta non ha funzionato, il calendario non appare né attivandolo né disattivandolo.
Non si vede più in homepage, e non si vede nemmeno più nella pagina https://www.icvs.edu.it/evento/.
Grazie e cordiali saluti
Anita Macciò

**Comment by GAETANOFRISCIA** [comment]
Confermo che anche noi abbiamo lo stesso problema!
Saluti
