### ISSUE TITLE
Numero di protocollo dell'Albo Online

### ISSUE THREAD

**Issue by gianlucaaiello56** [italia/design-scuole-wordpress-theme#601]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-scuole-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-scuole-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

L'albo pretorio **_non_** permette di inserire manualmente il numero di protocollo del documento. Vorrei sapere come fare per inserire manualmente il numero di protocollo del documento che vado ad inserire.

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

2.8.1.

**Comment by Simsimus** [comment]
Buongiorno,
il numero di protocollo (e relativa data) è quello presente a fondo pagina, da non confondere con il campo "Numerazione Progressiva Annuale" che una numerazione progressiva di pubblicazione non modificabile.
Saluti

**Comment by gianlucaaiello56** [comment]
Grazie per la risposta.
