### ISSUE TITLE
Togliere "Nessuno" nella tipologia della circolare

### ISSUE THREAD

**Issue by ricboc** [italia/design-scuole-wordpress-theme#618]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-scuole-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-scuole-wordpress-theme/blob/main/CONTRIBUTING.md)

### Proposta

Suggerisco di togliere "Nessuno" nella tipologia di circolare e lasciare solo le opzioni obbligatorie previste.
Per farlo basta modificare il file inc/admin/circolare.php tra la riga 85 e 86 aggiungendo `'show_option_none' => false,`

Così facendo verrebbe tolto "Nessuno" e di default, non essendo selezionata la tipologia, se prima del salvataggio ci dimentichiamo di selezionarla, il sistema ci obbliga ad inserirla.

### Motivazione e contesto

Se in tipologia circolare ci si dimentica di scegliere una tipologia tra quelle presenti e si lascia "Nessuno" che è impostato di default, essendo il campo obbligatorio, il sistema non inserisce la tipologia tra le opzioni presenti.

**Comment by EasyTeamSrl** [comment]
Mi sembra una buona proposta, che permette di ovviare al problema, frequente, della dimenticanza della tipologia.

**Comment by vcoopcsc** [comment]
Sono d'accordo!
