### ISSUE TITLE
con wordpress 5.7 e l'ultima versione PHP si visualizzano warning nel tema

### ISSUE THREAD

**Issue by teox79** [italia/design-scuole-wordpress-theme#62]
Utilizzando l'ultima versione di wordpress 5.7 e di conseguenza l'ultima versione di php vengono visualizzati dei warnig.
Ho provato con la versione 5.1.8 di wordpress che utilizza la vecchia versione di php e non ho riscontato il problema.
Allego screen[
![warning php](https://user-images.githubusercontent.com/12935780/111322931-b9b0ec80-8669-11eb-87fb-e0a6dcaa709e.png)
](url)

**Comment by ateicos** [comment]
Io ho modificato il codice di verifica dello stato IF in questo modo
`if( isset( $_GET) && isset( $_GET['post'] ) && is_numeric($_GET['post'])) {`

**Comment by webgrafia** [comment]
Buondì, se fate una pull request con questi fix li pubblico nel tema  così da risolvere la questione a monte

**Comment by alexghirelli** [comment]
@webgrafia This PR can be related to this issue #67.

**Comment by astagi** [comment]
Grazie @alexghirelli ! Chiudo. Segnalo nuova versione del tema disponibile (2.0.0)
