### ISSUE TITLE
Categoria dell'articolo

### ISSUE THREAD

**Issue by gianlucaaiello56** [italia/design-scuole-wordpress-theme#622]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-scuole-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-scuole-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Buon pomeriggio, vorrei segnalare che all'installazione del tema non risulta più la voce "Categoria" nella sezione "articoli" .
Io credo sia un aspetto importante per gli articoli ,oltre all'argomento.
Sarebbe possibile sapere come inserire la categoria ?
Vi ringrazio anticipatamente.

### Includi link o screenshot

![image](https://github.com/italia/design-scuole-wordpress-theme/assets/125404884/5b0ddc46-e273-41d2-be3b-d6ec34f8a577)
(manca la voce "Categoria")

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Chrome

### Che versione del tema stai utilizzando?

2.9.0.

**Comment by Simsimus** [comment]
Buongiorno, forse ti stai confondendo perché se per categoria intendi "Avvisi, Articoli, Notizie, ecc" quelle sono le tipologie e non le categorie...

**Comment by marcorubin** [comment]
Le categorie sono state nascoste dal tema

**Comment by zetareticoli** [comment]
@gianlucaaiello56 Nella pagina "Tipologia" puoi gestire quello che cerchi.
