### ISSUE TITLE
Domanda: il progetto è stato abbandonato?

### ISSUE THREAD

**Issue by Karolus81** [italia/design-scuole-wordpress-theme#63]
Dal momento che non vedo aggiornamenti da 3 mesi, vorrei sapere se il progetto sia stato abbandonato o meno.

Cordialità.

**Comment by webgrafia** [comment]
ciao @Karolus81 ,
il progetto è nato come progetto finanziato dal vecchio dipartimento per la Trasformazione Digitale (oggi MIT).
Al momento non ci sono commesse per la sua evoluzione, ma vive come progetto open-source, i cui bug sono (possono essere) gestiti dalla comunità dei developer.
Personalmente quando ho tempo e modo faccio piccoli interventi correttivi dei bug qui segnalati, ed essendo ancora uno dei gestori del progetto github approvo eventuali pull request che arrivano dagli utilizzatori.
Quindi in progetto non è totalmente abbandonato, e non è escluso che il Ministero riprenda in carico le eventuali evoluzioni.

Saluti
