### ISSUE TITLE
l'aggiornamento a 2.9 continua a resettare i menù

### ISSUE THREAD

**Issue by mrnooz** [italia/design-scuole-wordpress-theme#630]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-scuole-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-scuole-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Aggiornando alla versione 2.9 si perdono le impostazioni dei menu. Capisco che esse siano necessarie per l'asseverazione, ma le scuole desiderano poter modificarle in base alle proprie esigenze. 

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

2.9.0

**Comment by psantagati** [comment]
E' un problema anche delle versioni precedenti, se si attiva o disattiva il tema, se si aggiorna, se si sposta in una sotto cartella, l'effetto è che si perdono le "opzioni base" delle configurazioni, si resettano i menù, e si perdono i collegamenti ai media (loghi, gallerie e documenti).
Ho paura che dipenda più da wordpress che dal tema, in quanto sono dati che si memorizzano nella tabella option.

**Comment by zetareticoli** [comment]
@mrnooz in questa PR https://github.com/italia/design-scuole-wordpress-theme/pull/171 il problema del tema child era stato risolto

**Comment by psantagati** [comment]
Si non si trattava esattamente di un problema legato al tema child ma all'aggiornamento del tema principale.

Se non ho capito male la procedura di aggiornamento corretta è la seguente:
- "installare" il tema principale
- creare il tema child che includa style.css e function.php per le personalizzazioni
- attivare il tema child
Quando viene rilasciata una nuova versione del tema basta fare un upload con sovrascrittura nella cartella del tema principale (senza eliminare la vecchia, senza disattivare il tema child)

Solo in questo caso non si perdono configurazioni, media e menù.

**Comment by mrnooz** [comment]
>   Quando viene rilasciata una nuova versione del tema basta fare un upload con sovrascrittura nella cartella del tema principale (senza eliminare la vecchia, senza disattivare il tema child)

@psantagati ho  fatto così ma successivamente ho spento e riacceso il child per il fatto che era cambiato il modo di gestire le news automatiche in orizzontale e volevo testare la nuova home.
Il cambio da child a tema ufficiale non mi pare mi abbia mai resettato le impostazioni, è una cosa piuttosto fastidiosa così.

grazie @zetareticoli magari intanto sarebbe da indicarlo da qualche parte per chi si appresta ad aggiornare

**Comment by psantagati** [comment]
@mrnooz perché hai avuto la necessità di disattivare e riattivare il child? Non vedevi gli aggiornamenti del 2.9?

**Comment by psantagati** [comment]
chiaro. Quindi si può supporre che commentando il codice "personalizzato" del child invece di disattivare e riattivare il template può aggirare il problema...

**Comment by mrnooz** [comment]
@psantagati Probabilmente, ma non è detto che un child sia per sempre. 
Credo sia un ragionevole desiderio di consistenza poter switchare a piacere col tema ufficiale senza incorrere in problemi, così come accade con ogni altro tema WP. Si potrebbe implementare, sennò, un salvataggio o auto-salvataggio delle impostazioni, così che gli sprovveduti come me non debbano rifare la configurazione. 

So già che al prossimo aggiornamento sarò tentato di disabilitare il child, è più forte di me... ne ho già voglia adesso! 😄

**Comment by psantagati** [comment]
Il problema è che dipende anche da wordpress, non solo dal tema. Infatti a me è capitato anche con altri temi. Le info sono memorizzate nella tabella option del db. Credo che possiamo metterci il cuore in pace

**Comment by mrnooz** [comment]
@psantagati e vabbè
