### ISSUE TITLE
Se cancello gli argomenti la home non viene visualizzata correttamente

### ISSUE THREAD

**Issue by vcoopcsc** [italia/design-scuole-wordpress-theme#636]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-scuole-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-scuole-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Se ho impostato gli argomenti da mostrare in home e li cancello da Articolo->argomenti, la home non viene visualizzata correttamente (scompare il footer e non si riesce più ad accedere). 
Mi è chiaro che per evitare il problema bisogna procedere PRIMA ad eliminare i link agli argomenti in evidenza da Configurazione ->Home->sezione argomenti, ma sarebbe comunque meglio che non si creasse questo problema anche perché in tempo di asseverazione ciò causa il fallimento del processo per la mancanza degli elementi obbligatori (provacy policy, dichiarazione di accessibilità, ecc.). 

### Includi link o screenshot

Scomparsa barra nera in cima e impossibilità di accedere al backend<img width="1118" alt="image" src="https://github.com/italia/design-scuole-wordpress-theme/assets/92174841/3d0ddc3f-1210-4d86-8e40-f3e81ed0fcb2">
Sezione didattica visualizzata male e scomparsa del footer 
<img width="1128" alt="image" src="https://github.com/italia/design-scuole-wordpress-theme/assets/92174841/6de6c1a6-1aac-4dcc-8270-8bedf930ddd1">

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

2.9.0

**Comment by sviluppoRobyone** [comment]
Abbiamo apportato la correzione all'interno dei cambiamenti proposti nella #623
