### ISSUE TITLE
Se un luogo viene eliminato tutte le pagine che avevano un collegamento a quel luogo si rompono

### ISSUE THREAD

**Issue by vcoopcsc** [italia/design-scuole-wordpress-theme#637]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-scuole-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-scuole-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Se la scuola elimina un luogo, tutte le pagine collegate a quel luogo hanno bug: il footer scompare, i menu principali non sono navigabili, il menu a sinistra non è navigabile, non ci si riesce a loggare

### Includi link o screenshot

<img width="1052" alt="image" src="https://github.com/italia/design-scuole-wordpress-theme/assets/92174841/88bc4f50-edc0-42fe-99cb-f22e48c0d8b5">
<img width="958" alt="image" src="https://github.com/italia/design-scuole-wordpress-theme/assets/92174841/4ac4571b-539d-485b-8011-8bc42d7e1ac9">

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

2.9.0

**Comment by rcoopcsc** [comment]
ciao @zetareticoli, alla linea 165 di template-parts/luogo/card.php non trova $posizione_gps["lat"] e quindi si rompe all'href del link a google maps.

Ho risolto wrappando tutto il blocchetto di codice per mostrarlo solo se non è vuota la variabile $posizione_gps["lat"]) come da codice sotto. 

```

<?php if (!empty($posizione_gps["lat"])) : ?>
								<li>
									<div class="location-title">
										<svg class="icon svg-marker-simple" style="width: 14px; height: 14px;">
											<use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#svg-marker-simple"></use>
										</svg>
									</div>
									<div class="location-content">
										<p>
											<a href="https://www.google.com/maps/dir/'<?php echo $posizione_gps["lat"]; ?>,<?php echo $posizione_gps["lng"]; ?>'/@<?php echo $posizione_gps["lat"]; ?>,<?php echo $posizione_gps["lng"]; ?>,15z?hl=it" target="_blank"><?php _e("Naviga su Google Map", "design_scuole_italia"); ?></a>
										</p>
									</div>
								</li>
<?php endif; ?>

```

Se vuoi faccio la pr ed almeno quella parte si risolve. Dico "almeno" perchè rimarrebbe ancora il titoletto "Luoghi in cui viene erogato il servizio" nei template delle pagine singole.

**Comment by zetareticoli** [comment]
Sì, direi che puoi aprire una PR e, se riesci ad inserire anche il controllo sul titolo sarebbe ottimo 🙌

**Comment by rcoopcsc** [comment]
ciao @zetareticoli abbiamo corretto a monte il codice che generava l'errore, non caricando del tutto la card quando il luogo non esiste. Il controllo sul titolo a ben vedere non è ecessario perchè basta risalvare la pagina (che prima conteneva il riferimento al luogo successivamente cancellato) per non fare comparire neanche più il titoletto nel frontend.
