### ISSUE TITLE
Problema GDPR Privacy pagina Le Persone

### ISSUE THREAD

**Issue by vincenzomicrotech** [italia/design-scuole-wordpress-theme#646]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-scuole-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-scuole-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Buongiorno,

Su tutte le versioni dei template abbiamo riscontrato un importante problema di privacy. 

In particolare creando gli utenti nel sito per dare accesso all'area riservata Personale Scolastico, se gli utenti sono assegnati al "Ruolo nell'organizzazione" in modo corretto, quindi, come dirigente scolastico, Personale non docente e Personale Docente, vengono tutti visualizzati nella pagina "Le persone". 

Anche se questo non è propriamente un bug, risulta essere serio problema dal punto di vista privacy rendere disponibile al pubblico i nomi e l'elenco di tutto il personale scolastico senza alcun motivo.

E' evidente che alcuni ruoli come quelli del DS e del DSGA debbano essere pubblici ma non è altrettanto evidente che ad esempio il nome del singolo collaboratore ATA ha bisogno di essere pubblico sul sito.

Questo non accade se "Ruolo nell'organizzazione" per il singolo utente è impostato su "nessuno" o "altro".

Abbiamo fixato questo problema nel nostro child, modificando la pagina "Le Persone" rendendo pubblico solo il DS e il DSGA, sarebbe il caso di intervenire a monte e/o dare la possibilità di avere un flag per rendere pubblico o privato un account, in modo che il singolo utente può scegliere se comparire o meno nell'elenco.

Nonostante questo fix non è affatto detto che questi nomi e questo elenco non sia indicizzabile dai motori di ricerca aggravando in modo molto serio la privacy del personale scolastico ed esponendo la scuola e i DS a ricorsi e segnalazioni.

Si sottolinea che il nome è un dato personale mentre numero di telefono e email sono dati particolari. La diffusione di dati personali ed eventuale diffusione di dati particolari deve essere sempre commisurata ai principi di stretta necessità indispensabilità e non eccedenza delle finalità. I nostri DPO non ravvisano finalità per cui debba essere necessario la pubblicazione di suddetti nominativi e/o nei numeri di telefono e email pubblici (come specificato in ogni profilo utente). Comunque l'ente per poterli pubblicare deve acquisire preventivamente un consenso.

Di seguito 2 screenshot uno del nostro sito di testing in cui sono visualizzati tutti i ruoli e uno screenshot di una scuola in cui è visibile un lungo elenco di tutto il personale scolastico.

Grazie

### Includi link o screenshot

![ksnip_20240318-152248](https://github.com/italia/design-scuole-wordpress-theme/assets/107103113/cf899e7e-488d-4eee-92a2-b4d600ac397e)
![ksnip_20240318-152812](https://github.com/italia/design-scuole-wordpress-theme/assets/107103113/ed1be842-fb8f-4738-82a9-5b61cfa69c27)

### Su quale sisitema operativo stai riscontrando il problema?

Linux

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

TUTTE

**Comment by zetareticoli** [comment]
Resolved in #634
