### ISSUE TITLE
Sottotitolo non conforme alle linee guida

### ISSUE THREAD

**Issue by topperblues** [italia/design-scuole-wordpress-theme#655]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-scuole-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-scuole-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Buongiorno,
ho realizzato due siti web con progetto PNRR e siamo in fase di verifica.
Ci hanno segnalato che i sottotitoli della sezione struttura organizzativa, generati automaticamente selezionando i "Percorsi di studio della Scuola", non sono conformi alle linee guida poichè in maiuscolo.
Di conseguenza non superiamo il collaudo.
E' una modifica banale e modificherò il template per adeguarlo a quanto richiesto:
https://github.com/italia/design-scuole-wordpress-theme/blob/main/single-indirizzo.php#L103
```
 echo strtoupper($percorso->name);
```
in
```
 echo ucfirst($percorso->name);
```
Poichè non mi sembra di aver trovato altre segnalazioni del genere in giro, mi chiedo se sia una modifica utile per tutti (e quindi apro una Pull Request per la modifica del codice) o se è un caso che riguarda solo noi, per cui modifico solo la nostra istanza.
Saluti. 

### Su quale sisitema operativo stai riscontrando il problema?

Windows, macOS, Android, iOS, Linux

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

2.10.0

**Comment by sviluppoRobyone** [comment]
Mi sto chiedendo, in base a cosa hanno segnalato? 
Nel modello architetturale non ci sono riferimenti a maiuscolo e minuscolo, stessa cosa nel template HTML (non c'è quello dell'indirizzo)

Ora, le linee guida di linguaggio, suggeriscono di evitare il maiuscolo (non è quindi vietato), ma sinceramente rimango perplesso che questa indicazione sia sufficiente a non far superare l'asseverazione.

A meno che non mi sia perso qualche passaggio...

**Comment by topperblues** [comment]
Non saprei, per completezza riporto il testo della segnalazione anonimizzato:

- Tutti i titoli delle pagine del sito devono essere scritte in carattere minuscolo, ad esempio all'interno della pagina [XXXX] il titolo maiuscolo "SCUOLA SECONDARIA DI SECONDO GRADO" deve essere modificato o eliminato.
