### ISSUE TITLE
Documenti in evidenza

### ISSUE THREAD

**Issue by Simsimus** [italia/design-scuole-wordpress-theme#667]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-scuole-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-scuole-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Volevo segnalare che se un documento viene messo in evidenza e la relativa tipologia di appartenenza dovesse avere un nome lungo, tale documento verrebbe mostrato in home tagliato perchè il testo della tipologia viene rappresentato in una sola riga invece che due.

### Includi link o screenshot

![Evidenza](https://github.com/italia/design-scuole-wordpress-theme/assets/108821309/14f35625-b15b-405f-83fc-1c1f6a26022e)

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

2.10.0

**Comment by zetareticoli** [comment]
Ciao @Simsimus, a quanto pare se il testo del badge è più lungo dello spazio a disposizione, ciò fa sì che anche il titolo prosegue sulla stessa riga.

Il testo di un badge non può andare a capo, ma eventualmente può essere troncato con la proprietà `text-overflow`
