### ISSUE TITLE
Tabelle incarichi in amministrazione trasparente

### ISSUE THREAD

**Issue by maupao** [italia/design-scuole-wordpress-theme#680]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-scuole-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-scuole-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Buonasera, inserendo lo shortcode [ammap tipo="incarico" anno="2024" incarico="2"] in un documento per amministrazione trasparente si dovrebbe generare una tabella che raccoglie tutti gli incarichi inseriti dalla relativa. Quello che avviene inserendo lo shortcode è che compare l'intestazione della tabella ma non viene visualizzato nessuno degli incarichi inseriti. Inoltre non vengono più visualizzate le strutture collegate al documento. Una funzione simile è quella per generare la tabella con i bandi di gara, ma in quel caso lo short code restituisce correttamente la tabella e i riferimenti alle strutture rimangono. Purtroppo non essendo un programmatore non saprei dove e come intervenire.

### Includi link o screenshot

https://www.icsbarzano.edu.it/documento/incarichi-conferiti-a-dipendenti-di-altre-amministrazioni-anno-2024/

### Su quale sisitema operativo stai riscontrando il problema?

Linux

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

2.9.0

**Comment by maupao** [comment]
Aggiungo che mettendo lo shortcode scompare anche la barra nera che permette di passare nel backend di wordpress per chi è autenticato.

**Comment by maupao** [comment]
Si, il plugin di base è quello, ho visto che è forkato qui: https://github.com/italia/plugin_wp_amministrazione_aperta 

Infatti ho visto che è praticamente fermo solo che è una funzione molto utile alle scuole che usano il sito per pubblicare sotto forma di tabella gli incarichi. È possibile aggiornare quel plugin? Io non sono un programmatore e non saprei dove mettere le mani.

**Comment by maupao** [comment]
Quindi mi stai dicendo che è meglio che ponga la questione nel repository del plugin, perchè il probema è lì. Esatto?

**Comment by Simsimus** [comment]
Se la sua scuola vuole utilizzare tale sistema allora deve contattare lo sviluppatore del plugin Marco Milesi (https://profiles.wordpress.org/milmor/) e chiedere se ha in programma di aggiornarlo per le attuali versioni di wordpress. 
Però credo che il sistema corretto che le scuole dovrebbero adottare sia quello di inserire tali dati su PerlaPA in modo da ottenere tale elenco direttamente ed in automatico sul portale ministeriale https://consulentipubblici.dfp.gov.it.

**Comment by maupao** [comment]
Grazie per i consigli, riprovo a contattare @milesimarco e sentire come intende procedere e poi consiglio la scuola di procedere in tal senso.
