### ISSUE TITLE
Problemi di accessibilità pagina "Luoghi"

### ISSUE THREAD

**Issue by vcoopcsc** [italia/design-scuole-wordpress-theme#692]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-scuole-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-scuole-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

C'è un salto di H, da H1 "I Luoghi" si passa ad un H4 delle tipologie. Dovrebbe essere invece H1 "I luoghi" e H2 le tipologie

### Includi link o screenshot

<img width="870" alt="image" src="https://github.com/italia/design-scuole-wordpress-theme/assets/92174841/d0a98dbb-42b6-428a-9a24-15248e9dc43f">

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

2.12.0

**Comment by zetareticoli** [comment]
Ciao @vcoopcsc , hai per caso verificato che lo stesso problema si presenta nei templates statici?
