### ISSUE TITLE
Salto di H schede progetto

### ISSUE THREAD

**Issue by vcoopcsc** [italia/design-scuole-wordpress-theme#709]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-scuole-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-scuole-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Descrizione progetto è un H3, documenti è un H5 e dovrebbe essere un H3

### Includi link o screenshot

<img width="225" alt="image" src="https://github.com/user-attachments/assets/3593ca8c-914f-4e20-90c3-190d4b9a52b5">

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

2.12.1

**Comment by zetareticoli** [comment]
Ciao @vcoopcsc, non ho trovato in `single-scheda_progetto.php` il tag `<h5>` date segnalato. Sapresti dirmi dove hai individuato il bug? Grazie

**Comment by vcoopcsc** [comment]
@zetareticoli chiedo scusa per la svista, non ci sono errori, chiudo la issue
