### ISSUE TITLE
Calendario in homepage e in filtri non visibile

### ISSUE THREAD

**Issue by micfio** [italia/design-scuole-wordpress-theme#71]
Nuova installazione e configurazione,calendario non visibile.

**Comment by micfio** [comment]
Se gestisco la personalizzazione del tema con anteprima in tempo reale il calendario viene visualizzato correttamente.Mi potete aiutare? Grazie

**Comment by micfio** [comment]
Risolto con 👍 
Another thing is that WordPress already includes a copy of jQuery. Here is how you can load up jQuery in your theme the smart (and intended) way. Put the following code in your header.php file in the <head> section:

<?php wp_enqueue_script("jquery"); ?>

<?php wp_head(); ?>

**Comment by GAETANOFRISCIA** [comment]
Ho aggiunto wp_enqueue_script("jquery"); sopra il tag  “</head>” del file header.php ma niente il calendario non viene mostrato.
Naturalmente mostra gli eventi in home è impostato su si, mostra il calendario.
Gaetano Friscia

**Comment by micfio** [comment]
![16287972493647262497551559742465](https://user-images.githubusercontent.com/20971749/129258770-941a3383-297c-47d8-af4e-8353c3ac2ab6.jpg)

**Comment by GAETANOFRISCIA** [comment]
Niente da fare, anzi ho peggiorato la situazione perché cancellando la riga compare questo mess:
le tue modifiche al codice PHP sono state annullate a causa di un errore alla linea 2 del file wp-content/themes/design-scuole-wordpress-theme-master/template-parts/evento/card.php. Correggi e prova a salvare nuovamente.
syntax error, unexpected '$'
Ho controllato e la riga due è quella originale del tema

**Comment by GAETANOFRISCIA** [comment]
Sono riuscito a cancellare la riga, <?php wp_enqueue_script("jquery"); ?>
non risolveva il problema anzi se decidevo di mostrare solo gli eventi senza calendario quando aprivo il sito compariva in mess di errore
