### ISSUE TITLE
Delay invio circolari

### ISSUE THREAD

**Issue by fabrman** [italia/design-scuole-wordpress-theme#715]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-scuole-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-scuole-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Nel momento in cui si pubblica una circolare, l'invio dell'avviso agli utenti registrati viene inviato con ritardo che va da alcune ore a giorni. Viene anche ripetuto l'invio.
Il problema si è presentato con l'avvio del nuovo anno scolastico.

### Su quale sisitema operativo stai riscontrando il problema?

Windows, macOS, Android, iOS

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

2.6

**Comment by zetareticoli** [comment]
Ciao @fabrman, il problema da te segnalato non riguarda nello specifico il tema WP del modello ma con ogni probabilità un disservizio tecnico dei server su cui è ospitato.
