### ISSUE TITLE
Disfunzione configurazione

### ISSUE THREAD

**Issue by Cate55** [italia/design-scuole-wordpress-theme#72]
Buongiorno Marco ho attivato il tema su una configurazione probabilmente pasticciata e per la prima volta dopo varie installazioni tutte ottimamente riuscite, questa volta non riesco ad individuare la causa della disfunzione. Ti chiedo cortesemente un supporto.
Nell'area di configurazione tab Home mi dà errore critico senza la possibilità di selezionare gli articoli, ho eseguito prima di chiedere un  help varie procedure per escludere:
-versione php obsoleta
-incompatibilità plugins (li ho disattivati tutti)
-reinstallazione di Wordpress
-reinstallazione del tema
-disattivazione del child
Ho eseguito un debug l'errore indicato fa riferimento al fatto che le funzioni PHP richiamate dal file meta.php eseguono operazioni tali da richiedere più memoria di quella disponibile per il  piano hosting, ma attualmente sono impostati 512 mega di memory_limit (ho altre installazioni con il tuo tema sullo stesso hosting ma non ho queste anomalie)
Ti invio uno screenshot se può essere utile per capire il mio problema. 
Grazie mille
caterina toccafondi
![Errori-debug](https://user-images.githubusercontent.com/9642253/124717007-02d0c900-df05-11eb-95eb-8aa3a025f8d8.png)

**Comment by webgrafia** [comment]
ciao Caterina, come hai già capito quell'errore è causato dallo sforamento della memoria.
Quel componente fa una ricerca sugli articoli per permetterne la selezione, immagino che sia una installazione in cui sono già presenti molti articoli.
Al momento l'unica cosa che puoi fare è chiedere alla server farm di aumentare la memoria. Tengo comunque questa issue aperta per valutare se c'è qualche ottimizzazione possibile sull'utilizzo della memoria di quel componente

**Comment by Cate55** [comment]
> ciao Caterina, come hai già capito quell'errore è causato dallo sforamento della memoria.
> Quel componente fa una ricerca sugli articoli per permetterne la selezione, immagino che sia una installazione in cui sono già presenti molti articoli.
> Al momento l'unica cosa che puoi fare è chiedere alla server farm di aumentare la memoria. Tengo comunque questa issue aperta per valutare se c'è qualche ottimizzazione possibile sull'utilizzo della memoria di quel componente

Marco ciao grazie infinite per la risposta, credo di aver risolto dipende dall'enorme quantità di file, hai ragione, nella migrazione ho importato le circolari, probabilmente più volte e oltre ad essere tantissime si sono duplicate e non sovrascritte. Inoltre circolari gestite da un altro plugin, adesso sto riorganizzando il tutto.
Adoro questo tema lo trovo di una potenzialità unica, grazie per tutto!
Buona serata.

**Comment by astagi** [comment]
Risolto nella nuova versione del tema disponibile (2.0.0)
