### ISSUE TITLE
Testo alternativo immagini contenuti articolo in home

### ISSUE THREAD

**Issue by vcoopcsc** [italia/design-scuole-wordpress-theme#728]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-scuole-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-scuole-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

l'alt delle immagini dei contenuti di tipo "articolo" compare soltanto nell'anteprima in home. Nella pagina specifica della novità invece non compare.

### Includi link o screenshot

Immagine di contenuto di tipo novità in home
<img width="1125" alt="image" src="https://github.com/user-attachments/assets/8f434235-20bc-4e7e-91d7-31b8e39d9a05">

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

2.13.0

**Comment by sviluppoRobyone** [comment]
In realtà la copertina è e dovrebbe essere decorativa, quindi anche in home rimossa e inserita col CSS (è necessario ricordare che i non vedenti devono leggere tutte e sole le informazioni strettamente necessarie... se il testo da leggere è troppo paradossalmente l'accessibilità diminuisce...)
