### ISSUE TITLE
Problemi con le circolari

### ISSUE THREAD

**Issue by Karolus81** [italia/design-scuole-wordpress-theme#73]
Buongiorno,
le circolari riservate al personale scolastico non compaiono nella bacheca degli utenti.
Nel front-office la visibilità funziona, ma nel back office la bacheca è sempre vuota e non arrivano notifiche agli utenti.

Ho provato di tutto, ma non ne vengo fuori. 

Che mi dimentichi io qualcosa?

**Comment by GAETANOFRISCIA** [comment]
Anche noi stiamo riscontrando lo stesso problema e non troviamo soluzioni.
Gaetano Friscia

**Comment by GAETANOFRISCIA** [comment]
Noi abbiamo risolto creando nuovi ruoli (con members) destinatari delle circolari. In destinatari della circolare selezioniamo in base al ruolo. Sembra funzionare, arrivano le notifiche e le circolari compaiono nella bacheca.

**Comment by grimaldistudio** [comment]
C'è un bug nel file inc/admin/circolari.php alla riga 295
`$users = get_objects_in_term( $gruppi_circolari, "gruppo-utente" );`

$users dovrebbe essere un array di oggetti con la proprietà ID. Invece il metodo get_objects_in_term restituisce un array di valori.
Ho risolto in questo modo:
```
}else if($destinatari_circolari == "gruppo"){
        $gruppi_circolari = dsi_get_meta("gruppi_circolari", '', $post->ID);
        $users = get_objects_in_term( $gruppi_circolari, "gruppo-utente" );

```

subito dopo aggiungi 
```
$usersRebuild = [];
        foreach ($users as $k=>$value) {
             $object = new stdClass();
             $object->ID = $value;
             $usersRebuild[$k] = $object;
        }
        $users = $usersRebuild ;
 
}
```

Non è elegantissimo ma spero sia di aiuto lo stesso.

**Comment by astagi** [comment]
Risolto nella nuova versione del tema disponibile (2.0.0).
