### ISSUE TITLE
Sezione "Le Persone" non mostra più nulla dalla versione 2.15.0 del tema

### ISSUE THREAD

**Issue by memorynoise** [italia/design-scuole-wordpress-theme#736]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-scuole-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-scuole-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Dopo aver aggiornato il tema design-scuole-wordpress-theme dalla versione 2.10 alla 2.15 sono spariti tutti i contenuti relativi a docenti, amministrazione e personale dalla pagina[ /scuola/le-persone/](https://www.liceosciasciafermi.edu.it/scuola/le-persone/). Ho anche provato a ripristinare la versione del template "persone.php" dalla 2.10 su un tema figlio ma il contenuto di pagina continua a non renderizzare correttamente.

C'è stato un cambio nella struttura dei dati dei custom fields degli utenti tra versioni per caso? C'è modo di recuperare i vecchi dati? Query Monitor non mostra nessuna informazione utile a riguardo.

### Includi link o screenshot

https://www.liceosciasciafermi.edu.it/scuola/le-persone/
![www liceosciasciafermi edu it_scuola_le-persone_](https://github.com/user-attachments/assets/233275ed-33a2-4c09-9284-00424c80ace0)

### Su quale sisitema operativo stai riscontrando il problema?

Windows, macOS, Android, iOS

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

2.15.0

**Comment by enrimk** [comment]
Dalla 2.15, o da prima?
Dando un'occhiata al codice, c'è in effetti una modifica relativam. recente su questa parte, ma risale alla 2.11.
https://github.com/italia/design-scuole-wordpress-theme/commit/c91e5480d690124d4e0acc550442c4993046614c#diff-256b07682028b3c0bee87bf073a837071c1b4dd962cc6dc98b291fd0b7653241R12
Qui, si è aggiunto l'ordinamento per cognome.
A causa di come è stata strutturata la query, ha anche l'effetto di rendere di fatto _obbligatorio_ il cognome (produce una _inner join_ sulla tab. _usermeta_).
Può essere che gli utenti non abbiano il campo cognome compilato?

**Comment by memorynoise** [comment]
Confermo che è questo il caso, si è trattato di un aggiornamento dalla versione 2.9 alla 2.15.

I profili sono tornati ad apparire solo dopo che la voce "Protezione Privacy" sul singolo profilo utente è stato impostato su "no", devo ammettere che non avevo trovato nulla a riguardo nella documentazione.

Grazie per il chiarimento.
