### ISSUE TITLE
Errato ordine nella visualizzazione servizi su mobile 

### ISSUE THREAD

**Issue by renatadurighello** [italia/design-scuole-wordpress-theme#74]
Nella pagina dei servizi e degli indirizzi di studio il testo inserito nella descrizione estesa, che su desktop appare sotto la voce "Cos'è", su mobile appare subito sotto la descrizione breve. Sempre su mobile quindi l'intestazione "Cos'è" rimane senza la prima parte del suo contenuto.

**Comment by astagi** [comment]
Risolto nella nuova versione del tema disponibile (2.0.0).
