### ISSUE TITLE
Rendere opzionali le circolari in home?

### ISSUE THREAD

**Issue by renatadurighello** [italia/design-scuole-wordpress-theme#76]
La visualizzazione automatica dei contenuti in evidenza in home permette di escludere il calendario, ma non permette di escludere le circolari. Purtroppo però molte scuole usano altri canali per le comunicazioni interne, ad es. il registro elettronico e quindi questa colonna è destinata a restare vuota. Questo obbliga tutte queste scuole a rinunciare alla visualizzazione automatia, che invece è molto utile. Sarebbe possibile rendere anche questa categoria opzionale?

**Comment by Karolus81** [comment]
Sottoscrivo!

Domanda: ti funziona la visualizzazione delle circolari da leggere/firmare nel back-office/bacheca di wordpress?

**Comment by renatadurighello** [comment]
Purtroppo non uso la funzionalità e quindi non ti so dire, proverò magari a fare un test
