### ISSUE TITLE
Problemi con indirizzo email dei luoghi

### ISSUE THREAD

**Issue by Karolus81** [italia/design-scuole-wordpress-theme#77]
Buongiorno,
riscontro problemi nelle email dei luoghi.
Ho la seguente situazione
LUOGO:
Nb. i luoghi sono parte di SEDE CENTRALE

SEDE CENTRALE  email: viis01600r@almerico.edu.it
-- LABORATORIO A    email: tecnici@almerico.edu.it
-- LABORATORIO B    email: tecnici@almerico.edu.it
-- LABORATORIO E    email: accoglienza@almerico.edu.it

Se seleziono che i luoghi sono parte di SEDE CENTRALE mi viene sovrascritto il riferimento email dello specifico luogo con viis01600r@almerico.edu.it (che è quello della SEDE CENTRALE).

Se, invece, lascio che i luoghi siano parte di NESSUN LUOGO, le indicazioni email compaiono correttamente.

Che fare?

**Comment by renatadurighello** [comment]
Up
Ho lo stesso problema.

**Comment by webgrafia** [comment]
ciao, ho fatto una modifica al file single-luogo.php che dovrebbe correggere questo problema.
Datemi conferma che ora sia ok

**Comment by renatadurighello** [comment]
Ciao, ben ritrovato.
Purtroppo no.
In realtà l'indirizzo mail non compare proprio: alla voce Dove si trova compare la card del luogo padre. In essa gli orari di apertura sono correttamente quelli del luogo figlio, mentre telefono e mail sono quelli del luogo padre.
Lascio un esempio:
https://liceodalpiaz.edu.it/luogo/sede-centrale/bblioteca/
ho aggiunto manualmente la mail nelle informazioni aggiuntive.
Renata
p.s. ho svuotato cache e provato con altri browser e dispositivi

**Comment by webgrafia** [comment]
@renatadurighello ho fatto una ulteriore modifica al file
template-parts/luogo/card.php 
che dovrebbe aver risolto il problema (mostra i dati della struttura padre solo se quelli della figlia non sono valorizzati)

Fatemi sapere se risolve

**Comment by renatadurighello** [comment]
La modifica funziona e fa correttamente apparire mail e telefono del luogo "figlio".
Disgraziatamente però ...sparisce la mappa.
Ho provato a rimettere il vecchio file card.php e ricompare, quindi deve essere quello.

**Comment by webgrafia** [comment]
@renatadurighello puoi provare adesso? ho fatto un'altra modifica a quel file

**Comment by renatadurighello** [comment]
Sembra perfetto!!
Fuori una!
Grazie, Renata

**Comment by astagi** [comment]
Nuova versione del tema disponibile (2.0.0)
