### ISSUE TITLE
Stampa e condividi per evento si blocca sul menù che non è cliccabile

### ISSUE THREAD

**Issue by micfio** [italia/design-scuole-wordpress-theme#79]
Cliccando su un evento e sul dettaglio poi su stampa e condividi il menù compare in grigio è non è cliccabile.

**Comment by dfranzoni** [comment]
Anche io riscontro lo stesso problema

![SharedScreenshot](https://user-images.githubusercontent.com/29452040/139824708-94d9b025-d711-463e-8ffe-5f961cf08065.jpg)
.

**Comment by astagi** [comment]
Risolto nella nuova versione del tema disponibile (2.0.0).
