### ISSUE TITLE
Sparita la possibilità di inserire la spunta nei ruoli predefiniti 

### ISSUE THREAD

**Issue by GAETANOFRISCIA** [italia/design-scuole-wordpress-theme#81]
Quando creiamo un nuovo documento o qualsiasi altra cosa non compare più l'area per spuntare i ruoli predefiniti di wp.
Inoltre la navigazione all'interno di aree riservate ai sottoscrittori adesso è aperta a tutti. Qualcuno ha idea di cosa sia successo?
Grazie 
Gaetano Friscia
 IIS Nervi

**Comment by GAETANOFRISCIA** [comment]
Risolto

**Comment by astagi** [comment]
Nuova versione del tema disponibile (2.0.0)
