### ISSUE TITLE
Articoli protetti con password

### ISSUE THREAD

**Issue by AlexDarkGraphic** [italia/design-scuole-wordpress-theme#84]
Segnalo che gli articoli protetti con password, "nascondono" solo la parte testuale, lasciando in chiaro tutti gli allegati presenti.

**Comment by renatadurighello** [comment]
Ciao, volevo solo dirti che avevo fatto la stessa segnalazione nella issue75 per le pagine. Purtroppo non saprei dove andare a metter mano.

**Comment by vcoopcsc** [comment]
Seguo

**Comment by astagi** [comment]
Buonasera, risolto in versione 2.0.0 del tema.
