### ISSUE TITLE
Problema con la pubblicazione delle immagini nel rispetto dei requisiti di accessibilità e visualizzazione campi didascalia, ecc.

### ISSUE THREAD

**Issue by vcoopcsc** [italia/design-scuole-wordpress-theme#88]
Buongiorno, 

relativamente alla pubblicazione delle immagini, mi sono accorta che: 

1. pur compilando tutti i campi disponibili in backend, in frontend non compare nulla, né il titolo, né didascalia, né la descrizione, che sono campi molto utili anche per inserire i crediti; 
2. cosa non meno importante, mi sono accorta che **il testo alternativo che inserisco non compare nel codice** e quindi le immagini non decorative caricate rischiano di essere inaccessibili in quanto non vengono lette dai sistemi di lettura automatica. Ho fatto dei test in tutto il sito e il testo alternativo non compare mai nonostante io lo inserisca.

Avete delle soluzioni al riguardo? 

Grazie, Valentina

**Comment by vcoopcsc** [comment]
Buongiorno, ripropongo il quesito in questione.

**Comment by vcoopcsc** [comment]
Buongiorno, 

sto lavorando sulla versione 6.0.2 ma nel codice continuo a non vedere il testo alternativo che ho inserito in backend per nessuno delle immagini inserite. 
Grazie in anticipo

**Comment by astagi** [comment]
Buonasera! Mi serve sapere la versione del tema @vcoopcsc

**Comment by astagi** [comment]
Dopo aver effettuato alcune prove abbiamo notato che la parte di testo alternativo non compare nel codice. I punti che abbiamo testato sono relativi agli eventi ma occorre riguardare tutti i punti del tema dove questo si verifica. In relazione agli eventi abbiamo notato questo:

- Nella sezione descrizione dell'evento mettendo un immagine questa non fa comparire alcun `alt` come attributo

![image](https://user-images.githubusercontent.com/537363/188675193-9b1ff2cd-d3cb-4edc-ad9b-e19ee72d15b4.png)

```html
<img class="alignnone size-medium wp-image-51" src="http://miosito/wp-content/uploads/2022/09/unnamed-300x169.jpeg" alt="" width="300" height="169" srcset="http://miosito/wp-content/uploads/2022/09/unnamed-300x169.jpeg 300w, http://miosito/wp-content/uploads/2022/09/unnamed-1024x576.jpeg 1024w, http://miosito/wp-content/uploads/2022/09/unnamed-768x432.jpeg 768w, http://miosito/wp-content/uploads/2022/09/unnamed-1536x864.jpeg 1536w, http://miosito/wp-content/uploads/2022/09/unnamed-2048x1152.jpeg 2048w, http://miosito/wp-content/uploads/2022/09/unnamed-444x250.jpeg 444w" sizes="(max-width: 300px) 100vw, 300px">
```

- Nella parte dello slider Splide abbiamo invece l'attributo `alt` che però prende il titolo dell'immagine e non il testo alternativo

![image](https://user-images.githubusercontent.com/537363/188675915-ea748881-2239-4109-b02f-03af8bcc51d2.png)


```html
<a href="http://miosito/wp-content/uploads/2022/09/unnamed-scaled.jpeg" aria-label="Visualizza foto: Titolo immagine">
    <img src="http://miosito/wp-content/uploads/2022/09/unnamed-730x485.jpeg" alt="Titolo immagine">	
</a>
```

**Comment by zetareticoli** [comment]
@vcoopcsc potresti darci qualche dettaglio in più su dove hai riscontrato il problema? 

Nel senso, quando carichi un Media e poi lo alleghi ad un Evento / Articolo ?

**Comment by vcoopcsc** [comment]
Buongiorno, la versione che uso è la 2.0.1 e il problema lo riscontro per le immagini caricate negli articoli, eventi, luoghi, strutture, servizi, indirizzi di studio, anteprime in home delle novità, eventi e anche per i banner caricati in home nello spazio "Pubblicità e informazione". 
Come vi dicevo il problema si ha sia per il testo alternativo che è la cosa più importante, che per la didascalia che comunque non compare nonostante i campi siano riempiti in backend.
Grazie in anticipo

**Comment by vcoopcsc** [comment]
Buongiorno, il problema continua a sussistere, il testo alternativo non compare nel codice nonostante il campo venga valorizzato.
