### ISSUE TITLE
Articoli: prevedere di toglierli automaticamente dalla home una volta scaduti

### ISSUE THREAD

**Issue by vcoopcsc** [italia/design-scuole-wordpress-theme#90]
Buongiorno, scrivo non per segnalare un problema ma per dare un suggerimento. Troviamo molto utile il fatto che si possa pianificare la pubblicazione di articoli e notizie. Ciò che manca, anche dai feedback ricevuti, è la possibilità di **impostare una data per la "defissione" delle notizie, in modo tale che vengano tolte e rimesse in bozza automaticamente dal sistema una volta che viene impostata la data**. Questa possibilità agevolerebbe enormemente le scuole che non dovrebbero così accedere al backend e togliere le notizie manualmente e garantirebbe indirettamente un alleggerimento del sito web dalle notizie vecchie, che senza questo meccanismo rischierebbero di restare pubblicate ad oltranza. 
Grazie mille,

Valentina

**Comment by magiaslab** [comment]
Puoi semplicemente installare questo plugin che fa esattamente quello che chiedi

https://wordpress.org/plugins/post-expirator/
