### ISSUE TITLE
Ginger Cookie plugin - errore 500

### ISSUE THREAD

**Issue by dfranzoni** [italia/design-scuole-wordpress-theme#91]
Volevo segnalare che con il plugin Ginger Cookie attivo e con abilitata la visualizzazione del banner il server genera un errore HTTP 500 che purtroppo, essendo in hosting e non potendo accedere direttamente alla macchina, non riesco a capire che errore sia.

Questo errore 500 è apparso solo da un paio di giorni ed il plugin non è interessato da aggiornamenti automatici.

Avete idea di come risolvere il problema?

Grazie mille a tutti

**Comment by magiaslab** [comment]
E' capitato anche a me. Ho eliminato il plugin completamente e l'ho reinstallato dal repository di wp e l'errore è scomparso. Mantiene le impostazioni in quanto la disistallazione non cancella la tabella del db. E' un errore del jquery dello spinner

**Comment by astagi** [comment]
@dfranzoni @magiaslab il plugin e' stato rimosso in maniera definitiva.
