### ISSUE TITLE
Errore di visualizzazione in home dei contenuti "in evidenza"

### ISSUE THREAD

**Issue by vcoopcsc** [italia/design-scuole-wordpress-theme#93]
Buongiorno, 
abbiamo notato che se in backend si selezionano 6 contenuti da pubblicare in evidenza, il sesto non compare mai. Per farlo comparire è necessario selezionare un settimo contenuto. In questo modo, ossia selezionando 7 contenuti da mettere in evidenza in backend,  compariranno in frontend 6 contenuti. 
Come possiamo risolvere?

Buona giornata

**Comment by astagi** [comment]
Buongiorno @vcoopcsc con quale versione del tema sta lavorando?

**Comment by vcoopcsc** [comment]
Buongiorno, all'epoca con la vecchia versione. Adesso con la versione 6.0.2
