### ISSUE TITLE
Errori in "Novità" e tipologia articolo ancora non disponibile con Gutenberg

### ISSUE THREAD

**Issue by Mauro207** [italia/design-scuole-wordpress-theme#94]
Noto che purtroppo il template non viene supportato da tempo. Ci tengo comunque a segnalare questi errori. 

1. Gli articoli delle categorie indicate in _**Configurazione > Novità**_, non vengono mostrati tutti. Viene stampato nella home solo l'ultimo articolo della prima categoria tra quelle indicate nella sezione scritta prima. 
2. Con Gutenberg attivo rimane ancora impossibile selezionare, durante la stesura dell'articolo, la tipologia. Operazione che va fatta in **Tutti gli articoli** usando l'opzione per la modifica rapida. L'intera azione va poi ripetuta se si aggiorna in qualche modo l'articolo pubblicato.

**Comment by emafer** [comment]
Segnalo che il problema è dovuto all'aggiunta del campo a $cmb_abstrat e non a $cmb_undercontent (inc/admin/articolo.php)

**Comment by astagi** [comment]
@Mauro207 @emafer state lavorando con l'ultima versione di un mese fa?

**Comment by Mauro207** [comment]
> @Mauro207 @emafer state lavorando con l'ultima versione di un mese fa?

Non ancora, al momento della segnalazione e tutt'ora si sta utilizzando una versione precedente.

**Comment by astagi** [comment]
@Mauro207 @emafer credo che la miglior cosa sia provare a passare al tema nuovo, al momento non abbiamo un branch di supporto per la vecchia versione.
