### ISSUE TITLE
Agganciare i content type progetti e indirizzi di studio

### ISSUE THREAD

**Issue by vcoopcsc** [italia/design-scuole-wordpress-theme#96]
Buongiorno, 
sarebbe possibile prevedere di agganciare i progetti agli specifici indirizzi di studio a cui sono legati?

Grazie!

**Comment by astagi** [comment]
Buongiorno @vcoopcsc potrebbe allegare degli screenshot o comunque rendere più esplicita la richiesta e l'esigenza che ha? Grazie in anticipo

**Comment by vcoopcsc** [comment]
Buongiorno, mi spiego meglio. Nel backend, il **content type progetto** per come è fatto non ha un collegamento diretto con il content type indirizzo di studio. E' possibile invece collegare il content type progetto alle "Persone", "luoghi", "Documenti", "Servizi" e "Strutture", ma sarebbe utile che ci fosse anche la possibilità di collegare gli "indirizzi di studio" per specificare meglio quale indirizzo di studio è stato protagonista del progetto. 

Grazie in anticipo

**Comment by vcoopcsc** [comment]
Buongiorno, anche con l'ultimo aggiornamento non è disponibile questo collegamento tra content type
