### ISSUE TITLE
Errore sottomenù nel menù secondario

### ISSUE THREAD

**Issue by GAETANOFRISCIA** [italia/design-scuole-wordpress-theme#97]
![image](https://user-images.githubusercontent.com/82328398/168432708-eb1dd5f0-55a3-4e2c-8fd5-f90895ec6c32.png)
Nel front end il sotto menù al menù principale non viene visualizzato.
Potete aiutarci?
Gaetano

**Comment by AlexDarkGraphic** [comment]
mi accodo alla richiesta aggiungendo il fatto di poter modificare e/o eventualmente rimuovere la voce di menu "panoramica"
grazie

**Comment by astagi** [comment]
Riguardo al bug di visualizzazione non è possibile riprodurlo.

Non sono previsti template per il menu secondario su più livelli.
