### ISSUE TITLE
Ginger - EU Cookie Law e GDPR

### ISSUE THREAD

**Issue by anitamaccio** [italia/design-scuole-wordpress-theme#98]
Ciao, volevo controllare se Ginger - EU Cookie Law fosse adeguato al GDPR, ma cliccando su visita sito web del plugin si apre la pagina di un casinò online... nella directory dei plugin sul sito di wordpress non l'ho trovato, per cui per prudenza sono passata ad un altro plugin.

**Comment by astagi** [comment]
@anitamaccio grazie del report, il plugin e' stato rimosso in maniera definitiva. Nuova versione del tema disponibile (2.0.0).
