### ISSUE TITLE
Aggiornamento tema

### ISSUE THREAD

**Issue by GAETANOFRISCIA** [italia/design-scuole-wordpress-theme#99]
Buongiorno, quali sono le fasi operative per aggiornare la versione 1.0.11 del tema alla versione 2.0.0?.
Nel back end nel menù aspetto non compare aggiorna tema.
Gaetano Friscia

**Comment by zetareticoli** [comment]
Ciao,
il tema non fa (ancora) parte del catalogo ufficiale di Wordpress, pertanto la procedura di aggiornamento deve svolta manualmente.

**Comment by spicer1** [comment]
Buongiorno,

avevamo installato un mese fa la versione 1 del tema per iniziare ad inserire un po' di dati, considerando la pubblicazione della versione 2
ho sostituito manualmente con ftp la cartella 

wp2022/wp-content/themes/design-scuole-wordpress-theme-main

con quella della versione 2 del tema (rimuovendo quindi i vecchi files)

tuttavia dopo questa sostituzione ricevo dal log errori il seguente messaggio, e la pagina non viene caricata (pagina bianca ma presente solo il titolo della finestra):

il sito è il seguente:



---------------------------------
istitutocomprensivoempoliovest.edu.it [Wed Jun 29 00:11:32 2022] [error] [pid 17718] mod_proxy_fcgi.c(888): [client 79.18.134.124:0] AH01071: Got error 'PHP message: PHP Warning: Cannot modify header information - headers already sent by (output started at /var/www/vhosts/istitutocomprensivoempoliovest.edu.it/httpdocs/wp2022/wp-content/themes/design-scuole-wordpress-theme-main/walkers/header-walker.php:1) in /var/www/vhosts/istitutocomprensivoempoliovest.edu.it/httpdocs/wp2022/wp-includes/http.php on line 493\nPHP message: PHP Warning: Cannot modify header information - headers already sent by (output started at /var/www/vhosts/istitutocomprensivoempoliovest.edu.it/httpdocs/wp2022/wp-content/themes/design-scuole-wordpress-theme-main/walkers/header-walker.php:1) in /var/www/vhosts/istitutocomprensivoempoliovest.edu.it/httpdocs/wp2022/wp-includes/http.php on line 494\nPHP message: PHP Warning: Cannot modify header information - headers already sent by (output started at /var/www/vhosts/istitutocomprensivoempoliovest.edu.it/httpdocs/wp2022/wp-content/themes/design-scuole-wordpress-theme-main/walkers/header-walker.php:1) in /var/www/vhosts/istitutocomprensivoempoliovest.edu.it/httpdocs/wp2022/wp-admin/admin-ajax.php on line 27\nPHP message: PHP Warning: Cannot modify header information - headers already sent by (output started at /var/www/vhosts/istitutocomprensivoempoliovest.edu.it/httpdocs/wp2022/wp-content/themes/design-scuole-wordpress-theme-main/walkers/header-walker.php:1) in /var/www/vhosts/istitutocomprensivoempoliovest.edu.it/httpdocs/wp2022/wp-admin/admin-ajax.php on line 28\nPHP message: PHP Warning: Cannot modify header information - headers already sent by (output started at /var/www/vhosts/istitutocomprensivoempoliovest.edu.it/httpdocs/wp2022/wp-content/themes/design-scuole-wordpress-theme-main/walkers/header-walker.php:1) in /var/www/vhosts/istitutocomprensivoempoliovest.edu.it/httpdocs/wp2022/wp-includes/functions.php on line 6764\nPHP message: PHP Warning: Cannot modify header information - headers already sent by (output started at /var/www/vhosts/istitutocomprensivoempoliovest.edu.it/httpdocs/wp2022/wp-content/themes/design-scuole-wordpress-theme-main/walkers/header-walker.php:1) in /var/www/vhosts/istitutocomprensivoempoliovest.edu.it/httpdocs/wp2022/wp-admin/includes/misc.php on line 1380\nPHP message: PHP Warning: Cannot modify header information - headers already sent by (output started at /var/www/vhosts/istitutocomprensivoempoliovest.edu.it/httpdocs/wp2022/wp-content/themes/design-scuole-wordpress-theme-main/walkers/header-walker.php:1) in /var/www/vhosts/istitutocomprensivoempoliovest.edu.it/httpdocs/wp2022/wp-includes/functions.php on line 6878\n'"
---------------------------------

**Comment by zetareticoli** [comment]
@spicer1 Il bug segnalato in questa issue è stato risolto nel commit 94ba010472567e8dbf603da67fdb3ec2dc432431 #101

**Comment by zetareticoli** [comment]
@GAETANOFRISCIA Segno come `wontfix` in quanto la risposta alla tua domanda risolve la issue
